# data_6ut_shaxslar.py
# 6-sinf Tarix: Shaxslar faoliyati bo'yicha testlar bazasi

shaxslar_6ut = [
    {"s": "Yuqori Misr hukmdori bo‘lgan shaxsni aniqlang.", "v": ["Yaxmos", "Menes", "Tutmos II", "Sargon I"], "t": "Menes"},
    {"s": "Birlashgan mamlakatning birinchi hukmdori – fir’avni kim bo‘lgan?", "v": ["Menes", "Xammurapi", "Navuxodonosor II", "Kiaksar"], "t": "Menes"},
    {"s": "Fiva shahri hukmdori bo‘lgan shaxsni toping.", "v": ["Menes", "Tutmos II", "Yaxmos", "Sargon I"], "t": "Yaxmos"},
    {"s": "Gigsoslarni Misrdan haydab chiqargan hukmdor kim?", "v": ["Doro I", "Yaxmos", "Kir II", "Sargon I"], "t": "Yaxmos"},
    {"s": "Yangi podsholik asoschisi hisoblangan shaxsni aniqlang.", "v": ["Menes", "Tutmos II", "Yaxmos", "Sargon I"], "t": "Yaxmos"},
    {"s": "Falastin, Finikiya va Suriyani istilosini boshlagan hukmdor kim?", "v": ["Chandragupta", "Navuxodonosor II", "Tutmos II", "Doro I"], "t": "Tutmos II"},
    {"s": "Mil. avv. 3-ming yillikning ikkinchi yarmida butun Mesopotamiya podshosi bo‘lgan shaxsni toping.", "v": ["Xammurapi", "Sargon I", "Navuxodonosor II", "Kiaksar"], "t": "Sargon I"},
    {"s": "Akkad va Shumer shaharlarini o‘z hokimiyati ostida birlashtirgan hukmdor kim?", "v": ["Sargon I", "Xammurapi", "Chandragupta", "Sin Shixuandi"], "t": "Sargon I"},
    {"s": "Yagona bo‘lgan uzunlik, maydon va og‘irlik o‘lchovini joriy etgan hukmdorni aniqlang.", "v": ["Chandragupta", "Doro I", "Sargon I", "Solon"], "t": "Sargon I"},
    {"s": "Jahon tarixida birinchi bo‘lib muntazam qo‘shin tuzgan shaxsni belgilang.", "v": ["Aleksandr Makedonskiy", "Kir II", "Doro I", "Sargon I"], "t": "Sargon I"},
    {"s": "«To‘rt iqlim mamlakatlari podshosi» unvonini olgan hukmdor kim?", "v": ["Sargon I", "Xammurapi", "Navuxodonosor II", "Kiaksar"], "t": "Sargon I"},
    {"s": "Vafotidan so‘ng butun mamlakatda qo‘zg‘olonlar alanga olgan Akkad hukmdori kim?", "v": ["Chandragupta", "Ashoka", "Sargon I", "Filipp II"], "t": "Sargon I"},
    {"s": "XVIII asrda butun Mesopotamiyani yagona davlatga birlashtirishga muvaffaq bo‘lgan shaxsni aniqlang.", "v": ["Sargon I", "Xammurapi", "Navuxodonosor II", "Kir II"], "t": "Xammurapi"},
    {"s": "Tarixda qonunlar tuzgan birinchi hukmdor sifatida nom qoldirgan shaxsni toping.", "v": ["Drakont", "Solon", "Xammurapi", "Sin Shixuandi"], "t": "Xammurapi"},
    {"s": "Ushbu hukmdor vafotidan keyin tog‘lik kassitlar qabilalari shaharni bosib oladi. Bu qaysi hukmdor?", "v": ["Sargon I", "Navuxodonosor II", "Xammurapi", "Kiaksar"], "t": "Xammurapi"},
    {"s": "Uning davrida Yangi Bobil podsholigi o‘z ravnaqining cho‘qqisiga erishgan shaxsni aniqlang.", "v": ["Navuxodonosor II", "Xammurapi", "Kir II", "Doro I"], "t": "Navuxodonosor II"},
    {"s": "Misrni bosib olgan va Iyerusalim (Quddus)ni vayron qilib tashlagan hukmdor kim?", "v": ["Kir II", "Kambiz II", "Navuxodonosor II", "Sargon I"], "t": "Navuxodonosor II"},
    {"s": "Bobilni mustahkam qal’aga aylantirgan hukmdorni toping.", "v": ["Xammurapi", "Sargon I", "Navuxodonosor II", "Sin Shixuandi"], "t": "Navuxodonosor II"},
    {"s": "Turar joy binolari va mudofaa devorlari qurilishida pishgan g‘ishtdan foydalanish to‘g‘risida farmon bergan shaxsni aniqlang.", "v": ["Sin Shixuandi", "Solon", "Navuxodonosor II", "Perikl"], "t": "Navuxodonosor II"},
    {"s": "Bobil shahrida har biri mamlakat bosh xudolaridan birining nomi bilan atalgan sakkizta darvoza qurdurgan hukmdor kim?", "v": ["Navuxodonosor II", "Xammurapi", "Aleksandr Makedonskiy", "Salavk"], "t": "Navuxodonosor II"},
    {"s": "Kaspiy dengizidan janubi-g‘arbda joylashgan Midiyada qabilalar ittifoqlarining hukmdori kim bo‘lgan?", "v": ["Kir II", "Doro I", "Kiaksar", "Sargon I"], "t": "Kiaksar"},
    {"s": "Mil. avv. VII asrda Midiya davlatini qudratli davlatga aylantirgan podshoni toping.", "v": ["Kir II", "Kiaksar", "Doro I", "Kambiz II"], "t": "Kiaksar"},
    {"s": "Bobil bilan ittifoq bo‘lib Ossuriyani bosib olgan Midiya podshosi kim?", "v": ["Kir II", "Sargon I", "Kiaksar", "Doro I"], "t": "Kiaksar"},
    {"s": "Mil. avv. 558-yilda barcha forslarni o‘z hokimiyati ostida birlashtirgan ahamoniylar sulolasi vakili kim?", "v": ["Kir II", "Doro I", "Kambiz II", "Artakserks"], "t": "Kir II"},
    {"s": "Midiya podsholigini bo‘ysundirganidan so‘ng ulkan lashkar tuzgan va bosqinchilik yurishlarini davom ettirgan shaxsni aniqlang.", "v": ["Doro I", "Kir II", "Kambiz II", "Navuxodonosor II"], "t": "Kir II"},
    {"s": "Armaniston, Lidiya va Bobilni zabt etgan fors hukmdorini toping.", "v": ["Kir II", "Kambiz II", "Doro I", "Sargon I"], "t": "Kir II"},
    {"s": "Forslar orasida birinchi bo‘lib O‘rtayer dengizi sohiliga chiqqan, Falastin va Finikiyani bo‘ysundirgan shaxs kim?", "v": ["Doro I", "Kir II", "Kambiz II", "Aleksandr Makedonskiy"], "t": "Kir II"},
    {"s": "Mil.avv 545-540-yillarda Parfiya, Marg‘iyona va Baqtriyani egallagan hukmdorni aniqlang.", "v": ["Doro I", "Kir II", "Kambiz II", "Kiaksar"], "t": "Kir II"},
    {"s": "Mil.avv 530-yili massagetlar ustiga yurish qilib halok bo‘lgan fors podshosi kim?", "v": ["Kir II", "Doro I", "Kambiz II", "Sargon I"], "t": "Kir II"},
    {"s": "Mil.avv 525-yili Misrni zabt etgan va Misr xalqini asirlikka olgan hukmdor kim?", "v": ["Kir II", "Doro I", "Kambiz II", "Xammurapi"], "t": "Kambiz II"},
    {"s": "Taxtga chiqqan vaqtda bosib olingan mamlakatlarda qo‘zg‘olonlar avj olgan podshoni toping.", "v": ["Kir II", "Kambiz II", "Doro I", "Chandragupta"], "t": "Doro I"},
    {"s": "Hukmronligining birinchi yili (mil.avv 522-yili) Marg‘iyonada Frada qo‘zg‘olonini bostirgan shaxsni aniqlang.", "v": ["Doro I", "Kir II", "Filipp II", "Sargon I"], "t": "Doro I"},
    {"s": "Saklarning sardori Skunxani o‘ldirib, ularni tobe qilgan fors hukmdori kim?", "v": ["Kir II", "Aleksandr Makedonskiy", "Doro I", "Kambiz II"], "t": "Doro I"},
    {"s": "Qora dengiz bo‘ylarida yashovchi skiflar ustiga yurish qilgan Ahamoniy podshosini aniqlang.", "v": ["Kambiz II", "Doro I", "Kir II", "Salavk"], "t": "Doro I"},
    {"s": "Frakiyani bosib olishi yunon-fors urushlari boshlanib ketishiga sabab bo‘lgan hukmdor kim?", "v": ["Filipp II", "Miltiad", "Doro I", "Leonidd"], "t": "Doro I"},
    {"s": "Hindiston shimolidan O‘rtayer dengiziga qadar cho‘zilgan ulkan davlat barpo etgan shaxsni toping.", "v": ["Doro I", "Chandragupta", "Aleksandr Makedonskiy", "Sin Shixuandi"], "t": "Doro I"},
    {"s": "Butun mamlakat uchun «darik» deb nomlangan yagona oltin tangani muomalaga kiritgan shaxsni aniqlang.", "v": ["Vima Kadfiz", "Kanishka", "Doro I", "Sargon I"], "t": "Doro I"},
    {"s": "Persepol shahridan O‘rtayer dengiziga qadar «shoh yo‘li» degan savdo yo‘lini qurdirgan hukmdor kim?", "v": ["Sin Shixuandi", "Doro I", "Kir II", "Ashoka"], "t": "Doro I"},
    {"s": "Qo‘shinchalarni qaytadan tuzgan va saltanatni «satrapliklar»ga taqsimlagan shaxsni aniqlang.", "v": ["Doro I", "Salavk", "Konstantin", "Sezar"], "t": "Doro I"},
    {"s": "Yunon-makedonlarga qarshi kurashgan va Maurya davlatiga asos solgan shaxsni toping.", "v": ["Ashoka", "Kanishka", "Chandragupta", "Por"], "t": "Chandragupta"},
    {"s": "Poytaxti Pataliputra bo‘lgan davlatning asoschisini aniqlang.", "v": ["Chandragupta", "Ashoka", "Lyu Ban", "Sin Shixuandi"], "t": "Chandragupta"},
    {"s": "Mil. avv III asrda Maurya davlatini yuksak taraqqiyotga erishtirgan hukmdor kim?", "v": ["Chandragupta", "Ashoka", "Kudzula Kadfiz", "U-di"], "t": "Ashoka"},
    {"s": "Nomi «Sinning birinchi hukmdori» degan ma’noni bildiruvchi shaxsni aniqlang.", "v": ["Sin Shixuandi", "Lyu Ban", "U-di", "Chjan Szyan"], "t": "Sin Shixuandi"},
    {"s": "Mil. avv. 246-yilda Xitoyni o‘z hokimiyati ostida birlashtirgan hukmdorni toping.", "v": ["Sin Shixuandi", "Lyu Ban", "U-di", "Konfutsiy"], "t": "Sin Shixuandi"},
    {"s": "O‘z davlati hududini 36 viloyatga taqsimlagan va har biriga noiblarini tayinlagan hukmdor kim?", "v": ["Lyu Ban", "U-di", "Sin Shixuandi", "Konfutsiy"], "t": "Sin Shixuandi"},
    {"s": "Hali tirikligidayoq o‘ziga atab maqbara qurishga farmon bergan va 720 ming odamni 37 yil ishlatgan shaxsni aniqlang.", "v": ["Fir'avn Xufu", "Sin Shixuandi", "Navuxodonosor II", "Trayan"], "t": "Sin Shixuandi"},
    {"s": "Shimoliy Xitoy bo‘ylab qurilgan mudofaa devorini ko‘chmanchi xunnlardan himoyalanish uchun mustahkamlashni buyurgan hukmdor kim?", "v": ["Lyu Ban", "Sin Shixuandi", "U-di", "Chjan Szyan"], "t": "Sin Shixuandi"},
    {"s": "Mil.avv 206-yili qo‘zg‘olon ko‘tarib, Sin sulolasini ag‘darib Xan sulolasini hokimyat tepasiga olib kelgan shaxsni toping.", "v": ["Lyu Ban", "U-di", "Sin Shixuandi", "Chjan Szyan"], "t": "Lyu Ban"},
    {"s": "Xan sulolasi uning davrida eng qudratli davlatga aylangan shaxsni aniqlang.", "v": ["Sin Shixuandi", "Lyu Ban", "U-di", "Chandragupta"], "t": "U-di"},
    {"s": "Chjan Saynni xunnlarga qarshi ittifoqchi topish uchun yuborgan hukmdor kim?", "v": ["Sin Shixuandi", "Lyu Ban", "U-di", "Chjan Szyan"], "t": "U-di"},
    {"s": "Adolat qaror topishini xohlagan aristokratlar va demos qonunlar yozishni iltimos qilib murojaat etgan shaxsni toping.", "v": ["Drakont", "Solon", "Perikl", "Miltiad"], "t": "Drakont"},
    {"s": "Mil. avv. 621-yilda xalq boshqaruvini bekor qilgan va 'siyoh qolib, qon bilan yozilgan' qonunlarni amalga kiritgan hukmdor kim?", "v": ["Drakont", "Solon", "Perikl", "Miltiad"], "t": "Drakont"},
    {"s": "Qonunlarni arzimas darajada buzganlik uchun ham faqat o‘lim jazosini belgilagan va shahardan haydab yuborilgan shaxsni aniqlang.", "v": ["Sezar", "Mag'rur Tarkviniy", "Drakont", "Solon"], "t": "Drakont"},
    {"s": "Aristokratiyani (aslzodalar hokimiyati) demokratiya (xalq hokimiyati)ga almashtirgan islohotchi shaxsni toping.", "v": ["Drakont", "Solon", "Perikl", "Pisistrat"], "t": "Solon"},
    {"s": "Dehqonlarning qarzlarini va qarzdorlarni qul qilishni bekor qilgan Afina hukmdori kim?", "v": ["Perikl", "Miltiad", "Solon", "Drakont"], "t": "Solon"},
    {"s": "Nasl-nasabidan qat’iy nazar afinaliklarga davlat mansablarini egallash imkoniyatini bergan shaxsni aniqlang.", "v": ["Solon", "Drakont", "Perikl", "Filipp II"], "t": "Solon"},
    {"s": "Mil. avv. 443–429-yillarda 15 marotaba strateg lavozimiga saylangan shaxsni toping.", "v": ["Perikl", "Leonidd", "Solon", "Filipp II"], "t": "Perikl"},
    {"s": "Tarixchi Gerodot va haykaltarosh Fidiy bilan do‘st bo‘lgan Afina strategini aniqlang.", "v": ["Perikl", "Solon", "Miltiad", "Leonidd"], "t": "Perikl"},
    {"s": "Xalq majlisidagi lavozimlarga ish haqi to‘lashni joriy qilgan shaxs kim?", "v": ["Solon", "Perikl", "Drakont", "Lyu Ban"], "t": "Perikl"},
    {"s": "Akropolda qurilgan mashhur inshoot Parfenon ibodatxonasining tashabbuskori kim bo‘lgan?", "v": ["Perikl", "Filipp II", "Aleksandr Makedonskiy", "Sezar"], "t": "Perikl"},
    {"s": "Kam ta'minlangan oilalar teatr-spektakllarni ko‘rishi uchun pul jamg‘armasini tashkil etgan shaxsni toping.", "v": ["Solon", "Perikl", "Sezar", "Konstantin"], "t": "Perikl"},
    {"s": "Mil. avv 490-yilgi Marafon jangida yunonlar sarkardasi kim bo‘lgan?", "v": ["Miltiad", "Leonidd", "Perikl", "Filipp II"], "t": "Miltiad"},
    {"s": "Mil. avv 480-yilgi Fermopil jangida yunon qo‘shiniga boshchilik qilgan Sparta podshosi kim?", "v": ["Miltiad", "Leonidd", "Perikl", "Aleksandr Makedonskiy"], "t": "Leonidd"},
    {"s": "Yunoniston shaharlari o'rtasidagi urushlardan foydalanib, uni bosib olishni ko‘zlagan va falanga taktikasini qo‘llagan Makedoniya podshosi kim?", "v": ["Filipp II", "Aleksandr Makedonskiy", "Perikl", "Leonidd"], "t": "Filipp II"},
    {"s": "Forslarga qarshi ittifoq tuzib, “Elladani bosib olish sari olg‘a!” degan so‘zlarni aytgan hukmdor kim?", "v": ["Filipp II", "Aleksandr Makedonskiy", "Demosfen", "Miltiad"], "t": "Filipp II"},
    {"s": "“Ellada fuqarolari, makedoniyaliklarga qarshi kurashish uchun birlashaylik!” deb xalqqa murojaat qilgan shaxsni aniqlang.", "v": ["Filipp II", "Demosfen", "Perikl", "Solon"], "t": "Demosfen"},
    {"s": "Mil.avv 356-323-yillarda yashagan jahonning eng buyuk sarkardalaridan biri kim?", "v": ["Aleksandr Makedonskiy", "Filipp II", "Sezar", "Salavk"], "t": "Aleksandr Makedonskiy"},
    {"s": "Beotiyadagi Xeroniya jangida (mil.avv 338-y) o‘z suvoriy qo‘shinlari bilan yunonlarga qaqshatqich zarba bergan shaxsni toping.", "v": ["Filipp II", "Aleksandr Makedonskiy", "Leonidd", "Miltiad"], "t": "Aleksandr Makedonskiy"},
    {"s": "Mil.avv 330-yili Ahamoniylar davlati podshosi Doro III ni zabt etgan hukmdor kim?", "v": ["Aleksandr Makedonskiy", "Filipp II", "Salavk", "Antiox"], "t": "Aleksandr Makedonskiy"},
    {"s": "Mil.avv 328-yil kuzi Spitaman bilan hal qiluvchi jangni o‘tkazgan sarkarda kim?", "v": ["Filipp II", "Aleksandr Makedonskiy", "Salavk", "Krater"], "t": "Aleksandr Makedonskiy"},
    {"s": "Mil.avv 323-yil 13-iyunda Bobilda vafot etgan hukmdorni aniqlang.", "v": ["Aleksandr Makedonskiy", "Sezar", "Konstantin", "Trayan"], "t": "Aleksandr Makedonskiy"},
    {"s": "Mil. avv. 312-yilda Bobil (Suriya davlati) hukmdori bo‘lgan Aleksandrning lashkarboshisi kim?", "v": ["Salavk", "Antiox", "Krater", "Karan"], "t": "Salavk"},
    {"s": "Spitamanning qizi Apamaga uylangan va satrapliklar tizimini davom ettirgan shaxsni toping.", "v": ["Salavk", "Aleksandr Makedonskiy", "Diodot", "Demetriy"], "t": "Salavk"},
    {"s": "Salavk va Apamaning farzandi bo‘lib, sharqiy viloyatlar noibi etib tayinlangan shaxsni aniqlang.", "v": ["Diodot", "Antiox", "Yevtidem", "Demetriy"], "t": "Antiox"},
    {"s": "Mil.avv 280-yilda Salavkiylar davlatida hukmdor bo‘lib, uni 20 yil boshqargan shaxs kim?", "v": ["Antiox", "Salavk", "Mitridat I", "Kanishka"], "t": "Antiox"},
    {"s": "Mil.avv 250-yili Yunon-Baqtriya davlatining asoschisi hisoblangan 'mingta Baqtriya shahri hukmdori' kim?", "v": ["Diodot", "Yevtidem", "Demetriy", "Mitridat I"], "t": "Diodot"},
    {"s": "Yunon-Baqtriya podsholigi uning davrida eng katta sarhadlarga ega bo‘lgan va Hindistonning bir qismini qo‘shib olgan shaxsni toping.", "v": ["Diodot", "Yevtidem", "Demetriy", "Vima Kadfiz"], "t": "Demetriy"},
    {"s": "Parfiya podshosi bo‘lib, Baqtriyaga harbiy tazyiqni kuchaytirgan va Yunon-Baqtriyaning kuchsizlanishiga sabab bo‘lgan hukmdor kim?", "v": ["Mitridat I", "Kanishka", "Vima Kadfiz", "Kudzula Kadfiz"], "t": "Mitridat I"},
    {"s": "Birlashgan yuechji qabilalarining birinchi hukmdori bo‘lib, Afg‘oniston va Kashmirni bo‘ysundirgan shaxsni aniqlang.", "v": ["Kudzula Kadfiz", "Vima Kadfiz", "Kanishka", "Chandragupta"], "t": "Kudzula Kadfiz"},
    {"s": "Kushon podsholigida hukmdor nomi ko‘rsatilgan tanga zarb qilishni boshlagan va pul islohoti o‘tkazgan shaxs kim?", "v": ["Kudzula Kadfiz", "Vima Kadfiz", "Kanishka", "Doro I"], "t": "Vima Kadfiz"},
    {"s": "Kushon poytaxtini Baqtriyadan Peshovarga ko‘chirgan va davlatni cho‘qqisiga olib chiqqan hukmdorni toping.", "v": ["Kanishka", "Vima Kadfiz", "Ashoka", "Chandragupta"], "t": "Kanishka"},
    {"s": "Rimning oxirgi saylab qo'yilgan hukmdorini o‘ldirib hokimiyatni egallagan va keyinchalik quvg‘in qilingan shaxs kim?", "v": ["Mag‘rur Tarkviniy", "Sezar", "Oktavian", "Brut"], "t": "Mag‘rur Tarkviniy"},
    {"s": "Ikkinchi PUNI urushida Alp tog‘laridan oshib o‘tib, Kann yaqinida rimliklarni tor-mor etgan Karfagen sarkardasi kim?", "v": ["Gannibal", "Ssipion", "Spartak", "Mark Krass"], "t": "Gannibal"},
    {"s": "Mil.avv 202-yilda ZAMA jangida Gannibal qo‘shinlari ustidan g‘alaba qozongan rimlik sarkardani aniqlang.", "v": ["Ssipion", "Mark Krass", "Sezar", "Pompey"], "t": "Ssipion"},
    {"s": "Kapuyadagi gladiatorlik maktabidan qochib, mil.avv 74-71-yillarda eng yirik qullar qo‘zg‘olonini ko‘targan frakiyalik shaxs kim?", "v": ["Spartak", "Gannibal", "Sezar", "Brut"], "t": "Spartak"},
    {"s": "Spartak qo‘zg‘olonini bostirgan va keyinchalik Pompey bilan hokimiyat uchun kurashgan shaxsni toping.", "v": ["Mark Krass", "Ssipion", "Sezar", "Trayan"], "t": "Mark Krass"},
    {"s": "Galliya urushlaridagi g‘alabasidan so‘ng Rimga qaytib, «Qur’a tashlandi!» deya Rubikonni kechib o‘tgan shaxs kim?", "v": ["Sezar", "Oktavian", "Pompey", "Brut"], "t": "Sezar"},
    {"s": "Rim imperatori va diktatori bo‘lgan, biroq senatda Brut boshchiligidagi fitnachilar tomonidan o‘ldirilgan hukmdorni aniqlang.", "v": ["Sezar", "Oktavian", "Trayan", "Neron"], "t": "Sezar"},
    {"s": "Sezarning do‘sti bo‘lgan, ammo uni o‘ldirish fitnasiga boshchilik qilib, keyinchalik Filipp yaqinida mag‘lub bo‘lgan shaxs kim?", "v": ["Brut", "Mark Antoniy", "Oktavian", "Ssipion"], "t": "Brut"},
    {"s": "Sezarning jiyani, Rim imperiyasining asoschisi va 'Avgust' laqabini olgan hukmdorni toping.", "v": ["Oktavian", "Sezar", "Neron", "Trayan"], "t": "Oktavian"},
    {"s": "Milodiy 98-yilda taxtga chiqqan, daklar bilan urush olib borgan va imperiya hududini Mesopotamiyagacha kengaytirgan shaxs kim?", "v": ["Trayan", "Konstantin", "Feodosiy", "Neron"], "t": "Trayan"},
    {"s": "Milodiy 313-yilda xristianlikni boshqa dinlarga teng deb e’lon qilgan va poytaxtni Konstantinopolga ko‘chirgan hukmdorni aniqlang.", "v": ["Konstantin", "Feodosiy", "Trayan", "Oktavian"], "t": "Konstantin"},
    {"s": "Milodiy 395-yili Rim imperiyasini ikki o‘g‘li o‘rtasida G‘arbiy va Sharqiy qismlarga ajratib ketgan hukmdor kim?", "v": ["Feodosiy", "Konstantin", "Arkadiy", "Trayan"], "t": "Feodosiy"},
    {"s": "Milodiy I asr boshlarida Vifleemda tug‘ilgan va xristianlik ta’limotiga asos solgan payg‘ambar kim?", "v": ["Iso (a.s)", "Konstantin", "Pontiy Pilat", "Butrus"], "t": "Iso (a.s)"},
    {"s": "Roksananing ukasi bo‘lib, makedonlarning sara otliq gvardiyasi — agemaga qabul qilingan shaxsni aniqlang.", "v": ["Itan", "Spitaman", "Farasman", "Salavk"], "t": "Itan"},
    {"s": "Ahamoniylar podshosi Artakserks saroyida tabib bo‘lgan va Baqtriyaning Ossuriya bilan urushlari haqida yozgan tarixchi kim?", "v": ["Ktesiy", "Arrian", "Poliyen", "Gerodot"], "t": "Ktesiy"},
    {"s": "Ossuriya podshosi bo‘lib, Baqtriyaga qo‘shin tortgan va Baqtra qal’asini qamal qilgan shaxs kim?", "v": ["Nin", "Sargon I", "Xammurapi", "Kiaksar"], "t": "Nin"},
    {"s": "Ossuriyaliklarga qarshi Baqtriya qo‘shiniga boshchilik qilgan podshoni aniqlang.", "v": ["Oksiart", "Farasman", "Spitaman", "Diodot"], "t": "Oksiart"},
    {"s": "Marg‘iyonadagi Frada qo‘zg‘olonini bostirish uchun Doro I tomonidan yuborilgan shaxsni toping.", "v": ["Dodarshish", "Ranosbat", "Skunxa", "Miltiad"], "t": "Dodarshish"},
    {"s": "Ahamoniylar qo‘shini tarkibidagi mingboshi bo‘lib, Shiroq jasorati hikoyasida tilga olingan shaxs kim?", "v": ["Ranosbat", "Dodarshish", "Skunxa", "Doro I"], "t": "Ranosbat"},
    {"s": "1905-yilda 'Oks xazinasi' kitobini yozgan Britaniya muzeyi xazinachisini aniqlang.", "v": ["O. Dalton", "F. Berton", "Arrian", "Ktesiy"], "t": "O. Dalton"},
    {"s": "Amudaryo xazinasini qaroqchilardan qaytarib olgan angliyalik kapitan kim?", "v": ["F. Berton", "O. Dalton", "Ssipion", "Mark Krass"], "t": "F. Berton"},
    {"s": "Politimet daryosidagi jangda makedonlar qo‘shiniga boshchilik qilgan sarkardani toping.", "v": ["Karan", "Krater", "Salavk", "Aleksandr"], "t": "Karan"},
    {"s": "Davan (Farg‘ona) davlatiga tashrif buyurgan va u yerda 70 ta shahar borligini yozgan Xitoy elchisi kim?", "v": ["Chjan Szyan", "Lyu Ban", "U-di", "Sin Shixuandi"], "t": "Chjan Szyan"},
    {"s": "«Iliada» dostonining bosh qahramoni va Stiks daryosiga botirib olingan pahlavon kim?", "v": ["Axilles", "Paris", "Leonidd", "Perikl"], "t": "Axilles"},
    {"s": "Sparta malikasi Yelenani o‘g‘irlab, Troya urushiga sabab bo‘lgan shaxsni toping.", "v": ["Paris", "Axilles", "Filipp II", "Sezar"], "t": "Paris"},
    {"s": "«Aleksandrning harbiy yurishlari» asari muallifi va Xorazm podshosi Farasman haqida ma'lumot bergan tarixchi kim?", "v": ["Arrian", "Ktesiy", "Poliyen", "Gerodot"], "t": "Arrian"},
    {"s": "Shiroq jasorati haqida hikoya yozib qoldirgan mil. avv. II asr tarixchisi kim?", "v": ["Poliyen", "Arrian", "Ktesiy", "Strabon"], "t": "Poliyen"},
    {"s": "Aleksandr Makedonskiy davrida Xorazmda podsholik qilgan shaxsni aniqlang.", "v": ["Farasman", "Oksiart", "Spitaman", "Skunxa"], "t": "Farasman"},
    {"s": "Tarixchi Poliyenning yozishicha, saklarni halokatdan qutqarish uchun forslarni suvsiz sahroga boshlab kelgan cho‘pon kim?", "v": ["Skunxa", "Shiroq", "Farasman", "Oksiart"], "t": "Shiroq"},
    {"s": "Poliyen asarida forslar qo‘shini Shiroq bilan necha kunlik yo‘lga tushib, suvsiz sahroga kirib borgani aytiladi?", "v": ["Uch kunlik", "Besh kunlik", "Yetti kunlik", "O‘n kunlik"], "t": "Yetti kunlik"},
    {"s": "Fors mingboshisi Ranosbat Shiroqdan: “Buyuk shohimizni aldab, qo‘shinni bu yerga boshlab kelishga nima majbur qildi?” deb so‘raganda, Shiroq qanday javob bergan?", "v": ["Men adashib qoldim", "Men yengdim. Saklarni halokatdan qutqazish uchun sizlarni bu baloga giriftor qildim", "Menga oltinlar va'da qilishgan edi", "Yurtingizga qayting, shunda omon qolasiz"], "t": "Men yengdim. Saklarni halokatdan qutqazish uchun sizlarni bu baloga giriftor qildim"},
    {"s": "Poliyen keltirgan ma'lumotda 'Bu yerlarda qush uchsa – qanoti, odam yursa – oyog‘i kuyadi' deb qaysi hudud tasvirlangan?", "v": ["Baqtriya tog'lari", "Suvsiz sahro", "Qora dengiz bo'ylari", "Nil daryosi qirg'oqlari"], "t": "Suvsiz sahro"},
    {"s": "Shiroqning jasorati haqidagi hikoyada forslar qo'shinining qulovozi (yo'lboshlovchisi) bo'lib xizmat qilgan shaxs kim?", "v": ["Shiroq", "Ranosbat", "Skunxa", "Doro I"], "t": "Shiroq"}
]