# data_asarlar.py

asarlar_toplami = [
    {"s": "1. 'Al-jabr val-muqobala' asarining muallifi kim?", "v": ["Ahmad al-Farg‘oniy", "Beruniy", "Muso al-Xorazmiy", "Ibn Sino"], "t": "Muso al-Xorazmiy"},
    {"s": "2. 'Hind hisobi haqida kitob' asari kimning qalamiga mansub?", "v": ["Abu Bakr Narshaxiy", "Forobiy", "Muso al-Xorazmiy", "Zamaxshariy"], "t": "Muso al-Xorazmiy"},
    {"s": "3. 'Qo‘shish va ayirish haqida kitob' muallifini aniqlang.", "v": ["Muso al-Xorazmiy", "Beruniy", "Ibn Sino", "Forobiy"], "t": "Muso al-Xorazmiy"},
    {"s": "4. 'Kitob surat-al-arz' (Yer surati) asari muallifi kim?", "v": ["Ptolemey", "Ahmad al-Farg‘oniy", "Muso al-Xorazmiy", "Beruniy"], "t": "Muso al-Xorazmiy"},
    {"s": "5. 'Usturlob bilan ishlash haqida kitob' muallifi kim?", "v": ["Beruniy", "Muso al-Xorazmiy", "Ahmad al-Farg‘oniy", "Mirzo Ulug‘bek"], "t": "Muso al-Xorazmiy"},
    {"s": "6. 'Usturlob yasash haqida kitob' asari muallifini toping.", "v": ["Ibn Sino", "Forobiy", "Muso al-Xorazmiy", "Ptolemey"], "t": "Muso al-Xorazmiy"},
    {"s": "7. 'Usturlob yordamida azimutni aniqlash haqida' asari muallifi kim?", "v": ["Muso al-Xorazmiy", "Beruniy", "Ahmad al-Farg‘oniy", "Ulug‘bek"], "t": "Muso al-Xorazmiy"},
    {"s": "8. 'Kitob ar-ruhoma' asari muallifi kim?", "v": ["Beruniy", "Muso al-Xorazmiy", "Ibn Sino", "Forobiy"], "t": "Muso al-Xorazmiy"},
    {"s": "9. 'Kitob at-tarix' asari kimga tegishli?", "v": ["Muso al-Xorazmiy", "Abu Bakr Narshaxiy", "Rashiduddin", "Hofiz Abru"], "t": "Muso al-Xorazmiy"},
    {"s": "10. Astronomiyaga oid mashhur 'Zij' asari muallifi kim?", "v": ["Mirzo Ulug‘bek", "Muso al-Xorazmiy", "Beruniy", "G‘iyosiddin Koshiy"], "t": "Muso al-Xorazmiy"},
    {"s": "11. 'Usuldagi tartibotlar' asari muallifini aniqlang.", "v": ["Zamaxshariy", "G‘azzoliy", "Marg‘inoniy", "So‘fi Olloyor"], "t": "Zamaxshariy"},
    {"s": "12. 'G‘arib hadislar haqida ajoyib asar' muallifi kim?", "v": ["Imom Buxoriy", "Zamaxshariy", "Imom Termiziy", "Hakim Termiziy"], "t": "Zamaxshariy"},
    {"s": "13. 'Vorislik huquqi ilmi bo‘yicha mashq' asari muallifi kim?", "v": ["Zamaxshariy", "Marg‘inoniy", "Subhonqulixon", "Ibn Sino"], "t": "Zamaxshariy"},
    {"s": "14. 'Turli masalalarning muhimi' asari muallifini toping.", "v": ["Forobiy", "Zamaxshariy", "Beruniy", "G‘azzoliy"], "t": "Zamaxshariy"},
    {"s": "15. 'Al-Mufassal' asari muallifi kim?", "v": ["Zamaxshariy", "Ahmad al-Farg‘oniy", "Hakim Termiziy", "Forobiy"], "t": "Zamaxshariy"},
    {"s": "16. 'Kashshof' asari muallifi kim?", "v": ["G‘azzoliy", "Zamaxshariy", "Marg‘inoniy", "Imom Termiziy"], "t": "Zamaxshariy"},
    {"s": "17. 'Musiqa haqida katta kitob' asari muallifini aniqlang.", "v": ["Forobiy", "Ibn Sino", "Muso al-Xorazmiy", "Safiuddin Urmaviy"], "t": "Forobiy"},
    {"s": "18. 'Fazilatli xulqlar' asari muallifi kim?", "v": ["G'azzoliy", "Forobiy", "Zamaxshariy", "Yusuf Xos Hojib"], "t": "Forobiy"},
    {"s": "19. 'Arastu Metafizikasiga sharh' asari muallifi kim?", "v": ["Forobiy", "Ibn Sino", "Beruniy", "Zamaxshariy"], "t": "Forobiy"},
    {"s": "20. 'Urush va tinch turmush haqida kitob' muallifi kim?", "v": ["Amir Temur", "Forobiy", "Nizomulmulk", "Kaykovus"], "t": "Forobiy"},
    {"s": "21. 'Shaharni boshqarish' asari muallifini toping.", "v": ["Forobiy", "Nizomulmulk", "Yusuf Xos Hojib", "Ibn Sino"], "t": "Forobiy"},
    {"s": "22. 'Baxt-saodatga erishuv yo‘llari' asari muallifi kim?", "v": ["Yusuf Xos Hojib", "Forobiy", "G‘azzoliy", "So‘fi Olloyor"], "t": "Forobiy"},
    {"s": "23. 'Saydana' (Farmakognoziya) asari muallifi kim?", "v": ["Beruniy", "Ibn Sino", "Muso al-Xorazmiy", "Hakim Termiziy"], "t": "Beruniy"},
    {"s": "24. 'Kitob al-tafhim' asari muallifini aniqlang.", "v": ["Forobiy", "Beruniy", "Ahmad al-Farg‘oniy", "Ptolemey"], "t": "Beruniy"},
    {"s": "25. 'Geodeziya' asari muallifi kim?", "v": ["Beruniy", "Muso al-Xorazmiy", "Ptolemey", "Ibn Sino"], "t": "Beruniy"},
    {"s": "26. 'Mineralogiya' asari muallifi kim?", "v": ["Forobiy", "Beruniy", "Ibn Sino", "Subhonqulixon"], "t": "Beruniy"},
    {"s": "27. 'Hindiston' (Tahqiqi ma lil-Hind) asari muallifini toping.", "v": ["Beruniy", "Rashiduddin", "Ibn Battuta", "Abdurazzoq Samarqandiy"], "t": "Beruniy"},
    {"s": "28. 'Qadimgi xalqlardan qolgan yodgorliklar' asari muallifi kim?", "v": ["Narshaxiy", "Beruniy", "Rashiduddin", "Hofiz Abru"], "t": "Beruniy"},
    {"s": "29. 'Navodir al-usul' asari muallifi kim?", "v": ["Hakim Termiziy", "Imom Termiziy", "Imom Buxoriy", "So‘fi Olloyor"], "t": "Hakim Termiziy"},
    {"s": "30. 'Xatm ul-avliyo' asari muallifini aniqlang.", "v": ["Hakim Termiziy", "G‘azzoliy", "Marg‘inoniy", "Imom Termiziy"], "t": "Hakim Termiziy"},
    {"s": "31. 'Adab al-nafs' asari muallifi kim?", "v": ["Forobiy", "Hakim Termiziy", "Yusuf Xos Hojib", "Kaykovus"], "t": "Hakim Termiziy"},
    {"s": "32. 'Kitob haqiqat al-odamiya' asari muallifi kim?", "v": ["Hakim Termiziy", "Ibn Sino", "Forobiy", "Zamaxshariy"], "t": "Hakim Termiziy"},
    {"s": "33. 'Bad’u sha’ni Abu Abdulloh' asari muallifi kim?", "v": ["Hakim Termiziy", "Imom Termiziy", "Imom Buxoriy", "Narshaxiy"], "t": "Hakim Termiziy"},
    {"s": "34. 'Samoviy harakatlar va umumiy ilmi nujum' asari muallifini toping.", "v": ["Muso al-Xorazmiy", "Beruniy", "Ahmad al-Farg‘oniy", "Mirzo Ulug‘bek"], "t": "Ahmad al-Farg‘oniy"},
    {"s": "35. Ahmad al-Farg‘oniy tomonidan yozilgan 'Usturlob yasash haqida kitob' qaysi olimning shu nomli asari bilan bir xil?", "v": ["Muso al-Xorazmiy", "Beruniy", "Ptolemey", "Forobiy"], "t": "Muso al-Xorazmiy"},
    {"s": "36. 'Al-Farg‘oniy jadvallari' asari muallifi kim?", "v": ["Ahmad al-Farg‘oniy", "Mirzo Ulug‘bek", "G‘iyosiddin Koshiy", "Muso al-Xorazmiy"], "t": "Ahmad al-Farg‘oniy"},
    {"s": "37. 'Yetti iqlimni hisoblash haqida' asari muallifi kim?", "v": ["Beruniy", "Ahmad al-Farg‘oniy", "Ptolemey", "Ibn Battuta"], "t": "Ahmad al-Farg‘oniy"},
    {"s": "38. 'Oyning Yer ostida va ustida bo‘lish vaqtlarini aniqlash haqida risola' muallifi kim?", "v": ["Ahmad al-Farg‘oniy", "Beruniy", "Mirzo Ulug‘bek", "Muso al-Xorazmiy"], "t": "Ahmad al-Farg‘oniy"},
    {"s": "39. 'At-Ta’rix' (Tarix) asari muallifi kim?", "v": ["Imom Termiziy", "Narshaxiy", "Rashiduddin", "Rashiduddin Fazlulloh"], "t": "Imom Termiziy"},
    {"s": "40. 'Al-Ilal fil-hadis' asari muallifini toping.", "v": ["Imom Buxoriy", "Imom Termiziy", "Hakim Termiziy", "Marg‘inoniy"], "t": "Imom Termiziy"},
    {"s": "41. 'Ash-Shamoil an-nabaviya' asari muallifi kim?", "v": ["Imom Termiziy", "Imom Buxoriy", "So‘fi Olloyor", "G‘azzoliy"], "t": "Imom Termiziy"},
    {"s": "42. Imom Termiziyning eng mashhur hadislar to‘plami qaysi?", "v": ["Al-Jome’ as-sahih", "Hidoya", "Musnad", "Sahih ul-Buxoriy"], "t": "Al-Jome’ as-sahih"},
    {"s": "43. 'Ritorika', 'Sofistika' va 'Etika' kabi asarlar muallifi kim?", "v": ["Aristotel", "Platon", "Forobiy", "Ibn Sino"], "t": "Aristotel"},
    {"s": "44. 'Metafizika' asari muallifi kim?", "v": ["Aristotel", "Platon", "Ibn Sino", "Beruniy"], "t": "Aristotel"},
    {"s": "45. 'O‘zbek xalqining etnogenezi va etnik tarixi' asari muallifi kim?", "v": ["Ahmadali Asqarov", "Azamat Ziyo", "Akbar Zamonov", "Buryakov"], "t": "Ahmadali Asqarov"},
    {"s": "46. 'O‘zbek xalqining kelib chiqish tarixi' asari muallifini toping.", "v": ["Ahmadali Asqarov", "Azamat Ziyo", "O. Bo'riyev", "S.P. Tolstov"], "t": "Ahmadali Asqarov"},
    {"s": "47. 'Al-qonun fit-tib' (Tibbiyot qonunlari) asari muallifi kim?", "v": ["Ibn Sino", "Beruniy", "Muso al-Xorazmiy", "Subhonqulixon"], "t": "Ibn Sino"},
    {"s": "48. 'Risolatun fi taqsim al-mavjudot' asari muallifi kim?", "v": ["Ibn Sino", "Forobiy", "Beruniy", "Zamaxshariy"], "t": "Ibn Sino"},
    {"s": "49. 'Shohnoma' asari muallifini aniqlang.", "v": ["Firdavsiy", "Nizomiy", "Dehlaviy", "Navoiy"], "t": "Firdavsiy"},
    {"s": "50. 'Devonu lug‘otit-turk' asari muallifi kim?", "v": ["Mahmud Qoshg‘ariy", "Yusuf Xos Hojib", "Ahmad Yassaviy", "Alisher Navoiy"], "t": "Mahmud Qoshg‘ariy"},
    {"s": "51. 'Buxoro tarixi' (Tahqiqi viloyati Buxoro) asari muallifi kim?", "v": ["Abu Bakr Narshaxiy", "Rashiduddin", "Hofiz Abru", "Mirxond"], "t": "Abu Bakr Narshaxiy"},
    {"s": "52. 'Ilk o‘rta asrlardagi Choch tarixidan' asari muallifi kim?", "v": ["Y. F. Buryakov", "Ahmadali Asqarov", "Azamat Ziyo", "Akbar Zamonov"], "t": "Y. F. Buryakov"},
    {"s": "53. 'Turkiy xalqlar mafkurasi' asari muallifini toping.", "v": ["Usmon Turon", "Yusuf Xos Hojib", "Azamat Ziyo", "Ahmadali Asqarov"], "t": "Usmon Turon"},
    {"s": "54. 'O‘zbek davlatchiligi tarixi' asari muallifi kim?", "v": ["Azamat Ziyo", "Akbar Zamonov", "Ahmadali Asqarov", "Buryakov"], "t": "Azamat Ziyo"},
    {"s": "55. 'O‘rta asr tarixiy shaxslari hayotining ayrim noma’lum sahifalari' asari muallifi kim?", "v": ["Akbar Zamonov", "Azamat Ziyo", "Muhammad Hakimxon", "Munis Xorazmiy"], "t": "Akbar Zamonov"},
    {"s": "56. 'Qutadg‘u bilig' asari muallifini aniqlang.", "v": ["Yusuf Xos Hojib", "Mahmud Qoshg‘ariy", "Alisher Navoiy", "Kaykovus"], "t": "Yusuf Xos Hojib"},
    {"s": "57. 'Siyosatnoma' asari muallifi kim?", "v": ["Nizomulmulk", "Amir Temur", "Kaykovus", "Forobiy"], "t": "Nizomulmulk"},
    {"s": "58. 'Jome at-tavorix' asari muallifi kim?", "v": ["Rashiduddin", "Hofiz Abru", "Mirxond", "Yazdiy"], "t": "Rashiduddin"},
    {"s": "59. 'Qobusnoma' asari muallifi kim?", "v": ["Kaykovus", "Nizomulmulk", "Yusuf Xos Hojib", "Sa’diy Sheroziy"], "t": "Kaykovus"},
    {"s": "60. 'Ihyou ulumid-din' asari muallifini toping.", "v": ["G‘azzoliy", "So‘fi Olloyor", "Hakim Termiziy", "Imom Buxoriy"], "t": "G‘azzoliy"},
    {"s": "61. 'Qadimiy Xorazm sivilizatsiyasini izlab' asari muallifi kim?", "v": ["S. P. Tolstov", "Y.F. Buryakov", "Ahmadali Asqarov", "Azamat Ziyo"], "t": "S. P. Tolstov"},
    {"s": "62. Imom Buxoriyning eng mashhur asari qaysi?", "v": ["Al-Jome’ as-sahih", "Hidoya", "Maslak ul-muttaqin", "Kashshof"], "t": "Al-Jome’ as-sahih"},
    {"s": "63. 'Hidoya' (To‘g‘ri yo‘l) asari muallifi kim?", "v": ["Burhoniddin Marg‘inoniy", "G‘azzoliy", "Imom Buxoriy", "So‘fi Olloyor"], "t": "Burhoniddin Marg‘inoniy"},
    {"s": "64. 'Yulduzlar jadvali' asari muallifi kim?", "v": ["Ptolemey", "Beruniy", "Ahmad al-Farg‘oniy", "Yan Geveliy"], "t": "Ptolemey"},
    {"s": "65. 'Selenografiya' asari muallifini toping.", "v": ["Yan Geveliy", "Ptolemey", "Kopernik", "Galiley"], "t": "Yan Geveliy"},
    {"s": "66. 'Temur qarorgohi' asari muallifi kim?", "v": ["Rui Gonsales de Klavixo", "Pero Meksika", "Ibn Arabshoh", "Sharafiddin Ali Yazdiy"], "t": "Rui Gonsales de Klavixo"},
    {"s": "67. 'Samarqandga – Temur saroyiga sayohat kundaligi' asari muallifini aniqlang.", "v": ["Rui Gonsales de Klavixo", "Ibn Battuta", "Pero Meksika", "Grinlo"], "t": "Rui Gonsales de Klavixo"},
    {"s": "68. 'Falakning to‘qqiz gumbazi' asari muallifi kim?", "v": ["Xusrav Dehlaviy", "Sa’diy Sheroziy", "Jaloliddin Rumiy", "Firdavsiy"], "t": "Xusrav Dehlaviy"},
    {"s": "69. 'G‘oliblik kaliti' asari muallifi kim?", "v": ["Xusrav Dehlaviy", "Alisher Navoiy", "Amir Temur", "Yazdiy"], "t": "Xusrav Dehlaviy"},
    {"s": "70. 'Xizrxon va Duvarla' asari muallifini toping.", "v": ["Xusrav Dehlaviy", "Sa’diy Sheroziy", "Firdavsiy", "Nizomiy"], "t": "Xusrav Dehlaviy"},
    {"s": "71. 'Guliston' asari muallifi kim?", "v": ["Sa’diy Sheroziy", "Xusrav Dehlaviy", "Jaloliddin Rumiy", "Pahlavon Mahmud"], "t": "Sa’diy Sheroziy"},
    {"s": "72. 'Bo‘ston' asari muallifi kim?", "v": ["Sa’diy Sheroziy", "Xusrav Dehlaviy", "Navoiy", "Sa’diy Sheroziy"], "t": "Sa’diy Sheroziy"},
    {"s": "73. 'Risola' asari muallifi kim?", "v": ["Sulton Husayn Mirzo", "Alisher Navoiy", "Bobur", "Yazdiy"], "t": "Sulton Husayn Mirzo"},
    {"s": "74. 'Majolis ul-ushshoq' asari muallifini aniqlang.", "v": ["Sulton Husayn Mirzo", "Alisher Navoiy", "Mirxond", "Abdurazzoq Samarqandiy"], "t": "Sulton Husayn Mirzo"},
    {"s": "75. 'Taboqoti Nosiriy' asari muallifi kim?", "v": ["Abu Usmon Minhijiddin ibn Sirojiddin", "Rashiduddin Fazlulloh", "Alouddin Juvayniy", "Ibn Battuta"], "t": "Abu Usmon Minhijiddin ibn Sirojiddin"},
    {"s": "76. 'Shajarayi turk' asari muallifi kim?", "v": ["Abulg‘oziy Bahodirxon", "Muhammad Hakimxon", "Munis Xorazmiy", "Bayoniy"], "t": "Abulg‘oziy Bahodirxon"},
    {"s": "77. 'Tarixi jahongusho' asari muallifini toping.", "v": ["Alouddin Juvayniy", "Rashiduddin", "Nizomiddin Shomiy", "Ibn Battuta"], "t": "Alouddin Juvayniy"},
    {"s": "78. 'Zafarnoma' asari muallifi kim?", "v": ["Nizomiddin Shomiy", "Hofiz Abru", "Abdurazzoq Samarqandiy", "Mirxond"], "t": "Nizomiddin Shomiy"},
    {"s": "79. 'Temur Malik' asari muallifi kim?", "v": ["Mirkarim Osim", "Muhammad Ali", "Odil Yoqubov", "Pirimqul Qodirov"], "t": "Mirkarim Osim"},
    {"s": "80. 'Siyrat as-sulton Jalol ad-Din Mengburni' asari muallifi kim?", "v": ["Shihobiddin ibn Ahmad an-Nasaviy", "Alouddin Juvayniy", "Rashiduddin", "Minhijiddin"], "t": "Shihobiddin ibn Ahmad an-Nasaviy"},
    {"s": "81. 'Sayohatnoma' asari muallifi kim?", "v": ["Ibn Battuta", "Klavixo", "Grinlo", "Avliyo Chalabiy"], "t": "Ibn Battuta"},
    {"s": "82. 'Muntaxab ut-tavorixi Muiniy' asari muallifi kim?", "v": ["Muiniddin Natanziy", "Rashiduddin", "Abdurazzoq Samarqandiy", "Hofiz Abru"], "t": "Muiniddin Natanziy"},
    {"s": "83. 'Masnaviyi ma’naviy' asari muallifini aniqlang.", "v": ["Jaloliddin Rumiy", "Sa’diy Sheroziy", "Pahlavon Mahmud", "Nosiriddin Rabg‘uziy"], "t": "Jaloliddin Rumiy"},
    {"s": "84. 'Haqiqatlar xazinasi' asari muallifi kim?", "v": ["Pahlavon Mahmud", "Sa’diy Sheroziy", "So‘fi Olloyor", "Maxmur"], "t": "Pahlavon Mahmud"},
    {"s": "85. 'Qissasi Rabg‘uziy' (Qisas ul-anbiyo) asari muallifi kim?", "v": ["Nosiriddin Rabg‘uziy", "Navoiy", "Rabg‘uziy", "Dehlaviy"], "t": "Nosiriddin Rabg‘uziy"},
    {"s": "86. 'Mujmali Fasihiy' asari muallifini toping.", "v": ["Ahmad Fasih Havofiy", "Sharafiddin Ali Yazdiy", "Abdurazzoq Samarqandiy", "Mirxond"], "t": "Ahmad Fasih Havofiy"},
    {"s": "87. 'Sarabadorlar' asari muallifi kim?", "v": ["Muhammad Ali", "Mirkarim Osim", "Odil Yoqubov", "Shuhrat Ergashev"], "t": "Muhammad Ali"},
    {"s": "88. 'Temur tuzuklari' asari muallifi kim?", "v": ["Amir Temur", "Sharafiddin Ali Yazdiy", "Nizomiddin Shomiy", "Ibn Arabshoh"], "t": "Amir Temur"},
    {"s": "89. 'Menkim, Sohibqiron – Jahongir Temur' asari muallifi kim?", "v": ["Marsel Brion", "Jerar Valter", "M. Ivanin", "Perondino"], "t": "Marsel Brion"},
    {"s": "90. 'Asrlar yodgorligi' asari mualliflari kim?", "v": ["Jerar Valter va Marsel Brion", "M. Ivanin va F. Shlosser", "O. Bo‘riyev", "Pero Meksika"], "t": "Jerar Valter va Marsel Brion"},
    {"s": "91. 'Ikki buyuk sarkarda' asari muallifi kim?", "v": ["M. Ivanin", "Marsel Brion", "F. Shlosser", "Napoleon"], "t": "M. Ivanin"},
    {"s": "92. 'Umumjahon tarixi' asari muallifi kim?", "v": ["F. Shlosser", "M. Ivanin", "Jerar Valter", "Toynbi"], "t": "F. Shlosser"},
    {"s": "93. 'Amir Temur – Turon sultoni' asari muallifi kim?", "v": ["O. Bo‘riyev", "Azamat Ziyo", "Akbar Zamonov", "Muhammad Ali"], "t": "O. Bo‘riyev"},
    {"s": "94. 'Temur va uning saroyiga oid xotiralar' asari muallifi kim?", "v": ["Ioann Grinlo", "Rui Gonsales de Klavixo", "Pero Meksika", "Ibn Arabshoh"], "t": "Ioann Grinlo"},
    {"s": "95. 'Skifiyalik Tamerlanning ulug‘vorligi' asari muallifini toping.", "v": ["Perondino", "Pero Meksika", "Marsel Brion", "Klavixo"], "t": "Perondino"},
    {"s": "96. 'Buyuk Temur tarixi' asari muallifi kim?", "v": ["Pero Meksika", "Klavixo", "Ibn Arabshoh", "Sharafiddin Ali Yazdiy"], "t": "Pero Meksika"},
    {"s": "97. 'Amir Temur tarixi' (Ajoib al-maqdur) asari muallifi kim?", "v": ["Ibn Arabshoh", "Yazdiy", "Nizomiddin Shomiy", "Hofiz Abru"], "t": "Ibn Arabshoh"},
    {"s": "98. 'Tarixlar sarasi' (Zubdat ut-tavorix) asari muallifi kim?", "v": ["Hofiz Abru", "Abdurazzoq Samarqandiy", "Mirxond", "Yazdiy"], "t": "Hofiz Abru"},
    {"s": "99. 'Matlayi sa’dayn' asari muallifini toping.", "v": ["Abdurazzoq Samarqandiy", "Mirxond", "G‘iyosiddin Ali", "Hofiz Abru"], "t": "Abdurazzoq Samarqandiy"},
    {"s": "100. 'Temurning Hindistonga yurishi' asari muallifi kim?", "v": ["G‘iyosiddin Ali", "Nizomiddin Shomiy", "Sharafiddin Ali Yazdiy", "Ibn Battuta"], "t": "G‘iyosiddin Ali"},
    {"s": "101. 'Soflik bog‘i' (Ravzat us-safo) asari muallifi kim?", "v": ["Mirxond", "Xondamir", "Abdurazzoq Samarqandiy", "Yazdiy"], "t": "Mirxond"},
    {"s": "102. 'Amir Temur va temuriylar davriga bag‘ishlangan bibliografiya' muallifi kim?", "v": ["M. Dogen Hort", "Keren", "J. P. Run", "Marsel Brion"], "t": "M. Dogen Hort"},
    {"s": "103. 'Tamerlan yoxud Sohibqiron saltanati' asari muallifi kim?", "v": ["Keren", "J. P. Run", "Marsel Brion", "Jerar Valter"], "t": "Keren"},
    {"s": "104. 'Tamerlan' (yaxlit nomi) asari muallifi kim?", "v": ["J. P. Run", "Keren", "Marsel Brion", "Dogen Hort"], "t": "J. P. Run"},
    {"s": "105. 'Temur davri san’atlari' asari muallifi kim?", "v": ["Abdulhay Habibiy", "Ahmadali Asqarov", "Akbar Zamonov", "Azamat Ziyo"], "t": "Abdulhay Habibiy"},
    {"s": "106. 'Bo‘lgan emas', 'Ernazarbiy' va 'Avlodlar' kabi asarlar muallifi kim?", "v": ["Berdaq", "Ajiniyoz", "Kunxo‘ja", "Ibroyim Yusupov"], "t": "Berdaq"},
    {"s": "107. Berdaqning 'Omongeldi', 'Oydo‘stbiy' va 'Ahmoq bo‘lma' asarlari qaysi janrga mansub?", "v": ["Doston va she'rlar", "Tarixiy asar", "Tibbiy risola", "Sayohatnoma"], "t": "Doston va she'rlar"},
    {"s": "108. Berdaqning 'O‘g‘limga', 'Yordamber' va 'Umrim' asarlari muallifi kim?", "v": ["Berdaq", "Ajiniyoz", "Maxmur", "Ogahiy"], "t": "Berdaq"},
    {"s": "109. 'Qiz Mengesh bilan aytishuv' asari muallifi kim?", "v": ["Ajiniyoz", "Berdaq", "Kunxo‘ja", "Ibroyim Yusupov"], "t": "Ajiniyoz"},
    {"s": "110. Ajiniyozning 'Yaxshi', 'Bo‘lmasa', 'Bo‘ladi' va 'Kerak' asarlari muallifi kim?", "v": ["Ajiniyoz", "Maxmur", "Gulxaniy", "Berdaq"], "t": "Ajiniyoz"},
    {"s": "111. Ajiniyozning 'Bo‘zatov' va 'Yigitlar' asarlari muallifi kim?", "v": ["Ajiniyoz", "Kunxo‘ja", "Berdaq", "Ibroyim Yusupov"], "t": "Ajiniyoz"},
    {"s": "112. 'Lub-lavoih al-qamar fi-l-ixtiyorat' asari muallifi kim?", "v": ["Subhonqulixon", "Muhammad Sharif Buxoriy", "Sulton Ali", "Ibn Sino"], "t": "Subhonqulixon"},
    {"s": "113. 'Ihyo at-tibbi Subhoniy' (Subhonning hayotbaxsh tibbiyoti) muallifi kim?", "v": ["Subhonqulixon", "Muhammad Sharif Buxoriy", "Sulton Ali", "Ibn Sino"], "t": "Subhonqulixon"},
    {"s": "114. 'Mehtarning sifatlari' asari muallifi kim?", "v": ["Maxmur (Mahmud)", "Gulxaniy", "Munis", "Ogahiy"], "t": "Maxmur (Mahmud)"},
    {"s": "115. 'Hajviy she’rlar devoni' va 'Hapalak' asarlari muallifi kim?", "v": ["Maxmur (Mahmud)", "Gulxaniy", "Munis", "Ogahiy"], "t": "Maxmur (Mahmud)"},
    {"s": "116. 'El bilan', 'O‘roqchilar' va 'Cho‘ponlar' asarlari muallifi kim?", "v": ["Kunxo‘ja Ibrohim", "Berdaq", "Ajiniyoz", "Maxmur"], "t": "Kunxo‘ja Ibrohim"},
    {"s": "117. 'Maslak ul-muttaqin' va 'Sabot ul-ojizin' asari muallifi kim?", "v": ["So‘fi Olloyor", "Navoiy", "Bobur", "Mashrab"], "t": "So‘fi Olloyor"},
    {"s": "118. Muhammad Shayboniyxonning qaysi asari diniy-falsafiy mazmunga ega?", "v": ["Bahr ul-hido", "Devon", "Shayboniynoma", "Zafarnoma"], "t": "Bahr ul-hido"},
    {"s": "119. 'Shohnoma miniatyuralari' va 'Saroydagi bazmga tayyorgarlik' asarlari muallifi kim?", "v": ["Muhammad Murod Samarqandiy", "Kamoliddin Behzod", "Mahmud Muzahhib", "Muhammad Sharif"], "t": "Muhammad Murod Samarqandiy"},
    {"s": "120. 'Piyola tutgan malika' va 'Kitob o‘qiyotgan o‘smir' asarlari hammualliflari kim?", "v": ["Muhammad Sharif va Muhammad Murod Samarqandiy", "Behzod va Muzahhib", "Munis va Ogahiy", "Bayoniy va Ogahiy"], "t": "Muhammad Sharif va Muhammad Murod Samarqandiy"},
    {"s": "121. 'Xorazm tarixi' va 'Shajarayi Xorazmshohiy' asarlari muallifi kim?", "v": ["Yusufbek Bayoniy", "Munis Xorazmiy", "Ogahiy", "Abulg‘oziy Bahodirxon"], "t": "Yusufbek Bayoniy"},
    {"s": "122. 'Zafarnoma' asarining muallifi kim? (9-sinf darsligida Sharafiddin Ali Yazdiydan tashqari yana kim ko'rsatilgan)", "v": ["Muntaxabi Jome’ va tavorix-i shoni", "Nizomiddin Shomiy", "Hofiz Tanish Buxoriy", "Muhammad Solih"], "t": "Muntaxabi Jome’ va tavorix-i shoni"},
    {"s": "123. 'Dastur al-iloj' va 'Muqaddimayi dastur al-iloj' asarlari muallifi kim?", "v": ["Sulton Ali", "Muhammad Sharif Buxoriy", "Ibn Sino", "Muhammad Yusuf"], "t": "Sulton Ali"},
    {"s": "124. 'Isitmani o‘rganishga doir' asari muallifi kim?", "v": ["Muhammad Yusuf Qontomiri", "Sulton Ali", "Muhammad Sharif Buxoriy", "Subhonqulixon"], "t": "Muhammad Yusuf Qontomiri"},
    {"s": "125. 'Firdavs ul-iqbol' asarini yozishni boshlagan va 'Arnalar' asarini yozgan shaxs kim?", "v": ["Munis Xorazmiy", "Ogahiy", "Bayoniy", "Abulg‘oziy Bahodirxon"], "t": "Munis Xorazmiy"},
    {"s": "126. 'Boburnoma' asari muallifi kim?", "v": ["Z.M. Bobur", "Mirzo Ulug‘bek", "Alisher Navoiy", "Sulton Husayn Mirzo"], "t": "Z.M. Bobur"},
    {"s": "127. 'Abdullanoma' (Sharafnomayi shohiy) asari muallifi kim?", "v": ["Hofiz Tanish Buxoriy", "Muhammad Solih", "Mir Muhammad Amin Buxoriy", "Abdurahmon Tole"], "t": "Hofiz Tanish Buxoriy"},
    {"s": "128. 'Haft iqlim' asari muallifi kim?", "v": ["Amin Ahmad Roziy", "Mutribiy", "Hasanxo‘ja Nisoriy", "Rashiduddin"], "t": "Amin Ahmad Roziy"},
    {"s": "129. 'Tazkirati shuaro' asari muallifi kim?", "v": ["Mutribiy", "Hasanxo‘ja Nisoriy", "Munis", "Ogahiy"], "t": "Mutribiy"},
    {"s": "130. 'Muzakkiri ahbob' asari muallifi kim?", "v": ["Hasanxo‘ja Nisoriy", "Mutribiy", "Ogahiy", "Mashrab"], "t": "Hasanxo‘ja Nisoriy"},
    {"s": "131. 'Abulxayrxon tarixi' asari muallifi kim?", "v": ["Mas’ud bin Usmoniy Kuhistoniy", "Muhammad Solih", "Hofiz Tanish Buxoriy", "Rashiduddin"], "t": "Mas’ud bin Usmoniy Kuhistoniy"},
    {"s": "132. 'Shayboniynoma' asari muallifi kim? (Doston shaklida yozilgan)", "v": ["Muhammad Solih", "Shayboniyxon", "Binoyi", "Ro'zbehon Isfahoniy"], "t": "Muhammad Solih"},
    {"s": "133. 'Bahr ul-asror' asari muallifi kim?", "v": ["Mahmud ibn Vali", "Mirxond", "Xondamir", "Hofiz Abru"], "t": "Mahmud ibn Vali"},
    {"s": "134. 'Dastur al-muluk' (Hukmdorlar uchun dastur) asari muallifi kim?", "v": ["Xoja Samandar Termiziy", "Nizomulmulk", "Kaykovus", "Yusuf Xos Hojib"], "t": "Xoja Samandar Termiziy"},
    {"s": "135. 'Muqimxon tarixi' asari muallifi kim?", "v": ["Muhammad Yusuf Munshiy", "Mir Muhammad Amin Buxoriy", "Abdurahmon Tole", "Muhammad Hakimxon"], "t": "Muhammad Yusuf Munshiy"},
    {"s": "136. 'Ubaydullanoma' asari muallifi kim?", "v": ["Mir Muhammad Amin Buxoriy", "Muhammad Yusuf Munshiy", "Abdurahmon Tole", "Muhammad Solih"], "t": "Mir Muhammad Amin Buxoriy"},
    {"s": "137. 'Abulfayzxon tarixi' asari muallifi kim?", "v": ["Abdurahmon Tole", "Muhammad Yusuf Munshiy", "Mir Muhammad Amin Buxoriy", "Muhammad Hakimxon"], "t": "Abdurahmon Tole"},
    {"s": "138. 'Qipchoqxon tarixi' asari muallifi kim?", "v": ["Hojamqulixon Balxiy", "Muhammad Solih", "Mahmud ibn Vali", "Bayoniy"], "t": "Hojamqulixon Balxiy"},
    {"s": "139. 'Ayn at-tavorix' asari muallifi kim?", "v": ["Hoji Abdulazim Shar’iy", "Mulla Olim Maxdum Hoji", "Muhammad Hakimxon", "Narshaxiy"], "t": "Hoji Abdulazim Shar’iy"},
    {"s": "140. 'O‘zbekiston tarixi' asari (ro‘yxatdagi 31-band) muallifi kim?", "v": ["Akbar Zamonov", "Azamat Ziyo", "Ahmadali Asqarov", "Sh. Ergashev"], "t": "Akbar Zamonov"},
    {"s": "141. 'Muntaxab at-tavorix' asari muallifi kim?", "v": ["Muhammad Hakimxon", "Munis Xorazmiy", "Ogahiy", "Bayoniy"], "t": "Muhammad Hakimxon"},
    {"s": "142. 'Mizan at-tibb' (Tibbiyot mezoni) asari muallifi kim?", "v": ["Muhammad Sharif Buxoriy", "Sulton Ali", "Ibn Sino", "Subhonqulixon"], "t": "Muhammad Sharif Buxoriy"},
    {"s": "143. 'Turkiston tarixi' (Tarixi Turkiston) asari muallifi kim?", "v": ["Mulla Olim Maxdum Hoji", "Munavvarqori", "Abdulla Avloniy", "Alixonto'ra Sog'uniy"], "t": "Mulla Olim Maxdum Hoji"},
    {"s": "144. 'Ajiniyoz' nomli asar (36-band) muallifi kim?", "v": ["Ibroyim Yusupov", "Berdaq", "Ajiniyoz", "Maxmur"], "t": "Ibroyim Yusupov"},
    {"s": "145. 'Mona Liza' (Jokonda) asari muallifi kim?", "v": ["Leonardo da Vinchi", "Rafael", "Mikelanjelo", "Rembrandt"], "t": "Leonardo da Vinchi"},
    {"s": "146. 'Don Kixot' asari muallifi kim?", "v": ["Migel de Servantes", "Shekspir", "Daniel Defo", "Svift"], "t": "Migel de Servantes"},
    {"s": "147. 'O‘n besh yoshli kapitan' asari muallifi kim?", "v": ["Jyul Vern", "Fenimor Kuper", "Daniel Defo", "Servantes"], "t": "Jyul Vern"},
    {"s": "148. 'Rekviyem' asari muallifi kim?", "v": ["Volfgang Amadey Motsart", "Bax", "Betxoven", "Vivaldi"], "t": "Volfgang Amadey Motsart"},
    {"s": "149. 'Gulliverning sayohati' asari muallifi kim?", "v": ["Jonatan Svift", "Daniel Defo", "Jyul Vern", "Gyote"], "t": "Jonatan Svift"},
    {"s": "150. 'Sikstin Madonnasi' asari muallifi kim?", "v": ["Rafael Santi", "Leonardo da Vinchi", "Mikelanjelo", "Rembrandt"], "t": "Rafael Santi"},
    {"s": "151. 'Ensiklopediya' asari muallifi kim?", "v": ["Deni Didro", "Volter", "Russo", "Monteskyo"], "t": "Deni Didro"},
    {"s": "152. 'Faust' falsafiy dramasi muallifi kim?", "v": ["Iogann Volfgang Gyote", "Shekspir", "Bayron", "Shiller"], "t": "Iogann Volfgang Gyote"},
    {"s": "153. 'Chaqaloq ko‘targan Madonna' asari muallifi kim?", "v": ["Leonardo da Vinchi", "Rafael", "Mikelanjelo", "Antuan Vatto"], "t": "Leonardo da Vinchi"},
    {"s": "154. 'Robinzon Kruzoning hayoti va g‘aroyib sarguzashtlari' asari muallifi kim?", "v": ["Daniel Defo", "Svift", "Kuper", "Dikens"], "t": "Daniel Defo"},
    {"s": "155. 'Yer markaziga sayohat' asari muallifi kim?", "v": ["Jyul Vern", "Daniel Defo", "Fenimor Kuper", "Shekspir"], "t": "Jyul Vern"},
    {"s": "156. 'Masallar' asari muallifi kim?", "v": ["I.A. Krilov", "Esop", "Gulxaniy", "Bayron"], "t": "I.A. Krilov"},
    {"s": "157. 'Otello', 'Hamlet' va 'Qirol Lir' asarlari muallifi kim?", "v": ["Uilyam Shekspir", "Gyote", "Servantes", "Mor"], "t": "Uilyam Shekspir"},
    {"s": "158. 'Romeo va Julyetta' asari muallifi kim?", "v": ["Uilyam Shekspir", "Motsart", "Betxoven", "Svift"], "t": "Uilyam Shekspir"},
    {"s": "159. 'So‘nggi mogikan' asari muallifi kim?", "v": ["Fenimor Kuper", "Daniel Defo", "Jyul Vern", "Stou"], "t": "Fenimor Kuper"},
    {"s": "160. 'David haykali' muallifi kim?", "v": ["Mikelanjelo Buonarotti", "Leonardo", "Rafael", "Donatello"], "t": "Mikelanjelo Buonarotti"},
    {"s": "161. 'Utopiya' (Mavjud bo‘lmagan yer) asari muallifi kim?", "v": ["Tomas Mor", "Kampanella", "Makiavelli", "Russo"], "t": "Tomas Mor"},
    {"s": "162. 'Fantaziya yo‘lida sonata' (Oydin sonata) muallifi kim?", "v": ["Lyudovik van Betxoven", "Motsart", "Bax", "Shopen"], "t": "Lyudovik van Betxoven"},
    {"s": "163. 'Izquvar' asari muallifi kim?", "v": ["Fenimor Kuper", "Jyul Vern", "Daniel Defo", "Svift"], "t": "Fenimor Kuper"},
    {"s": "164. 'O‘yin taklif' asari muallifi kim?", "v": ["Antuan Vatto", "Rafael", "Rembrandt", "Da Vinchi"], "t": "Antuan Vatto"},
    {"s": "165. 'Qahramonona' asari muallifi kim?", "v": ["Lyudovik van Betxoven", "Motsart", "Bax", "Vagner"], "t": "Lyudovik van Betxoven"},
    {"s": "166. 'Yanada Buyuk Britaniya' asari muallifi kim?", "v": ["Charlz Dikens", "Shekspir", "Bayron", "Milton"], "t": "Charlz Dikens"},
    {"s": "167. 'Adashgan o‘g‘lining qaytishi' asari muallifi kim?", "v": ["Rembrandt", "Leonardo", "Mikelanjelo", "Vatto"], "t": "Rembrandt"},
    {"s": "168. 'Borodino' she’ri muallifi kim?", "v": ["M.Yu. Lermontov", "Pushkin", "Tolstoy", "Krilov"], "t": "M.Yu. Lermontov"},
    {"s": "169. 'Chingachguk – ulkan ilon' asari muallifi kim?", "v": ["Fenimor Kuper", "Jyul Vern", "Daniel Defo", "Stou"], "t": "Fenimor Kuper"},
    {"s": "170. 'Matto bayon etgan buyuk musibat' asari muallifi kim?", "v": ["Iogann Sebastyan Bax", "Motsart", "Betxoven", "Handel"], "t": "Iogann Sebastyan Bax"},
    {"s": "171. 'Beparvo' asari muallifi kim?", "v": ["Antuan Vatto", "Rembrandt", "Da Vinchi", "Rafael"], "t": "Antuan Vatto"},
    {"s": "172. 'Tom tog‘aning kulbasi' asari muallifi kim?", "v": ["Garriet Bicher Stou", "Fenimor Kuper", "Daniel Defo", "Dikens"], "t": "Garriet Bicher Stou"},
    {"s": "173. 'Qishloq xo‘jaligi ensiklopediyasi' asari muallifi kim?", "v": ["Syuy Guansi", "Su In-Sin", "Konfutsiy", "Lao-szi"], "t": "Syuy Guansi"},
    {"s": "174. 'Sayohatnoma' asari muallifi kim? (9-sinf Jahon tarixi)", "v": ["Avliyo Chalabiy", "Ibn Battuta", "Klavixo", "Marko Polo"], "t": "Avliyo Chalabiy"},
    {"s": "175. 'Osmon yaratgan va mehnat bilan olinadigan oziq-ovqat mahsulotlari haqida' asari muallifi kim?", "v": ["Su In-Sin", "Syuy Guansi", "Chjan Szyan", "Lyu Ban"], "t": "Su In-Sin"},
    {"s": "176. 'Xatlar' she’ri muallifi kim?", "v": ["Abdulla Oripov", "Erkin Vohidov", "Oybek", "Hamza"], "t": "Abdulla Oripov"},
    {"s": "177. 'Nal va Daman' asari muallifi kim?", "v": ["Abul Fayziy", "Navoiy", "Dehlaviy", "Firdavsiy"], "t": "Abul Fayziy"},
    {"s": "178. 'Tasviri efkor' (G‘oyalar ifodachisi) gazetasi muallifi kim?", "v": ["Ibrohim Shinasi", "Namiq Kemal", "Abdulla Avloniy", "Munavvarqori"], "t": "Ibrohim Shinasi"},
    {"s": "179. 'Teatr' gazetasi maqolasi muallifi kim?", "v": ["Namiq Kemal", "Ibrohim Shinasi", "Hoji Muin", "Behbudiy"], "t": "Namiq Kemal"},
    {"s": "180. 'Qabrdagi gulchambar' asari muallifi kim?", "v": ["Piter Abrahams", "Jyul Vern", "Dikens", "Gyote"], "t": "Piter Abrahams"},
    {"s": "181. 'Ufq' asari muallifi kim?", "v": ["Said Ahmad", "Oybek", "Shuhrat", "Shukrullo"], "t": "Said Ahmad"},
    {"s": "182. 'Urushning so‘nggi qurboni' asari muallifi kim?", "v": ["O‘tkir Hoshimov", "Said Ahmad", "O‘lmas Umarbekov", "Erkin Vohidov"], "t": "O‘tkir Hoshimov"},
    {"s": "183. 'Birinchi muallim' va 'Ikkinchi muallim' asarlari muallifi kim?", "v": ["Abdulla Avloniy", "Munavvarqori", "Behbudiy", "Fitrat"], "t": "Abdulla Avloniy"},
    {"s": "184. 'Turkiy guliston yoxud axloq' asari muallifi kim?", "v": ["Abdulla Avloniy", "Hamza", "Behbudiy", "Cho'lpon"], "t": "Abdulla Avloniy"},
    {"s": "185. 'Qiyomat qarz' asari muallifi kim?", "v": ["O‘lmas Umarbekov", "O‘tkir Hoshimov", "Said Ahmad", "Shukrullo"], "t": "O‘lmas Umarbekov"},
    {"s": "186. 'Adibi avval' va 'Adibi soniy' asarlari muallifi kim?", "v": ["Munavvarqori", "Abdulla Avloniy", "Hamza", "Fitrat"], "t": "Munavvarqori"},
    {"s": "187. 'Yer yuzi' asari muallifi kim?", "v": ["Munavvarqori", "Fitrat", "Behbudiy", "Cho'lpon"], "t": "Munavvarqori"},
    {"s": "188. 'Turkiston qayg‘usi' asari muallifi kim?", "v": ["Alixonto‘ra Sog‘uniy", "Munavvarqori", "Cho'lpon", "Behbudiy"], "t": "Alixonto‘ra Sog‘uniy"},
    {"s": "189. 'Urush yo‘llarida' asari muallifi kim?", "v": ["O‘rol Tansiqboev", "Bahodir Jalolov", "Akmal Ikromov", "Usmon Nosir"], "t": "O‘rol Tansiqboev"},
    {"s": "190. 'O‘tkan kunlar' romani muallifi kim?", "v": ["Abdulla Qodiriy", "Cho'lpon", "Fitrat", "Hamza"], "t": "Abdulla Qodiriy"},
    {"s": "191. 'Uloqda' hikoyasi muallifi kim?", "v": ["Abdulla Qodiriy", "Oybek", "Hamza", "Cho'lpon"], "t": "Abdulla Qodiriy"},
    {"s": "192. 'Erk istar ko‘ngil' asari muallifi kim?", "v": ["Shuhrat Ergashev", "Abdulla Oripov", "Erkin Vohidov", "Odil Yoqubov"], "t": "Shuhrat Ergashev"},
    {"s": "193. 'Masala' maqolasi muallifi kim?", "v": ["Mulla Rahimxon", "Munavvarqori", "Behbudiy", "Avloniy"], "t": "Mulla Rahimxon"},
    {"s": "194. 'Quyosh qoraymas' romani muallifi kim?", "v": ["Oybek", "Said Ahmad", "Shuhrat", "O‘lmas Umarbekov"], "t": "Oybek"},
    {"s": "195. 'Yovga o‘lim!' she’ri va 'Front bo‘ylab' asarlari muallifi kim?", "v": ["Oybek", "Hamid Olimjon", "G‘afur G‘ulom", "Shayxzoda"], "t": "Oybek"},
    {"s": "196. 'Sen yetim emassan' she’ri muallifi kim?", "v": ["G‘afur G‘ulom", "Hamid Olimjon", "Oybek", "Zulfiya"], "t": "G‘afur G‘ulom"},
    {"s": "197. 'Kafansiz ko‘milganlar' asari muallifi kim?", "v": ["Shukrullo", "Shuhrat", "Said Ahmad", "O‘tkir Hoshimov"], "t": "Shukrullo"},
    {"s": "198. 'Chorak asr hamnafas' asari muallifi kim?", "v": ["Kibriyo Qahhorova", "Zulfiya", "Saida Zunnunova", "Oybek"], "t": "Kibriyo Qahhorova"},
    {"s": "199. 'Qo‘lingga qurol ol!' she’ri muallifi kim?", "v": ["Hamid Olimjon", "Oybek", "G‘afur G‘ulom", "Shayxzoda"], "t": "Hamid Olimjon"},
    {"s": "200. 'Oila tarbiyasi' maqolasi muallifi kim?", "v": ["Hoji Muin", "Behbudiy", "Munavvarqori", "Abdulla Avloniy"], "t": "Hoji Muin"},
    {"s": "201. 'Hurriyati diniya' maqolasi muallifi kim?", "v": ["Ibrohim Tohiriy", "Behbudiy", "Fitrat", "Munavvarqori"], "t": "Ibrohim Tohiriy"}
]