# data_9ut_atamalar.py

atamalar_9ut = [
    {"s": "Lotincha «agrarius» so'zidan olingan bo'lib, yerga va qishloq xo‘jaligiga oid degan ma'noni anglatuvchi atama?", "v": ["Agrar", "Urbanizatsiya", "Modernizatsiya", "Kasanachilik"], "t": "Agrar"},
    {"s": "O'rta Osiyo xonliklarida harbiy vazir hisoblangan eng yuqori harbiy lavozim?", "v": ["Lashkarboshi", "To'pchiboshi", "Amirilashkar", "Yasovulboshi"], "t": "Amirilashkar"},
    {"s": "Sud hukmidan norozi bo‘lgach, uning ustidan shikoyat arizasi berish shakli?", "v": ["Sanksiya", "Apelatsiya", "Ultimatum", "Manifest"], "t": "Apelatsiya"},
    {"s": "Biror hududning qonun bilan chegaralangan davlat hokimiyatini mustaqil amalga oshirish huquqi?", "v": ["Federatsiya", "Vassallik", "Protektorat", "Avtonomiya"], "t": "Avtonomiya"},
    {"s": "Qabila urf-odatlariga tayanib ish ko‘radigan sud qanday ataladi?", "v": ["Qozi sudi", "Biy sudi", "Harbiy sud", "Notarial sud"], "t": "Biy sudi"},
    {"s": "Mamlakatdagi diniy-sudlov ishlariga rahbarlik qilgan amaldor?", "v": ["Qozikalon", "Bosh qozi", "Shayxulislom", "Muftiy"], "t": "Bosh qozi"},
    {"s": "Biror tashkilot yoki jamoa tomonidan vakolatli qilib yuborilgan vakil?", "v": ["Delegat", "Deputat", "Komendant", "Ispravnik"], "t": "Delegat"},
    {"s": "Buxoroda moliya, soliqlar va tashqi aloqalar bilan, Xivada esa xazina va zakot yig'imi bilan shug'ullangan oliy amaldor?", "v": ["Mehtar", "Devonbegi", "Mushrif", "Parvonachi"], "t": "Devonbegi"},
    {"s": "Xalqning arz va shikoyatlarini tinglash hamda ularni hal qilish bilan shug‘ullangan amaldor?", "v": ["Rais", "Mirobboshi", "Dodhoh", "Ko'kaldosh"], "t": "Dodhoh"},
    {"s": "Forscha «yig» degan ma'noni anglatuvchi, charxning ip o‘raladigan qismini yasovchi hunarmand?", "v": ["Dukchi", "Jevachi", "To'qimachi", "Mushrif"], "t": "Dukchi"},
    {"s": "Rossiya imperiyasining qonun chiqaruvchi hokimiyati hamda shaharning o‘zini-o‘zi boshqarish organi?", "v": ["Senat", "Kortes", "Duma", "Reyxstag"], "t": "Duma"},
    {"s": "Xalq og‘zaki ijodida qahramonlik va dostonlar majmuasi?", "v": ["Felyeton", "Epos", "Ocherk", "Roman"], "t": "Epos"},
    {"s": "Dindorlar orasida katta obro‘ga ega bo‘lgan diniy rahnamo unvoni?", "v": ["Muftiy", "Sadr", "Eshon", "Muhtasib"], "t": "Eshon"},
    {"s": "Davlatlarning o‘z siyosiy mustaqilligini cheklash yo‘li bilan yagona ittifoqqa birlashuvi?", "v": ["Federatsiya", "Konfederatsiya", "Unitar davlat", "Protektorat"], "t": "Federatsiya"},
    {"s": "Kundalik hayotdagi salbiy hodisalarni tanqid qilib yozilgan jurnal yoki gazeta maqolasi?", "v": ["Reportaj", "Felyeton", "Maqola", "Epos"], "t": "Felyeton"},
    {"s": "Ayrim fanlarga ixtisoslashtirilgan va ular bo‘yicha chuqur ta’lim beradigan o‘quv muassasasi?", "v": ["Seminariya", "Madrasa", "Gimnaziya", "Akademik litsey"], "t": "Gimnaziya"},
    {"s": "Rossiya imperiyasi boshqaruv tizimida uyezd politsiyasi boshlig‘i?", "v": ["Komendant", "Ispravnik", "Pristan", "Politsmeyster"], "t": "Ispravnik"},
    {"s": "Arabcha «yangi» degan ma’nomi bildiruvchi harakat va uning tarafdorlari?", "v": ["Islohotchilar", "Shuro", "Jadid", "Revolutsioner"], "t": "Jadid"},
    {"s": "«Qurol-aslaha» degan ma'noni anglatuvchi va qurol-aslahaxona boshlig'iga nisbatan qo'llanilgan unvon?", "v": ["To'pchiboshi", "Jevachi", "Lashkarboshi", "Amirilashkar"], "t": "Jevachi"},
    {"s": "Uyda yollanib ishlanadigan hunarmandchilik shakli?", "v": ["Manufaktura", "Kasanachilik", "Fabrika", "Artel"], "t": "Kasanachilik"},
    {"s": "Og‘ir mehnat sharoitida jazoni o‘tash joyi qanday ataladi?", "v": ["Katorga", "Kazarma", "Konslager", "Zindon"], "t": "Katorga"},
    {"s": "Italyancha «uycha» ma’nosini anglatuvchi, harbiy qismlar uchun qurilgan maxsus bino?", "v": ["Katorga", "Prisatn", "Kazarma", "Qal'a"], "t": "Kazarma"},
    {"s": "Mamlakat xavfsizligi va amirning do'st-dushmanlari haqida ma'lumot to'plash bilan shug'ullangan shaxs?", "v": ["Ko'kaldosh", "Mirshabboshi", "Jevachi", "Parvonachi"], "t": "Ko'kaldosh"},
    {"s": "Qal’a yoki tumandagi barcha qo‘shinlarning harbiy boshlig‘i?", "v": ["Ispravnik", "To'ra", "Komendant", "Mirob"], "t": "Komendant"},
    {"s": "Eski tuzum tarafdori bo‘lgan va har qanday islohotlarga qarshi chiquvchi shaxs?", "v": ["Radikal", "Konservativ", "Liberal", "Demokrat"], "t": "Konservativ"},
    {"s": "Mag‘lub davlatning g‘olib davlat foydasiga to'laydigan pul mablag‘i?", "v": ["Reparatsiya", "Kontributsiya", "Soliq", "Xiroj"], "t": "Kontributsiya"},
    {"s": "Harbiy bo‘linmalarning bevosita boshliqlari kim deb atalgan?", "v": ["Amirilashkar", "Lashkarboshi", "Mingboshi", "Yasovulboshi"], "t": "Lashkarboshi"},
    {"s": "Aminlar, oqsoqollar va ruhoniylarlardan iborat bo'lgan boshqaruv bo'g'ini?", "v": ["Mahalliy ma’muriyat", "Markaziy devon", "Zemstvo", "Duma"], "t": "Mahalliy ma’muriyat"},
    {"s": "Hukumatning juda muhim voqea munosabati bilan xalqqa qilgan qonun kuchiga teng murojaati?", "v": ["Dekret", "Nota", "Manifest", "Veksell"], "t": "Manifest"},
    {"s": "Insonlarning bilimi va tafakkurini oshirishga qaratilgan ta’lim-tarbiya jarayoni (arabcha)?", "v": ["Matbuot", "Maorif", "Madaniyat", "San'at"], "t": "Maorif"},
    {"s": "Gazeta, jurnal va bosma asarlar majmuasi qanday ataladi?", "v": ["Maorif", "Senzura", "Matbuot", "Epos"], "t": "Matbuot"},
    {"s": "Xonliklarda bosh vazir hamda xazina ishlari va xarajatlarini nazorat qiluvchi amaldor?", "v": ["Mehtar", "Mushrif", "Sadr", "Mirobboshi"], "t": "Mehtar"},
    {"s": "Yer atmosferasi va undagi fizik jarayonlarni o‘rganuvchi fan?", "v": ["Geologiya", "Ekologiya", "Meteorologiya", "Fizika"], "t": "Meteorologiya"},
    {"s": "Buxoroda dastlab harbiy bo‘linma boshlig‘i, keyinchalik Bosh vazir vazifasini bajargan lavozim?", "v": ["Qo'shbegi", "Mingboshi", "To'pchiboshi", "Otaliq"], "t": "Mingboshi"},
    {"s": "Sug‘orish inshootlari va suv ta’minoti hamda taqsimotiga mas’ul shaxs?", "v": ["Rais", "Mirobboshi", "Mushrif", "Mehtar"], "t": "Mirobboshi"},
    {"s": "Xivada osoyishtalikka, Buxoroda amir soqchilariga boshchilik qilgan amaldor?", "v": ["Mirshab", "Mirshabboshi", "Ko'kaldosh", "Yasovulboshi"], "t": "Mirshabboshi"},
    {"s": "Qo‘qon xonligidagi tartib-intizom ishlariga mas’ul bo‘lgan shaxslar?", "v": ["Raislar", "Yasovullar", "Mirshablar", "Aminlar"], "t": "Mirshablar"},
    {"s": "Amirlikda barcha rasmiy hujjatlarni yuritish bilan shug‘ullangan lavozim?", "v": ["Parvonachi", "Mirzaboshi", "Mehtar", "Mushrif"], "t": "Mirzaboshi"},
    {"s": "Iqtisodiyotning bir sohasidagi yakka hukmronlik (yunoncha «tanho sotish»)?", "v": ["Monopoliya", "Sindikat", "Kartel", "Bozor"], "t": "Monopoliya"},
    {"s": "Diniy-huquqiy masalalar bilan shug‘ullangan va shayxulislomga bo‘ysungan shaxs?", "v": ["Qozi", "Muftiy", "Muhtasib", "Sadr"], "t": "Muftiy"},
    {"s": "Shariat qoidalarining bajarilishi va amal qilinishi masalalari bilan shug‘ullangan amaldor?", "v": ["Rais", "Muftiy", "Muhtasib", "Shayxulislom"], "t": "Muhtasib"},
    {"s": "Diniy ishlar va bozordagi savdo-sotiqning to‘g‘ri yuritilishini nazorat qilgan amaldorlar?", "v": ["Muhtasib-raislar", "Mirshabboshi", "Mushriflar", "Aminlar"], "t": "Muhtasib-raislar"},
    {"s": "Soliqlarni o‘z vaqtida yig‘ib olish va ularni hisobga olib borishga javobgar shaxs?", "v": ["Mehtar", "Devonbegi", "Mushrif", "Mirob"], "t": "Mushrif"},
    {"s": "Mushtuk-puflamali cholg‘u asbobini toping.", "v": ["Nay", "Karnay", "G'ijjak", "Chang"], "t": "Karnay"},
    {"s": "Dinga qattiq berilgan va uning aqidalariga ko‘r-ko‘rona amal qiluvchi shaxs?", "v": ["Jadid", "Eshon", "Mutaassib", "Ma'rifatparvar"], "t": "Mutaassib"},
    {"s": "Arabcha «vaqtinchalik» ma’nosini anglatuvchi, muayyan muddatga tuzilgan hokimiyat?", "v": ["Doimiy hukumat", "Muvaqqat hukumat", "Muxtoriyat", "Diktatura"], "t": "Muvaqqat hukumat"},
    {"s": "Yuridik va boshqa turli hujjatlarni tasdiqlash bilan bog‘liq ishlar?", "v": ["Advokatura", "Notarial ishlar", "Sudlov", "Tergov"], "t": "Notarial ishlar"},
    {"s": "O'rta Osiyo xonliklarida masjid va madrasalar ixtiyoridagi yerlar qanday atalgan?", "v": ["Amlok yerlari", "Mulk yerlari", "Vaqf yerlari", "Bo'sh yerlar"], "t": "Vaqf yerlari"},
    {"s": "Amirlikda toj-u taxt vorisi (valiahd) tarbiyasi bilan shug‘ullangan amaldor?", "v": ["Ko'kaldosh", "Mehtar", "Otaliq", "Parvonachi"], "t": "Otaliq"},
    {"s": "Madrasalar ta’limini nazorat qiluvchi hamda xon bilan madrasalar o‘rtasidagi munosabatlarni yurituvchi shaxs?", "v": ["Sadr", "Olimlar yasovuli", "Muftiy", "Qozikalon"], "t": "Olimlar yasovuli"},
    {"s": "Oliy hukmdor farmonlarini xalqqa e’lon qiluvchi lavozim egasi?", "v": ["Mirzaboshi", "Dodhoh", "Parvonachi", "Yasovul"], "t": "Parvonachi"},
    {"s": "Jamoat xavfsizligini saqlovchi tashkilot (nemischa «ma’muriyat»)?", "v": ["Politsiya", "Armiya", "Zemstvo", "Duma"], "t": "Politsiya"},
    {"s": "Daryolar sohillarida kemalar to‘xtaydigan maxsus jihozlangan bandargoh?", "v": ["Bekat", "Pristan", "Terminal", "Bozor"], "t": "Pristan"},
    {"s": "Mustamlaka qaramligining shakli bo‘lib, bunda mamlakat tashqi siyosati mustamlakachiga o'tadi?", "v": ["Vassallik", "Protektorat", "Avtonomiya", "Federatsiya"], "t": "Protektorat"},
    {"s": "Puflama-nayli cholg‘u asboblarini toping.", "v": ["Nay, surnay", "G'ijjak, tanbur", "Chang, doira", "Karnay, nog'ora"], "t": "Nay, surnay"},
    {"s": "O‘qni tez otadigan avtomatik qurol?", "v": ["To'p", "Miltiq", "Pulemyot", "Kamon"], "t": "Pulemyot"},
    {"s": "Buxoro amirligida ijro hokimiyati boshlig‘i, Bosh vazir?", "v": ["Mingboshi", "Qo’shbegi", "Mehtar", "Yasovulboshi"], "t": "Qo’shbegi"},
    {"s": "Shariat qoidalarari asosida ish ko‘radigan sud tizimi?", "v": ["Biy sudlari", "Harbiy sud", "Qozi sudlari", "Xalq sudlari"], "t": "Qozi sudlari"},
    {"s": "Buxoro amirligi va Qo'qon xonligidagi oliy sud boshlig‘i?", "v": ["Muftiy", "Shayxulislom", "Qozikalon", "Rais"], "t": "Qozikalon"},
    {"s": "Jamiyatda keskin va qat’iy choralar ko‘rish tarafdori bo‘lgan oqim?", "v": ["Radikal", "Konservativ", "Liberal", "Evolyutsion"], "t": "Radikal"},
    {"s": "Joylarda qonunlar, diniy amallar va bozordagi o'lchovlar ustidan nazorat qilgan amaldor?", "v": ["Mirshab", "Muhtasib", "Rais", "Mirob"], "t": "Rais"},
    {"s": "Buxoro amirligidagi sud boshlig‘i lavozimi?", "v": ["Qozikalon", "Raiskalon", "Bosh qozi", "Shayxulislom"], "t": "Raiskalon"},
    {"s": "Sudlov, notarial ishlar va ta’lim tizimiga umumiy rahbarlik qilgan ijtimoiy qatlam?", "v": ["Dehqonlar", "Ruhoniylar", "Hunarmandlar", "Sipohiylar"], "t": "Ruhoniylar"},
    {"s": "Vaqf ishlari va madrasa-masjid mulklari bilan shug‘ullangan lavozim?", "v": ["Muftiy", "Sadr", "Mushrif", "Devonbegi"], "t": "Sadr"},
    {"s": "Matbuot ustidan nazorat qilib, zararli deb topilgan ma’lumotlarni cheklash?", "v": ["Izolatsiya", "Senzura", "Redaksiya", "Ekspertiza"], "t": "Senzura"},
    {"s": "Xivada diniy ishlar va shariat qoidalariga rioya qilinishiga mas’ul bo‘lgan eng oliy diniy mansab?", "v": ["Qozikalon", "Muftiy", "Shayxulislom", "Rais"], "t": "Shayxulislom"},
    {"s": "Bir turdagi mahsulot ishlab chiqaruvchi korxonalarning mahsulotni sotish bo‘yicha birlashmasi?", "v": ["Trest", "Kartel", "Sindikat", "Konsern"], "t": "Sindikat"},
    {"s": "Uyushmagan, to‘g‘ri tashkil etilmagan, o‘z-o‘zidan sodir bo‘ladigan harakat?", "v": ["Rejali", "Stixiyali", "Radikal", "Diplomatik"], "t": "Stixiyali"},
    {"s": "Amir qo‘shinlarining bosh qo‘mondoni va to‘pchi qismlar rahbar?", "v": ["Yasovulboshi", "Amirilashkar", "To’pchiboshi", "Lashkarboshi"], "t": "To’pchiboshi"},
    {"s": "Xiva xonligida xonning qarindoshlari va yaqinlariga beriladigan unvon?", "v": ["Bek", "Mir", "To’ra", "Sayyid"], "t": "To’ra"},
    {"s": "Torli-kamonchali cholg‘u asboblarini ko‘rsating.", "v": ["G’ijjak, qo’biz, uchtor", "Dutor, tanbur", "Chang, doira", "Nay, surnay"], "t": "G’ijjak, qo’biz, uchtor"},
    {"s": "Torli-noxunli cholg‘u asboblariga qaysilar kiradi?", "v": ["G'ijjak, chang", "Do’mbira, dutor, tanbur, ud, rubob", "Doira, nog'ora", "Karnay, surnay"], "t": "Do’mbira, dutor, tanbur, ud, rubob"},
    {"s": "Torli-zarbli cholg‘u asbobini toping.", "v": ["Tanbur", "Rubob", "Chang", "G'ijjak"], "t": "Chang"},
    {"s": "Teatr yoki sirk artistlarining ijodiy jamoasi?", "v": ["Ansambl", "Truppa", "Xor", "Kvartet"], "t": "Truppa"},
    {"s": "Mustamlakachilar tomonidan mahalliy, yerli xalqqa nisbatan ishlatilgan atama?", "v": ["Emigrant", "Tuzem", "Migrant", "Yunker"], "t": "Tuzem"},
    {"s": "Rossiya ma'muriyatida aholi yashash joyi nazoratchisi?", "v": ["Ispravnik", "Uchastka pristavi", "Volost", "Amin"], "t": "Uchastka pristavi"},
    {"s": "Bir davlatning boshqa davlatga hech qanday e’tirozga o‘rin qoldirmaydigan qat’iy talabi?", "v": ["Nota", "Manifest", "Ultimatum", "Dekret"], "t": "Ultimatum"},
    {"s": "Rossiya imperiyasida tumanlarga teng bo‘lgan ma’muriy-hududiy bo‘linma?", "v": ["Volost", "Uyezd", "Guberniya", "Viloyat"], "t": "Uyezd"},
    {"s": "Bir davlatning (yoki shaxsning) boshqa bir kuchli davlatga bo‘ysunish tartibi?", "v": ["Federatsiya", "Vassal", "Konfederatsiya", "Muxtoriyat"], "t": "Vassal"},
    {"s": "Uyezd tarkibiga kirgan, bir nechta qishloq yoki ovullardan iborat hudud?", "v": ["Volost", "Okrug", "Bo'lim", "Guberniya"], "t": "Volost"},
    {"s": "Hosilning 1/3 yoki 1/5 qismi miqdorida dehqonlardan olingan yer solig‘i?", "v": ["Zakot", "Xiroj", "Tanobona", "Boj"], "t": "Xiroj"},
    {"s": "Darveshlar va musofirlar uchun maishiy xona hamda masjiddan iborat bino?", "v": ["Madrasa", "Karvonsaroy", "Xonaqoh", "Maqbara"], "t": "Xonaqoh"},
    {"s": "Xiva xonligida xon qo‘shinlarining bosh qo‘mondoni va tartib-intizomga mas’ul shaxs?", "v": ["Amirilashkar", "Yasovulboshi", "To'pchiboshi", "Mirshab"], "t": "Yasovulboshi"},
    {"s": "Zarbli-membranali cholg‘u asboblarini toping.", "v": ["Chang, tanbur", "Doira, nog’ora, chindovul", "Nay, g'ijjak"], "t": "Doira, nog’ora, chindovul"},
    {"s": "Rossiya imperiyasida vakolatlari cheklangan mahalliy o'zini-o'zi boshqarish idorasi?", "v": ["Duma", "Senat", "Zemstvo", "Prigorod"], "t": "Zemstvo"},
    {"s": "Ikki tilda (masalan, o‘zbek va fors tillarida) ijod qiluvchi ijodkor?", "v": ["Polyglot", "Zullisonayn", "Mutarjim", "Kotib"], "t": "Zullisonayn"}
]