# data_11jt_atamalar.py

atamalar_11jt = [
    {"s": "Terroristik aktni bartaraf qilish va aholi xavfsizligini ta'minlash uchun o'tkaziladigan maxsus harbiy tadbirlar kompleksi nima?", "v": ["Militarizatsiya", "Shok terapiyasi", "Antiterror operatsiya", "Rangli inqilob"], "t": "Antiterror operatsiya"},
    {"s": "Janubi-Sharqiy Osiyo davlatlari assotsiatsiyasining qisqartma nomi qaysi?", "v": ["ASEAN", "BRIKS", "NATO", "YeI"], "t": "ASEAN"},
    {"s": "Braziliya, Rossiya, Hindiston, Xitoy va Janubiy Afrika mamlakatlaridan iborat ittifoq nomi?", "v": ["ASEAN", "BRIKS", "NATO", "Transmilliy korporatsiya"], "t": "BRIKS"},
    {"s": "Aholi, uning ko'payishi, tarkibi va joylashishi qonuniyatlarini o'rganuvchi fan?", "v": ["Logistika", "Sotsiologiya", "Demografiya", "Etnografiya"], "t": "Demografiya"},
    {"s": "Qat'iy xalqaro valutaga nisbatan milliy valutaning rasmiy kursini pasaytirish nima?", "v": ["Devalvatsiya", "Revalvatsiya", "Inflyatsiya", "Retsessiya"], "t": "Devalvatsiya"},
    {"s": "Bir-biri bilan qo‘shni yashaydigan turli etnik guruhlar o‘rtasidagi to‘qnashuv qanday ataladi?", "v": ["Etno-konfessional mojaro", "Etnik mojaro", "Siyosiy aksiya", "Rangli inqilob"], "t": "Etnik mojaro"},
    {"s": "Etnik ziddiyat diniy ziddiyat bilan qo‘shilib ketgan mojaro shakli qaysi?", "v": ["Etnik mojaro", "Etno-konfessional mojaro", "Gender tengsizlik", "Populizm"], "t": "Etno-konfessional mojaro"},
    {"s": "Erkaklar va ayollarning jamiyatdagi imkoniyatlari bir-biridan keskin farq qilishi nima?", "v": ["Gender tengsizlik", "Multikulturalizm", "Etnik mojaro", "Tolerantlik"], "t": "Gender tengsizlik"},
    {"s": "Davlatning geosiyosiy makonda o‘z maqsadiga erishish uchun qo‘llaydigan harakat texnologiyalari?", "v": ["Taktika", "Populizm", "Geostrategiya", "Militarizatsiya"], "t": "Geostrategiya"},
    {"s": "Jahon mamlakatlarining iqtisodiy, siyosiy va madaniy jihatdan birlashishi yoki yaqinlashishi jarayoni?", "v": ["Integratsiya", "Globallashuv", "Modernizatsiya", "Unifikatsiya"], "t": "Globallashuv"},
    {"s": "Aholining bir mamlakatdan boshqasiga vaqtincha yoki doimiy yashash uchun ko‘chib o‘tishi?", "v": ["Repatriatsiya", "Immigratsiya", "Demobilizatsiya", "Urbanizatsiya"], "t": "Immigratsiya"},
    {"s": "Ijtimoiy-iqtisodiy taraqqiyotning tarkibiy qismi bo‘lgan ijtimoiy institutlardagi o‘zgarishlar?", "v": ["Institutsional o'zgarishlar", "Neoliberal islohotlar", "Modernizatsiya", "Retsessiya"], "t": "Institutsional o'zgarishlar"},
    {"s": "Davlatlar o‘rtasida tovar, moliya va ishchi kuchi erkin harakatlanadigan iqtisodiy kenglik tashkil qilish uchun birlashish?", "v": ["Globallashuv", "Integratsiya", "Proteksionizm", "Devalvatsiya"], "t": "Integratsiya"},
    {"s": "Pul harakati, valuta kursi va ishlab chiqarish dinamikasi bilan xarakterlanuvchi iqtisodiyotning holati?", "v": ["Iqtisodiy konyunktura", "Retsessiya", "Shok terapiyasi", "Restrukturizatsiya"], "t": "Iqtisodiy konyunktura"},
    {"s": "Irqlarning teng emasligi va 'oliy' irqlarning hukmronligi haqidagi g‘ayriilmiy nazariya?", "v": ["Shovinizm", "Antisemitizm", "Irqchilik", "Multikulturalizm"], "t": "Irqchilik"},
    {"s": "Voqelikni bilishda ongning imkoniyatini rad etuvchi yoki uni cheklangan deb biluvchi falsafiy konsepsiya?", "v": ["Mistitsizm", "Irratsionallik", "Pozitsiya", "Modernizm"], "t": "Irratsionallik"},
    {"s": "Fan va texnika taraqqiyotida yangi sifat bosqichiga o‘tish va ishlab chiqaruvchi kuchlarni tubdan qayta qurish?", "v": ["ITI (ilmiy-texnik inqilob)", "Modernizatsiya", "Makrotexnologiya", "Geostrategiya"], "t": "ITI (ilmiy-texnik inqilob)"},
    {"s": "Davlat yoki shaxsni xalqaro hamjamiyatdan ajratib qo‘yish, yakkalash nima?", "v": ["Blokada", "Sanksiya", "Izolatsiya", "Repatriatsiya"], "t": "Izolatsiya"},
    {"s": "Qo‘shimcha qiymat olishda foydalaniladigan moddiy, intellektual va moliyaviy vositalar yig‘indisi?", "v": ["Ssuda", "Kapital", "Subsidiya", "Fond"], "t": "Kapital"},
    {"s": "Mafkuraviy plyuralizmning ifodasi bo‘lgan, zamonaviy demokratik mamlakatlarda siyosiy hayotni tashkil qilish tamoyili?", "v": ["Populizm", "Rangli inqilob", "Ko‘ppartiyaviylik prinsipi", "Geostrategiya"], "t": "Ko‘ppartiyaviylik prinsipi"},
    {"s": "Jahonda bir-biridan ustun bo‘lmagan bir nechta siyosiy va iqtisodiy markazlarning mavjudlik holati?", "v": ["Ko'pqutbli dunyo", "Globallashuv", "Integratsiya", "Ikkiqutbli dunyo"], "t": "Ko'pqutbli dunyo"},
    {"s": "Mansabdor shaxsning o‘z vakolatlarini shaxsiy manfaatlari yo‘lida qonunga xilof ravishda suiiste'mol qilishi?", "v": ["Populizm", "Korrupsiya", "Militarizatsiya", "Restrukturizatsiya"], "t": "Korrupsiya"},
    {"s": "Tovarlar va yuklarni bir hududdan boshqasiga yetkazib berish tizimini tashkil qilish?", "v": ["Marketing", "Menenjment", "Logistika", "Makrotexnologiya"], "t": "Logistika"},
    {"s": "Afg'on qabilalari tomonidan saylanadigan umumafg'on oqsoqollar kengashi qanday ataladi?", "v": ["Sho'ro", "Loyya jirgasi", "Bundesrat", "Landtag"], "t": "Loyya jirgasi"},
    {"s": "Mahsulot yaratish bo‘yicha ilmiy izlanishdan tortib servisgacha bo‘lgan barcha texnologik jarayonlar majmuyi?", "v": ["Makrotexnologiya", "ITI", "Modernizatsiya", "Siyosiy texnologiya"], "t": "Makrotexnologiya"},
    {"s": "Davlatning harbiy qudratini oshirishga qaratilgan iqtisodiy va siyosiy harakatlar?", "v": ["Demobilizatsiya", "Reaksiya", "Militarizatsiya", "Ekspansiya"], "t": "Militarizatsiya"},
    {"s": "Jamiyatni boshqarish layoqatiga ega bo‘lgan va hokimiyatni o‘z qo‘lida jamlagan saralangan shaxslar guruhi?", "v": ["Oligarxiya", "Milliy siyosiy elita", "Populistlar", "Byurokratiya"], "t": "Milliy siyosiy elita"},
    {"s": "Mistika va diniy-idealistik dunyoqarash shakliga moyillik nima?", "v": ["Irratsionallik", "Mistitsizm", "Modernizm", "Pozitsiya"], "t": "Mistitsizm"},
    {"s": "An'anaviy jamiyatdan yangilangan jamiyatga, agrar sivilizatsiyadan industrial sivilizatsiyaga o‘tish jarayoni?", "v": ["Integratsiya", "Urbanizatsiya", "Modernizatsiya", "Inqilob"], "t": "Modernizatsiya"},
    {"s": "Bir mamlakatda madaniyatlar xilma-xilligini saqlab qolishga yo‘naltirilgan siyosat va mafkura?", "v": ["Irqchilik", "Shovinizm", "Multikulturalizm", "Tolerantlik"], "t": "Multikulturalizm"},
    {"s": "Shimoliy Atlantika harbiy blokining qisqartma nomi qaysi?", "v": ["NATO", "ASEAN", "BRIKS", "BMT"], "t": "NATO"},
    {"s": "1920-1940-yillardagi fashistik tashkilotlarning g'oyaviy davomchisi bo‘lgan o‘ng radikal tashkilotlar?", "v": ["Neokonservatorlar", "Neoliberallar", "Neofashizm", "Ultrakonservatorlar"], "t": "Neofashizm"},
    {"s": "An'anaviy ijtimoiy qadriyatlarni saqlash va rivojlantirishga yo'naltirilgan konservatizm turi?", "v": ["Neofashizm", "Neoliberalizm", "Neokonservatizm", "Populizm"], "t": "Neokonservatizm"},
    {"s": "Bozor o‘zini o‘zi tartibga soladi deb hisoblovchi, davlatning iqtisodiyotga aralashuvini kamaytirishga qaratilgan islohot?", "v": ["Shok terapiyasi", "Neoliberal islohot", "Restrukturizatsiya", "Modernizatsiya"], "t": "Neoliberal islohot"},
    {"s": "Zamonaviy jamiyatning deyarli barcha sohalariga kirib kelgan maishiy va ko'ngilochar madaniyat?", "v": ["Ommaviy madaniyat", "Elitar madaniyat", "Demokratik adabiyot", "Multikulturalizm"], "t": "Ommaviy madaniyat"},
    {"s": "Saralangan fuqarolarga emas, xalq ommasi ehtiyojlariga qaratilgan siyosiy nutq yoki pozitsiya?", "v": ["Populizm", "Elitizm", "Militarizatsiya", "Geostrategiya"], "t": "Populizm"},
    {"s": "Muayyan sohadagi barcha imkoniyatlar va vositalar yig‘indisi, keng ma'noda 'zaxira'?", "v": ["Pozitsiya", "Potensial", "Kapital", "Subsidiya"], "t": "Potensial"},
    {"s": "Ma'lum voqea yoki hodisaga nisbatan munosabat yoki holat?", "v": ["Taktika", "Potensial", "Pozitsiya", "Doktrina"], "t": "Pozitsiya"},
    {"s": "Mandatlar partiyalar o‘rtasida ular olgan ovozlar soniga mos ravishda bo‘linadigan saylov tizimi?", "v": ["Majoritar tizim", "Proporsional saylov tizimi", "Aralash tizim", "Elitar tizim"], "t": "Proporsional saylov tizimi"},
    {"s": "Ichki bozorni boj va subsidiyalar orqali chet el raqobatidan himoya qilish siyosati?", "v": ["Proteksionizm", "Erkin savdo", "Devalvatsiya", "Integratsiya"], "t": "Proteksionizm"},
    {"s": "XX asr oxiri-XXI asr boshlaridagi norozilik namoyishlari va hokimiyat almashinuvlarining umumiy nomi?", "v": ["Siyosiy aksiya", "Rangli inqilob", "Shok terapiyasi", "Neoliberal islohot"], "t": "Rangli inqilob"},
    {"s": "Harbiy asirlar, qochoqlar yoki emigrantlarning o‘z vatanga qaytishi nima?", "v": ["Immigratsiya", "Repatriatsiya", "Deportatsiya", "Emigratsiya"], "t": "Repatriatsiya"},
    {"s": "Qarz yoki kreditni to‘lash shartlarini qayta ko‘rib chiqish va o‘zgartirish jarayoni?", "v": ["Devalvatsiya", "Retsessiya", "Restrukturizatsiya", "Subsidiya"], "t": "Restrukturizatsiya"},
    {"s": "Iqtisodiyotda ishlab chiqarishning nisbatan mo’tadil pasayishi yoki o'sish sur'atlarining sekinlashuvi?", "v": ["Inqiroz", "Retsessiya", "Devalvatsiya", "Modernizatsiya"], "t": "Retsessiya"},
    {"s": "Keskin iqtisodiy nazariya va unga asoslangan shiddatli islohotlar qanday ataladi?", "v": ["Shok terapiyasi", "Neoliberalizm", "Proteksionizm", "Retsessiya"], "t": "Shok terapiyasi"},
    {"s": "Jamiyat ongiga ta'sir o'tkazish orqali siyosiy maqsadga erishish usullari?", "v": ["Geostrategiya", "Makrotexnologiya", "Siyosiy texnologiya", "Populizm"], "t": "Siyosiy texnologiya"},
    {"s": "Davlat yoki muassasa tomonidan alohida shaxs yoki muassasaga ko‘rsatiladigan moliyaviy yordam?", "v": ["Ssuda", "Kredit", "Subsidiya", "Kapital"], "t": "Subsidiya"},
    {"s": "Ko‘zlangan maqsadga erishish uchun qo‘llaniladigan usul va vositalar yig‘indisi?", "v": ["Strategiya", "Taktika", "Pozitsiya", "Potensial"], "t": "Taktika"},
    {"s": "O‘zgacha dunyoqarash, xulq-atvor va urf-odatlarga nisbatan sabr-bardoshli bo‘lish?", "v": ["Multikulturalizm", "Gumanizm", "Tolerantlik", "Pozitsiya"], "t": "Tolerantlik"},
    {"s": "Totalitar jamiyatda aholini ommaviy ravishda mafkuraviy qayta tarbiyalash vositasi?", "v": ["Totalitar mafkura", "Demokratik adabiyot", "Ommaviy madaniyat", "Populizm"], "t": "Totalitar mafkura"},
    {"s": "Bir nechta mamlakatda ishlab chiqarish bo‘limlariga ega bo‘lgan va xalqaro biznes bilan shug‘ullanuvchi kompaniya?", "v": ["Kartel", "Trest", "Transmilliy korporatsiya", "Konsern"], "t": "Transmilliy korporatsiya"},
    {"s": "'Sovuq urush' davrida ikki lagerga (AQSH va SSSR) kirmagan davlatlarga nisbatan qo‘llanilgan atama?", "v": ["Ikkinchi dunyo", "To‘rtinchi dunyo", "Uchinchi dunyo", "G‘arb dunyosi"], "t": "Uchinchi dunyo"},
    {"s": "Keskin konservativ qarashlarga ega bo'lgan mutaassib kishi qanday ataladi?", "v": ["Neokonservator", "Ultrakonservator", "Reaksioner", "Neofashist"], "t": "Ultrakonservator"},
    {"s": "Narsalarni bitta tizim yoki shaklga keltirish jarayoni qanday ataladi?", "v": ["Integratsiya", "Urbanizatsiya", "Unifikatsiya", "Modernizatsiya"], "t": "Unifikatsiya"},
    {"s": "Shaharlar soni ko‘payib, ularda iqtisodiy va madaniy hayotning jamlanishi jarayoni?", "v": ["Migratsiya", "Globallashuv", "Urbanizatsiya", "Industriya"], "t": "Urbanizatsiya"},
    {"s": "Yuqumli kasalliklarga qarshi emlashda qo‘llaniladigan vosita?", "v": ["Batsilla", "Antibiotik", "Vaksina", "Ferment"], "t": "Vaksina"}
]