# data_10jt_atamalar.py

testlar_10jt = [
    {"s": "Ijtimoiy hayotda bozor munosabatlari, huquqiy davlat va inson huquqlari muhim rol o‘ynaydigan jamiyat bosqichi qanday ataladi?", "v": ["Postindustrial sivilizatsiya", "Industrial sivilizatsiya", "Agrar sivilizatsiya", "An'anaviy jamiyat"], "t": "Industrial sivilizatsiya"},
    {"s": "Hukumat va boshqa huquq manbalari dinning har qanday turidan alohida boʻlishi kerakligi haqidagi tushuncha qaysi?", "v": ["Liberalizm", "Sekulyarlik", "Izolyatsionizm", "Avtarkiya"], "t": "Sekulyarlik"},
    {"s": "Buyuk Britaniyaning 1815-yildan Birinchi jahon urushiga qadar dengizda va xalqaro munosabatlarda hukmron bo'lgan davri qanday nomlanadi?", "v": ["Britaniya mandati", "Pax Britanica", "Dominion davri", "Kolonializm"], "t": "Pax Britanica"},
    {"s": "Ingliz qirolini davlat boshlig‘i deb tan oladigan, Britaniya imperiyasi tarkibidagi qaram davlat qanday atalgan?", "v": ["Metropoliya", "Dominion", "Protektorat", "Mandat hududi"], "t": "Dominion"},
    {"s": "1871-yilda Fransiyani qisqa muddat (72 kun) boshqargan muvaqqat hukumat qaysi?", "v": ["Direktoriya", "Parij kommunasi", "Milliy konvent", "Muvaqqat kengash"], "t": "Parij kommunasi"},
    {"s": "Oliy hokimiyat organi tomonidan chiqarilgan, qonun kuchiga ega boʻlgan muhim qaror qanday nomlanadi?", "v": ["Mandat", "Dekret", "Direktiva", "Sanksiya"], "t": "Dekret"},
    {"s": "Lotincha 'birga' va 'markaz' so'zlaridan olingan, biror narsaning muayyan joyda to'planishini anglatuvchi atama qaysi?", "v": ["Modernizatsiya", "Konsentratsiya", "Desentralizatsiyalash", "Integratsiya"], "t": "Konsentratsiya"},
    {"s": "Boshqa bir davlat hududini butunlay yoki qisman egallab olish yoki oʻz davlatiga qoʻshib olish siyosati nima deyiladi?", "v": ["Okkupatsiya", "Anneksiya", "Intervensiya", "Izolyatsionizm"], "t": "Anneksiya"},
    {"s": "Dastlab hukumat amaldorlari hokimiyatini, keyinchalik yirik tashkilotlardagi xizmatchilar qatlamini ifodalagan tushuncha qaysi?", "v": ["Aristokratiya", "Byurokratiya", "Demokratiya", "Meritokratiya"], "t": "Byurokratiya"},
    {"s": "Rossiyada podshoning cheklanmagan mustabid hokimiyatiga asoslangan davlat tuzumi qanday atalgan?", "v": ["Mutlaq monarxiya", "Samoderjaviye", "Harbiy xunta", "Avtoritarizm"], "t": "Samoderjaviye"},
    {"s": "Siyosiy hokimiyat birgina hukmdor yoki bir guruh shaxslarning irodasiga asoslangan davlat boshqaruvi usuli qaysi?", "v": ["Totalitarizm", "Avtoritar rejim", "Liberalizm", "Parlamentarizm"], "t": "Avtoritar rejim"},
    {"s": "Bir yoki bir necha davlatning boshqa bir davlat ichki ishlariga zoʻrlik bilan aralashishi nima deb ataladi?", "v": ["Anneksiya", "Intervensiya", "Okkupatsiya", "Sanksiya"], "t": "Intervensiya"},
    {"s": "Boshqa davlatlar va xalqlarning ishlariga aralashmaslik g‘oyasiga asoslangan tashqi siyosat yo‘nalishi qaysi?", "v": ["Ekpansionizm", "Izolyatsionizm", "Sekulyarlik", "Globalizm"], "t": "Izolyatsionizm"},
    {"s": "Biror shaxsning vakolatini yoki muayyan narsaga bo'lgan huquqini tasdiqlovchi hujjat qanday ataladi?", "v": ["Dekret", "Mandat", "Direktiva", "Veksell"], "t": "Mandat"},
    {"s": "'To'da' yoki 'birlashish' ma'nosini anglatuvchi, totalitar tipdagi siyosiy diktatura qaysi?", "v": ["Sotsializm", "Fashizm", "Liberalizm", "Demokratiya"], "t": "Fashizm"},
    {"s": "Xususiy mulkni ijtimoiy mulkka aylantirish orqali tenglik va farovonlikka erishishni ko'zlovchi ta'limot qaysi?", "v": ["Kapitalizm", "Sotsializm", "Fashizm", "Millatchilik"], "t": "Sotsializm"},
    {"s": "Urushayotgan tomon qurolli kuchlarining o'zga davlat yerlarini bosib olib, vaqtincha egallab turishi qanday ataladi?", "v": ["Anneksiya", "Okkupatsiya", "Intervensiya", "Avtarkiya"], "t": "Okkupatsiya"},
    {"s": "Muayyan sharoitda biron-bir g‘oyani mutlaqlashtirib, vaziyatni hisobga olmay ko‘r-ko‘rona qo‘llash nima deb ataladi?", "v": ["Konservatizm", "Aqidaparastlik", "Liberalizm", "Natsionalizm"], "t": "Aqidaparastlik"},
    {"s": "Fuqarolarning eng muhim davlat masalalari bo'yicha ovoz berish yo'li bilan o'z fikrini bevosita bildirishi nima?", "v": ["Saylov", "Referendum", "Forum", "Konferensiya"], "t": "Referendum"},
    {"s": "Kommunizm tamoyillarini qo'llab-quvvatlaydigan va unga ishonadigan shaxs kim?", "v": ["Liberal", "Kommunist", "Fashist", "Demokrat"], "t": "Kommunist"},
    {"s": "Hur fikrli, erkin shaxs hamda murosasozlik tarafdori bo'lgan inson qanday nomlanadi?", "v": ["Konservator", "Liberal", "Radikal", "Sotsialist"], "t": "Liberal"},
    {"s": "Dunyoda tinchlik o'rnatishga ulkan hissa qo'shgan shaxslarga beriladigan xalqaro mukofot qaysi?", "v": ["Buker mukofoti", "Tinchlik bo‘yicha Nobel mukofoti", "Oskar mukofoti", "Davlat mukofoti"], "t": "Tinchlik bo‘yicha Nobel mukofoti"},
    {"s": "Xususiy mulk bo'lgan korxona, bank yoki yerlarni davlat ixtiyoriga olish jarayoni nima deyiladi?", "v": ["Privatizatsiya", "Natsionalizatsiya", "Modernizatsiya", "Desentralizatsiyalash"], "t": "Natsionalizatsiya"},
    {"s": "Davlatlarning yoki siyosiy partiyalarning o'zaro ahdlashgan ittifoqi yoki kelishuvi qanday ataladi?", "v": ["Korporatsiya", "Koalitsiya", "Forum", "Konferensiya"], "t": "Koalitsiya"},
    {"s": "Daromadga nisbatan xarajatlarning oshib ketishi yoki biror narsaning yetishmasligi (tanqislik) nima deyiladi?", "v": ["Proffitsit", "Defitsit", "Inflyatsiya", "Kredit"], "t": "Defitsit"},
    {"s": "Ommaviy yig‘in, majlis, kengash yoki yirik anjuman tushunchasini ifodalovchi atama qaysi?", "v": ["Konferensiya", "Forum", "Direktiva", "Kasta"], "t": "Forum"},
    {"s": "Rivojlangan yirik aksiyadorlar jamiyati yoki biron-bir faoliyat uchun uyushgan yuridik shaxslar majmui qanday ataladi?", "v": ["Koalitsiya", "Korporatsiya", "Bank", "Shartnoma"], "t": "Korporatsiya"},
    {"s": "Muayyan masalani muhokama qilish uchun davlat, partiya yoki olimlar vakillarining yig‘ilishi nima deyiladi?", "v": ["Forum", "Konferensiya", "Dekret", "Referendum"], "t": "Konferensiya"},
    {"s": "Mamlakatning oʻz-oʻzini ta’minlashiga asoslangan, tashqi iqtisodiy aloqalardan uzilgan biqiq xoʻjalik siyosati qaysi?", "v": ["Bozor iqtisodiyoti", "Avtarkiya", "Liberalizm", "Modernizatsiya"], "t": "Avtarkiya"},
    {"s": "Markazlashgan tizimdan markazlashmagan tizimga oʻtish jarayoni qanday nomlanadi?", "v": ["Demokratizatsiyalash", "Desentralizatsiyalash", "Konsentratsiya", "Natsionalizatsiya"], "t": "Desentralizatsiyalash"},
    {"s": "Demokratik tamoyillarni siyosiy tizimga, madaniyatga va turmush tarziga joriy etish nima deb ataladi?", "v": ["Modernizatsiya", "Demokratizatsiyalash", "Sotsializm", "Sekulyarlik"], "t": "Demokratizatsiyalash"},
    {"s": "Bir qancha mustamlaka hududlariga ega bo‘lgan yoki imperator boshqaradigan davlat qanday ataladi?", "v": ["Respublika", "Imperiya", "Dominion", "Konfederatsiya"], "t": "Imperiya"},
    {"s": "Davlat toʻntarishi orqali hokimiyatga kelgan harbiylarning diktatorlik boshqaruvi nima deyiladi?", "v": ["Samoderjaviye", "Harbiy xunta", "Demokratiya", "Teokratiya"], "t": "Harbiy xunta"},
    {"s": "Biror narsani yangilash, zamonaviy talablar va me’yorlarga muvofiq oʻzgartirish jarayoni qaysi?", "v": ["Evolyutsiya", "Modernizatsiya", "Aqidaparastlik", "Rekonkista"], "t": "Modernizatsiya"},
    {"s": "Yuqori organlar tomonidan berilgan, bajarilishi majburiy bo‘lgan rasmiy ko‘rsatma yoki yo‘l-yo‘riq qanday ataladi?", "v": ["Mandat", "Direktiva", "Dekret", "Veksell"], "t": "Direktiva"},
    {"s": "XX asrning ikkinchi yarmidan rivojlangan mamlakatlarda vujudga kelgan ijtimoiy taraqqiyotning yangi bosqichi qaysi?", "v": ["Industrial sivilizatsiya", "Postindustrial sivilizatsiya", "Axborot sivilizatsiyasi", "Agrar jamiyat"], "t": "Postindustrial sivilizatsiya"},
    {"s": "Sovet hokimiyati, sovet turmush tarzi yoki SSSRga qarshi qaratilgan qarashlar tizimi nima deb atalgan?", "v": ["Kommunizm", "Antisovetizm", "Sotsializm", "Fashizm"], "t": "Antisovetizm"},
    {"s": "Hind jamoasiga xos bo'lgan murakkab ijtimoiy tabaqalanish tizimi qanday nomlanadi?", "v": ["Budun", "Kasta tizimi", "Yomenlar", "Sinyoriya"], "t": "Kasta tizimi"},
    {"s": "1963–1979-yillarda Eronda shoh Muhammad Rizo Pahlaviy tomonidan amalga oshirilgan islohotlar majmui qanday nomlangan?", "v": ["Madaniy inqilob", "“Oq inqilob”", "Islom inqilobi", "Sanoat to'ntarishi"], "t": "“Oq inqilob”"},
    {"s": "Xalqaro majburiyatlarni buzgan davlatga nisbatan qo'llaniladigan iqtisodiy yoki harbiy jazo chorasi nima deyiladi?", "v": ["Direktiva", "Sanksiya", "Mandat", "Veksell"], "t": "Sanksiya"},
    {"s": "Butun hokimiyat harbiylarga tegishli bo'lgan, odatda to'ntarish orqali o'rnatiladigan boshqaruv shakli qaysi?", "v": ["Demokratik rejim", "Harbiy rejim", "Mutlaq monarxiya", "Avtoritarizm"], "t": "Harbiy rejim"},
    {"s": "Asosiy boyligi qishloq xo'jaligi bo'lgan, lekin sanoati uni qayta ishlashga yo'naltirilgan mamlakat turi qaysi?", "v": ["Industrial mamlakat", "Agrar-industrial mamlakat", "Postindustrial mamlakat", "Xomashyo bazasi"], "t": "Agrar-industrial mamlakat"},
    {"s": "Biror aholi guruhini irqi, millati yoki diniga ko'ra yoppasiga jismonan qirib yuborish jinoyati qanday ataladi?", "v": ["Aparteid", "Genotsid", "Anneksiya", "Sanksiya"], "t": "Genotsid"},
    {"s": "Irqiy kamsitishning eng ashaddiy va shafqatsiz ko'rinishi qaysi?", "v": ["Genotsid", "Aparteid", "Kasta", "Antisemitizm"], "t": "Aparteid"},
    {"s": "Ishlanayotgan narsalarni bir ish joyidan ikkinchisiga uzluksiz yetkazib beruvchi lentasimon transport qurilmasi qanday ataladi?", "v": ["Karavella", "Konveyer", "Lokomotiv", "Robot"], "t": "Konveyer"},
    {"s": "XX asr oxirlarida falsafa va san'atda modernizm an'analaridan chekinishni ifodalagan yo'nalish qaysi?", "v": ["Realizm", "Postmodernizm", "Klassitsizm", "Romantizm"], "t": "Postmodernizm"},
]