# data_7ut_atamalar.py

atamalar_7ut = [
    {"s": "Oliy darajadagi ilmiy tadqiqotlar bilan shug'ullanuvchi eng yuqori ilmiy tashkilot qanday ataladi?", "v": ["Akademiya", "Madrasa", "Kollegiya", "Skriptoriya"], "t": "Akademiya"},
    {"s": "Islom dinidagi eng muhim vazifalar, dindagi suyanchiq va ma'muriy ishlarni anglatuvchi atama qaysi?", "v": ["Tariqat", "Arkon", "Tasavvuf", "Xutba"], "t": "Arkon"},
    {"s": "Mahalliy aholiga yuklatilgan saroy, yo'l, inshootlar qurilishida ommaviy ishlab berish (hashar) majburiyati nima deb atalgan?", "v": ["Xiroj", "Begor", "Zakot", "Ushr"], "t": "Begor"},
    {"s": "Shahar va qishloq bozorlarida savdogarlardan olinadigan maxsus to‘lov yoki soliq qanday nomlangan?", "v": ["Zakot", "Boj", "Begor", "Jizya"], "t": "Boj"},
    {"s": "Turk xoqonligi davrida chorvador aholi qanday nom bilan atalgan?", "v": ["Kadivar", "Budun", "Chokar", "Kashovarz"], "t": "Budun"},
    {"s": "Ilk o'rta asrlarda dehqon mulkini qo'riqlovchi harbiy posbonlar qanday nomlangan?", "v": ["Budun", "Chokar", "Kadivar", "Kashovarz"], "t": "Chokar"},
    {"s": "Ilk o'rta asrlarda qishloq hokimi hamda mulkdor tabaqaning umumiy nomi qanday bo'lgan?", "v": ["Kadivar", "Dehqon", "Kashovarz", "Ixshid"], "t": "Dehqon"},
    {"s": "Mo‘g‘ullar davlatida mahalliy hokimlar huzuridagi qoon vakili, aholini ro'yxatga olish va soliq yig'ishga mas'ul shaxs kim?", "v": ["Beklarbegi", "Dorug‘a", "Bosqoq", "Sherif"], "t": "Dorug‘a"},
    {"s": "Kelib chiqishi yaqin turli qabila va elatlarning asrlar davomida qo‘shilib borishi jarayoni nima deb ataladi?", "v": ["Assimilyatsiya", "Etnik jarayon", "Evolyutsiya", "Integratsiya"], "t": "Etnik jarayon"},
    {"s": "O'rta asrlarda davlat hukmdori tomonidan chiqarilgan va qonun kuchiga ega bo'lgan buyruq qanday ataladi?", "v": ["Yorliq", "Farmon", "Patta", "Indulgensiya"], "t": "Farmon"},
    {"s": "Arab tilidan olingan bo'lib, 'egallash', 'zabt etish' yoki 'bosib olish' ma'nosini bildiruvchi atamani toping?", "v": ["Islom", "Fath", "G'oziy", "Hojib"], "t": "Fath"},
    {"s": "O'rta asrlarda O'rta Osiyoda misdan yasalgan mayda chaqa pul qanday nomlangan?", "v": ["Numisma", "Fulus", "Dinor", "Dirham"], "t": "Fulus"},
    {"s": "Haq din yo‘lida kurashuvchi jangchilar qanday nom bilan atalgan?", "v": ["Chokar", "G‘oziy", "Sarbador", "Drujina"], "t": "G‘oziy"},
    {"s": "Muhammad payg'ambar (s.a.v.)ning faoliyati va ko'rsatmalari haqidagi rivoyat va naqllar yig'indisi qaysi?", "v": ["Qur'on", "Hadis", "Tariqat", "Tasavvuf"], "t": "Hadis"},
    {"s": "Arab xalifaligi va keyingi davrlarda qo'llanilgan maxsus harbiy unvon egasi kim?", "v": ["Vazir", "Hojib", "Dorug'a", "Ixshid"], "t": "Hojib"},
    {"s": "Arabcha 'chek' ma'nosini beruvchi, hukmdor tomonidan katta xizmatlar uchun in'om qilingan chek yer qanday ataladi?", "v": ["Suyurg'ol", "Iqto", "Allod", "Benefitsiy"], "t": "Iqto"},
    {"s": "Mavjud tartibni yoki qonun-qoidalarni o'zgartirish maqsadida o'tkaziladigan chora-tadbirlar nima deb ataladi?", "v": ["Inqilob", "Islohot", "Fath", "Begor"], "t": "Islohot"},
    {"s": "Arab xalifaligi davrida alohida qo'shin qo'mondonlari hamda zabt etilgan viloyatlar noiblari qanday unvonga ega bo'lgan?", "v": ["Vazir", "Amir", "Ixshid", "Hojib"], "t": "Amir"},
    {"s": "Ilk o'rta asrlarda Sug'd kabi hududlarda viloyat hokimlariga berilgan unvon qaysi?", "v": ["Xoqon", "Ixshid", "Yabg'u", "Shod"], "t": "Ixshid"},
    {"s": "Islom dinini qabul qilmagan aholidan olinadigan jon solig'i qanday nomlangan?", "v": ["Xiroj", "Jizya", "Zakot", "Ushr"], "t": "Jizya"},
    {"s": "Mo'g'ulistonning g'arbiy qismida (Yettisuvda) shakllangan guruhga nisbatan ishlatilgan 'Jete' so'zi qanday ma'noni anglatadi?", "v": ["Qahramon", "Qaroqchi, talonchi", "Ko'chmanchi", "Jangchi"], "t": "Qaroqchi, talonchi"},
    {"s": "Qishloqning dehqonlarga qaram bo'lgan aholisi qanday nomlangan?", "v": ["Kashovarz", "Kadivar", "Budun", "Chokar"], "t": "Kadivar"},
    {"s": "Savdo yo'llari ustida karvonlar to'xtab o'tadigan mehmonxona, saroy yoki raboat qanday ataladi?", "v": ["Madrasa", "Karvonsaroy", "Xonaqoh", "Ratusha"], "t": "Karvonsaroy"},
    {"s": "Chingizxon o‘g‘li Chig‘atoyga meros bo‘lib tekkan va keyinchalik mustaqil davlatga aylangan hudud qanday nomlangan?", "v": ["Oltin O'rda", "Chig‘atoy ulusi", "Elxonlar davlati", "Movarounnahr"], "t": "Chig‘atoy ulusi"},
    {"s": "O'rta asrlarda oddiy qo'shchi va ziroatchilar qanday nomlangan?", "v": ["Dehqon", "Kashovarz", "Kadivar", "Budun"], "t": "Kashovarz"},
    {"s": "O'rta asr shaharlarining eng baland va mustahkam qismi, ya'ni hokim qasri joylashgan joy qanday ataladi?", "v": ["Shahriston", "Ko‘handiz (Ark)", "Rabod", "Burg"], "t": "Ko‘handiz (Ark)"},
    {"s": "Kitoblar va qo'lyozmalarga lavha (naqsh) chizish san'ati qanday nomlanadi?", "v": ["Sahhoflik", "Lavvohlik", "Miniatyura", "Piktografiya"], "t": "Lavvohlik"},
    {"s": "Musulmonlarning o'rta va oliy o'quv yurti qanday ataladi?", "v": ["Maktab", "Madrasa", "Kollegiya", "Akademiya"], "t": "Madrasa"},
    {"s": "Arabchada 'sajda qilinadigan joy' ma'nosini bildiruvchi musulmonlar ibodatxonasi qaysi?", "v": ["Madrasa", "Masjid", "Xonaqoh", "Sinagoga"], "t": "Masjid"},
    {"s": "VIII asrda Movarounnahrda arablarga qarshi qo'zg'olon ko'targan 'Niqobdor' laqabli shaxsning nomi nima edi?", "v": ["Abu Muslim", "Muqanna", "Sarbador", "G'oziy"], "t": "Muqanna"},
    {"s": "O'rta asrlarda xususiy mulk bo'lgan yerlar nima deb atalgan?", "v": ["Mulki devon", "Mulk", "Mulki vaqf", "Mulki inju"], "t": "Mulk"},
    {"s": "Bevosita davlat ixtiyorida bo'lgan yerlar qanday nomlangan?", "v": ["Mulki inju", "Mulki devon", "Mulki vaqf", "Mulk"], "t": "Mulki devon"},
    {"s": "Hukmdor va uning yaqinlariga (noiblarga) tegishli bo'lgan yerlar nima deb atalgan?", "v": ["Mulki vaqf", "Mulki inju", "Mulki devon", "Allod"], "t": "Mulki inju"},
    {"s": "Masjid, madrasa va boshqa diniy muassasalar tasarrufidagi yerlar qanday nomlanadi?", "v": ["Mulk", "Mulki vaqf", "Mulki inju", "Benefitsiy"], "t": "Mulki vaqf"},
    {"s": "Barcha hududlari yagona hukmdor hokimiyati tomonidan idora qilinuvchi davlat qanday ataladi?", "v": ["Tarqoq davlat", "Mustahkam markazlashgan davlat", "Federatsiya", "Konfederatsiya"], "t": "Mustahkam markazlashgan davlat"},
    {"s": "Mo'g'ullarda 'Duragay' ma'nosini anglatuvchi atama qaysi?", "v": ["Jete", "Qoraunas", "Ulus", "Budun"], "t": "Qoraunas"},
    {"s": "Turk xoqonligi davrida Ko‘k Tangriga sig‘inuvchi yakkaxudolik dini qanday nomlangan?", "v": ["Islom", "Qam-shomon", "Buddaviylik", "Mazdaklik"], "t": "Qam-shomon"},
    {"s": "Chorva mollari bosh sonining 2,5% miqdorida (40 tadan bitta) olinadigan mo'g'ullar davri solig'i qaysi?", "v": ["Ushr", "Qopchur", "Tamg'a", "Xiroj"], "t": "Qopchur"},
    {"s": "Shaharning savdo va hunarmandchilik mahallalari joylashgan tashqi mavzesi nima deb ataladi?", "v": ["Shahriston", "Rabod", "Ark", "Burg"], "t": "Rabod"},
    {"s": "O'rta asrlarda dastlab g'oziylar uchun qurilgan mustahkamlangan qarorgoh, keyinchalik mehmonxona vazifasini o'tagan bino qaysi?", "v": ["Madrasa", "Rabot", "Xonaqoh", "Masjid"], "t": "Rabot"},
    {"s": "Osmon jismlarini kuzatish uchun maxsus jihozlangan ilmiy muassasa qanday ataladi?", "v": ["Akademiya", "Rasadxona (Observatoriya)", "Skriptoriya", "Madrasa"], "t": "Rasadxona (Observatoriya)"},
    {"s": "Qog'ozni sahifalash va kitobni muqovalash bilan shug'ullanuvchi kasb egalari qanday nomlangan?", "v": ["Lavvohlik", "Sahhoflik", "Miniatyura", "Kotiblik"], "t": "Sahhoflik"},
    {"s": "XIV asrda Movarounnahrda mo'g'ul zulmiga qarshi chiqqan 'boshini dorga tikkanlar' harakati qanday ataladi?", "v": ["G'oziylar", "Sarbadorlar", "Muqannachilar", "Vikinglar"], "t": "Sarbadorlar"},
    {"s": "Osmon yoritqichlarining balandligini belgilash uchun ishlatiladigan ko'zgu-qaytargichli asbob qaysi?", "v": ["Kompas", "Sekstant", "Astrolyabiya", "Mikroskop"], "t": "Astrolyabiya"},
    {"s": "O'rta asr shaharlarining devor bilan o'ralgan asosiy ichki qismi qanday nomlangan?", "v": ["Rabod", "Shahriston", "Ark", "Burg"], "t": "Shahriston"},
    {"s": "Turk xoqonligida o‘n ming kishilik qo‘shin qo‘mondoni unvoni qanday bo'lgan?", "v": ["Yabg'u", "Shod", "Ixshid", "Hojib"], "t": "Shod"},
    {"s": "Bozorlarda savdogarlardan olinadigan savdo boji qanday nomlangan?", "v": ["Xiroj", "Tamg‘a", "Zakot", "Qopchur"], "t": "Tamg‘a"},
    {"s": "Komil inson darajasiga erishish yo'li, tasavvuf qoidalariga amal qilib yashash qanday ataladi?", "v": ["Islohot", "Tariqat", "Tasavvuf", "Arkon"], "t": "Tariqat"},
    {"s": "Musulmonlarni halollikka, poklikka va o'z mehnati bilan yashashga chorlovchi diniy-falsafiy ta'limot qaysi?", "v": ["Islom", "Tasavvuf (sufiylik)", "Tariqat", "Hadis"], "t": "Tasavvuf (sufiylik)"},
    {"s": "Turkiy aholi o‘rnashgan o‘lka tarixda qanday nom bilan atalgan?", "v": ["Movarounnahr", "Turkiston", "Xuroson", "Denlo"], "t": "Turkiston"},
    {"s": "Mo'g'ullar davrida qabila begi yoki hukmdorga nisbatan ishlatilgan atama qaysi?", "v": ["Xoqon", "O‘zbek", "Beklarbegi", "Dorug'a"], "t": "O‘zbek"},
    {"s": "Islom dinini chuqur biladigan din olimlari qanday nomlangan?", "v": ["G'oziylar", "Ulamo", "Sarbadorlar", "Shkolyarlar"], "t": "Ulamo"},
    {"s": "Arabcha 'o'ndan bir' ma'nosini beruvchi, hosilning 1/10 qismi hajmida olinadigan soliq qaysi?", "v": ["Xiroj", "Ushr", "Zakot", "Tamg'a"], "t": "Ushr"},
    {"s": "Davlat devonxona ishlarini boshqaruvchi eng yuqori lavozimli amaldor kim?", "v": ["Hojib", "Vazir", "Amir", "Ixshid"], "t": "Vazir"},
    {"s": "Dehqonchilik hosilining 1/3 qismi hajmida olinadigan asosiy yer solig'i qanday ataladi?", "v": ["Ushr", "Xiroj", "Zakot", "Kalon"], "t": "Xiroj"},
    {"s": "Musofirlar, dervishlar va g'ariblar tunab qoladigan maxsus bino qanday nomlangan?", "v": ["Madrasa", "Xonaqoh", "Ratusha", "Rabod"], "t": "Xonaqoh"},
    {"s": "Markaziy Osiyo xalqlari tarixida buyuk hukmdor, imperator darajasidagi shaxslar qanday unvon bilan atalgan?", "v": ["Amir", "Xoqon", "Ixshid", "Vazir"], "t": "Xoqon"},
    {"s": "Juma namozida hukmdor nomini aytib, uning haqiga duo o‘qish marosimi qanday ataladi?", "v": ["Azon", "Xutba", "Tariqat", "Arkon"], "t": "Xutba"},
    {"s": "Xoqon urug‘idan bo‘lgan va ma'lum bir hududni (yurtni) boshqargan hokim unvoni qaysi?", "v": ["Shod", "Yabg‘u", "Ixshid", "Hojib"], "t": "Yabg‘u"},
    {"s": "Dehqonlar va chorvadorlardan olinadigan umumiy majburiy soliq mo'g'ullar davrida nima deb atalgan?", "v": ["Tamg'a", "Yasoq", "Begor", "Boj"], "t": "Yasoq"},
    {"s": "Chopar va yo'lovchilar ot almashtiradigan maxsus yo'l bekatlari nima deb ataladi?", "v": ["Rabot", "Yomlar", "Karvonsaroy", "Xonaqoh"], "t": "Yomlar"},
    {"s": "Mol-mulkning (boylikning) 1/40 qismi hajmida muhtojlar uchun olinadigan majburiy soliq (sadaqa) qaysi?", "v": ["Ushr", "Zakot", "Xiroj", "Jizya"], "t": "Zakot"}
]