# data_11ut_atamalar.py

atamalar_11ut = [
    {"s": "Uchish apparatlarini maxsus asboblar yordamida belgilangan yo‘ldan olib borish haqidagi fan?", "v": ["Logistika", "Aeronavigatsiya", "Strategiya", "Magistral"], "t": "Aeronavigatsiya"},
    {"s": "Sud hukmi bilan jazo tayinlangan shaxsni davlat boshlig‘i qarori bilan jazo muddatidan ozod qilish?", "v": ["Sanksiya", "Yurisdiksiya", "Afv etish", "Referendum"], "t": "Afv etish"},
    {"s": "Oliy ta’lim dasturining birinchi bosqichini (tayanch bosqich) tugallagan talabalarning ilmiy darajasi?", "v": ["Bakalavr", "Magistr", "Fan doktori", "Dotsent"], "t": "Bakalavr"},
    {"s": "'Xalqaro', 'millatlararo' va 'umuminsoniy' kabi ma'nolarni anglatuvchi arabcha atama?", "v": ["Konfessiya", "Referendum", "Baynalmilal", "Mentalitet"], "t": "Baynalmilal"},
    {"s": "Davlat chegaralarini shartnomaga muvofiq xaritalarda tavsiflash va belgilash jarayoni nima?", "v": ["Demarkatsiya", "Delimitatsiya", "Konvertatsiya", "Integratsiya"], "t": "Delimitatsiya"},
    {"s": "Vakolatli davlat organiga (masalan, Oliy Majlisga) saylangan xalq vakili kim?", "v": ["Deputat", "Magistr", "Bakalavr", "Shafe"], "t": "Deputat"},
    {"s": "Iqtisodiy bankrotlikni oldini olish uchun mahsulot turini kengaytirish va yangi bozorlarga ixtisoslashish?", "v": ["Modernizatsiya", "Innovatsiya", "Diversifikatsiya", "Konvertatsiya"], "t": "Diversifikatsiya"},
    {"s": "Biror ilmiy yoki falsafiy ta’limot, nazariya yoki asosiy siyosiy nuqtayi nazar qanday ataladi?", "v": ["Konsepsiya", "Doktrina", "Strategiya", "Sanksiya"], "t": "Doktrina"},
    {"s": "Ma’lum xarajatlarni qoplash uchun davlat tomonidan pul mablag‘ining qaytarib bermaslik sharti bilan berilishi?", "v": ["Dotatsiya", "Ssuda", "Kredit", "Fond"], "t": "Dotatsiya"},
    {"s": "San’at sohasidagi yutuqlar bo‘yicha o‘tkaziladigan ommaviy bayram va ko‘rik-tanlov?", "v": ["Simpozium", "Sessiya", "Festival", "Sammit"], "t": "Festival"},
    {"s": "Binoning ikki qismini birlashtiruvchi usti yopiq uzun yo‘lak yoki tomosha zalining yuqori qismi?", "v": ["Magistral", "Galereya", "Infratuzilma", "Inshoot"], "t": "Galereya"},
    {"s": "Organizmning kimyoviy xususiyatlari va uning immuniteti (himoya qobiliyati) haqidagi fan?", "v": ["Demografiya", "Immunologiya", "Skrining", "Fiziologiya"], "t": "Immunologiya"},
    {"s": "Jamiyat hayoti va ishlab chiqarish uchun zarur sharoitni ta’minlovchi yordamchi sohalar majmui?", "v": ["Logistika", "Diversifikatsiya", "Infratuzilma", "Integratsiya"], "t": "Infratuzilma"},
    {"s": "Ilg‘or texnologiya va boshqarish sohasiga kiritilgan yangiliklar hamda ixtirolar nima deyiladi?", "v": ["Innovatsiya", "Modernizatsiya", "Diversifikatsiya", "Konsepsiya"], "t": "Innovatsiya"},
    {"s": "Ayrim qismlarning yoki fanlarning bir-biriga yaqinlashishi va o‘zaro bog‘lanish jarayoni?", "v": ["Globallashuv", "Integratsiya", "Unifikatsiya", "Delimitatsiya"], "t": "Integratsiya"},
    {"s": "Diniy ishonch, e’tiqod va mazhab ma’nosini anglatuvchi lotincha atama?", "v": ["Prozelitizm", "Tolerantlik", "Konfessiya", "Doktrina"], "t": "Konfessiya"},
    {"s": "Biror sohani rivojlantirishga qaratilgan keng qamrovli loyiha yoki qarashlar majmui?", "v": ["Strategiya", "Taktika", "Konsepsiya", "Doktrina"], "t": "Konsepsiya"},
    {"s": "Milliy valyutaning xorijiy valyutalarga erkin va cheklanmagan miqdorda almashtirilishi?", "v": ["Konvertatsiya", "Devalvatsiya", "Revalvatsiya", "Dotatsiya"], "t": "Konvertatsiya"},
    {"s": "Inson faoliyatining u yoki bu sohasini moddiy-texnik ta’minlashni boshqarish tizimi?", "v": ["Infratuzilma", "Strategiya", "Logistika", "Diversifikatsiya"], "t": "Logistika"},
    {"s": "Bakalavr va fan doktori o‘rtasidagi, tayanch kursdan so‘ng maxsus dastur asosida beriladigan ilmiy daraja?", "v": ["Magistr", "Bakalavr", "Dotsent", "Akademik"], "t": "Magistr"},
    {"s": "Asosiy qatnov yo‘li yoki tarmoqlangan sistemalarning bosh, markaziy qismi?", "v": ["Galereya", "Infratuzilma", "Magistral", "Trassa"], "t": "Magistral"},
    {"s": "Jamiyat yoki millatning tarixiy tarkib topgan tafakkur darajasi va rasm-rusumlari majmui?", "v": ["Mafkura", "Mentalitet", "Konfessiya", "Ma’rifat"], "t": "Mentalitet"},
    {"s": "Davlat, jamiyat yoki texnologiyaning yangi uslublar asosida yangilanishi va zamonaviylashishi?", "v": ["Innovatsiya", "Modernizatsiya", "Diversifikatsiya", "Integratsiya"], "t": "Modernizatsiya"},
    {"s": "Muayyan ijtimoiy guruh manfaatlarini himoya qiluvchi g‘oyadosh kishilarning siyosiy tashkiloti?", "v": ["Jamoa", "Kasaba uyushmasi", "Partiya", "Elita"], "t": "Partiya"},
    {"s": "Bir diniy konfessiyadagi dindorlarni o‘zga dinga (mazhabga) kiritishga qaratilgan harakat?", "v": ["Prozelitizm", "Missionerlik", "Konfessiya", "Tolerantlik"], "t": "Prozelitizm"},
    {"s": "Davlat ahamiyatiga ega muhim masalalar bo‘yicha o‘tkaziladigan umumxalq ovoz berish yo‘li?", "v": ["Saylov", "Referendum", "Sessiya", "Simpozium"], "t": "Referendum"},
    {"s": "Ikki yoki bir necha davlat boshliqlarining oliy darajadagi uchrashuvi va kengashi?", "v": ["Sammit", "Simpozium", "Festival", "Sessiya"], "t": "Sammit"},
    {"s": "Huquqbuzarga nisbatan qo‘llaniladigan va uning uchun muayyan oqibatlar keltiruvchi jazo chorasi?", "v": ["Dekret", "Nota", "Sanksiya", "Veto"], "t": "Sanksiya"},
    {"s": "Ruhoniylar yoki boshlang‘ich maktab o‘qituvchilari tayyorlaydigan maxsus o‘quv yurti?", "v": ["Gimnaziya", "Litsey", "Seminariya", "Kollej"], "t": "Seminariya"},
    {"s": "Vakolatli organlarning (Oliy Majlis, sud) ma’lum davr ichida o‘tkazadigan majlislar turkumi?", "v": ["Simpozium", "Sessiya", "Sammit", "Kongress"], "t": "Sessiya"},
    {"s": "Birovga yon bosuvchi, homiylik qiluvchi yoki vositachi ma’nosini anglatuvchi atama?", "v": ["Deputat", "Magistr", "Shafe", "Vasiy"], "t": "Shafe"},
    {"s": "Biror ilmiy masala bo‘yicha o‘tkaziladigan xalqaro ilmiy kengash yoki anjuman?", "v": ["Simpozium", "Sammit", "Sessiya", "Seminariya"], "t": "Simpozium"},
    {"s": "Kasallikni erta aniqlash maqsadida aholini maxsus usullar yordamida ommaviy tekshirish?", "v": ["Monitoring", "Skrining", "Tashxis", "Ekspertiza"], "t": "Skrining"},
    {"s": "Maqsadga erishish uchun uzoq muddatga mo‘ljallangan ta’sir vositalari va uslublari majmui?", "v": ["Taktika", "Strategiya", "Reja", "Konsepsiya"], "t": "Strategiya"},
    {"s": "O‘zgalarning fikir, e’tiqodi va turmush tarziga nisbatan bag‘rikeng va sabrli bo‘lish?", "v": ["Tolerantlik", "Sanksiya", "Mentalitet", "Konfessiya"], "t": "Tolerantlik"},
    {"s": "Bir necha davlat hududidan o‘tuvchi (daryo yoki yo‘llarga nisbatan) chegaralararo tushuncha?", "v": ["Baynalmilal", "Integratsiya", "Transchegaraviy", "Delimitatsiya"], "t": "Transchegaraviy"},
    {"s": "Huquqiy masalalarni hal qilish va sudlov ishlarini olib borish huquqi, vakolat sohasi?", "v": ["Sanksiya", "Konsepsiya", "Yurisdiksiya", "Arbitraj"], "t": "Yurisdiksiya"}
]