# data_ixtirolar.py

ixtirolar_toplami = [
    {"s": "1. 1876-yilda 'Elektr shami'ni ixtiro qilgan Rus olimi kim?", "v": ["Tomas Edison", "P. N. Yablochkov", "Aleksandr Popov", "Monye"], "t": "P. N. Yablochkov"},
    {"s": "2. 1879-yilda 'Havosi so‘rib olingan ko‘mir tolali cho‘g‘lanish lampasi'ni kim yaratgan?", "v": ["P. N. Yablochkov", "Tomas Edison", "Aleksandr Bell", "G. Gers"], "t": "Tomas Edison"},
    {"s": "3. 1879-yilda dunyoda birinchi bo'lib issiqlik elektr stansiyasini (IES) kim qurgan?", "v": ["Tomas Edison", "Monye", "R. Kirxgof", "Tomson"], "t": "Tomas Edison"},
    {"s": "4. 1879-yilda 'Fonograf' (ovoz yozish va takror eshitish apparati) ixtirochisi kim?", "v": ["Aleksandr Bell", "Aleksandr Popov", "Tomas Edison", "Guglielmo Markoni"], "t": "Tomas Edison"},
    {"s": "5. Qurilishda 'Temir-beton' ixtirosi kimning nomi bilan bog‘liq?", "v": ["Eyfel", "Monye", "L. Bakeland", "I. A. Time"], "t": "Monye"},
    {"s": "6. 1889-yilda Fransiyada faqat metalldan yasalgan, 300 metrli minorani kim barpo etgan?", "v": ["Monye", "R. Kirxgof", "Eyfel", "K. Ader"], "t": "Eyfel"},
    {"s": "7. Metallurgiyada avtomatlashtirish jarayoniga kim asos solgan?", "v": ["R. Kirxgof", "G. Daymler", "I. A. Time", "Charlz Bebbij"], "t": "R. Kirxgof"},
    {"s": "8. XX asr boshida 'Plastmassa olish yo‘li'ni ixtiro qilgan Belgiyalik olim kim?", "v": ["Jozef Mari Jakkard", "L. Sperri", "L. Bakeland", "Tomson"], "t": "L. Bakeland"},
    {"s": "9. Metall kesish jarayonini ilmiy jihatdan tekshirishga asos solgan Rus olimi kim?", "v": ["N. I. Kibalchich", "I. A. Time", "Aleksandr Popov", "N. Y. Jukovskiy"], "t": "I. A. Time"},
    {"s": "10. 'Elektr bilan payvandlash' usulini kashf etgan Amerikalik ixtirochi kim?", "v": ["Tomson", "Tomas Edison", "G. Daymler", "R. Dizel"], "t": "Tomson"},
    {"s": "11. Germaniyada benzin bilan ishlaydigan yengil dvigatel va ilk avtomobilni kim yaratgan?", "v": ["R. Dizel", "G. Daymler", "Karl Bens", "Vilgelm Rentgen"], "t": "G. Daymler"},
    {"s": "12. 1897-yilda yonilg‘i siqilganda o‘z-o‘zidan alangalanadigan yangi turdagi dvigatelni kim ixtiro qildi?", "v": ["G. Daymler", "Karl Bens", "R. Dizel", "Eyfel"], "t": "R. Dizel"},
    {"s": "13. Birinchi aeroplanlarni yaratish ustida ishlagan Rus, Ingliz va Fransuz ixtirochilari kimlar?", "v": ["Rayt birodarlari", "A.F. Mojayskiy, G. Filipps, K. Ader", "L. Sperri va N. I. Kibalchich", "Charlz Bebbij va Jakkard"], "t": "A.F. Mojayskiy, G. Filipps, K. Ader"},
    {"s": "14. 1903-yilda ilk bor samolyotda uchishni muvaffaqiyatli amalga oshirganlar kim?", "v": ["A.F. Mojayskiy", "K. Ader", "Uilber va Orvill Raytlar", "L. Sperri"], "t": "Uilber va Orvill Raytlar"},
    {"s": "15. 'Raqamli hisoblash mashinasi' g'oyasi muallifi bo'lgan Ingliz olimi kim?", "v": ["Charlz Bebbij", "Jozef Mari Jakkard", "Tomson", "Aleksandr Bell"], "t": "Charlz Bebbij"},
    {"s": "16. Tikuv mashinalarini dasturlashtirish ixtirosi muallifi kim?", "v": ["Charlz Bebbij", "Jozef Mari Jakkard", "Monye", "Eyfel"], "t": "Jozef Mari Jakkard"},
    {"s": "17. Samolyotlarni avtomatik boshqarish (avtopilot) tizimini yaratgan Amerikalik kim?", "v": ["Uilber Rayt", "Aleksandr Bell", "L. Sperri", "Tomas Edison"], "t": "L. Sperri"},
    {"s": "18. Raketaplan loyihasini ishlab chiqqan ixtirochi kim?", "v": ["N. I. Kibalchich", "Aleksandr Popov", "G. Gers", "I. A. Time"], "t": "N. I. Kibalchich"},
    {"s": "19. Elektromagnit to‘lqinlar tarqalishini jahonda birinchi bo‘lib tajribada isbotlagan Nemis olimi kim?", "v": ["Vilgelm Rentgen", "G. Gers", "Albert Eynshteyn", "R. Kirxgof"], "t": "G. Gers"},
    {"s": "20. 1896-yilda simsiz aloqa (radio) uchun asboblar yaratgan va birinchi radiotelegramma uzatgan Rus olimi kim?", "v": ["Guglielmo Markoni", "Tomas Edison", "Aleksandr Popov", "P. N. Lebedev"], "t": "Aleksandr Popov"},
    {"s": "21. 1897-yilda radio signallarni uzoq masofaga uzatish qurilmasiga patent olgan Italyan ixtirochisi kim?", "v": ["Guglielmo Markoni", "Aleksandr Popov", "Aleksandr Bell", "Monye"], "t": "Guglielmo Markoni"},
    {"s": "22. Telefon apparatiga birinchi bo‘lib imtiyoznoma olgan Shotlandiyalik ixtirochi kim?", "v": ["Tomas Edison", "Aleksandr Popov", "Aleksandr Bell", "Guglielmo Markoni"], "t": "Aleksandr Bell"},
    {"s": "23. 'Irsiyat qonunlari'ni kashf etib, genetika faniga asos solgan olim kim?", "v": ["Charlz Darvin", "G. Mendel", "Lui Paster", "Robert Kox"], "t": "G. Mendel"},
    {"s": "24. Inson xatti-harakatining negizida bosh miya qobig‘idagi fiziologik jarayonlar yotishini isbotlagan Rus olimi kim?", "v": ["I. P. Pavlov", "I. Mechnikov", "F. A. Lesh", "Lui Paster"], "t": "I. P. Pavlov"},
    {"s": "25. 1900-yilda xilma-xil organik moddalarni sintez qilish usulini yaratgan olim kim?", "v": ["P. Griss", "S. Arrenius", "V. Grinyar", "M. G. Kucherov"], "t": "V. Grinyar"},
    {"s": "26. 'Diazotlash reaksiyasi'ni kashf etib, azotli bo‘yoqlar sinfiga yo'l ochgan olim kim?", "v": ["P. Griss", "V. Grinyar", "S. Arrenius", "M. G. Kucherov"], "t": "P. Griss"},
    {"s": "27. 1887-yilda 'Elektrolitik dissotsiatsiya nazariyasi'ni yaratgan Shved olimi kim?", "v": ["M. G. Kucherov", "S. Arrenius", "Robert Kox", "Lui Paster"], "t": "S. Arrenius"},
    {"s": "28. 1881-yilda 'Gidratlanish reaksiyasi'ni kashf etgan olim kim?", "v": ["S. Arrenius", "V. Grinyar", "M. G. Kucherov", "P. Griss"], "t": "M. G. Kucherov"},
    {"s": "29. Barcha organizmlarning hujayrali tuzilishi haqidagi kashfiyot muallifi bo‘lgan Nemis olimi kim?", "v": ["T. Shvan", "Charlz Darvin", "Robert Kox", "R. Virxov"], "t": "T. Shvan"},
    {"s": "30. Evolyutsiya nazariyasi va 'Turlarning kelib chiqishi' asari muallifi bo‘lgan Ingliz olimi kim?", "v": ["T. Shvan", "G. Mendel", "Charlz Darvin", "Lui Paster"], "t": "Charlz Darvin"},
    {"s": "31. Mahsulotlarni sterillash (pasterlash) va quturishga qarshi emlash usullarini yaratgan olim kim?", "v": ["Robert Kox", "I. Mechnikov", "I. P. Pavlov", "Lui Paster"], "t": "Lui Paster"},
    {"s": "32. 1880-yilda Ichterlama (tif) tug‘diruvchi mikrobni kashf etgan Nemis olimi kim?", "v": ["K. Eber", "F. Lyofer", "F. A. Lesh", "Robert Kox"], "t": "K. Eber"},
    {"s": "33. 1884-yilda Bo‘g‘ma (difteriya) tug‘diruvchi mikrobni kim aniqlagan?", "v": ["K. Eber", "F. Lyofer", "Robert Kox", "R. Virxov"], "t": "F. Lyofer"},
    {"s": "34. Hozirgi zamon patologik anatomiya asoslarini yaratgan Nemis olimi kim?", "v": ["T. Shvan", "Robert Kox", "R. Virxov", "F. Lyofer"], "t": "R. Virxov"},
    {"s": "35. 1875-yilda Amyoba dizenteriyasini tug‘diruvchi mikrobni aniqlagan Rus olimi kim?", "v": ["I. P. Pavlov", "I. Mechnikov", "F. A. Lesh", "K. Eber"], "t": "F. A. Lesh"},
    {"s": "36. 1895-yilda 'Rentgen apparati'ni yaratgan va birinchi bo'lib Fizika bo'yicha Nobel mukofotini olgan olim kim?", "v": ["Vilgelm Konrad Rentgen", "Albert Eynshteyn", "J. Tomson", "E. Rezerford"], "t": "Vilgelm Konrad Rentgen"},
    {"s": "37. Sil kasalligini keltirib chiqaruvchi batsillani kashf etgan Nemis olimi kim?", "v": ["Lui Paster", "Robert Kox", "K. Eber", "I. Mechnikov"], "t": "Robert Kox"},
    {"s": "38. Organizmlarni mikroblardan himoya qilish haqidagi yangi ta’limot yaratgan Nobel mukofoti laureati kim?", "v": ["Robert Kox", "Lui Paster", "I. P. Pavlov", "I. Mechnikov"], "t": "I. Mechnikov"},
    {"s": "39. 1884-yilda 'Tunsiz porox'ni kashf etgan Fransuz olimi kim?", "v": ["A. Nobel", "Vyel ve", "D. I. Mendeleyev", "A. Bekkerel"], "t": "Vyel ve"},
    {"s": "40. 1869-yilda 'Kimyoviy elementlarning davriy jadvali'ni yaratgan olim kim?", "v": ["A. Nobel", "Vyel ve", "D. I. Mendeleyev", "M. Sklodovskaya-Kyuri"], "t": "D. I. Mendeleyev"},
    {"s": "41. 1888-yilda 'Dinamit'ni ixtiro qilgan Shvetsiyalik olim kim?", "v": ["A. Nobel", "Vyel ve", "D. I. Mendeleyev", "A. Bekkerel"], "t": "A. Nobel"},
    {"s": "42. Matematika sohasidagi buyuk kashfiyotlari bilan tanilgan Rus, Italyan va Avstriyalik olimlar guruhi kimlar?", "v": ["Kirxgof, Lebedev, Kurks", "N.I. Lobachevskiy, Y. Beltrami, D. Gilbert", "Rezerford, Bor, Eynshteyn", "Tomson, Bekkerel, Kyuri"], "t": "N.I. Lobachevskiy, Y. Beltrami, D. Gilbert"},
    {"s": "43. 1904-yilda qanotning ko‘tarish kuchini aniqlash formulasini yaratgan Rus olimi kim?", "v": ["N. Y. Jukovskiy", "P. N. Lebedev", "I. A. Time", "N. I. Kibalchich"], "t": "N. Y. Jukovskiy"},
    {"s": "44. 'Yorug‘likning elektromagnit nazariyasi'ni ilgari surgan olim kim?", "v": ["G. Gers", "Vilgelm Rentgen", "P. N. Lebedev", "J. Tomson"], "t": "P. N. Lebedev"},
    {"s": "45. 1870-yilda siyraklashtirilgan havodagi katod nurlari ustida tadqiqot olgan Ingliz olimi kim?", "v": ["U. Kurks", "J. Tomson", "E. Rezerford", "N. Bor"], "t": "U. Kurks"},
    {"s": "46. 1897-yilda elektronlar oqimini aniqlagan Ingliz fizigi kim?", "v": ["U. Kurks", "J. Tomson", "E. Rezerford", "N. Bor"], "t": "J. Tomson"},
    {"s": "47. Manfiy zaryadlangan metall plastinka nurlanganda zaryadini yo‘qotishini isbotlagan olim kim?", "v": ["A. Bekkerel", "M. Sklodovskaya-Kyuri", "V. Galvane", "P. N. Lebedev"], "t": "V. Galvane"},
    {"s": "48. Uran atomlarining o‘z-o‘zidan nur chiqarishini (radioaktivlikni) aniqlagan Fransuz olimi kim?", "v": ["A. Bekkerel", "M. Sklodovskaya-Kyuri", "P. Kyuri", "V. Galvane"], "t": "A. Bekkerel"},
    {"s": "49. Radioaktivlik faqat uran atomlariga xos emasligini isbotlagan Polshalik olima kim?", "v": ["A. Bekkerel", "M. Sklodovskaya-Kyuri", "P. Kyuri", "V. Galvane"], "t": "M. Sklodovskaya-Kyuri"},
    {"s": "50. Poloniy va Radiy elementlarini ajratib olgan olimlar juftligi kim?", "v": ["Rezerford va Bor", "Bekkerel va Kyuri", "M. Sklodovskaya-Kyuri va P. Kyuri", "Tomson va Kurks"], "t": "M. Sklodovskaya-Kyuri va P. Kyuri"},
    {"s": "51. Atomning 'Planetar modeli'ni yaratgan Ingliz olimi kim?", "v": ["J. Tomson", "E. Rezerford", "N. Bor", "Albert Eynshteyn"], "t": "E. Rezerford"},
    {"s": "52. E. Rezerfordning modeliga tuzatish kiritib, energiyaning kvantlar shaklida chiqishini isbotlagan Daniyalik olim kim?", "v": ["Albert Eynshteyn", "J. Tomson", "N. Bor", "P. N. Lebedev"], "t": "N. Bor"},
    {"s": "53. 1905-yilda 'Nisbiylik nazariyasi'ni yaratgan Nemis fizigi kim?", "v": ["Albert Eynshteyn", "N. Bor", "E. Rezerford", "Vilgelm Rentgen"], "t": "Albert Eynshteyn"}
]