data_mustamlakachilik = [
    {"s": "Fransiya nechanchi yilda Jazoirni bosib olgan?", "v": ["1881", "1896", "1830", "1912"], "t": "1830"},
    {"s": "Fransiya nechanchi yilda Tunisni bosib olgan?", "v": ["1830", "1881", "1891", "1896"], "t": "1881"},
    {"s": "Gvineya va Senegal hududlarini qaysi davlat bosib olgan?", "v": ["Fransiya", "Buyuk Britaniya", "Germaniya", "Rossiya"], "t": "Fransiya"},
    {"s": "Fransiya nechanchi yillarda Gvineya, Senegal va Mavritaniyani bosib olgan?", "v": ["1830-1850-yillar", "1881-1884-yillar", "1891-1896-yillar", "1912-1915-yillar"], "t": "1891-1896-yillar"},
    {"s": "Mavritaniya hududini qaysi davlat bosib olgan?", "v": ["Ispaniya", "Fransiya", "Portugaliya", "Belgiya"], "t": "Fransiya"},
    {"s": "Fransiya nechanchi yilda Madagaskarni bosib olgan?", "v": ["1884", "1894", "1896", "1912"], "t": "1896"},
    {"s": "Fransiya nechanchi yilda Marokashni bosib olgan?", "v": ["1896", "1912", "1884", "1830"], "t": "1912"},
    {"s": "Fransiya nechanchi yilda Vetnamni bosib olgan?", "v": ["1884", "1894", "1912", "1881"], "t": "1884"},
    {"s": "Fransiya nechanchi yilda Laosni bosib olgan?", "v": ["1884", "1894", "1896", "1830"], "t": "1894"},
    {"s": "Yunan viloyati va Guamchjuvan ko’rfazini qaysi davlat bosib olgan?", "v": ["Fransiya", "Buyuk Britaniya", "Yaponiya", "Rossiya"], "t": "Fransiya"},
    {"s": "Gambiya va Syerra-Leona hududlarini qaysi davlat bosib olgan?", "v": ["Buyuk Britaniya", "Fransiya", "Portugaliya", "Italiya"], "t": "Fransiya"},
    {"s": "Oltin Qirg’oq hududini qaysi davlat bosib olgan?", "v": ["Germaniya", "Fransiya", "Portugaliya", "Belgiya"], "t": "Fransiya"},
    {"s": "Fil Suyagi Qirg’og’i va Dagomeya hududlarini qaysi davlat bosib olgan?", "v": ["Fransiya", "Italiya", "Ispaniya", "Portugaliya"], "t": "Fransiya"},
    {"s": "Buyuk Britaniya nechanchi yilda Hindistonni bosib olgan?", "v": ["1882", "1899", "1858", "1917"], "t": "1858"},
    {"s": "Buyuk Britaniya nechanchi yilda Misrni bosib olgan?", "v": ["1858", "1882", "1889", "1917"], "t": "1882"},
    {"s": "Kenia va Uganda hududlarini qaysi davlat bosib olgan?", "v": ["Germaniya", "Buyuk Britaniya", "Fransiya", "Portugaliya"], "t": "Buyuk Britaniya"},
    {"s": "Buyuk Britaniya nechanchi yillarda Bur Respublikasini bosib olgan?", "v": ["1891-1896", "1899-1902", "1882-1885", "1908-1912"], "t": "1899-1902"},
    {"s": "Veyxayvey bandargohi va Yanszi ko’rfazini qaysi davlat bosib olgan?", "v": ["Yaponiya", "Buyuk Britaniya", "Rossiya", "Germaniya"], "t": "Buyuk Britaniya"},
    {"s": "Buyuk Britaniya nechanchi yilda Sudanning bir qismini bosib olgan?", "v": ["1882", "1889", "1867", "1917"], "t": "1889"},
    {"s": "Rodeziya va Zululend hududlarini qaysi davlat bosib olgan?", "v": ["Germaniya", "Buyuk Britaniya", "Italiya", "Portugaliya"], "t": "Buyuk Britaniya"},
    {"s": "Transvaal va Oranj hududlarini qaysi davlat bosib olgan?", "v": ["Buyuk Britaniya", "Fransiya", "Belgiya", "Germaniya"], "t": "Buyuk Britaniya"},
    {"s": "Natal va Kap hududlarini qaysi davlat bosib olgan?", "v": ["Ispaniya", "Buyuk Britaniya", "Rossiya", "AQSH"], "t": "Buyuk Britaniya"},
    {"s": "Buyuk Britaniya nechanchi yilda Efiopiyaning bir qismini bosib olgan?", "v": ["1858", "1882", "1867", "1899"], "t": "1867"},
    {"s": "Buyuk Britaniya nechanchi yilda Bag’dodni (Iroq) bosib olgan?", "v": ["1889", "1902", "1912", "1917"], "t": "1917"},
    {"s": "Germaniya nechanchi yilda Angra-Pekenni bosib olgan?", "v": ["1897", "1882", "1907", "1898"], "t": "1882"},
    {"s": "Shandun viloyati qaysi davlat tomonidan bosib olingan?", "v": ["Yaponiya", "Germaniya", "Rossiya", "Buyuk Britaniya"], "t": "Germaniya"},
    {"s": "Szyaochjouvan (Sindao) hududini qaysi davlat bosib olgan?", "v": ["Germaniya", "AQSH", "Yaponiya", "Rossiya"], "t": "Germaniya"},
    {"s": "Germaniya nechanchi yillarda Shandun va Szyaochjouvanni bosib olgan?", "v": ["1882-1884", "1891-1896", "1897-1898", "1907-1910"], "t": "1897-1898"},
    {"s": "Togo va Kamerun hududlarini qaysi davlat bosib olgan?", "v": ["Fransiya", "Germaniya", "Portugaliya", "Italiya"], "t": "Germaniya"},
    {"s": "Gvineyaning shimoliy qismi va Zanzibar hududlarini qaysi davlat bosib olgan?", "v": ["Buyuk Britaniya", "Germaniya", "Fransiya", "Ispaniya"], "t": "Germaniya"},
    {"s": "Karolina va Mariana orollarini qaysi davlat bosib olgan?", "v": ["Germaniya", "AQSH", "Yaponiya", "Buyuk Britaniya"], "t": "Germaniya"},
    {"s": "Marshall orollarini qaysi davlat bosib olgan?", "v": ["Fransiya", "Germaniya", "AQSH", "Yaponiya"], "t": "Germaniya"},
    {"s": "Germaniya nechanchi yilda Gottentot, gerero va Nama qabilalarini bo'ysundirgan?", "v": ["1898", "1907", "1882", "1879"], "t": "1907"},
    {"s": "AQSH nechanchi yilda Gavayi orollarini bosib olgan?", "v": ["1903", "1875", "1898", "1864"], "t": "1898"},
    {"s": "Puerto-Riko hududini qaysi davlat bosib olgan?", "v": ["Ispaniya", "AQSH", "Germaniya", "Rossiya"], "t": "AQSH"},
    {"s": "Guam va Filippin hududlarini qaysi davlat bosib olgan?", "v": ["AQSH", "Portugaliya", "Yaponiya", "Buyuk Britaniya"], "t": "AQSH"},
    {"s": "Kuba hududini 1898-yilda qaysi davlat bosib olgan?", "v": ["Ispaniya", "AQSH", "Fransiya", "Rossiya"], "t": "AQSH"},
    {"s": "AQSH nechanchi yilda Puerto-Riko, Guam, Filippin va Kubani bosib olgan?", "v": ["1895", "1903", "1898", "1905"], "t": "1898"},
    {"s": "AQSH nechanchi yilda Panamani bosib olgan?", "v": ["1898", "1903", "1912", "1908"], "t": "1903"},
    {"s": "Rossiya nechanchi yilda Xiva xonligini bosib olgan?", "v": ["1868", "1876", "1873", "1885"], "t": "1873"},
    {"s": "Rossiya nechanchi yilda Qo’qon xonligini bosib olgan?", "v": ["1873", "1876", "1864", "1885"], "t": "1876"},
    {"s": "Rossiya nechanchi yilda Buxoro amirligini bosib olgan?", "v": ["1873", "1864", "1868", "1876"], "t": "1868"},
    {"s": "Turkmanlar hududi va Kushka shahri nechanchi yilda Rossiya tomonidan bosib olingan?", "v": ["1864", "1876", "1885", "1905"], "t": "1885"},
    {"s": "Rossiya nechanchi yilda Kavkazni butunlay bosib olgan?", "v": ["1885", "1864", "1873", "1868"], "t": "1864"},
    {"s": "Port Artur (Lyuyshun) hududi qaysi davlat tomonidan bosib olingan?", "v": ["Yaponiya", "Rossiya", "AQSH", "Germaniya"], "t": "Rossiya"},
    {"s": "Avstriya-Vengriya nechanchi yilda Bosniya-Gersogovinani bosib olgan?", "v": ["1898", "1912", "1908", "1904"], "t": "1908"},
    {"s": "Eritreya hududini qaysi davlat bosib olgan?", "v": ["Italiya", "Fransiya", "Germaniya", "Portugaliya"], "t": "Italiya"},
    {"s": "Italiya nechanchi yilda Liviyani bosib olgan?", "v": ["1882", "1896", "1912", "1908"], "t": "1912"},
    {"s": "Ispaniya nechanchi yilda Kubani bosib olgan?", "v": ["1898", "1510", "1904", "1912"], "t": "1510"},
    {"s": "Ispaniya nechanchi yilda Marokashning bir qismini bosib olgan?", "v": ["1912", "1904", "1884", "1896"], "t": "1904"},
    {"s": "Gvineyaning bir qismini qaysi davlat bosib olgan?", "v": ["Ispaniya", "Portugaliya", "Belgiya", "Italiya"], "t": "Portugaliya"},
    {"s": "Yaponiya nechanchi yilda Ryukyu orollarini bosib olgan?", "v": ["1875", "1879", "1895", "1910"], "t": "1879"},
    {"s": "Yaponiya nechanchi yilda Kurill orollarini bosib olgan?", "v": ["1879", "1875", "1905", "1895"], "t": "1875"},
    {"s": "Yaponiya nechanchi yilda Koreyani bosib olgan?", "v": ["1905", "1910", "1895", "1879"], "t": "1910"},
    {"s": "Tayvan va Penxu orollarini Yaponiya nechanchi yilda bosib olgan?", "v": ["1905", "1875", "1895", "1910"], "t": "1895"},
    {"s": "Peskador orollari qaysi davlat tomonidan 1895-yilda bosib olingan?", "v": ["Yaponiya", "Rossiya", "AQSH", "Germaniya"], "t": "Yaponiya"},
    {"s": "Saxalinning janubini Yaponiya nechanchi yilda egallagan?", "v": ["1895", "1905", "1910", "1879"], "t": "1905"},
    {"s": "Futsziyan hududi qaysi davlatning ta'sir doirasida bo'lgan?", "v": ["AQSH", "Yaponiya", "Rossiya", "Germaniya"], "t": "Yaponiya"},
    {"s": "Berilgan ma'lumotlarga ko'ra, Kongo hududi qaysi davlatlar o'rtasida bo'lingan?", "v": ["Germaniya, Italiya, Rossiya", "Fransiya, Portugaliya, Belgiya", "AQSH, Ispaniya, Yaponiya", "Britaniya, Avstriya, Rossiya"], "t": "Fransiya, Portugaliya, Belgiya"},
    {"s": "Somali hududini qaysi davlatlar bosib olgan edi?", "v": ["Rossiya, AQSH, Yaponiya", "Buyuk Britaniya, Italiya", "Fransiya, Germaniya, Portugaliya", "Belgiya, Ispaniya, Avstriya"], "t": "Buyuk Britaniya, Italiya"},
    {"s": "Samoa orollarini qaysi davlatlar egallagan edi?", "v": ["Fransiya, Belgiya", "Germaniya, AQSH", "Italiya, Portugaliya", "Yaponiya, Buyuk Britaniya"], "t": "Germaniya, AQSH"},
    {"s": "Nigeriya hududi qaysi davlatlar tomonidan bosib olingan?", "v": ["Fransiya, Buyuk Britaniya", "Germaniya, Belgiya", "Ispaniya, Portugaliya", "Italiya, Rossiya"], "t": "Fransiya, Buyuk Britaniya"}
]