# data_8jt_atamalar.py

atamalar_8jt = [
    {"s": "XIV asrdan boshlab Fransiyada qirol avlodidan bo‘lgan taxt vorisi, vaqtinchalik qirol qanday atalgan?", "v": ["Gertsog", "Dofin", "Kurfyurst", "Doj"], "t": "Dofin"},
    {"s": "Angliyada yerga mustaqil ishlov beruvchi erkin dehqonlar va kichik yer egalari qanday nomlangan?", "v": ["Vassallar", "Yomenlar", "Kadivarlar", "Chokarlar"], "t": "Yomenlar"},
    {"s": "Davlatda hukmdorning cheklanmagan hokimiyat va vakolatlarga ega bo‘lgan yakka boshqaruv shakli qaysi?", "v": ["Respublika", "Mutlaq monarxiya", "Teokratiya", "Demokratiya"], "t": "Mutlaq monarxiya"},
    {"s": "Qadimgi ingliz tilidagi “Eng land” so‘zi qanday ma’noni bildiradi?", "v": ["Britlar yeri", "Angllar yeri", "Sakslar maskani", "Erkinlar yurti"], "t": "Angllar yeri"},
    {"s": "Lotincha 'qog'oz' yoki 'yorliq' ma'nosini anglatuvchi, jamiyatning ma’lum huquqlarini ifodalagan hujjat qaysi?", "v": ["Farmon", "Xartiya", "Veksel", "Konstitutsiya"], "t": "Xartiya"},
    {"s": "Fransuz tilidan olingan bo‘lib, “gapirmoq”, “so‘zlamoq” ma’nosini bildiruvchi davlat organi qaysi?", "v": ["Kortes", "Parlament", "Seym", "Veche"], "t": "Parlament"},
    {"s": "Angliyada qo‘llanilgan, 1 akr necha sotixga teng yer maydoni hisoblangan?", "v": ["10 sotix", "40 sotix", "100 sotix", "6 sotix"], "t": "40 sotix"},
    {"s": "Angliyada mayda tanga pullarga nisbatan ishlatilgan pul birligi qanday nomlangan?", "v": ["Dukat", "Pens yoki penni", "Florin", "Statir"], "t": "Pens yoki penni"},
    {"s": "Germaniyada qirolni saylash vakolatiga ega bo‘lgan 7 nafar imperiya knyazlari qanday atalgan?", "v": ["Dojlar", "Kurfyurstlar", "Kardinallar", "Pan"], "t": "Kurfyurstlar"},
    {"s": "VIII–XVIII asrlarda Venetsiya respublikasining saylangan rahbari (yunoncha 'rahbar' ma'nosida) qanday atalgan?", "v": ["Konsul", "Doj", "Dofin", "Lord"], "t": "Doj"},
    {"s": "1284-yilda Venetsiya tomonidan chiqarilgan, 'gersog' ma'nosini anglatuvchi Italiya oltin pullari qaysi?", "v": ["Statir", "Dukat", "Fulus", "Dinor"], "t": "Dukat"},
    {"s": "Katolik cherkovining Rim papasidan keyingi eng oliy ruhoniysi (lotincha 'yurak' ma'nosida) kim?", "v": ["Yepiskop", "Kardinal", "Abbat", "Pastir"], "t": "Kardinal"},
    {"s": "XIII–XIV asrlarda Italiya shahar-davlatlaridagi hokimiyat boshqaruvi tizimi va idorasi qanday nomlangan?", "v": ["Kommuna", "Sinyoriya", "Ratusha", "Kortes"], "t": "Sinyoriya"},
    {"s": "VIII–XV asrlarda Pireney yarimorolining arablardan qaytarib olinishi jarayoni nima deb ataladi?", "v": ["Fath", "Rekonkista", "Inkvizitsiya", "Reformatsiya"], "t": "Rekonkista"},
    {"s": "Ispan tilida 'o'rin, joy' ma'nosini bildiruvchi, Ispaniya va Portugaliyadagi vakillik yig'ini qanday ataladi?", "v": ["Seym", "Kortes", "Veche", "Parlament"], "t": "Kortes"},
    {"s": "Qadimgi slavyan tilida 'kengash' ma'nosini anglatuvchi xalq yig'ini qaysi?", "v": ["Seym", "Veche", "Pan", "Rada"], "t": "Veche"},
    {"s": "Chexiya va Polsha davlatlarida feodal yer egasi, xo'jayin yoki janobga nisbatan qanday atama ishlatilgan?", "v": ["Lord", "Pan", "Don", "Sinyor"], "t": "Pan"},
    {"s": "O‘rta asrlarda Chexiya va Polsha davlatlarida vakillik yig‘inlari (parlament) qanday atalgan?", "v": ["Kortes", "Seym", "Veche", "General shtatlar"], "t": "Seym"},
    {"s": "Usmoniy turklar tomonidan Bolqon yarimorolidagi bosib olingan yerlarning umumiy nomi qaysi?", "v": ["Anadolu", "Rum eli (Rumeliya)", "Levant", "Mag'rib"], "t": "Rum eli (Rumeliya)"},
    {"s": "'Qarorgoh' yoki 'chodir' ma'nosini anglatuvchi, mo'g'ullar davlati nomi sifatida ishlatilgan atama qaysi?", "v": ["Ulus", "O'rda", "Marka", "Jete"], "t": "O'rda"},
    {"s": "Mo'g'ulcha 'in'om' ma'nosini anglatuvchi, harbiy xizmatlar uchun beriladigan merosiy yer qanday ataladi?", "v": ["Iqto", "Suyurg'ol", "Allod", "Patta"], "t": "Suyurg'ol"},
    {"s": "Dehli sultonligida turkiy qullardan bo'lgan navkarlar va ularning orasidan chiqqan sultonlar qanday nomlangan?", "v": ["Mamluklar", "G'ulomlar", "Sipohiylar", "Samuraiylar"], "t": "G'ulomlar"},
    {"s": "Dehli yaqinidagi hozirgi markaziy aeroport joylashgan joy qanday nomlanadi?", "v": ["Xonbaliq", "Palam", "Dasin", "Beypin"], "t": "Palam"},
    {"s": "Mo'g'ullar davrida 'Xonbaliq' deb nomlangan, hozirgi Xitoy poytaxti qaysi?", "v": ["Shanxay", "Pekin (Beyszin)", "Sian", "Guanchjou"], "t": "Pekin (Beyszin)"},
    {"s": "Dengizda katta to'lqinlarni yuzaga keltiruvchi juda kuchli shamol qanday ataladi?", "v": ["Musson", "Tayfun", "Simum", "Passat"], "t": "Tayfun"},
    {"s": "Mali hukmdorlarining siyosiy va diniy vakolatlarni birlashtirgan oliy unvoni qaysi?", "v": ["Fir'avn", "Mansa", "Negus", "Sulton"], "t": "Mansa"},
    {"s": "Misrda kavkazlik va turkiy o'smir qullardan tashkil qilingan harbiylar qatlami qanday nomlangan?", "v": ["G'ulomlar", "Mamluklar", "Janissarlar", "Kshatriylar"], "t": "Mamluklar"},
    {"s": "Amerika tub aholisiga berilgan 'Hindu' nomi qaysi yanglishish natijasida paydo bo'lgan?", "v": ["Eskimoslar", "Xristofor Kolumbning Hindiston deb o'ylashi", "Atsteklar", "Mayyalar"], "t": "Xristofor Kolumbning Hindiston deb o'ylashi"},
    {"s": "Kishilarning tashqi qiyofasi va irsiy belgilari bo'yicha farqlanuvchi guruhi nima deyiladi?", "v": ["Millat", "Irq", "Elat", "Jamoa"], "t": "Irq"},
    {"s": "Markaziy va Janubiy Amerikani zabt etishga kirishgan ispan va portugal bosqinchilari qanday ataladi?", "v": ["Vikinglar", "Konkistadorlar", "Kreollar", "Lord"], "t": "Konkistadorlar"},
    {"s": "G‘arbiy Yevropada yirik mulkdorlar va zodagonlarga nisbatan hurmat ma’nosida ishlatilgan atama qaysi?", "v": ["Pan", "Lord", "Doj", "Dofin"], "t": "Lord"},
    {"s": "Italyancha 'banco' (sarrof peshtaxtasi) so'zidan olingan moliya muassasasi qaysi?", "v": ["Birja", "Bank", "Faktoriya", "Bozor"], "t": "Bank"},
    {"s": "Nemischa 'almashtirish' ma'nosini beruvchi, savdogarlar pul olish uchun ishlatgan yozma hujjat qaysi?", "v": ["Xartiya", "Veksel", "Patta", "Farmon"], "t": "Veksel"},
    {"s": "Oliy martabali ruhoniylar boshchilik qiladigan yirik xristian ibodatxonasi qanday ataladi?", "v": ["Kapella", "Sobor", "Sinagoga", "Xonaqoh"], "t": "Sobor"},
    {"s": "Qal’a devoridan bo‘rtib chiqqan dumaloq mudofaa minorasi qaysi?", "v": ["Mashikuli", "Barbakan", "Ko'handiz", "Donjon"], "t": "Barbakan"},
    {"s": "Qalʼa devori yuqorisida vertikal oʻq otish uchun moʻljallangan ilmoqli mudofaa inshooti qaysi?", "v": ["Barbakan", "Mashikuli", "Ark", "Darvoza"], "t": "Mashikuli"},
    {"s": "Antik va o'rta asr manbalarida tilga olingan qadimgi pul birligi qaysi?", "v": ["Dukat", "Statir (stater)", "Fulus", "Pens"], "t": "Statir (stater)"}
]