# 9-sinf Jahon Tarixi Atamalari - Bazasi

testlar_9jt = [
    {"s": "Qora tanlilarni qullikdan ozod qilish harakati nima deb ataladi?", "v": ["Anarxizm", "Abolitsionizm", "Segregatsiya", "Aparteid"], "t": "Abolitsionizm"},
    {"s": "Yerga egalik va undan foydalanish tartiblarini qayta o‘zgartirish nima?", "v": ["Urbanizatsiya", "Konsessiya", "Millatlashtirish", "Agrar islohot"], "t": "Agrar islohot"},
    {"s": "AQShda qishloq xo'jaligi mahsulotlarini ekin maydonlarini kengaytirish hisobiga ko'paytirish yo'li qanday atalgan?", "v": ["Prussiyacha yo'l", "Amerikacha yo'l", "Intensiv yo'l", "Modernizatsiya"], "t": "Amerikacha yo'l"},
    {"s": "Har qanday hokimiyat va davlat tuzumini rad etuvchi, faqat shaxs irodasini tan oluvchi ta’limot qaysi?", "v": ["Anarxizm", "Sotsializm", "Liberalizm", "Konservatizm"], "t": "Anarxizm"},
    {"s": "Bir davlat hududini butunlay yoki qisman egallab olish (lotincha - birlashtirish) nima?", "v": ["Intervensiya", "Okkupatsiya", "Anneksiya", "Ekspansiya"], "t": "Anneksiya"},
    {"s": "622-yilda muhojirlarga va Rasulullohga yordam bergan Madina qabilalari a'zolari kimlar?", "v": ["G'oziylar", "Chokarlar", "Muridlar", "Ansorlar"], "t": "Ansorlar"},
    {"s": "1904-1907-yillarda tuzilgan B.Britaniya, Fransa va Rossiya ittifoqi qaysi?", "v": ["Uchlar Ittifoqi", "Antanta", "To'rtlar Ittifoqi", "Muqaddas Ittifoq"], "t": "Antanta"},
    {"s": "Yahudiylarga qarshi milliy dushmanlikni avj oldirish siyosati nima?", "v": ["Shovinizm", "Irredentizm", "Antisemitizm", "Aparteid"], "t": "Antisemitizm"},
    {"s": "1889-yilda tuzilgan Avstriya sotsial-demokratik partiyasi qisqartmasi qaysi?", "v": ["ASDP", "GSDP", "RSDRP", "HMK"], "t": "ASDP"},
    {"s": "Ko'chalarda mudofaa uchun qurilgan sun’iy to‘siq nima deyiladi?", "v": ["Barbakan", "Mashikuli", "Barrikada", "Qal'a"], "t": "Barrikada"},
    {"s": "Kasallik qo‘zg‘atuvchi tayoqchasimon mikroorganizm (mikrob) nima?", "v": ["Batsilla", "Virus", "Ferment", "Antibiotik"], "t": "Batsilla"},
    {"s": "Masjid va qabristonlarda tinch o‘tirib, sust qarshilik ko‘rsatish usuli?", "v": ["Boykot", "Best", "Svaraj", "Svadeshi"], "t": "Best"},
    {"s": "Biror narsani yoki iqtisodiy aloqalarni butunlay inkor qilish (to'xtatish) nima?", "v": ["Sanksiya", "Ssuda", "Direktiva", "Boykot"], "t": "Boykot"},
    {"s": "Germaniya parlamentining yuqori palatasi (Ittifoq kengashi) qanday ataladi?", "v": ["Reyxstag", "Bundesrat", "Landtag", "Senat"], "t": "Bundesrat"},
    {"s": "1915-yilda rus armiyasining Polsha va Boltiqbo‘yidan chekinishi nima deb ataladi?", "v": ["Nevel qirg'ini", "Verden qirg'ini", "Buyuk chekinish", "Brusilov yorib o'tishi"], "t": "Buyuk chekinish"},
    {"s": "Rus qo‘shini tomonidan 1915-yilda Polsha va G‘arbiy Ukrainaning tashlab chiqilishi qanday nomlangan?", "v": ["Buyuk chekinish", "Okkupatsiya", "Reaksiya", "Evakuatsiya"], "t": "Buyuk chekinish"},
    {"s": "Rossiyada monarxiyaning cheklanmagan hokimiyatini asoslovchi davlat tuzumi?", "v": ["Absolyutizm", "Respublika", "Chorizm", "Diktatura"], "t": "Chorizm"},
    {"s": "AQSH tashqi ishlar vazirligi qanday nomlanadi?", "v": ["Davlat departamenti", "Senat", "Oq uy", "Pentagon"], "t": "Davlat departamenti"},
    {"s": "Rossiya imperiyasida parlamentning yuqori palatasi qaysi edi?", "v": ["Davlat dumasi", "Davlat kengashi", "Boyarlar kengashi", "Senat"], "t": "Davlat kengashi"},
    {"s": "Yevropa madaniyatidagi inqiroz va hayotdan bezish kayfiyatini ifodalovchi tushuncha?", "v": ["Modernizm", "Realizm", "Dekadentlik", "Gumanizm"], "t": "Dekadentlik"},
    {"s": "Oliy hokimiyat yoki boshqaruv organi chiqargan qonun kuchiga teng qaror?", "v": ["Manifest", "Nota", "Dekret", "Veksell"], "t": "Dekret"},
    {"s": "Harbiy xizmatdan bo‘shatish va armiyani tinchlik holatiga o'tkazish nima?", "v": ["Mobilizatsiya", "Demobilizatsiya", "Ekspansiya", "Migratsiya"], "t": "Demobilizatsiya"},
    {"s": "Xalq manfaatiga xizmat qiluvchi va voqelikni haqqoniy aks ettiruvchi adabiyot?", "v": ["Demokratik adabiyot", "Dekadent adabiyot", "Klassitsizm", "Ma'rifatparvarlik"], "t": "Demokratik adabiyot"},
    {"s": "Shoshilinch yuboriladigan rasmiy xabar nima deyiladi?", "v": ["Nota", "Dekret", "Depesha", "Manifest"], "t": "Depesha"},
    {"s": "Rossiyada 1,1 gektarga teng bo'lgan uzunlik va maydon o'lchov birligi?", "v": ["Akr", "Milya", "Fut", "Desyatina"], "t": "Desyatina"},
    {"s": "Hech qanday qonun bilan cheklanmagan, zo‘rlikka tayanuvchi hokimiyat?", "v": ["Diktatura", "Monarxiya", "Federatsiya", "Respublika"], "t": "Diktatura"},
    {"s": "Siyosiy rahbarlik tamoyili yoki tizimli ta’limot qanday ataladi?", "v": ["Manifest", "Konvensiya", "Doktrina", "Veksell"], "t": "Doktrina"},
    {"s": "Mustamlakachi davlatlaming o‘zgalar hududini va bozorlarini bosib olish siyosati?", "v": ["Ekspansiya", "Evolyutsiya", "Emigratsiya", "Reformatsiya"], "t": "Ekspansiya"},
    {"s": "Mulkdorlarning boshqalar mehnati mahsulini o‘zlashtirib olishi nima?", "v": ["Investitsiya", "Konsensiya", "Bozor", "Ekspluatatsiya"], "t": "Ekspluatatsiya"},
    {"s": "XIX asr oxirida 13-14 yoshli qizlardan iborat bo'lgan ishchi qatlami?", "v": ["Yomenlar", "Fabrika ayollari", "Kadivarlar", "Chokarlar"], "t": "Fabrika ayollari"},
    {"s": "Tabiat, jamiyat va tafakkur taraqqiyotining umumiy qonuniyatlari haqidagi fan?", "v": ["Falsafa", "Tarix", "Sotsiologiya", "Iqtisodiyot"], "t": "Falsafa"},
    {"s": "To‘g‘riligi amalda tasdiqlangan, jamiyat qonuniyatlarini ochib beruvchi bilimlar tizimi?", "v": ["Ilm", "Fan", "Ma'rifat", "Tajriba"], "t": "Fan"},
    {"s": "Hududiy jihatdan mustaqillikka ega bir necha davlatdan iborat yagona ittifoq davlati?", "v": ["Unitar davlat", "Imperiya", "Federatsiya", "Konfederatsiya"], "t": "Federatsiya"},
    {"s": "Favqulodda, nodir kabi ma'nolarni anglatuvchi tushuncha qaysi?", "v": ["Fenomenologik", "Gumanitar", "Modern", "Klassik"], "t": "Fenomenologik"},
    {"s": "1906-yilda Italiyada tashkil topgan yirik sanoat aksiyadorlik jamiyati nomi?", "v": ["Renault", "Ford", "Ferrari", "Fiat"], "t": "Fiat"},
    {"s": "Ovoz yozib olish va uni takror eshittirish apparati qanday ataladi?", "v": ["Fonograf", "Telegraf", "Radio", "Grammofon"], "t": "Fonograf"},
    {"s": "Fan-texnika inqilobi atamasining qisqartma shaklini toping.", "v": ["FTT", "FTI", "ITP", "FNF"], "t": "FTI"},
    {"s": "G'arbiy Ukraina hududi tarixda qanday nomlangan?", "v": ["Rumeliya", "Kirenaika", "Galitsiya", "Tanganika"], "t": "Galitsiya"},
    {"s": "1891-yilda Germaniyada tuzilgan shovinistik tashkilot qaysi?", "v": ["German Ittifoqi", "Antanta", "Reyx", "Kanslerlik"], "t": "German Ittifoqi"},
    {"s": "Germaniyaning Sharqiy Afrikadagi mustamlakasi (Zanzibar) qanday atalgan?", "v": ["Tanganika", "Kamerun", "Germaniya Sharqiy Afrikasi", "Togo"], "t": "Germaniya Sharqiy Afrikasi"},
    {"s": "1912-yilda Xitoyda demokratik kuchlar tomonidan tuzilgan Milliy partiya qaysi?", "v": ["Tunminxay", "Sin", "Ixetuan", "Gomindan"], "t": "Gomindan"},
    {"s": "Irlandiyada o‘z-o‘zini idora qilish harakati qanday nomlangan?", "v": ["Gomrul", "Shinfeyn", "Svaraj", "Svadeshi"], "t": "Gomrul"},
    {"s": "1875-yilda tashkil etilgan Germaniya sotsial-demokratik partiyasi qisqartmasi?", "v": ["ASDP", "GSDP", "RSDRP", "HMK"], "t": "GSDP"},
    {"s": "Inson shaxsiga, inson huquqi va manfaatlariga oidlikni anglatuvchi tushuncha?", "v": ["Demokratik", "Sekulyar", "Gumanitar", "Liberal"], "t": "Gumanitar"},
    {"s": "Tarix, falsafa, tilshunoslik kabi inson hayoti va madaniyatini o‘rganuvchi fanlar?", "v": ["Gumanitar fanlar", "Tabiiy fanlar", "Texnik fanlar", "Aniq fanlar"], "t": "Gumanitar fanlar"},
    {"s": "Misr hukmdorlarining XIX asrdagi unvoni qanday bo'lgan?", "v": ["Mansa", "Negus", "Hadiv", "Fir'avn"], "t": "Hadiv"},
    {"s": "Harbiylarning cheklanmagan hokimiyati nima deyiladi?", "v": ["Harbiy diktatura", "Samoderjaviye", "Teokratiya", "Respublika"], "t": "Harbiy diktatura"},
    {"s": "1885-yilda Bombey shahrida tuzilgan Hindistonning birinchi siyosiy partiyasi?", "v": ["Musulmonlar ligasi", "Shinfeyn", "HMK (Hindiston milliy kongressi)", "Svaraj"], "t": "HMK (Hindiston milliy kongressi)"},
    {"s": "„Yangi usmonlilar“ g'oyalarini targ'ib qilgan turk gazetasi nomi?", "v": ["Kesari", "Minbao", "Ibrat", "Siroj ul-axbor"], "t": "Ibrat"},
    {"s": "1889-yilda tashkil etilgan Xalqaro sotsialistik ishchi partiyalari uyushmasi qaysi?", "v": ["I Internatsional", "II Internatsional", "Millatlar ligasi", "Komintern"], "t": "II Internatsional"},
    {"s": "Kishining o‘qish va tajriba orqali orttirgan bilimi (arabcha)?", "v": ["Fan", "Ilm", "Ma'rifat", "Malaka"], "t": "Ilm"},
    {"s": "Bir davlatdan boshqasiga doimiy yashash uchun ko‘chib kelgan shaxs?", "v": ["Immigrant", "Emigrant", "Migrant", "Qochqin"], "t": "Immigrant"},
    {"s": "Kapitalizm jamiyatining eng yuqori va oxirgi davri qanday ataladi?", "v": ["Feodalizm", "Sotsializm", "Imperializm", "Kommunizm"], "t": "Imperializm"},
    {"s": "Alohida odam yoki shaxs nima deb ataladi?", "v": ["Ommaviy", "Jamoa", "Individ", "Millat"], "t": "Individ"},
    {"s": "Sanoat, xususan, yirik sanoatni anglatuvchi lotincha atama?", "v": ["Industriya", "Agrar", "Manufaktura", "Hunarmandchilik"], "t": "Industriya"},
    {"s": "O'zga davlat ichki ishlariga va hududiy yaxlitligiga zo'rlik bilan aralashish?", "v": ["Anneksiya", "Izolyatsionizm", "Intervensiya", "Sanksiya"], "t": "Intervensiya"},
    {"s": "Italyanlar yashaydigan hududlarni Italiyaga qo'shib olishni targ'ib qiluvchi harakat?", "v": ["Antisemitizm", "Panislomizm", "Irredentizm", "Shovinizm"], "t": "Irredentizm"},
    {"s": "Mavjud tartiblarni tubdan (lekin inqilobsiz) o‘zgartirish nima?", "v": ["Islohot", "Revolutsiya", "Reaksiya", "Inqiroz"], "t": "Islohot"},
    {"s": "Xitoyda tuzilgan 'Tinchlik va adolat uchun ko‘tarilgan musht' tashkiloti?", "v": ["Ixetuan", "Gomindan", "Tunminxay", "Sin"], "t": "Ixetuan"},
    {"s": "1910-yilda Transvaal, Oranj, Natal va Kap birlashuvidan qaysi davlat hosil bo'ldi?", "v": ["Efiopiya", "Misr", "Janubiy Afrika Ittifoqi", "Jazoir"], "t": "Janubiy Afrika Ittifoqi"},
    {"s": "Germaniyada hukumat Bosh vaziri lavozimi qanday atalgan?", "v": ["Prezident", "Monarx", "Kansler", "Shtatgalter"], "t": "Kansler"},
    {"s": "O‘z egasiga daromad keltiruvchi jami vositalar va mablag‘lar (sarmoya)?", "v": ["Kapital", "Boj", "Xiroj", "Ssuda"], "t": "Kapital"},
    {"s": "Mustaqil kompaniyalarning narx va bozorlarni bo'lishib olish bo'yicha bitimi?", "v": ["Trest", "Kartel", "Sindikat", "Konsern"], "t": "Kartel"},
    {"s": "Bal Gangadxara Tilak tomonidan Hindistonda tashkil qilingan gazeta?", "v": ["Ibrat", "Minbao", "Kesari (Sher)", "Siroj ul-axbor"], "t": "Kesari (Sher)"},
    {"s": "Hozirgi Liviya hududi tarixda qanday nomlangan?", "v": ["Rumeliya", "Kirenaika", "Jazoir", "Tanganika"], "t": "Kirenaika"},
    {"s": "Bir yoki bir necha davlatga qarshi tuzilgan vaqtinchalik harbiy-siyosiy ittifoq?", "v": ["Federatsiya", "Konfederatsiya", "Koalitsiya", "Antanta"], "t": "Koalitsiya"},
    {"s": "Chet el kapitali bilan ichki bozor o'rtasida vositachilik qiluvchi mahalliy boylar?", "v": ["Komprador", "Proletariat", "Yunker", "Yomen"], "t": "Komprador"},
    {"s": "Ishlab chiqarishning bir yerga yoki bir qo‘lga to‘planishi nima deyiladi?", "v": ["Modernizatsiya", "Desentralizatsiya", "Konsentratsiya", "Urbanizatsiya"], "t": "Konsentratsiya"},
    {"s": "Manfaatlar umumiyligi asosida uyushgan yirik korxonalar birlashmasi?", "v": ["Kartel", "Trest", "Sindikat", "Konsern"], "t": "Konsern"},
    {"s": "Davlat obyektlarini muayyan shartlar bilan ekspluatatsiyaga berish bitimi?", "v": ["Konsessiya", "Shartnoma", "Konvensiya", "Farmon"], "t": "Konsessiya"},
    {"s": "Ko‘p tomonlama xalqaro shartnoma turlaridan biri?", "v": ["Dekret", "Nota", "Konvensiya", "Traktat"], "t": "Konvensiya"},
    {"s": "Monopolistik aksiyadorlar birlashmasi qanday ataladi?", "v": ["Korporatsiya", "Artel", "Jamoa", "Kooperativ"], "t": "Korporatsiya"},
    {"s": "AQSHdagi o'ta irqchi va terrorchi tashkilot nomi qaysi?", "v": ["Antanta", "Shinfeyn", "Ku-kluks-klan", "Black Panthers"], "t": "Ku-kluks-klan"},
    {"s": "Bismarkning katolik cherkoviga qarshi tadbiri (Madaniyat uchun kurash)?", "v": ["Kulturkampf", "Reaksiya", "Reformatsiya", "Sekulyarlik"], "t": "Kulturkampf"},
    {"s": "Germaniya ittifoqi tarkibidagi davlatlarning parlamenti qanday atalgan?", "v": ["Landtag", "Reyxstag", "Bundesrat", "Duma"], "t": "Landtag"},
    {"s": "Katta yer-mulk (lotincha) ma'nosini anglatuvchi atama?", "v": ["Latifundiya", "Desyatina", "Akr", "Tanob"], "t": "Latifundiya"},
    {"s": "Buyuk Britaniyadagi katta yer egalari qanday nomlangan?", "v": ["Lendlordlar", "Yunkerlar", "Yomenlar", "Lordlar"], "t": "Lendlordlar"},
    {"s": "AQSHda qora tanli kishilarni sudsiz va so‘roqsiz jazolash nima deb ataladi?", "v": ["Harbiy sud", "Inkvizitsiya", "Linch sudi", "Sanksiya"], "t": "Linch sudi"},
    {"s": "Germaniya tomonidan cho'ktirilgan va bortida AQSH fuqarolari bo'lgan kema?", "v": ["Luzitaniya", "Titanik", "Avrora", "Potyomkin"], "t": "Luzitaniya"},
    {"s": "Rossiya tomonidan ijaraga olingan Port Artur bandargohi?", "v": ["Sindao", "Dalniy", "Lyuyshun", "Vladivostok"], "t": "Lyuyshun"},
    {"s": "Fransuzlar Jazoirda mahalliy aholini kamsitish uchun qo'llagan kodekslar?", "v": ["Mahalliy kodeks", "Xartiya", "Konstitutsiya", "Dekret"], "t": "Mahalliy kodeks"},
    {"s": "Islomda oxirzamon bo‘lganida kelib, yerda adolat o‘rnatuvchi payg‘ambar?", "v": ["Ansor", "Muhojir", "Mahdiy", "Xalifa"], "t": "Mahdiy"},
    {"s": "Sanoatda asosiy qismni tashkil etuvchi, maxsus malakaga ega ishchilar?", "v": ["Malakali ishchilar", "G'ulomlar", "Fabrika ayollari", "Dehqonlar"], "t": "Malakali ishchilar"},
    {"s": "Hukumatning muhim voqea munosabati bilan xalqqa qilgan yozma murojaati?", "v": ["Dekret", "Nota", "Manifest", "Veksell"], "t": "Manifest"},
    {"s": "1907-yilda Rossiyada tuzilgan rangli metallurgiya jamiyati nomi?", "v": ["Med", "Prodmet", "Produgol", "Neft"], "t": "Med"},
    {"s": "Rossiyada hunarmandlar va mayda savdogarlardan iborat shahar aholisi?", "v": ["Dehqonlar", "Kazaklar", "Meshchanlar", "Yunker"], "t": "Meshchanlar"},
    {"s": "Aholining bir hududdan yoki mamlakatdan ikkinchisiga ko'chishi?", "v": ["Urbanizatsiya", "Ekspansiya", "Migratsiya", "Emigratsiya"], "t": "Migratsiya"},
    {"s": "Fransiyada parlament qanday nomlangan?", "v": ["Milliy Majlis", "Kortes", "Seym", "Duma"], "t": "Milliy Majlis"},
    {"s": "1609,3 metrga teng uzunlik o‘lchovi qaysi?", "v": ["Kilometr", "Fut", "Milya", "Desyatina"], "t": "Milya"},
    {"s": "1905-yildan Xitoy uyushmalari ittifoqi tomonidan chiqarilgan gazeta?", "v": ["Minbao", "Ibrat", "Kesari", "Siroj ul-axbor"], "t": "Minbao"},
    {"s": "Bir davlatning ikkinchi davlatga maxsus topshiriq bilan yuborgan vakillari?", "v": ["Missiya", "Elchixona", "Konsullik", "Delegatsiya"], "t": "Missiya"},
    {"s": "Pul jamg‘armalarini jamlash, taqsimlash va ishlatish bilan bog‘liq munosabatlar?", "v": ["Savdo", "Sanoat", "Moliya", "Bank"], "t": "Moliya"},
    {"s": "Bank kapitali bilan sanoat kapitalining birlashib ketishi natijasida nima hosil bo'ladi?", "v": ["Moliya kapitali", "Ssuda", "Trest", "Konsern"], "t": "Moliya kapitali"},
    {"s": "Yakka hukmronlikka asoslangan boshqaruv shakli (yunoncha)?", "v": ["Monarxiya", "Respublika", "Diktatura", "Federatsiya"], "t": "Monarxiya"},
    {"s": "Kapitalizmning moliya oligarxiyasi va monopoliyalar hukmron bosqichi?", "v": ["Monopolistik kapitalizm", "Erkin raqobat davri", "Feodalizm", "Kommunizm"], "t": "Monopolistik kapitalizm"},
    {"s": "Iqtisodiyotning bir sohasidagi tanho hukmronlik (yunoncha)?", "v": ["Raqobat", "Birja", "Monopoliya", "Kartel"], "t": "Monopoliya"},
    {"s": "Amerika amerikaliklar uchun shiori ostidagi AQSH tashqi siyosati?", "v": ["Monro doktrinasi", "Neytrallitet", "Ekspansiya", "Islohot"], "t": "Monro doktrinasi"},
    {"s": "Saylovda qatnashish uchun fuqaroning ma’lum miqdordagi mulkka ega bo‘lishi?", "v": ["Saylov huquqi", "Referendum", "Mulk senzi", "Kasta"], "t": "Mulk senzi"},
    {"s": "Hindistonda tuzilgan musulmonlar siyosiy partiyasi nomi?", "v": ["Musulmonlar ligasi", "HMK", "Shinfeyn", "Gomrul"], "t": "Musulmonlar ligasi"},
    {"s": "Amaldagi hukumat siyosatiga qarshi chiquvchi kuchlar qanday ataladi?", "v": ["Koalitsiya", "Reaksiya", "Muxolifat", "Inqilobchilar"], "t": "Muxolifat"},
    {"s": "Efiopiyada podshoning unvoni qanday bo'lgan?", "v": ["Negus", "Mansa", "Hadiv", "Fir'avn"], "t": "Negus"},
    {"s": "1917-yil aprelida Antantaning G'arbiy frontdagi qonli va muvaffaqiyatsiz hujumi?", "v": ["Nevel qirg‘ini", "Verden qirg'ini", "Somma jangi", "Brusilov hujumi"], "t": "Nevel qirg‘ini"},
    {"s": "Fransiya Bosh qo'mondoni nomi bilan atalgan 1917-yilgi qonli jang (takror)?", "v": ["Somma jangi", "Vaterloo", "Nevel qirg‘ini", "Ipr jangi"], "t": "Nevel qirg‘ini"},
    {"s": "Bir davlatning boshqa davlatga yozgan rasmiy murojaatnomasi?", "v": ["Depesha", "Dekret", "Nota", "Manifest"], "t": "Nota"},
    {"s": "Siyosiy hukmronlikning bir hovuch ulkan kapital egalari qo‘lida to'planishi?", "v": ["Oligarxiya", "Demokratiya", "Monarxiya", "Respublika"], "t": "Oligarxiya"},
    {"s": "Muhandislar, shifokorlar va o‘qituvchilardan iborat jamiyat qatlami?", "v": ["O'rta qatlam", "Proletariat", "Burjua", "Dehqonlar"], "t": "O'rta qatlam"},
    {"s": "Musulmon olamini mustamlakachilarga qarshi birlashtirish harakatining nomi?", "v": ["Panislomizm", "Panturkizm", "Antisemitizm", "Shovinizm"], "t": "Panislomizm"},
    {"s": "Turkiy xalqlarni birlashtirish g‘oyasiga Rossiya va Britaniya tomonidan berilgan nom?", "v": ["Panturkizm", "Panislomizm", "Shovinizm", "Kommunizm"], "t": "Panturkizm"},
    {"s": "1871-yil martda Parijda tashkil etilgan mehnatkashlar hokimiyati?", "v": ["Parij Kommunasi", "Milliy Majlis", "Direktoriya", "Konsullik"], "t": "Parij Kommunasi"},
    {"s": "Saylov asosida tuziladigan qonun chiqaruvchi oliy davlat organi?", "v": ["Parlament", "Vazirlar Mahkamasi", "Sud", "Konsullik"], "t": "Parlament"},
    {"s": "Zararli mikroorganizmlarni o'ldirish uchun suyuqlikni 60-80°C gacha qizdirish?", "v": ["Pasterlash", "Sterilizatsiya", "Filtrlash", "Dezinfeksiya"], "t": "Pasterlash"},
    {"s": "Yaponiyada parlamentning yuqori palatasi qanday ataladi?", "v": ["Senat", "Lordlar", "Perlar", "Bundesrat"], "t": "Perlar"},
    {"s": "Er-xotin Kyurilar tomonidan kashf etilgan, Polsha sharafiga nomlangan element?", "v": ["Poloniy", "Radiy", "Uran", "Toriy"], "t": "Poloniy"},
    {"s": "1905-yilda qo‘zg‘olon ko‘targan Rossiya Qora dengiz floti bronenosesi?", "v": ["Avrora", "Varyag", "Potyomkin", "Luzitaniya"], "t": "Potyomkin"},
    {"s": "Rossiya qora metallurgiyasida muhim ahamiyatga ega bo'lgan monopoliya?", "v": ["Prodmet", "Produgol", "Med", "Nobel"], "t": "Prodmet"},
    {"s": "Rossiya ko‘mir sanoatidagi eng yirik monopoliya nomi?", "v": ["Prodmet", "Produgol", "Neft", "Gaz"], "t": "Produgol"},
    {"s": "Zaharli gazdan himoyalanish uchun yaratilgan maxsus vosita?", "v": ["Protivogaz", "Respirator", "Shlem", "Niqob"], "t": "Protivogaz"},
    {"s": "Z. Freyd tomonidan asab kasalliklarini ongsizlikni o'rganish orqali davolash?", "v": ["Psixoanaliz", "Terapiya", "Gipnoz", "Jarrohlik"], "t": "Psixoanaliz"},
    {"s": "Rossiyadagi badavlat dehqonlar qanday atalgan?", "v": ["Yunkerlar", "Meshchanlar", "Quloqlar", "Yomenlar"], "t": "Quloqlar"},
    {"s": "Nurlanuvchi degan ma'noni anglatuvchi, Kyurilar kashf etgan element?", "v": ["Poloniy", "Radiy", "Kobalt", "Temir"], "t": "Radiy"},
    {"s": "Urushda ko'rilgan zararni yengilgan davlat tomonidan g'olibga to'lanishi?", "v": ["Kontributsiya", "Reparatsiya", "Tovon", "Boj"], "t": "Reparatsiya"},
    {"s": "Fuqarolarning umumiy saylovi asosida boshqariladigan davlat shakli?", "v": ["Respublika", "Monarxiya", "Imperiya", "Diktatura"], "t": "Respublika"},
    {"s": "Germaniya parlamentining quyi palatasi nomi qaysi?", "v": ["Rexstag (Reyxstag)", "Bundesrat", "Landtag", "Senat"], "t": "Rexstag (Reyxstag)"},
    {"s": "Tub joy aholisini (masalan, indeyslarni) saqlash uchun ajratilgan hudud?", "v": ["Koloniya", "Kanton", "Rezervatsiya", "Ghetto"], "t": "Rezervatsiya"},
    {"s": "Bir davlat diplomatik vakillarining qarorgohi nima deyiladi?", "v": ["Rezidensiya", "Konsullik", "Elchixona", "Shahar"], "t": "Rezidensiya"},
    {"s": "1898-yilda tuzilgan Rossiya sotsial-demokratik ishchi partiyasi?", "v": ["RSDRP", "ASDP", "GSDP", "HMK"], "t": "RSDRP"},
    {"s": "Rossiyada podshoning cheklanmagan mustabid hokimiyati?", "v": ["Samoderjaviye", "Respublika", "Konstitutsion monarxiya", "Demokratiya"], "t": "Samoderjaviye"},
    {"s": "Aholini majburan irqiy guruhlarga bo‘lish siyosati qanday ataladi?", "v": ["Integratsiya", "Assimilyatsiya", "Segregatsiya", "Konsentratsiya"], "t": "Segregatsiya"},
    {"s": "Qadimgi Rimda va ko'p zamonaviy davlatlarda yuqori palata nomi?", "v": ["Senat", "Kortes", "Duma", "Majlis"], "t": "Senat"},
    {"s": "Ajralib chiqishga intilish yoki ittifoqchi ruxsatisiz dushman bilan tuzilgan bitim?", "v": ["Separatizm", "Federalizm", "Shovinizm", "Koalitsiya"], "t": "Separatizm"},
    {"s": "1889-yili ingliz monopolisti Reyter Eronda ochgan bank?", "v": ["Shahanshohbank", "Melli bank", "Eron-Britaniya banki", "Markaziy bank"], "t": "Shahanshohbank"},
    {"s": "1905-yili A. Griffit tuzgan Biz o'zimiz partiyasi nomi qaysi?", "v": ["Shinfeyn", "Gomrul", "Ku-kluks-klan", "Antanta"], "t": "Shinfeyn"},
    {"s": "Irqiy ayirmachilik va milliy nizoni avj oldiruvchi o‘taketgan millatchilik?", "v": ["Shovinizm", "Gumanizm", "Liberalizm", "Demokratiya"], "t": "Shovinizm"},
    {"s": "Germaniyada ayrim hududiy birliklar (shtatlar) hokimi qanday atalgan?", "v": ["Shtatgalter", "Kansler", "Prezident", "Podsho"], "t": "Shtatgalter"},
    {"s": "Xitoyda 1644-1911-yillarda hukmronlik qilgan sulola qaysi?", "v": ["Sin sulolasi", "Min sulolasi", "Yuan sulolasi", "Xan sulolasi"], "t": "Sin sulolasi"},
    {"s": "Bir turdagi mahsulot ishlab chiqaruvchi korxonalarning mahsulot sotish birlashmasi?", "v": ["Sindikat", "Kartel", "Trest", "Konsern"], "t": "Sindikat"},
    {"s": "Xitoyda 1911-yilda boshlangan va bir yil davom etgan inqilob nomi?", "v": ["Madaniy inqilob", "Taypinlar qo'zg'oloni", "Sinxay inqilobi", "Afyun urushi"], "t": "Sinxay inqilobi"},
    {"s": "Muhammad Tarziy muharrirligida Afg'onistonda chiqqan gazeta?", "v": ["Siroj ul-axbori afg‘oniya", "Ibrat", "Minbao", "Kesari"], "t": "Siroj ul-axbori afg‘oniya"},
    {"s": "Taraqqiyotga qarshi, eskirgan tartiblarns saqlashga urinuvchi kuch?", "v": ["Siyosiy reaksiya", "Progressizm", "Liberalizm", "Reformizm"], "t": "Siyosiy reaksiya"},
    {"s": "Moddiy boyliklar garovi hisobiga foiz to'lash sharti bilan beriladigan qarz?", "v": ["Ssuda", "Soliq", "Boj", "Xiroj"], "t": "Ssuda"},
    {"s": "Moddalar va asboblarni mikrorganizmlardan butunlay tozalash (lotincha - toza)?", "v": ["Sterilizatsiya", "Pasterlash", "Filtrlash", "Dezinfeksiya"], "t": "Sterilizatsiya"},
    {"s": "Urush harakatlarini to‘xtatish uchun tuzilgan xalqaro bitim qanday ataladi?", "v": ["Sulh", "Shartnoma", "Dekret", "Konvensiya"], "t": "Sulh"},
    {"s": "1906-yilda Hindistonda boshlangan O‘z ishlab chiqarishimiz harakati?", "v": ["Svadeshi", "Svaraj", "Satyagraxa", "Xilofat"], "t": "Svadeshi"},
    {"s": "Hindistonda ilgari surilgan O‘z hokimiyatimiz g'oyasi qanday nomlangan?", "v": ["Svadeshi", "Svaraj", "Gomrul", "Shinfeyn"], "t": "Svaraj"},
    {"s": "Xitodagi Sindao bandargohi Germaniya tomonidan qanday nomlangan?", "v": ["Szyaochjouvan", "Lyuyshun", "Port Artur", "Shanxay"], "t": "Szyaochjouvan"},
    {"s": "Germaniyaning Sharqiy Afrikadagi (janub va markaz) mustamlakasi?", "v": ["Tanganika", "Kamerun", "Togo", "Marokash"], "t": "Tanganika"},
    {"s": "1915-yilda Bolgariya, Germaniya, Avstriya-Vengriya va Usmonli davlati ittifoqi?", "v": ["To‘rtlar ittifoqi", "Uchlar Ittifoqi", "Antanta", "NATO"], "t": "To‘rtlar ittifoqi"},
    {"s": "Mag'lub davlatdan g'olib davlat foydasiga majburan undiriladigan haq (forscha)?", "v": ["Tovon", "Reparatsiya", "Ssuda", "Boj"], "t": "Tovon"},
    {"s": "Xalqaro shartnoma yoki bitim (lotincha) qanday ataladi?", "v": ["Traktat", "Nota", "Dekret", "Depesha"], "t": "Traktat"},
    {"s": "Buyuk Britaniyadagi kasaba uyushmalari qanday nomlangan?", "v": ["Tred-yunionlar", "Shinfeyn", "Gomrul", "Kartel"], "t": "Tred-yunionlar"},
    {"s": "Korxonalarning ishlab chiqarish va savdoni yagona markazdan boshqarish birlashmasi?", "v": ["Trest", "Kartel", "Sindikat", "Konsern"], "t": "Trest"},
    {"s": "Sun Yat Sen tomonidan 1905-yilda tuzilgan „Xitoy uyushmalari ittifoqi?", "v": ["Tunminxay", "Gomindan", "Ixetuan", "Sin"], "t": "Tunminxay"},
    {"s": "1879-1882-yillarda Germaniya, Avstriya-Vengriya va Italiya o'rtasida tuzilgan blok?", "v": ["Uchlar Ittifoqi", "Antanta", "To'rtlar Ittifoqi", "Muqaddas Ittifoq"], "t": "Uchlar Ittifoqi"},
    {"s": "Germaniyadagi yirik elektr monopoliyasi qanday nomlangan?", "v": ["Umumiy elektr jamiyati", "Umumiy elektr kompaniyasi", "Siemens", "Bosch"], "t": "Umumiy elektr jamiyati"},
    {"s": "AQSHdagi yirik elektr monopoliyasi nomi qaysi?", "v": ["Umumiy elektr kompaniyasi", "Umumiy elektr jamiyati", "General Electric", "Tesla"], "t": "Umumiy elektr kompaniyasi"},
    {"s": "Jamiyat hayotida shaharlar rolining va aholisining ortishi jarayoni?", "v": ["Migratsiya", "Konsentratsiya", "Urbanizatsiya", "Industriya"], "t": "Urbanizatsiya"},
    {"s": "1815-yilda Napoleon qo'shini so'nggi bor tor-mor etilgan joy?", "v": ["Vaterloo", "Verden", "Somma", "Borodino"], "t": "Vaterloo"},
    {"s": "Birinchi jahon urushida 2 milliondan ortiq odam halok bo'lgan qirg'inbarot janglar?", "v": ["Verden qirg‘ini", "Nevel qirg'ini", "Borodino jangi", "Brusilov hujumi"], "t": "Verden qirg‘ini"},
    {"s": "Verden jangida 2 million kishi halok bo'lgani uchun berilgan nom (takror)?", "v": ["Verden qirg'ini", "Somma qirg'ini", "Ipr qirg'ini", "Vaterloo qirg'ini"], "t": "Verden qirg'ini"},
    {"s": "1871-yilda Jamoliddin al-Afg‘oniy tomonidan tuzilgan „Vatan partiyasi“?", "v": ["Xizb ul-Vatan", "Yosh turklar", "Musulmonlar ligasi", "HMK"], "t": "Xizb ul-Vatan"},
    {"s": "1915-yil aprelida birinchi marta ishlatilgan kimyoviy qurol nomi qaysi?", "v": ["Xlor (zaharli gaz)", "Iprit", "Fosgen", "Dinamit"], "t": "Xlor (zaharli gaz)"},
    {"s": "Barcha madaniyatlarni yevropalashtirish g‘oyasi nima deb ataladi?", "v": ["Yevrosentrizm", "Panislomizm", "Globalizm", "Islohotchilik"], "t": "Yevrosentrizm"},
    {"s": "AQSHning Lotin Amerikasidagi xalqaro politsiya roli siyosati qanday atalgan?", "v": ["Yo‘g‘on kaltak", "Monro doktrinasi", "Ochiq eshiklar", "Neytrallitet"], "t": "Yo‘g‘on kaltak"},
    {"s": "1889-yilda tuzilgan „Birlik va taraqqiyot“ partiyasi a’zolarining nomi?", "v": ["Yosh turklar", "Yangi usmonlilar", "Gomindan", "Svaraj"], "t": "Yosh turklar"},
    {"s": "Germaniyadagi katta yer egalari qanday nomlangan?", "v": ["Yunkerlar", "Lendlordlar", "Quloqlar", "Yomenlar"], "t": "Yunkerlar"},
    {"s": "1915-yilda Germaniya Ipr jangida ishlatgan, 5000 kishi o'limiga sabab bo'lgan gaz?", "v": ["Zaharli gaz (xlor)", "Azot", "Is gazi", "Kislorod"], "t": "Zaharli gaz (xlor)"}
]