# data_6_atamalar.py

atamalar_6 = [
    {"s": "Qadimgi Yunoniston shaharlarida xalq yig'ilishi joyi va markaziy maydon qanday atalgan?", "v": ["Akropol", "Agora", "Forum", "Polis"], "t": "Agora"},
    {"s": "O`rta Osiyo xalqlari orasida “xanjar” so'zi qanday nom bilan atalgan?", "v": ["Sagaris", "Stil", "Akinak", "Goplit"], "t": "Akinak"},
    {"s": "Mil.avv II mingyillikda Attikaning g`arbiy qismida yunonlar tomonidan bunyod etilgan, “Yuqori shahar” ma‘nosini anglatuvchi qal‘ani toping.", "v": ["Agora", "Akropol", "Term", "Polis"], "t": "Akropol"},
    {"s": "Ustida shaharga suv keladigan anhori bo'lgan baland ko'prik qanday nomlanadi?", "v": ["Akveduk", "Katapulta", "Triyera", "Amfiteatr"], "t": "Akveduk"},
    {"s": "Ispaniyadagi so'nggi paleolitga oid qoya rasmlari topilgan g'or nomini ko'rsating.", "v": ["Moxenjodaro", "Altamir", "Bobil", "Tepe-Gavr"], "t": "Altamir"},
    {"s": "Sahna atrofida tomoshabinlar o'tirishiga mo'ljallangan qurilmalar bilan qurshalgan tomsiz katta inshoot qanday ataladi?", "v": ["Palestra", "Amfiteatr", "Akropol", "Forum"], "t": "Amfiteatr"},
    {"s": "Insonni qurshab turgan muhitda jonlar va ruhlarning mavjudligiga bo'lgan e‘tiqod qaysi atama bilan ifodalanadi?", "v": ["Fetishizm", "Animizm", "Totemizm", "Buddaviylik"], "t": "Animizm"},
    {"s": "Qadimgi Yunoniston va Qadimgi Rim tarixini ifodalovchi, lotincha “qadimgi” ma’nosini beruvchi tushunchani toping.", "v": ["Sivilizatsiya", "Antik tarix", "Etnografiya", "Arxeologiya"], "t": "Antik tarix"},
    {"s": "Qadimgi odamlarning suyak qoldiqlarini tekshirib, uning tashqi qiyofasini tiklovchi fan qanday ataladi?", "v": ["Antropologiya", "Arxeologiya", "Etnografiya", "Epigrafika"], "t": "Antropologiya"},
    {"s": "Oltin mo'ynani izlab “Argo” kemasida safarga chiqqan Ellada qahramonlari qanday nomlangan?", "v": ["Avgurlar", "Argonavtlar", "Ellinlar", "Havoriylar"], "t": "Argonavtlar"},
    {"s": "Ashyoviy manbalarni o‘rganuvchi va ular bo‘yicha tarixiy o‘tmishni qayta tiklovchi fan nomini toping.", "v": ["Etnografiya", "Epigrafika", "Arxeologiya", "Numizmatika"], "t": "Arxeologiya"},
    {"s": "Zardushtiylik dinining muqaddas kitobi, “Qat‘iy belgilangan qonun-qoidalar” ma‘nosini anglatuvchi asarni ko'rsating.", "v": ["Braxman", "Avesto", "Sanskrit", "Mif"], "t": "Avesto"},
    {"s": "Rimdagi biror masala yuzasudan fol ochuvchi kohinlar qanday atalgan?", "v": ["Avgurlar", "Pontifiklar", "Liktorlar", "Strateglar"], "t": "Avgurlar"},
    {"s": "Janubiy Afrikadan topilgan eng qadimgi odam turi qanday nomlanadi?", "v": ["Pitekantrop", "Avstralopitek", "Sinantrop", "Neandertal"], "t": "Avstralopitek"},
    {"s": "Mil. avv II mingyillikda Mesopotamiya janubidagi yirik davlat, “Xudolar darvozasi” ma‘nosini anglatuvchi shaharni toping.", "v": ["Misr", "Bobil", "Sparta", "Afina"], "t": "Bobil"},
    {"s": "Hindlar e‘tiqodiga ko'ra, xudo Braxmaning og‘zidan chiqqan deb hisoblanuvchi ruhoniylar tabaqasi qanday ataladi?", "v": ["Vayshilar", "Kshatriylar", "Braxmanlar", "Shudralar"], "t": "Braxmanlar"},
    {"s": "Siddhartha Gautamaning «ma’rifatlangan» ma'nosini anglatuvchi ikkinchi ismi yoki laqabini toping.", "v": ["Budda", "Braxman", "Iso", "Zardusht"], "t": "Budda"},
    {"s": "Miloddan avvalgi VI asrda Hindistonda Siddhartha Gautama tomonidan asos solingan diniy ta‘limot qaysi?", "v": ["Zardushtiylik", "Buddaviylik", "Islom", "Xristianlik"], "t": "Buddaviylik"},
    {"s": "Avestoga kora, oz hududini himoya qilish uchun birlashgan bir qancha qabilalar ittifoqi qanday nomlangan?", "v": ["Nmana", "Varzana", "Dax’yu", "Polis"], "t": "Dax’yu"},
    {"s": "Nil daryosi O'rtayer dengiziga quyilta joyidagi uchburchaksimon hududni yunonlar qanday atashgan?", "v": ["Oykumena", "Delta", "Varna", "Nom"], "t": "Delta"},
    {"s": "Yunoncha «xalq hokimiyati» ma’nosini beruvchi, davlat boshqaruvida fuqarolar ishtirok etadigan ijtimoiy tuzumni toping.", "v": ["Imperiya", "Respublika", "Demokratiya", "Diktatura"], "t": "Demokratiya"},
    {"s": "Afinaning oddiy aholisi qanday nom bilan atalgan?", "v": ["Meteklar", "Demos", "Aristokratlar", "Patritsiylar"], "t": "Demos"},
    {"s": "Rimda favqulodda vaziyatlar yuz berganda 6 oy muddatga tayinlanuvchi yakkabosh hukmdor kim?", "v": ["Konsul", "Diktator", "Imperator", "Strateg"], "t": "Diktator"},
    {"s": "Qadimgi Yunoniston mamlakati o'z davrida qanday nomlangan?", "v": ["Italiya", "Ellada", "Mesopotamiya", "Attika"], "t": "Ellada"},
    {"s": "Qadimgi yunonlar o'zlarini qanday nom bilan atashgan?", "v": ["Italiklar", "Varvarlar", "Ellinlar", "Patritsiylar"], "t": "Ellinlar"},
    {"s": "Qadimgi bitik va yozuvlarni organish bilan shugullanuvchi maxsus fan nomini ko'rsating.", "v": ["Numizmatika", "Epigrafika", "Etnografiya", "Antropologiya"], "t": "Epigrafika"},
    {"s": "Qadimgi odamlarning udumlari va madaniy an‘analarini hozirgi qabilalar misolida o`rganuvchi olim kim?", "v": ["Arxeolog", "Etnograf", "Epigrafist", "Antropolog"], "t": "Etnograf"},
    {"s": "Og'ir qurollangan askarlarning 9 yoki 16 qator bo'lib saf tortish tartibi qanday ataladi?", "v": ["Kogorta", "Senturiya", "Falanga", "Legion"], "t": "Falanga"},
    {"s": "Yunoncha “donishmandlikni sevish” ma’nosini anglatuvchi soha qaysi?", "v": ["Ritorika", "Grammatika", "Falsafa", "Tarix"], "t": "Falsafa"},
    {"s": "Ayrim buyumlar omad keltiradi yoki falokatdan asraydi deb ishonish qanday nomlanadi?", "v": ["Animizm", "Fetishizm", "Totemizm", "Magiya"], "t": "Fetishizm"},
    {"s": "Misr hukmdori qaysi unvon bilan atalgan va bu unvon “ulug' xonadon” ma‘nosini beradi?", "v": ["Imperator", "Podsho", "Fir’avn", "Strateg"], "t": "Fir’avn"},
    {"s": "Devordagi hali kurumagan (nam) suvoqqa chizilgan rasm qanday ataladi?", "v": ["Mozaika", "Freska", "Ikonopis", "Stil"], "t": "Freska"},
    {"s": "Rimda yig'ilish joyi va bozor maydoni bo'lib xizmat qilgan shahar markazi qaysi?", "v": ["Agora", "Forum", "Akropol", "Term"], "t": "Forum"},
    {"s": "Mesopotamiyaning afsonaviy qahramoni hamda Uruk shahri podshosi bo'lgan shaxsni toping.", "v": ["Hammurapi", "Gilgamish", "Tutmos", "Perikl"], "t": "Gilgamish"},
    {"s": "Qadimgi Rimda tomosha uchun yirtqich hayvonlar yoki bir-biri bilan urushtirilgan qul kim deb atalgan?", "v": ["Goplit", "Gladiator", "Liktor", "Legioner"], "t": "Gladiator"},
    {"s": "Qadimgi Yunoniston va Makedoniya qo'shinining og'ir qurollangan piyoda jangchisi qanday nomlangan?", "v": ["Goplit", "Akinak", "Falanga", "Senturiya"], "t": "Goplit"},
    {"s": "Rimda tarix, geografiya, geometriya va musiqa oqitiladigan orta maktab qanday atalgan?", "v": ["Palestra", "Grammatika", "Ritorika", "Akademiya"], "t": "Grammatika"},
    {"s": "Iso Masihning o'n ikki nafar shogirdlari tarixda qanday nom qoldirishgan?", "v": ["Avgurlar", "Havoriylar", "Pontifiklar", "Kohinlar"], "t": "Havoriylar"},
    {"s": "Odamlar xudolarga sig'inadigan va muqaddas hisoblangan bino qanday ataladi?", "v": ["Amfiteatr", "Ibodatxona", "Piramida", "Forum"], "t": "Ibodatxona"},
    {"s": "Barcha mehnat qurollari umumiy bo‘lgan va hamma birgalikda mehnat qilgan insoniyatning ilk davri qanday nomlanadi?", "v": ["Ibtidoiy jamoa tuzumi", "Sivilizatsiya", "Davlatchilik davri", "Monarxiya"], "t": "Ibtidoiy jamoa tuzumi"},
    {"s": "Turmush va mehnat umumiyligi asosida birlashgan eng qadimgi odamlar jamoasini toping.", "v": ["Urug'", "Ibtidoiy to’da", "Qabila", "Varna"], "t": "Ibtidoiy to’da"},
    {"s": "Gomerning Troya urushi voqealariga bag'ishlangan dostoni qaysi?", "v": ["Ramayana", "Iliada", "Avesto", "Gilgamish"], "t": "Iliada"},
    {"s": "Spartaliklar tomonidan qulga aylantirilgan va o'zlari bilan bir tilda so'zlashuvchi mahalliy aholi kimlar?", "v": ["Meteklar", "Ilotlar", "Plebeylar", "Perieklar"], "t": "Ilotlar"},
    {"s": "Yunoncha «buqa» yoki «buzoqcha» ma’nosini bildiruvchi, Apennin yarimorolida joyhaziran davlatni toping.", "v": ["Italiya", "Iberiya", "Attika", "Latsiy"], "t": "Italiya"},
    {"s": "Lotincha “hukmdor” ma’nosini anglatuvchi, dastlab faxriy harbiy unvon, keyinchalik mutloq hukmdor unvoni qaysi?", "v": ["Diktator", "Imperator", "Konsul", "Fir'avn"], "t": "Imperator"},
    {"s": "Hukmdorning cheklanmagan hokimiyati o'rnatilgan davlat qanday nomlanadi?", "v": ["Respublika", "Imperiya", "Polis", "Demokratiya"], "t": "Imperiya"},
    {"s": "Apennin yarimorolida istiqomat qilgan qadimiy qabilalar majmuasi qanday ataladi?", "v": ["Ellinlar", "Italiklar", "Forslar", "Shumerlar"], "t": "Italiklar"},
    {"s": "Qadimgi misrliklarning “muqaddas bitiklar” ma‘nosini beruvchi yozuvi qaysi?", "v": ["Mixxat", "Iyerogliflar", "Sanskrit", "Alifbo"], "t": "Iyerogliflar"},
    {"s": "Rimda konsullikka nomzodlar saylov kuni kiyadigan oppoq va harir libos qanday atalgan?", "v": ["Toga", "Kandida", "Stil", "Stola"], "t": "Kandida"},
    {"s": "Biror lavozimni egallashga harakat qiluvchi nomzod shaxs bugungi kunda ham qanday ataladi?", "v": ["Kandidat", "Konsul", "Senator", "Liktor"], "t": "Kandidat"},
    {"s": "Qadimgi davrda shahar devorlarini buzish uchun ishlatilgan toshotar qurol nomini ko'rsating.", "v": ["Falanga", "Katapulta", "Triyera", "Akinak"], "t": "Katapulta"},
    {"s": "Rim shahri qurilgan yetti tepalikning eng balandi qaysi?", "v": ["Akropol", "Kapitoliy tepaligi", "Palatin", "Olimp"], "t": "Kapitoliy tepaligi"},
    {"s": "Rim armiyasidagi bir necha senturiyalardan tashkil topgan harbiy bo`linma qanday atalgan?", "v": ["Falanga", "Kogorta", "Demos", "Triyera"], "t": "Kogorta"},
    {"s": "Ibodatxonalarda xizmat qiluvchi ruhoniylar qanday nomlangan?", "v": ["Strateglar", "Kohinlar", "Avgurlar", "Liktorlar"], "t": "Kohinlar"},
    {"s": "Rimda lotincha “ijaraga yer oluvchi” ma’nosini bildiruvchi mayda yer ijarachilari kimlar?", "v": ["Kolonlar", "Plebeylar", "Ilotlar", "Meteklar"], "t": "Kolonlar"},
    {"s": "O'z vatanini tark etib, yeni yerlarda barpo etilgan manzilgohlar nima deb ataladi?", "v": ["Nomlar", "Koloniyalar", "Polislar", "Shahar-davlatlar"], "t": "Koloniyalar"},
    {"s": "Qadimgi xitoyliklar tomonidan ixtiro qilingan, doim janubni ko‘rsatuvchi asbobni toping.", "v": ["Seysmograf", "Kompas", "Stil", "Astrolyabiya"], "t": "Kompas"},
    {"s": "Rim respublikasi davrida har yili ikki kishi saylanadigan oliy siyosiy lavozim qaysi?", "v": ["Imperator", "Konsul", "Diktator", "Strateg"], "t": "Konsul"},
    {"s": "Rimda konsullarning xavfsizligini ta'minlovchi 12 nafar faxriy qorovul qanday atalgan?", "v": ["Senturionlar", "Liktorlar", "Avgurlar", "Goplitlar"], "t": "Liktorlar"},
    {"s": "Insoniyat tarixida urug` jamoasi ayol kishi atrofida jipslashgan davr qanday nomlanadi?", "v": ["Patriarxat", "Matriarxat", "Demokratiya", "Respublika"], "t": "Matriarxat"},
    {"s": "Afinada doimiy yashaydigan, lekin chet ellik hisoblangan aholi qatlamini toping.", "v": ["Ilotlar", "Meteklar", "Demos", "Perieklar"], "t": "Meteklar"},
    {"s": "Yunonlar tomonidan “ikki daryo oralig`i” deb atalgan, Dajla va Frot daryolari oralig'idagi hudud qaysi?", "v": ["Mesopotamiya", "Misr", "Hindiston", "Falastin"], "t": "Mesopotamiya"},
    {"s": "Qadimgi xalqlarning dunyo yaralishi, xudolar va qahramonlar haqidagi afsonalari nima deb ataladi?", "v": ["Doston", "Tarix", "Mif", "Falsafa"], "t": "Mif"},
    {"s": "Mezolit davriga oid, toshdan yasalgan juda mayda mehnat qurollari qanday nomlanadi?", "v": ["Akinak", "Mikrolit", "Sagaris", "Stil"], "t": "Mikrolit"},
    {"s": "Mesopotamiyada og'irlik o'lchovi sifatida ishlatilgan, 550 gramm kumushga teng birlikni toping.", "v": ["Tirsak", "Mino", "Talant", "Shekel"], "t": "Mino"},
    {"s": "Shumerlar tomonidan yaratilgan, loy taxtachalarga yoziladigan qadimgi yozuv turi qaysi?", "v": ["Iyeroglif", "Mixxat", "Sanskrit", "Alifbo"], "t": "Mixxat"},
    {"s": "Hindiston hududidagi eng qadimgi shahar va sivilizatsiya markazlaridan birini ko'rsating.", "v": ["Bobil", "Moxenjodaro", "Afina", "Rim"], "t": "Moxenjodaro"},
    {"s": "Rangli shisha yoki mayda tosh parchalaridan terib ishlangan tasviriy san'at turi qanday ataladi?", "v": ["Freska", "Mozaika", "Stil", "Iyeroglif"], "t": "Mozaika"},
    {"s": "Avesto kitobida keltirilgan, ota boshliq bo'lgan katta oila qanday nomlangan?", "v": ["Nmana", "Varzana", "Dax’yu", "Varna"], "t": "Nmana"},
    {"s": "Qadimgi tangalarni va ularning zarb qilinish tarixini o`rganuvchi fan qaysi?", "v": ["Epigrafika", "Numizmatika", "Arxeologiya", "Etnografiya"], "t": "Numizmatika"},
    {"s": "Qadimgi Misr hududida vujudga kelgan ilk kichik davlatlar qanday atalgan?", "v": ["Polislar", "“Nom”lar", "Koloniyalar", "Viloyatlar"], "t": "“Nom”lar"},
    {"s": "Misrdagi ilk davlatni (nomni) boshqargan hukmdor unvoni qanday bo'lgan?", "v": ["Fir'avn", "Nomarx", "Strateg", "Konsul"], "t": "Nomarx"},
    {"s": "Peloponnesda Zevs xudosi sharafiga to'rt yilda bir o'tkaziladigan sport musobaqalari qanday nomlangan?", "v": ["Triumf", "Olimpiada o'yinlari", "Termlar", "Forumlar"], "t": "Olimpiada o'yinlari"},
    {"s": "Zardushtiylikda vafot etgan odamning tozalangan suyaklarini saqlash uchun mo'ljallangan idish qanday ataladi?", "v": ["Sarkofag", "Ossuariy", "Piramida", "Maqbara"], "t": "Ossuariy"},
    {"s": "Yunonlar yer yuzining odamlar yashaydigan, ma'lum bo'lgan qismini nima deb atashgan?", "v": ["Delta", "Oykumena", "Polis", "Ellada"], "t": "Oykumena"},
    {"s": "Afinada o'g'il bolalarga jismoniy tarbiya, adabiyot va musiqa o'rgatiladigan xususiy maktab qaysi?", "v": ["Grammatika", "Palestra", "Ritorika", "Akademiya"], "t": "Palestra"},
    {"s": "Ota tomonidan yaqin qarindoshlarning bir necha avlodini birlashtirgan oila qanday ataladi?", "v": ["Matriarxal oila", "Patrialxal oila", "Urug'", "To'da"], "t": "Patrialxal oila"},
    {"s": "Qadimgi Misrda yozuv ashyosi sifatida ishlatilgan qamish poyasidan tayyorlangan materialni toping.", "v": ["Stil", "Papirus", "Pergament", "Qog'oz"], "t": "Papirus"},
    {"s": "Qadimgi Rim shahrining eng qadimgi va imtiyozli tub aholisi kimlar?", "v": ["Plebeylar", "Patritsiylar", "Meteklar", "Ilotlar"], "t": "Patritsiylar"},
    {"s": "Yunoncha “bolani kuzatib boruvchi” ma’nosini beruvchi, bugungi kunda ta’lim sohasi vakili bo'lgan atamani toping.", "v": ["Strateg", "Pedagog", "Kohin", "Nomarx"], "t": "Pedagog"},
    {"s": "Afinada yashaydigan, ammo to‘laqonli fuqarolik huquqiga ega bo‘lmagan erkin aholi qanday atalgan?", "v": ["Meteklar", "Perieklar", "Ilotlar", "Demos"], "t": "Perieklar"},
    {"s": "Misr fir‘avnlarining mahobatli toshlardan qurilgan maqbaralari qanday nomlanadi?", "v": ["Maqbara", "Piramida", "Akveduk", "Sarkofag"], "t": "Piramida"},
    {"s": "Rimga boshqa joylardan ko`chib kelgan va huquqlari cheklangan aholi qatlami qanday atalgan?", "v": ["Patritsiylar", "Plebeylar", "Kolonlar", "Liktorlar"], "t": "Plebeylar"},
    {"s": "Qadimgi Misrda uzunlikni o'lchashda ishlatilgan 52,5 santimetrli birlikni toping.", "v": ["Mino", "Podsho tirsagi", "Stil", "Funt"], "t": "Podsho tirsagi"},
    {"s": "Qadimgi yunon manbalarida Zarafshon daryosi qanday nom bilan keltirilgan?", "v": ["Nil", "Politiment", "Oks", "Yaksart"], "t": "Politiment"},
    {"s": "Yunoncha “shahar” yoki “shahar-davlat” ma'nosini anglatuvchi atamani ko'rsating.", "v": ["Forum", "Polis", "Agora", "Nom"], "t": "Polis"},
    {"s": "Rimda diniy marosimlarni tartibga soluvchi va bayramlar taqvimi uchun mas'ul bo'lgan oliy ruhoniy kim?", "v": ["Avgur", "Pontifik", "Liktor", "Strateg"], "t": "Pontifik"},
    {"s": "Qadimgi dunyoda “so'zlovchi mehnat quroli” deb atalgan, huquqsiz inson kim?", "v": ["Kolon", "Qul", "Plebey", "Metek"], "t": "Qul"},
    {"s": "Lotincha “umumiy ish” ma‘nosini bildiruvchi, davlatni saylab qo'yiladigan organlar boshqaradigan tuzum qaysi?", "v": ["Imperiya", "Respublika", "Monarxiya", "Diktatura"], "t": "Respublika"},
    {"s": "Chiroyli va ta'sirli nutq so'zlash san'ati qanday nomlanadi?", "v": ["Grammatika", "Ritorika", "Falsafa", "Tarix"], "t": "Ritorika"},
    {"s": "O`rta Osiyo jangchilarining quroli bo'lgan “jangavor oybolta” qanday atalgan?", "v": ["Akinak", "Sagaris", "Mikrolit", "Falanga"], "t": "Sagaris"},
    {"s": "Qadimgi hindlarning “Mahabharata” va “Ramayana” asarlari yozilgan adabiy tili qaysi?", "v": ["Iyeroglif", "Sanskrit", "Mixxat", "Lotin tili"], "t": "Sanskrit"},
    {"s": "Fir‘avnlarning mumiyolangan jasadi qo'yiladigan mahobatli tosh tobut qanday ataladi?", "v": ["Ossuariy", "Sarkofag", "Piramida", "Tirsak"], "t": "Sarkofag"},
    {"s": "Rimda “oqsoqollar kengashis” ma‘nosini anglatuvchi oliy davlat organi nomini toping.", "v": ["Kengash", "Senat", "Demos", "Kogorta"], "t": "Senat"},
    {"s": "Rim qo'shinidagi 80 nafar jangchidan iborat bo'lgan kichik harbiy bo'linma qanday atalgan?", "v": ["Kogorta", "Senturiya", "Falanga", "Legioner"], "t": "Senturiya"},
    {"s": "Qadimgi Xitoyda zilzilani va uning yo'nalishini aniqlash uchun ixtiro qilingan asbob qaysi?", "v": ["Kompas", "Seysmograf", "Stil", "Akveduk"], "t": "Seysmograf"},
    {"s": "Piramidalarni qo'riqlab turuvchi, tanasi arslon va boshi odam shaklidagi haykal qanday ataladi?", "v": ["Sfinks", "Argonavt", "Budda", "Gilgamish"], "t": "Sfinks"},
    {"s": "Tevaragidagi yerlarni boshqaruvchi, o'zini-o'zi idora qiladigan mustaqil shahar qanday nomlanadi?", "v": ["Koloniya", "Shahar-davlat (polis)", "Imperiya", "Forum"], "t": "Shahar-davlat (polis)"},
    {"s": "Shaharlar, yozuv va davlat boshqaruvi rivojlangan jamiyat taraqqiyotining yuqori bosqichi qanday ataladi?", "v": ["Antik davr", "Sivilizatsiya", "Mezolit", "Ibtidoiy davr"], "t": "Sivilizatsiya"},
    {"s": "Qadimgi dunyoda yozuv yozish (mum surtilgan taxtachaga) uchun ishlatilgan metall tayoqcha nomini toping.", "v": ["Akinak", "Stil", "Mikrolit", "Sagaris"], "t": "Stil"},
    {"s": "Afinada qo'shinni boshqaruvchi yoki Beshyuzlar kengashiga rahbarlik qiluvchi shaxs kim?", "v": ["Nomarx", "Strateg", "Konsul", "Diktator"], "t": "Strateg"},
    {"s": "Kanallar va ariqlar qazib, ekin maydonlariga suv yetkazib berish jarayoni qanday ataladi?", "v": ["Dehqonchilik", "Sun’iy sug`orish", "Termachilik", "O'zlashtiruvchi xo'jalik"], "t": "Sun’iy sug`orish"},
    {"s": "Qadimgi Rimda ham cho'milish, ham dam olish va muloqot joyi bo'lgan jamoat binolari qaysi?", "v": ["Amfiteatr", "Termlar", "Forum", "Akveduk"], "t": "Termlar"},
    {"s": "Rimda g'olib sarkardaning shahar bo'ylab tantanali kirib kelishi va g'alaba bayrami qanday atalgan?", "v": ["Olimpiada", "Triumf", "Veto", "Forum"], "t": "Triumf"},
    {"s": "Rimlik o'g'il bolalar 14 yoshga to'lgach kiya boshlaydigan oppoq rangli milliy libos qanday nomlangan?", "v": ["Kandida", "Toga", "Stola", "Tunika"], "t": "Toga"},
    {"s": "Qadimgi yunonlarning uch qator eshkakli, tez harakatlanuvchi harbiy kemasi qaysi?", "v": ["Argo", "Triyera", "Karavella", "Galera"], "t": "Triyera"},
    {"s": "Umumiy mehnat qurollariga ega bo'lgan va birgalikda yashaydigan qarindoshlar jamoasi nima deb ataladi?", "v": ["To'da", "Urug’", "Varna", "Kogorta"], "t": "Urug’"},
    {"s": "Tabiatning tayyor mahsulotlarini yig'ish va ov qilishga asoslangan xo'jalik turi qanday nomlanadi?", "v": ["Ishlab chiqaruvchi xo'jalik", "Ozlashtiruvchi xojalik", "Sug'orma dehqonchilik", "Chorvachilik"], "t": "Ozlashtiruvchi xojalik"},
    {"s": "Qadimgi Hindistonda aholining kasbi va ijtimoiy kelib chiqishiga qarab to'rt tabaqaga bo'linishi qanday ataladi?", "v": ["Nom", "Varna (kasta)", "Polis", "Dax'yu"], "t": "Varna (kasta)"},
    {"s": "Dastlab yunon tilini bilmaydigan ajnabiylarga, keyinchalik esa madaniyatsiz kishilarga nisbatan ishlatilgan so'zni toping.", "v": ["Ellin", "Varvar", "Metek", "Ilot"], "t": "Varvar"},
    {"s": "Avesto kitobiga ko'ra, bir hududda yonma-yon yashaydigan qo'shnichilik jamoasi qanday nomlangan?", "v": ["Nmana", "Varzana", "Dax'yu", "Varna"], "t": "Varzana"},
    {"s": "Rim xalq tribunlarining Senat qarorini to'xtatib qo'yish huquqi, lotincha “taqiqlayman” ma'nosini beruvchi atama qaysi?", "v": ["Triumf", "Veto", "Stil", "Konsul"], "t": "Veto"}
]