# data_10ut_atamalar.py

atamalar_10ut = [
    {"s": "Bosqinchilikdan iborat bo‘lgan, tajovuzkorlikka asoslangan harakat nima deb ataladi?", "v": ["Agressiya", "Ekspansiya", "Militarizatsiya", "Okkupatsiya"], "t": "Agressiya"},
    {"s": "Hunarmandlarning jamoa bo‘lib ishlash uchun tuzilgan uyushmasi (italyancha 'hunarmand')?", "v": ["Kasaba uyushmasi", "Artel", "Kolxoz", "Sindikat"], "t": "Artel"},
    {"s": "Rossiya sotsial-demokratik ishchi partiyasining 1903-yil II syezdida ko'pchilikni tashkil etgan guruh?", "v": ["Mensheviklar", "Kadetlar", "Bolsheviklar", "Eserlar"], "t": "Bolsheviklar"},
    {"s": "Turkistonda 1918-1925-yillarda sovet rejimiga qarshi olib borilgan istiqlolchilik harakatiga sho'ro hukumati tomonidan berilgan kamsituvchi nom?", "v": ["Bosmachilik", "Jadidchilik", "Millatchilik", "Terrorizm"], "t": "Bosmachilik"},
    {"s": "Ot dumining qilidan to‘qilgan, yuzni yopib turuvchi to‘r parda?", "v": ["Paranji", "Ro'mol", "Chachvon", "Niqob"], "t": "Chachvon"},
    {"s": "Arman millatchilarining 'Ittifoq' partiyasi a’zolari qanday atalgan?", "v": ["Kadetlar", "Dashnoqlar", "Bolsheviklar", "Mensheviklar"], "t": "Dashnoqlar"},
    {"s": "Hukumat yoki tashkilotning muhim hujjatni ko‘pchilik e’tiboriga yetkazuvchi rasmiy bayonoti?", "v": ["Manifest", "Deklaratsiya", "Sanksiya", "Ultimatum"], "t": "Deklaratsiya"},
    {"s": "Metrik sistema qabul qilinguncha Rossiyada qo‘llangan, 1,09 gektarga teng yer o'lchov birligi?", "v": ["Desyatina", "Tanob", "Pud", "Gektar"], "t": "Desyatina"},
    {"s": "Sovetlar tarkibida dehqonlar manfaatini himoya qilgan sotsial-revolyutsionerlar guruhi?", "v": ["Kadetlar", "Bolsheviklar", "Eserlar", "Maksimalistlar"], "t": "Eserlar"},
    {"s": "Maxsus yuk, harbiy texnika va qo‘shinlar ortilgan poyezd yoki avtokolonna?", "v": ["Karvon", "Eshelon", "Transport", "Sanitar poyezd"], "t": "Eshelon"},
    {"s": "Odamlar, korxonalar va boyliklarni urush yoki ofat xavfidan saqlash uchun xavfsiz joyga ko‘chirish?", "v": ["Repatriatsiya", "Deportatsiya", "Evakuatsiya", "Immigratsiya"], "t": "Evakuatsiya"},
    {"s": "Maqsadi va dunyoqarashi mushtarak bo‘lgan kishilarning siyosiy birlashmasi (partiya)?", "v": ["Firqa", "Syezd", "Shu’ba", "Jamoa"], "t": "Firqa"},
    {"s": "Rossiya o'lchov tizimida taxminan 410 grammga teng bo‘lgan og‘irlik birligi?", "v": ["Pud", "Misqol", "Funt", "Chorak"], "t": "Funt"},
    {"s": "Bir daryo oqimida o'zaro bog'langan holda joylashgan bir nechta gidroelektrostansiyalar majmuyi?", "v": ["IESlar tarmog'i", "GESlar kaskadi", "Energo-tizim", "Suv ombori"], "t": "GESlar kaskadi"},
    {"s": "Tik yoki qaytarma yoqali, ustidan kamar bog‘lanadigan harbiy ustki ko‘ylak?", "v": ["Mundir", "Gimnastyorka", "Shinel", "Kamzul"], "t": "Gimnastyorka"},
    {"s": "Xalq xo‘jaligining barcha sohalarini yirik mashina texnikasi asosiga o‘tkazish jarayoni?", "v": ["Kollektivlashtirish", "Industrlashtirish", "Modernizatsiya", "Avtomatlashtirish"], "t": "Industrlashtirish"},
    {"s": "Millatlar ozodligi va huquqiy tengligiga asoslangan birdamlik va hamkorlik tamoyili?", "v": ["Shovinizm", "Millatchilik", "Internatsionalizm", "Tolerantlik"], "t": "Internatsionalizm"},
    {"s": "Sho‘roi Ulamo va Sho‘royi ittifoqchilar partiyalarining birlashuvidan tuzilgan partiya?", "v": ["Ittifoqi muslimin", "Milliy Markaz", "Sho'royi Islomiya", "Turk Adam markaziyat"], "t": "Ittifoqi muslimin"},
    {"s": "Lager yoki kazarmada kasallarni yoki ayblanuvchilarni yakkalash uchun ajratilgan maxsus joy?", "v": ["Zindon", "Izolyator", "Katorga", "Palata"], "t": "Izolyator"},
    {"s": "Rossiyada 1905-yilda tashkil topgan 'konstitutsion demokratlar' partiyasi a’zolari?", "v": ["Eserlar", "Kadetlar", "Dashnoqlar", "Bolsheviklar"], "t": "Kadetlar"},
    {"s": "Harbiy tilda otliq qo‘shinlar nima deb ataladi?", "v": ["Artilleriya", "Piyoda", "Kavaleriya", "Desant"], "t": "Kavaleriya"},
    {"s": "Bir necha partiyaning umumiy maqsad yo‘lida ittifoq bo'lib tuzgan hukumati?", "v": ["Muvaqqat hukumat", "Koalitsion hukumat", "Partokratik hukumat", "Milliy hukumat"], "t": "Koalitsion hukumat"},
    {"s": "Mayda dehqon xo‘jaliklaridan ommaviy ravishda kolxozlar (jamoa xo'jaligi) tashkil qilish?", "v": ["Industrlashtirish", "Natsionalizatsiya", "Kollektivlashtirish", "Kooperatsiya"], "t": "Kollektivlashtirish"},
    {"s": "Siyosiy mahbuslar yoki asirlarni bir joyga to'plash uchun tashkil etilgan maxsus lager?", "v": ["Konsentratsion lager", "Katorga", "Harbiy qism", "Izolyator"], "t": "Konsentratsion lager"},
    {"s": "Dastlab Italiyada yetim bolalar uchun boshpana bo‘lgan, hozirda oliy musiqa o'quv yurti?", "v": ["Gimnaziya", "Seminariya", "Konservatoriya", "Akademiya"], "t": "Konservatoriya"},
    {"s": "Kishilar yoki tashkilotlarning ishlab chiqarishda hamkorlik asosida ishlash shakli (lotincha 'sheriklik')?", "v": ["Artel", "Kooperatsiya", "Kolxoz", "Korporatsiya"], "t": "Kooperatsiya"},
    {"s": "Mavjud davlat tuzumini tanqid qilib, tubdan (radikal) o‘zgarishlar talab qiluvchi siyosiy oqim?", "v": ["Konservatorlar", "Liberallar", "Maksimalistlar", "Islohotchilar"], "t": "Maksimalistlar"},
    {"s": "'Kraymussovet' deb atalgan Turkiston o‘lka musulmonlari soveti qanday nomlangan?", "v": ["Sho'royi Islomiya", "Milliy Markaz", "Ittifoqi muslimin", "Yosh buxoroliklar"], "t": "Milliy Markaz"},
    {"s": "Minalarni irg‘itib otishga mo‘ljallangan o't ochish quroli?", "v": ["Pulemyot", "Minomyot", "Pushka", "Miltiq"], "t": "Minomyot"},
    {"s": "Dalada faqat bir xil ekinni (masalan, faqat paxtani) mutassil yetishtirish tizimi?", "v": ["Almashlab ekish", "Monokultura", "Melioratsiya", "Agrar islohot"], "t": "Monokultura"},
    {"s": "Biron-bir hududning o‘z ichki ishlarini mustaqil boshqarish huquqi?", "v": ["Federatsiya", "Suverenitet", "Muxtoriyat", "Protektorat"], "t": "Muxtoriyat"},
    {"s": "Xususiy mulk bo‘lgan yer, zavod va transportlarni davlat ixtiyoriga olish jarayoni?", "v": ["Privatizatsiya", "Natsionalizatsiya", "Industrlashtirish", "Konvertatsiya"], "t": "Natsionalizatsiya"},
    {"s": "Musulmon ayollarning keng yopinchiq ko‘rinishidagi yuzni berkitib turuvchi kiyimi?", "v": ["Paranji", "Chachvon", "Hijob", "Doppi"], "t": "Paranji"},
    {"s": "Davlat boshqaruvida birgina partiyaning mutloq hukmronligiga asoslangan tizim?", "v": ["Demokratik", "Teokratik", "Partokratik", "Monarxik"], "t": "Partokratik"},
    {"s": "Metal mahsulotlarini aylanuvchi valar orasidan siqib o'tkazib ishlab chiqarish bo'limi?", "v": ["Bolg'alash sexi", "Quyuv sexi", "Prokat sexi", "Payvandlash sexi"], "t": "Prokat sexi"},
    {"s": "Yashash uchun o‘z ishchi kuchini sotishga majbur bo‘lgan kambag'al yollanma ishchilar sinfi?", "v": ["Burjuaziya", "Proletar", "Dehqon", "Ziyoli"], "t": "Proletar"},
    {"s": "16,38 kg ga teng bo‘lgan og‘irlik o‘lchov birligi?", "v": ["Chorak", "Pud", "Funt", "Botmon"], "t": "Pud"},
    {"s": "Turkistonda Oktabr to'ntarishigacha mahalliy politsiya boshlig'i, keyinchalik istiqlolchilik harakati rahbarlari unvoni?", "v": ["Bek", "Qo'shbegi", "Qo’rboshi", "Lashkarboshi"], "t": "Qo’rboshi"},
    {"s": "Dehqonlarni g‘oyaviy jihatdan birlashtirib turgan ittifoq qanday nomlangan?", "v": ["Kolxoz", "Qo’shchi", "Artel", "Zemstvo"], "t": "Qo’shchi"},
    {"s": "Sovet rejimining badavlat va o'rtahol dehqonlarni 'mushtumzo'r' deb tugatish siyosati?", "v": ["Quloqlar (kulachestvo)", "Proletarizatsiya", "Kollektivlashtirish", "Industrlashtirish"], "t": "Quloqlar (kulachestvo)"},
    {"s": "Davlat ahamiyatiga ega masalalar bo‘yicha o‘tkaziladigan umumxalq so‘rovi?", "v": ["Saylov", "Sessiya", "Referendum", "Simpozium"], "t": "Referendum"},
    {"s": "Tibbiy xizmat xodimlari va uskunalari bilan jihozlangan, yaradorlarni tashishga mo'ljallangan poyezd?", "v": ["Yuk poyezdi", "Sanitar poyezd", "Eshelon", "Ekspress"], "t": "Sanitar poyezd"},
    {"s": "Hujjat yoki qarorning oliy organ tomonidan tasdiqlanishi natijasida qonuniy kuchga kirishi?", "v": ["Dekret", "Manifest", "Sanksiya", "Doktrina"], "t": "Sanksiya"},
    {"s": "Turkiston taraqqiyparvarlarining 1917-yil mart oyida tuzilgan ijtimoiy-siyosiy tashkiloti?", "v": ["Sho’royi Islomiya", "Sho'royi Ulamo", "Milliy Markaz", "Yosh xivaliklar"], "t": "Sho’royi Islomiya"},
    {"s": "Tashkilot yoki boshqaruvning bir bo‘lagi, qismi yoki tarmog'i?", "v": ["Firqa", "Idora", "Shu’ba", "Kengash"], "t": "Shu’ba"},
    {"s": "Prezidentning birinchi o‘rinbosari va yordamchisi hisoblangan lavozim?", "v": ["Spiker", "Bosh vazir", "Vitse-prezident", "Maslahatchi"], "t": "Vitse-prezident"},
    {"s": "Oddiy askarlarga beriladigan eng birinchi, boshlang‘ich harbiy unvon?", "v": ["Serjant", "Yefreytor", "Leytenant", "Kapitan"], "t": "Yefreytor"}
]