# data_7_sinf_1_qism.py

testlar_7jt = [
    {"s": "40 ming yil avval qaysi qit'aga dastlabki odamlar o‘ta boshlagan?", "v": ["Avstraliya", "Amerika", "Antarktida", "Yevropa"], "t": "Amerika"},
    {"s": "Mil. avv. V asrda Xitoyda qaysi donishmandlarning ta'limotlari qaror topdi?", "v": ["Budda va Ashoka", "Konfutsiy va Lao-szilar", "Suqrot va Aflotun", "Mani va Mazdak"], "t": "Konfutsiy va Lao-szilar"},
    {"s": "Mil. avv. IV asrda Xitoyda qanday ulkan inshootni qurish boshlangan?", "v": ["Buyuk Xitoy devori", "Ajanta ibodatxonasi", "Avliyo Sofiya ibodatxonasi", "Tenochtitlan shahri"], "t": "Buyuk Xitoy devori"},
    {"s": "Hindistondagi Ajanta ibodatxonasi qaysi davrlar oralig‘ida qurilgan?", "v": ["Mil. avv. V – milodiy III asrlar", "Mil. avv. II – milodiy VII asrlar", "Milodiy I – IX asrlar", "Mil. avv. IV – milodiy I asrlar"], "t": "Mil. avv. II – milodiy VII asrlar"},
    {"s": "Mil. avv. I asrda qaysi davlat o‘zaro nizolar va xitoyliklar bilan janglar tufayli parchalanib ketdi?", "v": ["Qadimgi Choson", "Silla", "Koguryo", "Pekche"], "t": "Qadimgi Choson"},
    {"s": "Mil. avv. I asrda parchalangan Qadimgi Choson o‘rnida qaysi uch qirollik vujudga keldi?", "v": ["Tan, Sun, Xan", "Pekche, Silla va Koguryo", "Yamato, Nara, Koryo", "Kushon, Gupta, Xarsha"], "t": "Pekche, Silla va Koguryo"},
    {"s": "Mil. avv. I asrdan boshlab qaysi hududdagi qabilalarning qayta birlashuvi natijasida qirolliklar tuzila boshladi?", "v": ["Janubiy Hindiston", "Markaziy Osiyo", "Shimoliy Koreya", "G‘arbiy Yevropa"], "t": "Shimoliy Koreya"},
    {"s": "I–II asrlarda Koreyadagi qaysi davlat qudratli davlatga aylandi?", "v": ["Pekche", "Koguryo", "Silla", "Koryo"], "t": "Koguryo"},
    {"s": "III asrda Koguryoda qaysi ta'limotga e'tiqod qilish kuzatiladi?", "v": ["Buddaviylik", "Konfutsiylik", "Islom", "Xristianlik"], "t": "Konfutsiylik"},
    {"s": "III asrda qaysi imperiya inqirozga uchragach, ko‘chmanchi turkiy qabilalarning hujumi kuchaydi?", "v": ["Xan imperiyasi", "Rim imperiyasi", "Gupta imperiyasi", "Suy sulolasi"], "t": "Xan imperiyasi"},
    {"s": "Koreya yarimorolining janubiy qismida Pekche davlati qachon vujudga keldi?", "v": ["I–II asrlarda", "III–IV asrlarda", "V–VI asrlarda", "VII asrda"], "t": "III–IV asrlarda"},
    {"s": "Xitoyliklar choy o‘simligini dorivor ekanligini qachon kashf qildilar?", "v": ["Mil. avv. I asrda", "I–II asrlarda", "III–IV asrlarda", "V–VI asrlarda"], "t": "III–IV asrlarda"},
    {"s": "IV asrdan boshlab qaysi buyuk imperiya o‘zining avvalgi qudratini yo‘qota boshlaydi?", "v": ["Xitoy imperiyasi", "Rim imperiyasi", "Arab xalifaligi", "Franklar davlati"], "t": "Rim imperiyasi"},
    {"s": "IV asrda Koreyadagi qaysi qirollik markazlashgan davlatga aylandi?", "v": ["Koguryo", "Silla", "Pekche", "Koryo"], "t": "Pekche"},
    {"s": "IV asrda qaysi mamlakatda qabilalar ittifoqi shakllanib, u bo‘lajak davlat asosi vazifasini o‘tadi?", "v": ["Koreyada", "Yaponiyada", "Hindistonda", "Fransiyada"], "t": "Yaponiyada"},
    {"s": "IV asrdan boshlab Yevropada qaysi din tarqala boshlagan?", "v": ["Islom", "Buddaviylik", "Xristianlik", "Yahudiylik"], "t": "Xristianlik"},
    {"s": "IV asrda xristianlikda qanday rasmiy tus olingan?", "v": ["Xochga sig‘inish", "Namoz o‘qish", "Butga sig‘inish", "Haj qilish"], "t": "Xochga sig‘inish"},
    {"s": "IV asrda Pekcheda qaysi ta'limotga e'tiqod qilish kuzatildi?", "v": ["Buddaviylik", "Konfutsiylik", "Shintoizm", "Daoizm"], "t": "Buddaviylik"},
    {"s": "Xristian dini qaysi asrdan boshlab german qabilalari orasida ham tarqala boshladi?", "v": ["III asrdan", "IV asrdan", "V asrdan", "VI asrdan"], "t": "IV asrdan"},
    {"s": "IV asr boshlarida xitoyliklarni o‘z hududidan batamom surib chiqargan davlat:", "v": ["Koguryo", "Silla", "Pekche", "Yamato"], "t": "Koguryo"},
    {"s": "Koreyada buddizm tarqala boshlagan davr:", "v": ["III asr boshlari", "IV asr boshlari", "IV asr oxirlari", "V asr o‘rtalari"], "t": "IV asr oxirlari"},
    {"s": "IV–V asrlarda qaysi yirik german qabilalari ittifoqlari shakllandi?", "v": ["Alemann, got, franklar", "Angl, saks, brittlar", "Normann, viking, varanglar", "Hun, turk, mo‘g‘ullar"], "t": "Alemann, got, franklar"},
    {"s": "IV–V asrlarda Guptalar imperiyasi qaysi dengizgacha bo‘lgan hududlarni birlashtirgan?", "v": ["O‘rta Yer dengizi", "Arabiston dengizi", "Kaspiy dengizi", "Qizil dengiz"], "t": "Arabiston dengizi"},
    {"s": "Shimoliy dashtlarning ko‘chmanchi qabilalari Xitoy hududiga qarab silji boshlagan davr:", "v": ["III–IV asrlar", "IV–V asrlar", "V–VI asrlar", "VI–VII asrlar"], "t": "IV–V asrlar"},
    {"s": "IV–VI asrlarda Rim imperiyasining shimoliy hududlarida qanday tarixiy jarayon boshlandi?", "v": ["German qabilalarining ko‘chish jarayoni", "Salib yurishlari", "Islom fathlari", "Shaharlarning qulashi"], "t": "German qabilalarining ko‘chish jarayoni"},
    {"s": "Germanlarda mulkiy tabaqalanish qachon kuchaygan?", "v": ["III–IV asrlarda", "IV–VI asrlarda", "VII–VIII asrlarda", "IX asrda"], "t": "IV–VI asrlarda"},
    {"s": "V asrda Koguryo poytaxti qaysi shaharga ko‘chirilgan?", "v": ["Seul", "Pxenyan", "Kionshu", "Tokio"], "t": "Pxenyan"},
    {"s": "Yevropada yer egaligi munosabatlariga o‘tish jarayonidan cherkov ham chetda qolmagan davr:", "v": ["IV asr", "V asr", "VI asr", "VII asr"], "t": "V asr"},
    {"s": "V asr o‘rtalaridan Franklar Rim imperiyasining qaysi daryolar havzasidagi hududlariga tahdid sola boshladi?", "v": ["Reyn va Dunay", "Sena va Luara", "Tibr va Po", "Nil va Furot"], "t": "Reyn va Dunay"},
    {"s": "Franklar qirolli Xlodvig xristianlikni qachon qabul qilgan?", "v": ["IV asr oxirida", "V asrning oxirida", "VI asr boshida", "VII asr o‘rtasida"], "t": "V asrning oxirida"},
    {"s": "V–VI asrlarda brittlarni bo‘ysundirib, ilk feodal qirolliklarini tuzgan qabilalar:", "v": ["Got va vestgotlar", "Anglosaks qabilalari", "Frank va alemannlar", "Sitsiliyaliklar"], "t": "Anglosaks qabilalari"},
    {"s": "V asr oxiridan XV asr oxiriga qadar davom etgan davr:", "v": ["Qadimgi dunyo", "O‘rta asrlar tarixi", "Yangi tarix", "Eng yangi tarix"], "t": "O‘rta asrlar tarixi"},
    {"s": "VI asrda Sillada qaysi ta'limotga e'tiqod qilish kuzatiladi?", "v": ["Buddaviylik", "Konfutsiylik", "Islom", "Shintoizm"], "t": "Buddaviylik"},
    {"s": "Mashhur tarixchi Kesariyalik Prokopiy qaysi asrda yashab ijod qilgan?", "v": ["IV asr", "V asr", "VI asr", "VII asr"], "t": "VI asr"},
    {"s": "VI asrda slavyanlarning uchinchi qismi qaysi daryo sohiliga yetib keldi?", "v": ["Dnepr", "Volga", "Dunay", "Reyn"], "t": "Dunay"},
    {"s": "VI asrda Vizantiya imperiyasida qaysi shaharlar gullab-yashnagan?", "v": ["Konstantinopol, Aleksandriya, Antioxiya", "Rim, Parij, London", "Bag‘dod, Qohira, Damashq", "Pekin, Pxenyan, Nara"], "t": "Konstantinopol, Aleksandriya, Antioxiya"},
    {"s": "VI asrda Guptalar imperiyasi qaysi qabilalar hujumi natijasida parchalandi?", "v": ["Hunlar", "Gotlar", "Eftaliylar", "Arablar"], "t": "Eftaliylar"},
    {"s": "VI asrning boshlarida brittlarni kim birlashtiradi?", "v": ["Xlodvig", "Amvrosiy Avrelian", "Artur", "Buyuk Karl"], "t": "Amvrosiy Avrelian"},
    {"s": "VI asr o‘rtalariga kelib Ostgot qirolligining qulashiga nima sabab bo‘ldi?", "v": ["Vizantiya istilolari", "Arablar bosqini", "Dehqonlar qo‘zg‘oloni", "Vabo epidemiyasi"], "t": "Vizantiya istilolari"},
    {"s": "Qabilalar orasida suv va yaylovlar uchun kurash qachon kuchaydi?", "v": ["IV–V asrlar", "V–VI asrlar", "VI–VII asrlar", "VIII–IX asrlar"], "t": "VI–VII asrlar"},
    {"s": "VII asrda Vizantiyada qanday dahshatli qurol ixtiro qilingan?", "v": ["Porox", "Yunon olovi", "Katapulta", "Arbalet"], "t": "Yunon olovi"},
    {"s": "Arabiston shaharlari va ko‘chmanchi qabilalar yagona davlatga qachon birlashdi?", "v": ["VI asrda", "VII asrda", "VIII asrda", "IX asrda"], "t": "VII asrda"},
    {"s": "Yaponiya qaysi asrdan boshlab Nippon deb atala boshlandi?", "v": ["V asrdan", "VI asrdan", "VII asrdan", "VIII asrdan"], "t": "VII asrdan"},
    {"s": "VII asrda Hindistonda 70 ga yaqin knyazliklar bo‘lganligini yozgan tarixchi:", "v": ["Sima Syan", "Syuan Szyan", "Lao-szi", "Konfutsiy"], "t": "Syuan Szyan"},
    {"s": "Hindiston shimolida Xarsha imperiyasi qachon tashkil topdi?", "v": ["VII asr boshlarida", "VII asr oxirida", "VIII asr boshida", "VI asr oxirida"], "t": "VII asr boshlarida"},
    {"s": "VII asrning boshlarida Arabiston yarimorolida qaysi din shakllandi?", "v": ["Xristianlik", "Buddaviylik", "Islom", "Zardushtiylik"], "t": "Islom"},
    {"s": "VII asrning ikkinchi yarmida qaysi diniy-siyosiy mazhab parchalanib ketdi?", "v": ["Sunniylar", "Shiarlar", "Xavorijlar", "Mo'taziliylar"], "t": "Xavorijlar"},
    {"s": "Arab xalifaligining tashkil topishi qaysi asrlardagi fathlar natijasidir?", "v": ["V–VI asrlar", "VI–VII asrlar", "VII–VIII asrlar", "VIII–IX asrlar"], "t": "VII–VIII asrlar"},
    {"s": "VII–X asrlarda Islom dini qaysi hududga kirib keldi?", "v": ["Yevropaga", "Koreya zaminiga", "Amerikaga", "Yaponiyaga"], "t": "Koreya zaminiga"},
    {"s": "VII–X asrlarda qaysi xalqlar o‘z davlatlarini tashkil qildilar?", "v": ["Germanlar", "Slavyanlar", "Turklar", "Mayyalar"], "t": "Slavyanlar"},
    {"s": "Tunisdagi 'Zaytuna' ilm dargohi qachon tashkil etilgan?", "v": ["VII asrda", "VIII asrda", "IX asrda", "X asrda"], "t": "VIII asrda"},
    {"s": "VIII asrda qog‘oz yasashning o‘zlashtirilishi nimaga sabab bo‘ldi?", "v": ["Kitoblarning arzon va hammabop bo‘lishiga", "Universitetlar yopilishiga", "Savdo to‘xtashiga", "Urushlar kamayishiga"], "t": "Kitoblarning arzon va hammabop bo‘lishiga"},
    {"s": "Yaponiyada zodagonlarning bolalari uchun maktablar qachon ochila boshladi?", "v": ["VII asrdan", "VIII asrdan", "IX asrdan", "X asrdan"], "t": "VIII asrdan"},
    {"s": "VIII asr o‘rtalarida Arab xalifaligida hokimiyat kimlarning qo‘liga o‘tdi?", "v": ["Umaviylar", "Abbosiylar", "Saljuqiylar", "Fotimiylar"], "t": "Abbosiylar"},
    {"s": "VIII asr o‘rtalarida Koreyadagi qaysi qirollikning 'Oltin davri' boshlandi?", "v": ["Koguryo", "Pekche", "Silla", "Koryo"], "t": "Silla"},
    {"s": "VIII asr oxiri – XI asr o‘rtalarida dengiz yo‘li bilan bosqinchilik qilgan xalq:", "v": ["Arablar", "Vikinglar", "Franklar", "Slavyanlar"], "t": "Vikinglar"},
    {"s": "Yangi darslik (2022) bo‘yicha O‘rta asrlar davri qaysi asrlarni o‘z ichiga oladi?", "v": ["V–XV asrlar", "VII–XII asrlar", "VIII–XIII asrlar", "IX–XIV asrlar"], "t": "V–XV asrlar"},
    {"s": "Saljuqiylar Buxoro va Samarqandga qachon kelib joylashgan edi?", "v": ["VIII asrda", "IX asrda", "X asrda", "XI asrda"], "t": "X asrda"},
    {"s": "IX asrdan boshlab qaysi hududlar xalifalikdan mustaqil bo‘la boshladi?", "v": ["Misr, Eron, Movarounnahr", "Ispaniya va Marokash", "Hindiston va Xitoy", "Gretsiya va Bolgariya"], "t": "Misr, Eron, Movarounnahr"},
    {"s": "Konstantinopoldagi Magnavroliy maktabi qachon ochilgan?", "v": ["VIII asrda", "IX asrda", "X asrda", "XI asrda"], "t": "IX asrda"},
    {"s": "IX asrda Bag‘dodda qaysi ilm dargohi ochildi?", "v": ["Bayt ul-hikma", "Al-Azhar", "Sorbonna", "Oksford"], "t": "Bayt ul-hikma"},
    {"s": "Xitoyda ilk bo‘rtma iyeroglifli kitob qachon bosilgan?", "v": ["VIII asrda", "IX asrda", "X asrda", "XI asrda"], "t": "IX asrda"},
    {"s": "IX asrga oid arab hujjatida 'oltinga boy mamlakat' deb qaysi davlat tilga olingan?", "v": ["Yaponiya", "Silla", "Hindiston", "Franklar"], "t": "Silla"},
    {"s": "Anglosaks davlatlari birlashtirilib, mamlakat 'Angliya' deb atala boshlagan davr:", "v": ["IX asr boshlari", "IX asr oxiri", "X asr boshlari", "VIII asr oxiri"], "t": "IX asr boshlari"},
    {"s": "IX asr boshlarida hozirgi Chexiya o‘rnida qaysi davlat paydo bo‘ldi?", "v": ["Muqaddas Rim", "Buyuk Moraviya", "Polsha qirolligi", "Vengriya"], "t": "Buyuk Moraviya"},
    {"s": "Yapon alifbosi qachon kashf qilingan?", "v": ["IX asr boshida", "IX asrning o‘rtalarida", "X asr boshida", "VIII asr oxirida"], "t": "IX asrning o‘rtalarida"},
    {"s": "Sharqiy slavyanlar Ryurikni knyazlikka qachon chaqirishgan?", "v": ["IX asr boshida", "IX asrning ikkinchi yarmida", "X asr boshida", "VIII asr o‘rtasida"], "t": "IX asrning ikkinchi yarmida"},
    {"s": "Fransiya mustaqil gersoglik va grafliklarga qachon bo‘linib ketdi?", "v": ["VIII–IX asrlar", "IX–X asrlar", "X–XI asrlar", "XI–XII asrlar"], "t": "IX–X asrlar"},
    {"s": "Venetsiya, Genuya, Marsel kabi shaharlar qachon yuksala boshladi?", "v": ["VIII–IX asrlar", "IX–X asrlar", "X–XI asrlar", "XI–XII asrlar"], "t": "X–XI asrlar"},
    {"s": "Xitoyda o‘rta asr shaharlari vujudga kelgan va rivojlangan davr:", "v": ["VII–X asrlar", "VIII–XI asrlar", "IX–XIII asrlar", "X–XIV asrlar"], "t": "VII–X asrlar"},
    {"s": "Mamlakat Fransiya deb atala boshlangan davr:", "v": ["IX asr", "X asr", "XI asr", "XII asr"], "t": "X asr"},
    {"s": "Benefitsiy (shartli yer) qachon feodga (merosiy yerga) aylandi?", "v": ["IX asrda", "X asrda", "XI asrda", "XII asrda"], "t": "XI asrda"},
    {"s": "Qurdoba amirligi xalifalikdan qachon ajralib chiqdi?", "v": ["IX asrdan", "X asrdan", "XI asrdan", "XII asrdan"], "t": "X asrdan"},
    {"s": "Mashhur tarixchi Lev Diakon qaysi asrda yashagan?", "v": ["IX asr", "X asr", "XI asr", "XII asr"], "t": "X asr"},
    {"s": "Qohiradagi 'Al-Azhar' ilm dargohi qachon tashkil etilgan?", "v": ["IX asrda", "X asrda", "XI asrda", "XII asrda"], "t": "X asrda"},
    {"s": "Chexiya davlatiga asos solingan va Polsha davlati vujudga kelgan davr:", "v": ["X asr", "IX asr", "XI asr", "VIII asr"], "t": "X asr"},
    {"s": "Kiyev Rusi xristianlikni Vizantiyadan qachon qabul qildi?", "v": ["IX asr o‘rtasida", "X asr oxirlarida", "XI asr boshida", "VIII asr oxirida"], "t": "X asr oxirlarida"},
    {"s": "Rus knyazi Vladimir o‘z xalqi uchun xristianlikni qachon tanladi?", "v": ["IX asr oxiri", "X asr oxiri", "XI asr boshi", "X asr o‘rtasi"], "t": "X asr oxiri"},
    {"s": "Musulmon adabiyoti qaysi asrda fors tiliga tarjima qilina boshladi?", "v": ["IX asrda", "X asrda", "XI asrda", "XII asrda"], "t": "X asrda"},
    {"s": "X asrda Qurdoba xalifasi kutubxonasida qancha qo‘lyozma saqlangan?", "v": ["100 ming", "200 ming", "400 ming", "1 million"], "t": "400 ming"},
    {"s": "Fransiyada hunarmandchilik va savdo qachon yuksaldi?", "v": ["IX–X asrlar", "X–XI asrlar", "XI–XII asrlar", "XII–XIII asrlar"], "t": "XI–XII asrlar"},
    {"s": "Shimoliy Yevropada yangi shaharlar qachon paydo bo‘ldi?", "v": ["IX–X asrlar", "X–XI asrlar", "XI–XII asrlar", "XII–XIII asrlar"], "t": "XI–XII asrlar"},
    {"s": "Xitoyda yer tanqisligi tufayli dehqonlar qo‘zg‘oloni qachon bo‘ldi?", "v": ["IX–XI asrlar", "X–XII asrlar", "XI–XIII asrlar", "XII–XIV asrlar"], "t": "XI–XIII asrlar"},
    {"s": "Xitoyda kitob bosish dastgohi qachon yaratildi?", "v": ["X asrda", "XI asrda", "XII asrda", "XIII asrda"], "t": "XI asrda"},
    {"s": "XI asrda qaysi davlat Muqaddas Rim imperiyasi tarkibiga kiritildi?", "v": ["Polsha", "Chexiya", "Vengriya", "Fransiya"], "t": "Chexiya"},
    {"s": "Xitoyda shaharsozlik yuksak darajaga ko‘tarilgan davr:", "v": ["X asr", "XI asr", "XII asr", "XIII asr"], "t": "XI asrda"},
    {"s": "Papalar imperatorlarga qarshi kurashni qachon boshladi?", "v": ["X asrdan", "XI asrdan", "XII asrdan", "XIII asrdan"], "t": "XI asrdan"},
    {"s": "Normannlar Angliyaga qachon qayta hujum boshladilar?", "v": ["XI asr boshlarida", "X asr oxirida", "XII asr boshida", "IX asr o‘rtasida"], "t": "XI asr boshlarida"},
    {"s": "Mahmud G‘aznaviy Hindiston shimoliga yurishlarni qachon amalga oshirdi?", "v": ["X asr oxirida", "XI asr boshlarida", "XI asr oxirida", "XII asr boshida"], "t": "XI asr boshlarida"},
    {"s": "Vizantiya Bolgariyani qachon istilo qildi?", "v": ["XI asr boshlarida", "X asr oxirida", "XII asr boshida", "XI asr o‘rtasida"], "t": "XI asr boshlarida"},
    {"s": "Huquqshunoslik va falsafa fakultetlari bo‘lgan universitet qachon ochilgan?", "v": ["XI asr boshida", "XI asrning o‘rtalarida", "XII asr boshida", "X asr oxirida"], "t": "XI asrning o‘rtalarida"},
    {"s": "Vladimir Monomax va qipchoqlar o‘rtasidagi urushlar qachon bo‘ldi?", "v": ["XI asr o‘rtasida", "XI asrning so‘ngida", "XII asr boshida", "X asr oxirida"], "t": "XII asr boshida"},
    {"s": "XI asr oxirida Saljuqiylar davlati qaysi dengizlargacha yetgan?", "v": ["O‘rta Yer va Marmar", "Arabiston va Hind", "Kaspiy va Qora", "Boltiq va Shimoliy"], "t": "O‘rta Yer va Marmar"},
    {"s": "XI asr oxirida o‘g‘uzlar Anatoliyada qaysi sultonlikni tuzishdi?", "v": ["G‘aznaviylar", "Ko‘niya sultonligi", "Usmonli sultonligi", "Xorazmshohlar"], "t": "Ko‘niya sultonligi"},
    {"s": "Turk millati shakllana boshlagan davr:", "v": ["X asr oxiri", "XI asr oxiri", "XII asr oxiri", "XIII asr oxiri"], "t": "XI asr oxiri"},
    {"s": "Sharqdagi qulay vaziyat salib yurishlari uchun qachon sharoit yaratdi?", "v": ["XI asr o‘rtasida", "XI asr oxirida", "XII asr boshida", "X asr oxirida"], "t": "XI asr oxirida"},
    {"s": "Musulmon hukmdorlarning o‘zaro urushlari qachondan ziyoratchilarga xavf sola boshladi?", "v": ["XI asr boshidan", "XI asr oxiridan", "XII asr boshidan", "X asr oxiridan"], "t": "XI asr oxiridan"},
    {"s": "Yevropada birinchi universitetlar qachon paydo bo‘ldi?", "v": ["X–XI asrlar", "XI–XII asrlar", "XII–XIII asrlar", "XIII–XIV asrlar"], "t": "XI–XII asrlar"},
    {"s": "Mo‘g‘ullarda mulkiy tabaqalanish qaysi asrdan kuchaya boshladi?", "v": ["XI asr boshidan", "XII asr boshidan", "XII asrning ikkinchi yarmi", "XIII asr boshidan"], "t": "XII asrning ikkinchi yarmi"},
    {"s": "Yaponiyada syogun unvoni qaysi asrdan joriy etildi?", "v": ["XI asrdan", "XII asrdan", "XIII asrdan", "XIV asrdan"], "t": "XII asrdan"},
    {"s": "Sulton Malikshoh hukmronlik qilgan yillarni ko‘rsating:", "v": ["1063–1072-yillar", "1072–1092-yillar", "1038–1092-yillar", "1092–1118-yillar"], "t": "1072–1092-yillar"},
    {"s": "Saljuqiylar vizantiyaliklar ustidan Mansikert jangida qachon g‘alaba qozondi?", "v": ["1055-yili", "1066-yili", "1071-yili", "1074-yili"], "t": "1071-yili"},
    {"s": "Saljuqiylar Buxoro va Samarqandni qachon butunlay egalladi?", "v": ["1055-yili", "1071-yili", "1074-yili", "1092-yili"], "t": "1074-yili"},
    {"s": "Chex knyaziga yordami uchun qirollik toji qachon in'om etildi?", "v": ["1074-yili", "1080-yili", "1085-yili", "1095-yili"], "t": "1085-yili"},
    {"s": "Papa Urban II Klermon shahrida salib yurishiga qachon da'vat qildi?", "v": ["1085-yili", "1092-yili", "1095-yili", "1096-yili"], "t": "1095-yili"},
    {"s": "Imperator Aleksey I ritsarlarga vassallik qasamyodini qachon qabul qildirdi?", "v": ["1095-yilda", "1096-yilning kuzida", "1097-yilda", "1099-yilda"], "t": "1096-yilning kuzida"},
    {"s": "Salib yurishlari umumiy hisobda qaysi yillar oralig‘ida bo‘lib o‘tdi?", "v": ["1095–1258-yillar", "1096–1270-yillar", "1100–1300-yillar", "1099–1291-yillar"], "t": "1096–1270-yillar"},
    {"s": "Antioxiya uchun Bogemond I va Kerboga qo‘shinlari o‘rtasidagi jang qachon bo‘ldi?", "v": ["1096-yil 15-avgust", "1097-yil 20-oktyabr", "1099-yil 15-iyul", "1095-yil 27-noyabr"], "t": "1097-yil 20-oktyabr"},
    {"s": "Suriya va Falastinda salibchilar davlatlari qachon tuzildi?", "v": ["1099-yilgacha davom etgan yurishlar natijasida", "1147-yili", "1187-yili", "1204-yili"], "t": "1099-yilgacha davom etgan yurishlar natijasida"},
    {"s": "Vladimir Monomax hukmronlik qilgan yillarni aniqlang:", "v": ["1093–1113-yillar", "1113–1125-yillar", "1125–1132-yillar", "1078–1093-yillar"], "t": "1113–1125-yillar"},
    {"s": "Germaniyada Shtaufenlar sulolasi qachon hokimiyatga keldi?", "v": ["1125-yili", "1137-yili", "1152-yili", "1190-yili"], "t": "1137-yili"},
    {"s": "Musulmon sarkardasi Nuriddin Zangiy qaysi yili taxtga o‘tirdi?", "v": ["1137-yili", "1144-yili", "1146-yili", "1155-yili"], "t": "1146-yili"},
    {"s": "Ikkinchi salib yurishi qaysi yillarda uyushtirildi?", "v": ["1096–1099-yillar", "1147–1149-yillar", "1189–1192-yillar", "1202–1204-yillar"], "t": "1147–1149-yillar"},
    {"s": "Fridrix I Barbarossa hukmronlik qilgan yillarni ko‘rsating:", "v": ["1137–1152-yillar", "1152–1190-yillar", "1155–1190-yillar", "1190–1197-yillar"], "t": "1152–1190-yillar"},
    {"s": "Angliyada Genrix II (Plantagenet) hukmronlik qilgan yillar:", "v": ["1135–1154-yillar", "1154–1189-yillar", "1189–1199-yillar", "1152–1190-yillar"], "t": "1154–1189-yillar"},
    {"s": "Fridrix I Rimda imperator sifatida qachon toj kiygan?", "v": ["1152-yili", "1155-yili", "1158-yili", "1176-yili"], "t": "1155-yili"},
    {"s": "Mo‘g‘ullar xoni Temuchin hayot yillarini aniqlang:", "v": ["1162–1227-yillar", "1155–1227-yillar", "1167–1227-yillar", "1206–1227-yillar"], "t": "1155–1227-yillar"},
    {"s": "Suriyada musulmonlarning yagona siyosiy hokimiyati qachon vujudga keldi?", "v": ["1146-yili", "1152-yili", "1155-yili", "1169-yili"], "t": "1155-yili (Damashq egallanishi bilan)"},
    {"s": "Fridrix I Italiyaning shimoliy shaharlarini qachon bo‘ysundirdi?", "v": ["1155-yili", "1158-yili", "1162-yili", "1176-yili"], "t": "1158-yili"},
    {"s": "Salohiddin Ayyubiy boshchiligida Misr qachon egallandi?", "v": ["1155-yili", "1169-yili", "1174-yili", "1187-yili"], "t": "1169-yili"},
    {"s": "Imperator qo‘shini italiyaliklardan Lenyano jangida qachon mag‘lub bo‘ldi?", "v": ["1158-yili", "1162-yili", "1176-yili", "1183-yili"], "t": "1176-yili"},
    {"s": "Yaponiyadagi Xeyyan shahri qachon yong‘in natijasida vayron bo‘ldi?", "v": ["1155-yili", "1177-yili", "1185-yili", "1192-yili"], "t": "1177-yili"},
    {"s": "Salohiddin Ayyubiy Quddusni qachon qaytarib oldi?", "v": ["1169-yili", "1187-yili", "1189-yili", "1192-yili"], "t": "1187-yili"},
    {"s": "Uchinchi salib yurishi davrini aniqlang:", "v": ["1147–1149-yillar", "1189–1192-yillar", "1202–1204-yillar", "1217–1221-yillar"], "t": "1189–1192-yillar"},
    {"s": "Papa Innokentiy III hukmronlik (papalik) qilgan yillar:", "v": ["1198–1216-yillar", "1187–1198-yillar", "1216–1227-yillar", "1227–1241-yillar"], "t": "1198–1216-yillar"},
    {"s": "To‘rtinchi salib yurishi qaysi yillarda bo‘lib o‘tdi?", "v": ["1189–1192-yillar", "1202–1204-yillar", "1212-yillar", "1217–1221-yillar"], "t": "1202–1204-yillar"},
    {"s": "Temuchin qachon Ulug‘ xon (Chingizxon) deb e'lon qilindi?", "v": ["1155-yili", "1200-yili", "1206-yili", "1211-yili"], "t": "1206-yili"},
    {"s": "Chingizxon Shimoliy Xitoyga qarshi qachon urush boshladi?", "v": ["1206-yili", "1211-yili", "1215-yili", "1218-yili"], "t": "1211-yili"},
    {"s": "Stefan ismli cho‘pon bola boshchiligidagi 'Bolalar salib yurishi' qachon bo‘ldi?", "v": ["1204-yili", "1206-yili", "1212-yili", "1215-yili"], "t": "1212-yili"},
    {"s": "Yettisuv va Sharqiy Turkistonga mo‘g‘ul bosqinlari qachon boshlangan?", "v": ["1211-yili", "1215-yili", "1218-yili", "1219-yili"], "t": "1218-yili"},
    {"s": "Mo‘g‘ullarning Xorazmshohlar davlatiga bosqini qaysi yillarda bo‘ldi?", "v": ["1211–1215-yillar", "1218–1220-yillar", "1219–1221-yillar", "1221–1224-yillar"], "t": "1219–1221-yillar"},
    {"s": "Chingizxon zabt etilgan yerlarni uluslarga qachon taqsimlab berdi?", "v": ["1221-yili", "1224-yili", "1227-yili", "1231-yili"], "t": "1224-yili"},
    {"s": "Papa Grigoriy IX ning papalik davri:", "v": ["1198–1216-yillar", "1227–1241-yillar", "1241–1254-yillar", "1216–1227-yillar"], "t": "1227–1241-yillar"},
    {"s": "Mo‘g‘ullar Koryo (Koreya) qirolligini qachon bosib oldi?", "v": ["1218-yili", "1224-yili", "1231-yili", "1279-yili"], "t": "1231-yili"},
    {"s": "Botuxonning Sharqiy Yevropadagi istilochilik urushlari davri:", "v": ["1224–1227-yillar", "1237–1242-yillar", "1243–1250-yillar", "1256–1260-yillar"], "t": "1237–1242-yillar"},
    {"s": "Mo‘g‘ullarning bostirib kelishi Ko‘niya sultonligini qachon zaiflashtirdi?", "v": ["1231-yili", "1237-yili", "1243-yili", "1256-yili"], "t": "1243-yili"},
    {"s": "Xuloku Eronni qachon bosib oldi?", "v": ["1243-yili", "1256-yili", "1258-yili", "1260-yili"], "t": "1256-yili"},
    {"s": "Arab xalifaligi qachon butunlay barham topdi?", "v": ["1224-yili", "1256-yili", "1258-yili", "1260-yili"], "t": "1258-yili (Xuloku Bag‘dodni egallashi bilan)"},
    {"s": "Mo‘g‘ullarning Yaqin Sharq va Afrikaga yurishini kim va qachon to‘xtatib qoldi?", "v": ["1260-yili, Sulton Sayfiddin Qutuz", "1258-yili, Abbosiy xalifalar", "1270-yili, Lyudovik IX", "1243-yili, Saljuqiy sultonlar"], "t": "1260-yili, Sulton Sayfiddin Qutuz"},
    {"s": "Sakkizinchi (so‘nggi) salib yurishi qachon bo‘lib o‘tdi?", "v": ["1248–1254-yillar", "1269–1270-yillar", "1270–1291-yillar", "1204–1212-yillar"], "t": "1270–1291-yillar"},
    {"s": "Xitoy Xubilayxon tomonidan butunlay qachon bosib olindi?", "v": ["1258-yili", "1260-yili", "1279-yili", "1308-yili"], "t": "1279-yili"},
    {"s": "Saljuqiylar davlati qachon bir nechta beyliklarga bo‘linib ketdi?", "v": ["1243-yili", "1258-yili", "1308-yili", "1330-yili"], "t": "1308-yili"},
    {"s": "Amerika qit'asida mayyalarda shahar-davlatlar qachon vujudga keldi?", "v": ["Milodiy I ming yillikda", "Mil. avv. I ming yillikda", "Milodiy II ming yillikda", "Milodiy 1200-yili"], "t": "Milodiy I ming yillikda"},
    {"s": "Xitoyda buddaviylik yuqori tabaqa vakillari orasida qachon tarqala boshladi?", "v": ["Milodiy I asrda", "Milodiy I ming yillik o‘rtalaridan", "III asrda", "VII asrda"], "t": "III asrda"},
    {"s": "V asr o‘rtalarida Franklar Rimning qaysi daryolari havzasidagi hududlariga hujumni kuchaytirgan?", "v": ["Reyn va Dunay", "Sena va Luara", "Tibr va Po", "Volga va Dnepr"], "t": "Reyn va Dunay"},
    {"s": "VII asrning ikkinchi yarmida qaysi diniy oqim parchalanib, keyinchalik yo‘qolib ketgan?", "v": ["Shiarlar", "Abbosiylar", "Xavorijlar", "Mo‘taziliylar"], "t": "Xavorijlar"},
    {"s": "IX asrda Xitoyda kitob chop etishning qanday usuli kashf etilgan?", "v": ["Metall harfli bosma", "Ilk bo‘rtma iyeroglifli kitob", "Qo‘lyozma nusxa ko‘chirish", "Elektron nusxa"], "t": "Ilk bo‘rtma iyeroglifli kitob"},
    {"s": "X asrda Benefitsiy qanday mulk turiga aylandi?", "v": ["Vaqtinchalik yer", "Cherkov mulki", "Merosiy yer-mulk (Feod)", "Davlat yerlari"], "t": "Merosiy yer-mulk (Feod)"},
    {"s": "XI asr oxirida Kichik Osiyoda qaysi xalqlar qo‘shilishidan turk millati shakllana boshladi?", "v": ["O‘g‘uz turklari, yunonlar, forslar...", "Arablar, forslar va turklar", "Slavyanlar va germanlar", "Mo‘g‘ullar va xitoyliklar"], "t": "O‘g‘uz turklari, yunonlar, forslar, arman va gruzinlar"},
    {"s": "XII asr oxirida qaysi papa yangi salib yurishlarini tashkil etishga kirishdi?", "v": ["Urban II", "Lev III", "Innokentiy III", "Grigoriy IX"], "t": "Innokentiy III"},
    {"s": "XIII asr oxirida salib yurishlarining to‘xtatilishiga asosiy sabab nima edi?", "v": ["Musulmonlarning g‘alabasi", "G‘arbiy Yevropa mamlakatlarida boshlangan o‘zgarishlar", "Rim papasining vafoti", "Mo‘g‘ullar bosqini"], "t": "G‘arbiy Yevropa mamlakatlarida boshlangan o‘zgarishlar"},
    {"s": "XV asr o‘rtalarida Yevropada fan va madaniyat rivojiga ulkan hissa qo‘shgan ixtiro:", "v": ["Porox", "Kitob bosish dastgohi", "Kompas", "Teleskop"], "t": "Kitob bosish dastgohi"},
    {"s": "418-yilda vestgotlar ilk varvar qirolligini qaysi hududda tuzdilar?", "v": ["Britaniyada", "Janubi-g‘arbiy Galliyada", "Shimoliy Afrikada", "Italiyada"], "t": "Janubi-g‘arbiy Galliyada"},
    {"s": "527–548-yillarda yepiskop Ekkleziy tomonidan Ravennada nima qurilgan?", "v": ["Avliyo Sofiya ibodatxonasi", "Bazilika (Shohona bino)", "Panteon", "Kolizey"], "t": "Bazilika (Shohona bino)"},
    {"s": "637-yil aprel oyida Islom olamida qanday muhim islohot o‘tkazildi?", "v": ["Qur'on kitob holiga keltirildi", "Hijriy yil taqvimi joriy etildi", "Poytaxt Damashqqa ko‘chirildi", "Fathlar to‘xtatildi"], "t": "Hijriy yil taqvimi joriy etildi"},
    {"s": "681-yili Bulg‘or podsholigiga asos solgan shaxs:", "v": ["Simeon", "Asparux", "Oleg", "Ryurik"], "t": "Asparux"},
    {"s": "751–987-yillar oralig‘ida Franklar davlatini boshqargan sulola:", "v": ["Merovinglar", "Karolinglar", "Kapetinglar", "Shtaufenlar"], "t": "Karolinglar"},
    {"s": "842-yilda normannlar tomonidan vayron qilingan yirik shahar:", "v": ["Parij", "London", "Rim", "Konstantinopol"], "t": "London"},
    {"s": "882-yili Oleg Kiyevni egallagach, qaysi davlat tashkil topdi?", "v": ["Buyuk Moraviya", "Kiyev Rusi", "Polsha qirolligi", "Vizantiya"], "t": "Kiyev Rusi"},
    {"s": "919-yili Saksoniya gersogi Genrix qaysi davlat hukmdori etib saylandi?", "v": ["G‘arbiy Frank", "Sharqiy Frank", "Angliya", "Italiyada"], "t": "Sharqiy Frank"},
    {"s": "962-yildan 1806-yilgacha mavjud bo‘lgan imperiya:", "v": ["Rim imperiyasi", "Muqaddas Rim imperiyasi", "Franklar imperiyasi", "Vizantiya imperiyasi"], "t": "Muqaddas Rim imperiyasi"},
    {"s": "1013-yili Angliyani zabt etgan Daniya qiroli:", "v": ["Buyuk Alfred", "Kanut", "Vilgelm I", "Ekbert"], "t": "Kanut"},
    {"s": "1055-yili Saljuqiylar Bag‘dodni egallagach, xalifa qaysi vazifalardan mahrum bo‘ldi?", "v": ["Diniy vazifalardan", "Dunyoviy vazifalardan", "Sud ishlaridan", "Hammasidan"], "t": "Dunyoviy vazifalardan"},
    {"s": "1071-yilda Mansikert jangi kimlar o‘rtasida bo‘lib o‘tdi?", "v": ["Franklar va Arablar", "Saljuqiylar va Vizantiyaliklar", "Mo‘g‘ullar va Ruslar", "Inglizlar va Fransuzlar"], "t": "Saljuqiylar va Vizantiyaliklar"},
    {"s": "1097-yil 20-oktyabrda salibchilar qaysi shahar uchun jang qildilar?", "v": ["Quddus", "Antioxiya", "Edessa", "Tripoli"], "t": "Antioxiya"},
    {"s": "1113–1125-yillarda hukmronlik qilgan Rus knyazi:", "v": ["Oleg", "Vladimir I", "Vladimir Monomax", "Yaroslav Mudriy"], "t": "Vladimir Monomax"},
    {"s": "1155-yili Nuriddin Zangiy qaysi shaharni egallab, Suriyada yagona hokimiyat o‘rnatdi?", "v": ["Halab", "Damashq", "Qohira", "Bag‘dod"], "t": "Damashq"},
    {"s": "1176-yilgi Lenyano jangida Fridrix I Barbarossa kimlardan mag‘lub bo‘ldi?", "v": ["Arablardan", "Italiyaliklardan (Lombardiya ligasi)", "Fransuzlardan", "Inglizlardan"], "t": "Italiyaliklardan (Lombardiya ligasi)"},
    {"s": "1212-yilda Stefan ismli cho‘pon bola nima bilan shug‘ullandi?", "v": ["Qo‘zg‘olon ko‘tardi", "Bolalarni salib yurishiga targ‘ib qildi", "Yangi din yaratdi", "Qirolni ag‘dardi"], "t": "Bolalarni salib yurishiga targ‘ib qildi"},
    {"s": "1224-yilda Chingizxon o‘z o‘g‘li Chig‘atoyga qaysi hududlarni berdi?", "v": ["Rossiya yerlarini", "Zabit etilgan hududlarni (uluslarga bo‘lib)", "Faqat Mo‘g‘ulistonni", "Hindistonni"], "t": "Zabit etilgan hududlarni (uluslarga bo‘lib)"},
    {"s": "1258-yilda Arab xalifaligining tugatilishiga sabab bo‘lgan voqea:", "v": ["Salib yurishlari", "Xulokuning Bag‘dodni egallashi", "Ichki nizolar", "Vabo epidemiyasi"], "t": "Xulokuning Bag‘dodni egallashi"},
    {"s": "1260-yilda mo‘g‘ullar yurishini Yaqin Sharqda kim to‘xtatdi?", "v": ["Salohiddin Ayyubiy", "Sulton Sayfiddin Qutuz", "Boyazid I", "Alp Arslon"], "t": "Sulton Sayfiddin Qutuz"},
    {"s": "1308-yilda qaysi yirik turkiy davlat bir nechta beyliklarga bo‘linib ketdi?", "v": ["G‘aznaviylar", "Saljuqiylar", "Xorazmshohlar", "Qoraxoniylar"], "t": "Saljuqiylar"},
    {"s": "Milodiy I ming yillik o‘rtalarida Xitoyda qaysi din tarqala boshlagan?", "v": ["Islom", "Xristianlik", "Buddaviylik", "Zardushtiylik"], "t": "Buddaviylik"},
    {"s": "III asrda Xan imperiyasi inqirozga uchragach, qaysi qabilalar hujumi kuchaydi?", "v": ["German", "Slavyan", "Ko‘chmanchi turkiy", "Vikinglar"], "t": "Ko‘chmanchi turkiy"},
    {"s": "IV asrda Yaponiyada shakllangan narsa nima edi?", "v": ["Imperiya", "Shintoizm dini", "Qabilalar ittifoqi (bo‘lajak davlat asosi)", "Samuraylar tabaqasi"], "t": "Qabilalar ittifoqi (bo‘lajak davlat asosi)"},
    {"s": "V asrda Koguryo poytaxti Pxenyan shahriga qayerdan ko‘chirilgan?", "v": ["Avvalgi poytaxtidan", "Seuldan", "Tokiodan", "Pekindan"], "t": "Avvalgi poytaxtidan (Parchalanish va mustahkamlanish davri)"},
    {"s": "VI asrda Dunay daryosi sohiliga yetib kelgan xalq:", "v": ["Franklar", "Slavyanlar", "Arablar", "Normannlar"], "t": "Slavyanlar"},
    {"s": "VII asrda Yaponiya o‘zini qanday atay boshladi?", "v": ["Yamato", "Nippon (Kunchiqar mamlakat)", "Koreya", "Sin"], "t": "Nippon (Kunchiqar mamlakat)"},
    {"s": "VIII asr o‘rtalarida Silla qirolligining qanday davri boshlandi?", "v": ["Inqiroz davri", "Oltin davri", "Urushlar davri", "Mo‘g‘ul bosqini davri"], "t": "Oltin davri"},
    {"s": "IX asrda Buyuk Moraviya davlati hozirgi qaysi davlat o‘rnida bo‘lgan?", "v": ["Polsha", "Chexiya", "Vengriya", "Germaniya"], "t": "Chexiya"},
    {"s": "X asr oxirida Rus knyazi Vladimir qaysi dinni tanladi?", "v": ["Islom", "Buddizm", "Xristianlik", "Yahudiylik"], "t": "Xristianlik"},
    {"s": "XI asr boshlarida G‘azna hukmdori Mahmud Hindistonga necha marta yurish qilgan?", "v": ["10 marta", "12 marta", "15 marta", "17 marta"], "t": "17 marta"},
    {"s": "XII asrda asteklar asos solgan shahar:", "v": ["Kusko", "Tenochtitlan", "Mexiko", "Palenke"], "t": "Tenochtitlan"},
    {"s": "XIII asrda Chexiya Yevropada qanday mavqega ega edi?", "v": ["Eng zaif davlat", "Eng kuchli davlatlardan biri", "Vizantiya vassali", "Arablar ittifoqchisi"], "t": "Eng kuchli davlatlardan biri"},
    {"s": "XIV asrda maktablarda darslar qaysi tilda o‘tilishi boshlandi?", "v": ["Lotin tilida", "Arab tilida", "Milliy tillarda", "Yunon tilida"], "t": "Milliy tillarda"},
    {"s": "Milodiy 43-yili Britaniyani kimlar bosib oldi?", "v": ["Franklar", "Rimliklar", "Angllar", "Saksla"], "t": "Rimliklar"},
    {"s": "410-yili Rimni egallagan vestgotlar sarkardasi:", "v": ["Attila", "Alarix", "Odoakr", "Geyzerix"], "t": "Alarix"},
    {"s": "532–537-yillarda qurilgan Avliyo Sofiya ibodatxonasi qaysi shaharda joylashgan?", "v": ["Rim", "Konstantinopol", "Ravenna", "Iskandariya"], "t": "Konstantinopol"},
    {"s": "632-yili Muhammad (s.a.v.) qayerda vafot etdilar?", "v": ["Makka", "Madina", "Toif", "Quddus"], "t": "Madina"},
    {"s": "668-yili Koreya yarimorolini o‘z hokimiyati ostida birlashtirgan davlat:", "v": ["Koguryo", "Pekche", "Silla", "Koryo"], "t": "Silla"},
    {"s": "732-yilgi Puate jangi necha kun davom etgan?", "v": ["1 kun", "3 kun", "7 kun", "10 kun"], "t": "7 kun"},
    {"s": "756-yili Ispaniyada ajralib chiqqan birinchi mustaqil amirlik:", "v": ["Qurdoba (Kordova)", "Granada", "Sevilya", "Toledo"], "t": "Qurdoba (Kordova)"},
    {"s": "800-yili Rim papasi Karlga qayerda toj kiygizdi?", "v": ["Parijda", "Avliyo Pyotr ibodatxonasida", "Avliyo Sofiya ibodatxonasida", "Vestminsterda"], "t": "Avliyo Pyotr ibodatxonasida"},
    {"s": "IX asr boshlarida qaysi davlatlar birlashtirilib, 'Angliya' nomi paydo bo‘ldi?", "v": ["Norman davlatlari", "Anglosaks davlatlari", "Britt va keltlar", "Frank qirolliklari"], "t": "Anglosaks davlatlari"},
    {"s": "IX asrning o‘rtalarida kashf qilingan yapon alifbosining o‘ziga xosligi nimada?", "v": ["Faqat iyerogliflardan iborat", "Yapon tiliga moslashtirilgan bo‘g‘inli alifbo", "Lotin alifbosi asosida", "Arab alifbosi asosida"], "t": "Yapon tiliga moslashtirilgan bo‘g‘inli alifbo"},
    {"s": "X asrda Fransiya nomi qaysi viloyat nomidan kelib chiqqan?", "v": ["Normandiya", "Il-de-Frans", "Akvitaniya", "Burgundiya"], "t": "Il-de-Frans"},
    {"s": "X asrda Qurdoba xalifasining kutubxonasi qanchalik boy edi?", "v": ["100 ming kitob", "250 ming kitob", "400 ming qo‘lyozma", "1 million kitob"], "t": "400 ming qo‘lyozma"},
    {"s": "XI asrda papalar imperatorlarga qarshi nima uchun kurash boshladilar?", "v": ["Xristian cherkovi ustidan nazoratni qayta qo‘lga olish uchun", "Yer talashib", "Soliqlar uchun", "Poytaxtni ko‘chirish uchun"], "t": "Xristian cherkovi ustidan nazoratni qayta qo‘lga olish uchun"},
    {"s": "XI asr oxirida Saljuqiylar davlati qaysi hududlarni qamrab olgan edi?", "v": ["Faqat Movarounnahrni", "Sharqiy Turkistondan O‘rta Yer dengizigacha", "Faqat Eron va Iroqni", "Hindistondan Misrgacha"], "t": "Sharqiy Turkistondan O‘rta Yer dengizigacha"},
    {"s": "XII asrdan boshlab Yevropada shamol tegirmonlari qayerdan kelgan tajriba asosida qurildi?", "v": ["Xitoydan", "Suriyada ko‘rilgan tajriba asosida", "Vizantiyadan", "Skandinaviyadan"], "t": "Suriyada ko‘rilgan tajriba asosida"},
    {"s": "XIII asrda Koreyada qurilgan ibodatxonalarning joylashuvi qanday bo‘lgan?", "v": ["Shahar markazlarida", "Borish mushkul bo‘lgan tog‘li joylarda", "Dengiz qirg‘oqlarida", "Xitoy devori bo‘ylab"], "t": "Borish mushkul bo‘lgan tog‘li joylarda"},
    {"s": "XIV asrga qadar xitoyliklar choyni qanday iste'mol qilganlar?", "v": ["Quruq holda", "Suyuq taom (sho‘rva) singari pishirib", "Faqat dori sifatida ichib", "Shirinlik sifatida"], "t": "Suyuq taom (sho‘rva) singari pishirib"},
    {"s": "407-yilda Rim legionlari qayerdan Italiyaga qaytib ketishga majbur bo‘ldi?", "v": ["Galliyadan", "Britaniyadan", "Ispaniyadan", "Germaniyadan"], "t": "Britaniyadan"},
    {"s": "476-yili isyon ko‘targan va so‘nggi Rim imperatorini ag‘dargan sarkarda:", "v": ["Alarix", "Odoakr", "Atilla", "Xlodvig"], "t": "Odoakr"},
    {"s": "632-yildan 661-yilgacha bo‘lgan davr Islom tarixida qanday ataladi?", "v": ["Xulafoyi roshidin (Choryorlar) davri", "Umaviylar davri", "Abbosiylar davri", "Saljuqiylar davri"], "t": "Xulafoyi roshidin (Choryorlar) davri"},
    {"s": "681-yili Bolgar davlatiga asos solgan xalq qayerdan kelgan edi?", "v": ["Skandinaviyadan", "Arabistondan", "Markaziy Osiyo va dashtlardan (Turkiy xalqlar)", "Rimdan"], "t": "Markaziy Osiyo va dashtlardan (Turkiy xalqlar)"},
    {"s": "751-yili Franklarda Merovinglar sulolasi o‘rniga qaysi sulola keldi?", "v": ["Kapetinglar", "Karolinglar", "Valualar", "Burbonlar"], "t": "Karolinglar"},
    {"s": "843-yilgi Verden shartnomasi hozirgi qaysi davlatlar asosini yaratdi?", "v": ["Fransiya, Germaniya, Italiya", "Angliya, Fransiya, Ispaniya", "Polsha, Chexiya, Vengriya", "Rossiya, Ukraina, Belarus"], "t": "Fransiya, Germaniya, Italiya"},
    {"s": "863-yili Kirill va Mefodiy slavyanlar uchun nima yaratishdi?", "v": ["Davlat", "Alifbo (Kirillitsa)", "Din", "Qonunlar to‘plami"], "t": "Alifbo (Kirillitsa)"},
    {"s": "962-yili Otton I imperatorlik tojini qayerda kiygan?", "v": ["Axenda", "Rimda (Papa Ioann XII tomonidan)", "Konstantinopolda", "Parijda"], "t": "Rimda (Papa Ioann XII tomonidan)"},
    {"s": "988-yili Kiyev Rusida xristianlikning qaysi yo‘nalishi rasman qabul qilindi?", "v": ["Katoliklik", "Pravoslavlik", "Protestantlik", "Protestantizm"], "t": "Pravoslavlik"},
    {"s": "1054-yilda xristian cherkovi necha qismga bo‘lindi?", "v": ["Ikki qismga (Rim-katolik va Yunon-pravoslav)", "Uch qismga", "Bo‘linmadi", "To‘rt qismga"], "t": "Ikki qismga (Rim-katolik va Yunon-pravoslav)"},
    {"s": "1096-yilda birinchi bo‘lib Quddus sari kimlar yo‘l oldi?", "v": ["Faqat ritsarlar", "Dehqonlar va kambag‘allar (Ruhoniylar boshchiligida)", "Qirollar qo‘shini", "Savdogarlar"], "t": "Dehqonlar va kambag‘allar (Ruhoniylar boshchiligida)"},
    {"s": "1187-yili Hittin jangidan so‘ng Salohiddin Ayyubiy qaysi shaharni ozod qildi?", "v": ["Damashq", "Quddus", "Bag‘dod", "Qohira"], "t": "Quddus"},
    {"s": "1204-yili to‘rtinchi salib yurishi natijasida qaysi shahar salibchilar tomonidan talandi?", "v": ["Quddus", "Qohira", "Konstantinopol", "Rim"], "t": "Konstantinopol"},
    {"s": "1211-yilda Chingizxon qaysi davlatga qarshi 200 minglik qo‘shin bilan yurish boshladi?", "v": ["Xorazmshohlar", "Shimoliy Xitoy (Szin imperiyasi)", "Kiyev Rusi", "Hindiston"], "t": "Shimoliy Xitoy (Szin imperiyasi)"},
    {"s": "1258-yili mo‘g‘ullar tomonidan Bag‘dodda qancha aholi qatl qilingan (tarixiy ma'lumot)?", "v": ["100 ming", "Juda ko‘p (Xalifalik tugatildi)", "50 ming", "10 ming"], "t": "Juda ko‘p (Xalifalik tugatildi)"},
    {"s": "1308-yili Saljuqiylar davlatining qulashi qaysi yangi turkiy davlatning yuksalishiga yo‘l ochdi?", "v": ["Temuriylar", "Usmonli turklar (Beyliklar asosida)", "Safaviylar", "Boburiylar"], "t": "Usmonli turklar (Beyliklar asosida)"},
    {"s": "V asrda Yevropada cherkov qanday qilib yirik yer egalariga aylandi?", "v": ["Sotib oldi", "Feodal munosabatlarga o‘tish va hadyalar hisobiga", "Urush orqali tortib oldi", "Imperator taqiqladi"], "t": "Feodal munosabatlarga o‘tish va hadyalar hisobiga"},
    {"s": "VI asrda Vizantiyada hunarmandchilikning qaysi turi juda rivojlangan edi?", "v": ["Chini buyumlar", "Ipak to‘qish va zargarlik", "Porox tayyorlash", "Kitob bosish"], "t": "Ipak to‘qish va zargarlik"},
    {"s": "VII asrda arablar egallagan Misr va Suriya avval kimlarga tegishli edi?", "v": ["Eronga", "Vizantiyaga", "Rimga", "Franklarga"], "t": "Vizantiyaga"},
    {"s": "VIII asrda arablarning Yevropa ichkarisiga yurishini kim to‘xtatgan?", "v": ["Buyuk Karl", "Karl Martell (Puate jangida)", "Pipin Pakana", "Lyudovik"], "t": "Karl Martell (Puate jangida)"},
    {"s": "IX asrda Bag‘dodda tashkil etilgan 'Bayt ul-hikma' ning asosiy vazifasi nima edi?", "v": ["Faqat diniy ta'lim", "Ilmiy asarlarni arab tiliga tarjima qilish va tadqiqot", "Harbiy tayyorgarlik", "Savdo aloqalari"], "t": "Ilmiy asarlarni arab tiliga tarjima qilish va tadqiqot"},
    {"s": "X asrda Polsha davlatiga asos solgan knyaz:", "v": ["Vladimir", "Meshko I", "Simeon", "Otton"], "t": "Meshko I"},
    {"s": "XI asrda Vizantiyani qaysi turkiy qabilalar xavf ostiga qo‘ydi?", "v": ["Mo‘g‘ullar", "Saljuqiylar (O‘g‘uzlar)", "Xazarlar", "Bulg‘orlar"], "t": "Saljuqiylar (O‘g‘uzlar)"},
    {"s": "XII asrda Yevropada gotika uslubidagi qanday binolar qurila boshlandi?", "v": ["Qasrlar", "Hashamatli ibodatxonalar (Soborlar)", "Karvonsaroylar", "Maktablar"], "t": "Hashamatli ibodatxonalar (Soborlar)"},
    {"s": "XIII asrda Onon daryosi bo‘yida o‘tkazilgan mo‘g‘ullar qurultoyi qachon bo‘lgan?", "v": ["1200-yili", "1206-yili", "1211-yili", "1227-yili"], "t": "1206-yili"},
    {"s": "XIV asrda Yevropada 'Qora o‘lim' (vabo) tarqalganda cherkovning mavqei nima bo‘ldi?", "v": ["Zaiflashdi (odamlarni qutqara olmagani uchun)", "Kuchaydi", "O‘zgarmadi", "Yo‘qolib ketdi"], "t": "Zaiflashdi (odamlarni qutqara olmagani uchun)"},
    {"s": "XV asrda Vizantiya (Sharqiy Rim) imperiyasi kimlar tomonidan tugatildi?", "v": ["Saljuqiylar", "Usmonli turklar (1453-y)", "Arablar", "Mo‘g‘ullar"], "t": "Usmonli turklar (1453-y)"},
    {"s": "418-yili tashkil topgan Vestgot qirolligi hozirgi qaysi davlat hududida edi?", "v": ["Germaniya", "Fransiya va Ispaniya (Galliya)", "Italiya", "Gretsiya"], "t": "Fransiya va Ispaniya (Galliya)"},
    {"s": "527-yili Vizantiya taxtiga o‘tirgan Yustinian I ning xotini kim edi?", "v": ["Yelena", "Teodora", "Anna", "Mariya"], "t": "Teodora"},
    {"s": "610-yili Muhammad (s.a.v.) necha yoshda edilar?", "v": ["25 yoshda", "40 yoshda", "63 yoshda", "50 yoshda"], "t": "40 yoshda"},
    {"s": "661-yili Umaviylar xalifalik poytaxtini qayerga ko‘chirishdi?", "v": ["Madinaga", "Damashqqa", "Bag‘dodga", "Qohiraga"], "t": "Damashqqa"},
    {"s": "711-yili Jabal at-Tariq boshchiligidagi qo‘shin qaysi bo‘g‘oz orqali o‘tdi?", "v": ["Bosfor", "Gibraltar", "Dardanell", "Suvaysh"], "t": "Gibraltar (Jabal at-Tariq nomi bilan atalgan)"},
    {"s": "768-yili taxtga o‘tirgan Buyuk Karl necha yil hukmronlik qildi?", "v": ["30 yil", "40 yil", "46 yil", "50 yil"], "t": "46 yil"},
    {"s": "800-yili Karl imperator bo‘lgach, G‘arbda qaysi imperiya qayta tiklangandek bo‘ldi?", "v": ["Vizantiya", "G‘arbiy Rim imperiyasi", "Aleksandr imperiyasi", "Fors imperiyasi"], "t": "G‘arbiy Rim imperiyasi"},
    {"s": "829-yili Angliya birlashtirilgach, uning birinchi qiroli kim bo‘ldi?", "v": ["Alfred", "Ekbert", "Kanut", "Vilgelm I"], "t": "Ekbert"},
    {"s": "871–900-yillarda Buyuk Alfred qaysi bosqinchilarga qarshi kurashdi?", "v": ["Arablarga", "Daniyaliklarga (Vikinglar)", "Franklarga", "Slavyanlarga"], "t": "Daniyaliklarga (Vikinglar)"},
    {"s": "911-yili normannlarga Fransiyaning shimolidan qayer berildi?", "v": ["Parij", "Normandiya", "Lion", "Marsel"], "t": "Normandiya"},
    {"s": "962-yili tashkil topgan Muqaddas Rim imperiyasining birinchi imperatori:", "v": ["Buyuk Karl", "Otton I", "Fridrix Barbarossa", "Genrix IV"], "t": "Otton I"},
    {"s": "988-yili Rus xalqini xristianlashtirgan knyaz Vladimir qaysi shahar knyazi edi?", "v": ["Moskva", "Kiyev", "Novgorod", "Vladimir"], "t": "Kiyev"},
    {"s": "1066-yili Gastings jangida kim g‘alaba qozondi?", "v": ["Angliya qiroli Garold", "Normandiya gersogi Vilgelm (Bosqinchi)", "Buyuk Karl", "Richard Sheryurak"], "t": "Normandiya gersogi Vilgelm (Bosqinchi)"},
    {"s": "1071-yili Mansikert jangida Vizantiya imperatori kim edi?", "v": ["Yustinian", "Roman IV Diogen", "Aleksey I", "Konstantin"], "t": "Roman IV Diogen"},
    {"s": "1095-yili Klermon cherkov yig‘ilishida 'Xudo shuni xohlaydi!' deb hayqirgan odamlar kimlar edi?", "v": ["Faqat boylar", "Salib yurishiga otlangan barcha tabaqalar", "Faqat askarlar", "Imperatorlar"], "t": "Salib yurishiga otlangan barcha tabaqalar"},
    {"s": "1147-yili ikkinchi salib yurishiga kimlar boshchilik qildi?", "v": ["Lyudovik VII va Konrad III", "Buyuk Karl va Otton", "Richard Sheryurak va Filipp II", "Rim papasi"], "t": "Fransiya qiroli Lyudovik VII va Germaniya imperatori Konradi III"},
    {"s": "1190-yili uchinchi salib yurishi paytida kichik daryodan o‘tayotib cho‘kib ketgan hukmdor:", "v": ["Richard Sheryurak", "Fridrix I Barbarossa", "Filipp II Avgust", "Salohiddin Ayyubiy"], "t": "Fridrix I Barbarossa"},
    {"s": "1206-yili Temuchinga berilgan 'Chingiz' unvoni qanday ma'noni anglatadi?", "v": ["Temirchi", "Okean (Dengiz) kabi buyuk hukmdor", "Botir askar", "Osmon farzandi"], "t": "Okean (Dengiz) kabi buyuk hukmdor"},
    {"s": "1219-yili Chingizxon qo‘shinlari O‘trorni necha oy qamal qildi?", "v": ["6 oy", "1 yil", "1 oy", "3 oy"], "t": "6 oy"},
    {"s": "1258-yili Mo‘g‘ullar Bag‘dodni egallashda qanday texnikadan foydalanishgan?", "v": ["Faqat otliq askarlar", "Xitoy texnikasi (manjanaiq va o‘t sochuvchilar)", "Faqat qabr qazish", "Dengiz kemalari"], "t": "Xitoydan keltirilgan manjanaiq (tosh otar) va o‘t sochuvchi qurilmalar"},
    {"s": "1270-yili sakkizinchi salib yurishi paytida Tunisda vabo kasalidan vafot etgan qirol:", "v": ["Filipp II", "Lyudovik IX (Avliyo Lyudovik)", "Richard I", "Genrix II"], "t": "Lyudovik IX (Avliyo Lyudovik)"},
    {"s": "XIII asrda Venetsiyalik Marko Polo Xitoyda necha yil yashagan?", "v": ["5 yil", "10 yil", "17 yil", "25 yil"], "t": "17 yil"},
    {"s": "40 ming yil avval Amerika qit'asiga odamlar qaysi yo‘l orqali o‘tgan?", "v": ["Suv ostidan", "Bering bo‘g‘ozi (quruqlik payti)", "Kemada", "Uchib"], "t": "Bering bo‘g‘ozi (o‘sha paytdagi quruqlik) orqali"},
    {"s": "III–IV asrlarda xitoyliklar choyni nima maqsadda ishlatishgan?", "v": ["Faqat chanqoq bosish uchun", "Dorivor o‘simlik sifatida", "Qurilishda", "Bo‘yoq sifatida"], "t": "Dorivor o‘simlik sifatida (tetiklashtiruvchi)"},
    {"s": "VI asrda Vizantiya imperiyasi hududi qaysi qit'alarni qamrab olgan?", "v": ["Yevropa, Osiyo, Afrika", "Faqat Yevropa", "Osiyo va Amerika", "Faqat Osiyo"], "t": "Yevropa, Osiyo, Afrika"},
    {"s": "VII asr boshida tashkil topgan Xarsha imperiyasi qancha vaqt yashadi?", "v": ["10 yil", "40 yil atrofida", "100 yil", "200 yil"], "t": "Taxminan 40 yil (Xarsha vafotigacha)"},
    {"s": "VIII asrda qog‘oz ishlab chiqarish siri arablarga kimlardan o‘tgan?", "v": ["Hindlardan", "Xitoyliklardan (Talas jangi)", "Forslardan", "Yunonlardan"], "t": "Xitoyliklardan (Talas jangidan so‘ng)"},
    {"s": "IX asrda sharqiy slavyanlar Ryurikni qayerdan chaqirishgan?", "v": ["Rimdan", "Skandinaviyadan (Varyaglar)", "Vizantiyadan", "Xazariyadan"], "t": "Skandinaviyadan (Varyaglar)"},
    {"s": "X asrda vujudga kelgan feodalizmning asosiy belgisi nima?", "v": ["Hamma tengligi", "Yerga egalik va vassallik tizimi", "Faqat savdo qilish", "Qulchilik"], "t": "Yerga egalik qilish va vassallik tizimi"},
    {"s": "XI asrda O‘rta Osiyoda vujudga kelgan Saljuqiylar davlati poytaxtlari qaysilar bo‘lgan?", "v": ["Faqat Bag‘dod", "Nishopur, Rey, Isfahon", "Buxoro va Samarqand", "Qohira"], "t": "Nishopur, Rey, Isfahon"},
    {"s": "XII asrda Yevropa bozorlarida qaysi davlatlarning tangalari (dinorlar) asosiy pul bo‘lgan?", "v": ["Franklarning", "Arab xalifaligining", "Xitoyning", "Rusning"], "t": "Arab xalifaligining"},
    {"s": "XIII asrda mo‘g‘ullar zabt etgan hududlarda qanday aloqa tizimi o‘rnatildi?", "v": ["Telefon", "Yam (Pochta-bekat tizimi)", "Kabutar pochtasi", "Dengiz pochtasi"], "t": "Yam (Pochta-bekat tizimi)"},
    {"s": "XIV asrda Angliya va Fransiya o‘rtasida qanday uzoq urush boshlandi (1337-y)?", "v": ["7 yillik urush", "100 yillik urush", "30 yillik urush", "Salib yurishi"], "t": "100 yillik urush"},
    {"s": "XV asr oxirida (1492-y) Amerika qit'asini yevropaliklar uchun kim qayta kashf qildi?", "v": ["Marko Polo", "Xristofor Kolumb", "Vasko da Gama", "Magellan"], "t": "Xristofor Kolumb"},
    {"s": "Mil. avv. V asrda yashagan Konfutsiyning asosiy g‘oyasi nima?", "v": ["Insonparvarlik, tartib va kattalarga hurmat", "Faqat urush qilish", "Boylik to‘plash", "Tabiatga sig‘inish"], "t": "Insonparvarlik, tartib-intizom va kattalarga hurmat"},
    {"s": "Mil. avv. I asrda Koreyadagi uch qirollikdan qaysi biri eng shimolda joylashgan edi?", "v": ["Silla", "Pekche", "Koguryo", "Koryo"], "t": "Koguryo"},
    {"s": "IV asrda xristianlik rasmiy dinga aylangach, cherkov rahbari kim bo‘ldi?", "v": ["Imperator", "Rim papasi (G‘arbda)", "Knyaz", "Qirol"], "t": "Rim papasi (G‘arbda)"},
    {"s": "V asr oxirida Franklar qiroli Xlodvig qaysi sulolaga asos solgan edi?", "v": ["Merovinglar", "Karolinglar", "Kapetinglar", "Burbonlar"], "t": "Merovinglar"},
    {"s": "VI asrda Vizantiyada qabul qilingan qonunlar to‘plami qanday ataladi?", "v": ["'Saliq haqiqati'", "Yustinian kodeksi", "'Rus haqiqati'", "'Yasa'"], "t": "'Fuqarolik huquqlari to‘plami' (Yustinian kodeksi)"},
    {"s": "VII asrda Islom dini tarqalishi natijasida qaysi buyuk imperiya butunlay quladi?", "v": ["Vizantiya", "Sosoniylar (Eron) imperiyasi", "Rim imperiyasi", "Franklar davlati"], "t": "Sosoniylar (Eron) imperiyasi"},
    {"s": "VIII asrda Yevropada eng kuchli davlat rahbari:", "v": ["Alfred", "Buyuk Karl", "Xlodvig", "Otton"], "t": "Buyuk Karl"},
    {"s": "IX asrda Movarounnahrda qaysi mustaqil davlat vujudga keldi?", "v": ["Abbosiylar", "Somoniylar", "Saljuqiylar", "G‘aznaviylar"], "t": "Somoniylar"},
    {"s": "X asrda Skandinaviyadan kelgan normannlar Amerikaning qirg‘oqlariga yetib borishganmi?", "v": ["Ha (Leyf Eriksson boshchiligida)", "Yo‘q", "Faqat Islandiya", "Faqat Angliya"], "t": "Ha (Leyf Eriksson boshchiligida)"},
    {"s": "XI asrda Saljuqiylar tomonidan Vizantiya imperatorining asir olinishi qayerda yuz berdi?", "v": ["Konstantinopolda", "Mansikertda", "Quddusda", "Rimda"], "t": "Mansikertda"},
    {"s": "XII asrda Yevropa shaharlari o‘zini-o‘zi boshqarish uchun kimlarga qarshi kurashdi?", "v": ["Papalarga", "Senyorlarga (Feodallarga)", "Dehqonlarga", "Hunarmandlarga"], "t": "Senyorlarga (Feodallarga)"},
    {"s": "XIII asrda Chingizxon vafotidan so‘ng uning o‘rniga kim buyuk xon bo‘ldi?", "v": ["Jo‘ji", "Chig‘atoy", "O‘qtoy (Ugedey)", "Tulu"], "t": "O‘qtoy (Ugedey)"},
    {"s": "XIV asrda O‘rta Osiyoda qaysi buyuk sarkarda o‘z davlatiga asos soldi?", "v": ["Chingizxon", "Amir Temur", "To‘xtamishxon", "Bobur"], "t": "Amir Temur"},
    {"s": "XV asrda Islom olamida me'morchilikning eng yuksak namunasi hisoblangan bino:", "v": ["Avliyo Sofiya", "Registon ansambli (Samarqand)", "Tojmaxal", "Alhambra"], "t": "Registon ansambli (Samarqand)"},
    {"s": "Milodiy I ming yillik oxirida (X asr) dunyoning eng rivojlangan shahri qaysi edi?", "v": ["Rim", "London", "Bag‘dod (yoki Qurdoba)", "Parij"], "t": "Bag‘dod (yoki Qurdoba)"},
    {"s": "V asrda germanlar Rimni egallagach, qaysi davr tugadi?", "v": ["O‘rta asrlar", "Qadimgi dunyo tarixi", "Yangi tarix", "Temir davri"], "t": "Qadimgi dunyo tarixi"},
    {"s": "VI asrda Vizantiya ipak qurti tuxumini qayerdan yashirincha olib kelgan?", "v": ["Hindistondan", "Xitoydan (Rohiblar hassasi ichida)", "Erondan", "Rusdan"], "t": "Xitoydan (Rohiblar hassasi ichida)"},
    {"s": "VII asrda Arab xalifaligida davlat tili qaysi til edi?", "v": ["Fors tili", "Arab tili", "Yunon tili", "Lotin tili"], "t": "Arab tili"},
    {"s": "VIII asrda Yevropada 'Buyuk Karl Uyg‘onishi' nima bilan bog‘liq?", "v": ["Urushlar bilan", "Ta'lim, maktablar va lotin tili bilan", "Islom bilan", "Savdo bilan"], "t": "Ta'lim, maktablar va lotin tilini o‘rganish bilan"},
    {"s": "IX asrda Vikinglar qaysi orollarni egallab, u yerda davlatlar tuzishdi?", "v": ["Faqat Islandiya", "Islandiya, Grenlandiya, Britaniya orollari", "Yaponiya", "Avstraliya"], "t": "Islandiya, Grenlandiya, Britaniya orollari"},
    {"s": "X asrda Dunyodagi eng qadimgi universitet qayerda ochildi?", "v": ["Oksfordda", "Fesda (Qaroviyun) va Qohirada (Al-Azhar)", "Sorbonnada", "Bolonyada"], "t": "Fesda (Qaroviyun, 859-y) va Qohirada (Al-Azhar, 970-y)"},
    {"s": "XI asrda Saljuqiylar davlatida vazirlik qilgan mashhur siymo:", "v": ["Beruniy", "Nizomulmulk", "Ibn Sino", "Al-Xorazmiy"], "t": "Nizomulmulk"},
    {"s": "XII asrda Yevropada ritsarlik madaniyati nimalarda namoyon bo‘ldi?", "v": ["Faqat dehqonchilikda", "Turnirlar va harbiy odob", "Faqat kitob yozishda", "Savdo sotiqda"], "t": "Turnirlar, \"Sadoqatli yor\"ga xizmat va harbiy odob"},
    {"s": "XIII asrda Mo‘g‘ullar qo‘shinining asosi nima edi?", "v": ["Piyoda askarlar", "Intizomli otliq askarlar", "Dengiz floti", "Fillardan iborat qo‘shin"], "t": "Intizomli otliq askarlar"},
    {"s": "XIV asrda Vizantiya imperiyasi qaysi hududlargacha kichrayib qoldi?", "v": ["Butun Bolqon", "Konstantinopol va uning atrofi", "Misr va Suriya", "Kichik Osiyo"], "t": "Konstantinopol va uning atrofi"},
    {"s": "XV asrda Buyuk geografik kashfiyotlarga asosiy turtki nima edi?", "v": ["Shunchaki qiziqish", "Sharqqa dengiz yo‘lini topish va ziravorlar savdosi", "Urush qilish", "Dinni tarqatish"], "t": "Sharqqa (Hindistonga) dengiz yo‘lini topish va ziravorlar savdosi"},
    {"s": "Mil. avv. IV asrda Buyuk Xitoy devori nima uchun qurila boshlagan?", "v": ["Sayyohlar uchun", "Shimoldan ko‘chmanchilar (Xunlar) hujumidan himoyalanish uchun", "Suv toshqinidan", "Shaharlarni birlashtirish uchun"], "t": "Shimoldan ko‘chmanchi qabilalar (Xunlar) hujumidan himoyalanish uchun"},
    {"s": "IV asrda xristian dini germanlar orasida tarqalgach, ularning yozuvi qanday o‘zgardi?", "v": ["O‘zgarmadi", "Lotin va yunon alifbosi asosida yozuvlar paydo bo‘ldi", "Faqat rasm chizishdi", "Arab yozuvini olishdi"], "t": "Lotin va yunon alifbosi asosida yozuvlar paydo bo‘ldi"},
    {"s": "VI asrda Hindistonda Gupta imperiyasi parchalangach, nima yuz berdi?", "v": ["Yagona davlat tuzildi", "Mayda knyazliklar (Feodal tarqoqlik)", "Arablar bosib oldi", "Xitoyga qo‘shildi"], "t": "Ko‘plab mayda knyazliklar vujudga keldi (Feodal tarqoqlik)"},
    {"s": "VIII–XIII asrlar Yangi darslik bo‘yicha qaysi davrni qamrab oladi?", "v": ["Qadimgi davr", "O‘rta asrlar davri", "Yangi davr", "Eng yangi davr"], "t": "O‘rta asrlar davri"}
]