# data_7jt_atamalar.py

atamalar_7jt = [
    {"s": "G‘arbiy Yevropa feodal jamiyatida avloddan-avlodga meros bo‘lib o‘tadigan yer-mulk qanday atalgan?", "v": ["Benefitsiy", "Allod", "Domen", "Suyurg‘ol"], "t": "Allod"},
    {"s": "Portugalcha 'e’tiqod ishi' ma'nosini bildiruvchi, din dushmanlarini ommaviy jazolash marosimi qanday nomlanadi?", "v": ["Inkvizitsiya", "Interdikt", "Autodafe", "Indulgensiya"], "t": "Autodafe"},
    {"s": "Italyancha 'banko' (o'rindiq) so'zidan olingan, hozirgi kunda moliya muassasasini anglatuvchi atamani toping.", "v": ["Bank", "Birja", "Faktoriya", "Yarmarka"], "t": "Bank"},
    {"s": "Oltin O‘rdada ijro hokimiyati va qo‘shin boshlig‘i bo'lgan, ba’zida xondan ham yuqori mavqega ega amaldor kim?", "v": ["Bosqoq", "Beklarbegi", "Tungin", "Sherif"], "t": "Beklarbegi"},
    {"s": "G‘arbiy Yevropada senyorning o‘z vassaliga harbiy xizmati evaziga in’om etgan yer-mulki (Sharqdagi iqto muqobili) qanday ataladi?", "v": ["Allod", "Benefitsiy", "Grass", "Patta"], "t": "Benefitsiy"},
    {"s": "Bryugge shahridagi mehmonxona nomi bilan bog'liq bo'lgan, savdogarlar to‘planadigan va qimmatli qog'ozlar sotiladigan joy qanday ataladi?", "v": ["Bank", "Birja", "Faktoriya", "Yarmarka"], "t": "Birja"},
    {"s": "Mo‘g‘ullar davrida soliq va bojlarning to‘lanishini nazorat qiluvchi maxsus tayinlangan noiblar qanday nomlangan?", "v": ["Beklarbegi", "Bosqoqlar", "Tlatoani", "Sheriflar"], "t": "Bosqoqlar"},
    {"s": "Britaniyaning asosiy aholisi hisoblangan qadimgi kelt qabilalarini ko'rsating.", "v": ["Brittlar", "Normanlar", "Franklar", "Gotlar"], "t": "Brittlar"},
    {"s": "III asrdan boshlab xristian cherkovi oliy ruhoniylarining cherkov muammolarini hal etish uchun chaqiradigan qurultoyi qanday ataladi?", "v": ["Sinagoga", "Cherkov yig‘inlari", "Konfeederatsiya", "Parlament"], "t": "Cherkov yig‘inlari"},
    {"s": "XIII asr o'rtalarida mo‘g‘ullar tomonidan o'tkazilgan ro‘yxatga olishdan so'ng, aholi zimmasiga yuklatilgan katta to‘lov nima deb atalgan?", "v": ["Talab", "Chiqim", "Boj", "Tamg'a"], "t": "Chiqim"},
    {"s": "Koreys tilida «Tonggi tarovat» ma’nosini anglatuvchi ilk koreys davlati nomini toping.", "v": ["Yaponiya", "Choson", "Xitoy", "Syoyen"], "t": "Choson"},
    {"s": "O'quvchilarni munozara olib borishga va o‘z fikrini isbotlashga o‘rgatadigan mantiq fani qanday ataladi?", "v": ["Ritorika", "Dialektika", "Grammatika", "Falsafa"], "t": "Dialektika"},
    {"s": "Lotincha 'dominium' (mulk) so'zidan olingan, feodalning o'ziga tegishli va qaram dehqonlar ishlaydigan yer-mulki qanday nomlanadi?", "v": ["Benefitsiy", "Domen", "Allod", "Grass"], "t": "Domen"},
    {"s": "Bir necha o‘ndan bir necha yuzgacha ko'ngillilarni birlashtirgan harbiy bo‘linma qanday ataladi?", "v": ["Keshik", "Drujina", "Kogorta", "Legion"], "t": "Drujina"},
    {"s": "Feodallar toifasining merosiy imtiyozlarga ega bo'lgan qismi qanday nomlanadi?", "v": ["Vassallar", "Dvoryanlar", "Ritsarlar", "Baronlar"], "t": "Dvoryanlar"},
    {"s": "O‘rta yer dengizi sohillarida italiyalik savdogarlar tomonidan barpo etilgan savdo manzilgohlari nima deb atalgan?", "v": ["Faktoriyalar", "Koloniyalar", "Birjalar", "Markalar"], "t": "Faktoriyalar"},
    {"s": "Fransiyadagi tabaqaviy-vakillik organi bo'lgan oliy muassasa qanday nomlanadi?", "v": ["Parlament", "General shtatlar", "Senat", "Kengash"], "t": "General shtatlar"},
    {"s": "Dastlab Falastinda, keyinchalik Rodos va Malta orollarida joylashgan ritsarlik ordeni qaysi?", "v": ["Tampliyerlar", "Gospitalyerlar (ioanniylar)", "Tevton ordeni", "Nemis ordeni"], "t": "Gospitalyerlar (ioanniylar)"},
    {"s": "XII asr o'rtalarida Shimoliy Fransiyada vujudga kelgan me'morchilik va san'at uslubini toping.", "v": ["Roman uslubi", "Gotika uslubi", "Barokko", "Klassitsizm"], "t": "Gotika uslubi"},
    {"s": "Qirol tomonidan tayinlanib, hududni uning nomidan boshqaruvchi, soliq yig'uvchi va harbiy qo'mondonlik qiluvchi amaldor kim?", "v": ["Sherif", "Graf", "Baron", "Vassal"], "t": "Graf"},
    {"s": "O'rta asrlar maktablarida bolalarni o‘qishga o‘rgatuvchi tilshunoslik ilmi qanday atalgan?", "v": ["Grammatika", "Ritorika", "Dialektika", "Mantiq"], "t": "Grammatika"},
    {"s": "Harbiy xizmat o'tash sharti bilan in'om etilgan yer maydoni qanday nomlanadi?", "v": ["Domen", "Grass", "Allod", "Patta"], "t": "Grass"},
    {"s": "Vizantiya harbiy kemalarida ishlatilgan, neft va oltingugurt aralashmasidan tayyorlangan yonuvchi modda qanday ataladi?", "v": ["Dinamit", "Grek olovi", "Porox", "Ballista"], "t": "Grek olovi"},
    {"s": "Lotincha 'afv' ma'nosini anglatuvchi, cherkov tomonidan sotiladigan gunohlardan kechish yorliqlari qanday nomlanadi?", "v": ["Patta", "Indulgensiya", "Yorliq", "Autodafe"], "t": "Indulgensiya"},
    {"s": "Yeretiklarga (dahriylarga) qarshi kurashish uchun cherkov tomonidan tuzilgan maxsus qidiruv va sud organi qaysi?", "v": ["Autodafe", "Inkvizitsiya", "Interdikt", "Konsilium"], "t": "Inkvizitsiya"},
    {"s": "Cherkov tomonidan biror mamlakatda ibodat va diniy marosimlarning vaqtinchalik taqiqlanishi nima deb ataladi?", "v": ["Indulgensiya", "Interdikt", "Inkvizitsiya", "Autodafe"], "t": "Interdikt"},
    {"s": "Arabcha 'itoat' va 'tobelik' ma'nosini anglatuvchi, dunyodagi yirik dinlardan birini ko'rsating.", "v": ["Xristianlik", "Islom", "Buddaviylik", "Yahudiylik"], "t": "Islom"},
    {"s": "Sariq rangli, tiniq va qattiq qatronsimon ma'dan qanday ataladi?", "v": ["Marmar", "Kahrabo", "Yashma", "Zumrad"], "t": "Kahrabo"},
    {"s": "Chingizxon ixtiyoridagi maxsus gvardiya (shaxsiy qo'riqchilar) qanday nom bilan yuritilgan?", "v": ["Drujina", "Keshik", "Kogorta", "Falanga"], "t": "Keshik"},
    {"s": "Inklarda qo'llanilgan, ma'lumotlarni saqlash va uzatish uchun ishlatilgan tugunli xat nima deb ataladi?", "v": ["Mixxat", "Kipu", "Iyeroglif", "Piktografiya"], "t": "Kipu"},
    {"s": "O'rta asr universitetlarida talabalar yashaydigan yotoqxona tipidagi joylar qanday atalgan?", "v": ["Faktoriya", "Kollegiya", "Akademiya", "Gimnaziya"], "t": "Kollegiya"},
    {"s": "O'rta asr shaharlarining feodallarga qarshi kurashi natijasida qo'lga kiritgan 'erkinlik huquqi' qanday nomlanadi?", "v": ["Domen", "Kommuna", "Vassallik", "Immunitet"], "t": "Kommuna"},
    {"s": "Normann qabilalarida harbiy yo‘lboshchi hamda qabila boshlig'i qanday unvon bilan atalgan?", "v": ["Graf", "Konung", "Gertsog", "Imperator"], "t": "Konung"},
    {"s": "Ispaniya va Italiyani Vizantiya hamda Osiyo mamlakatlari bilan bog‘lovchi dengiz savdo yo‘li qaysi?", "v": ["Shimoliy savdo yo'li", "Levant savdo yo‘li", "Buyuk Ipak yo'li", "Volga yo'li"], "t": "Levant savdo yo‘li"},
    {"s": "Universitetlarda dars beruvchi o‘qituvchilar qanday ilmiy unvon bilan atalgan?", "v": ["Shkolyarlar", "Magistrlar", "Talaba", "Rektor"], "t": "Magistrlar"},
    {"s": "Buyuk Karl davlatida chegaralarni himoya qilish uchun tuzilgan harbiy viloyatlar nima deb atalgan?", "v": ["Markalar", "Grafliklar", "Viloyatlar", "Faktoriyalar"], "t": "Markalar"},
    {"s": "Mamlakatning barcha hududlari yagona hukmdorga bo'ysunadigan boshqaruv shakli qanday ataladi?", "v": ["Demokratiya", "Markazlashgan qirol hokimiyati", "Feodal tarqoqlik", "Respublika"], "t": "Markazlashgan qirol hokimiyati"},
    {"s": "Merosning kichik o'g'illarga emas, faqat katta o‘g‘ilga qoldirilishi tizimi qanday nomlanadi?", "v": ["Matriarxat", "Mayorat tizimi", "Vassallik", "Kollegiya"], "t": "Mayorat tizimi"},
    {"s": "XII asrdan boshlab Yaponiyada imperator qanday unvon bilan atala boshlangan?", "v": ["Shogun", "Mikado", "Samuray", "Daimyo"], "t": "Mikado"},
    {"s": "Qo'lyozma kitoblarni bezash uchun yaratilgan o'ta nafis va kichik hajmli tasviriy san'at asari qanday ataladi?", "v": ["Freska", "Miniatyura", "Panno", "Mozaika"], "t": "Miniatyura"},
    {"s": "Turli xil tosh, koshin yoki metall bo'laklaridan terib ishlangan mahobatli bezak san'ati turi qaysi?", "v": ["Miniatyura", "Mozaika", "Panno", "Freska"], "t": "Mozaika"},
    {"s": "Muqaddas Bibi Maryamga bag‘ishlangan va 'Tevton ordeni' deb ham yuritiladigan ritsarlik tashkiloti qaysi?", "v": ["Tampliyerlar", "Nemis ordeni", "Gospitalyerlar", "Maltaliklar"], "t": "Nemis ordeni"},
    {"s": "XII asrda ixtiro qilingan, ipakdan to'qiladigan shoyi so'zana yoki devor bezagi qanday ataladi?", "v": ["Miniatyura", "Panno", "Mozaika", "Gilam"], "t": "Panno"},
    {"s": "Fransuzcha 'gapirmoq' (parle) so'zidan olingan, davlat boshqaruvidagi vakillik organi qaysi?", "v": ["Senat", "Parlament", "Kongress", "Diktatura"], "t": "Parlament"},
    {"s": "Hindistonda ro'jalar tomonidan amaldorlarga yoki xizmat ko'rsatgan kishilarga vaqtincha foydalanishga berilgan yer qanday atalgan?", "v": ["Suyurg'ol", "Patta", "Benefitsiy", "Domen"], "t": "Patta"},
    {"s": "Asteklarda qo'llanilgan, rasmlar ketma-ketligi orqali ma'lumotni ifodalaydigan yozuv turi qaysi?", "v": ["Mixxat", "Piktografik yozuv", "Alifbo", "Kipu"], "t": "Piktografik yozuv"},
    {"s": "Muhammad (s.a.v.)ga 23 yil davomida vahiy qilingan, 114 suradan iborat islom muqaddas kitobini toping.", "v": ["Injil", "Qur’on", "Tavrot", "Avesto"], "t": "Qur’on"},
    {"s": "Notiqlik san'ati, she'r va badiiy asarlar yozish qoidalarini o'rgatuvchi fan qanday ataladi?", "v": ["Ritorika", "Grammatika", "Dialektika", "Geometriya"], "t": "Ritorika"},
    {"s": "Ulkan devorlar, gumbazlar va arkali kichik derazalari bilan ajralib turadigan o'rta asrlar me'morchilik uslubi qaysi?", "v": ["Gotika", "Roman uslubi", "Barokko", "Uyg'onish davri"], "t": "Roman uslubi"},
    {"s": "G'arbiy Yevropada X-XIII asrlarda hukm surgan va Qadimgi Rim me'morchiligi unsurlaridan foydalangan uslubni ko'rsating.", "v": ["Klassitsizm", "Roman uslubi", "Gotika", "Modern"], "t": "Roman uslubi"},
    {"s": "O'rta asrlarda o'z ixtiyorida qaram dehqonlar va vassallari bo'lgan yirik yer egasi kim?", "v": ["Ritsar", "Senyor", "Kolon", "Merosxor"], "t": "Senyor"},
    {"s": "O'rta asr shaharlarida bir xil kasb egalarining (hunarmandlarning) uyushmasi qanday atalgan?", "v": ["Faktoriya", "Sex", "Birja", "Korporatsiya"], "t": "Sex"},
    {"s": "Angliyada grafliklarda qirol vakili sifatida soliq yig'ish va tartibni saqlashga mas'ul bo'lgan shaxs kim?", "v": ["Graf", "Sherif", "Baron", "Lord"], "t": "Sherif"},
    {"s": "Boltiq dengizi orqali London, Bryugge va Novgorod kabi shaharlarni bog'lagan savdo yo'li qanday nomlangan?", "v": ["Shimoliy savdo yo'li", "Levant savdo yo'li", "Buyuk Ipak yo'li", "Transsaxara yo'li"], "t": "Shimoliy savdo yo'li"},
    {"s": "O'rta asr universitetlarida tahsil oluvchi talabalar qanday nomlangan?", "v": ["Magistrlar", "Shkolyarlar", "Dotsentlar", "Bakalavrlar"], "t": "Shkolyarlar"},
    {"s": "Yovuz va ezgu ruhlarga, ularning inson hayotiga ta'siriga ishonishga asoslangan qadimiy e'tiqod qaysi?", "v": ["Islom", "Shomonlik", "Buddaviylik", "Xristianlik"], "t": "Shomonlik"},
    {"s": "Yahudiylar ibodat qiladigan muqaddas bino qanday ataladi?", "v": ["Cherkov", "Sinagoga", "Masjid", "Pagoda"], "t": "Sinagoga"},
    {"s": "Mo'g'ulcha 'in'om' ma'nosini anglatuvchi, nasldan-naslga o'tadigan harbiy-suyurg'ol yer-mulki qanday nomlanadi?", "v": ["Iqto", "Suyurg‘ol", "Allod", "Grass"], "t": "Suyurg‘ol"},
    {"s": "Yaponiyada vujudga kelgan xususiy yer egalari mulklari qanday atalgan?", "v": ["Mikado", "Syoyenlar", "Xanke", "Daimyo"], "t": "Syoyenlar"},
    {"s": "Mo'g'ullar tomonidan aholidan yig'ib olinadigan shoshilinch soliq turi qaysi?", "v": ["Chiqim", "Talab", "Boj", "Tamg'a"], "t": "Talab"},
    {"s": "Quddusdagi ma'bad (tepalik) nomi bilan atalgan, ziyoratchilarni himoya qiluvchi ritsarlik ordeni qaysi?", "v": ["Gospitalyerlar", "Tampliyerlar", "Tevtonlar", "Maltaliklar"], "t": "Tampliyerlar"},
    {"s": "Asteklarda lashkarboshi, oliy hukmdor va bosh kohin vazifasini bajargan shaxs kim?", "v": ["Mikado", "Tlatoani", "Shogun", "Konung"], "t": "Tlatoani"},
    {"s": "Mahsulotlarni shaxsiy iste'mol uchun emas, balki bozorda sotish uchun ishlab chiqaradigan xo'jalik qanday ataladi?", "v": ["Natural xo'jalik", "Tovar xo'jaligi", "Ibtidoiy xo'jalik", "Yordamchi xo'jalik"], "t": "Tovar xo'jaligi"},
    {"s": "Erkin franklarning yuzlik yig‘inlarida boshliq (yuzboshi) bo'lgan shaxs qanday nomlangan?", "v": ["Sherif", "Tungin", "Graf", "Baron"], "t": "Tungin"},
    {"s": "Chingizxon farzandlariga mulk sifatida bo‘lib bergan, mo‘g‘ullar bosib olgan katta hududlar nima deb ataladi?", "v": ["Viloyat", "Ulus", "Marka", "Graflik"], "t": "Ulus"},
    {"s": "Lotincha 'umumiylik' ma'nosini anglatuvchi, turli yo‘nalishlarda mutaxassislar tayyorlaydigan oliy o‘quv yurti qaysi?", "v": ["Kollegiya", "Universitet", "Akademiya", "Gimnaziya"], "t": "Universitet"},
    {"s": "G'arbiy Yevropada bir feodalning ikkinchisiga bo'ysunish va xizmat qilish tizimi qanday ataladi?", "v": ["Kommuna", "Vassallik", "Immunitet", "Mayorat"], "t": "Vassallik"},
    {"s": "Har bir viloyatning ishlab chiqarishning ma'lum bir sohasiga ixtisoslashuvi nima deb ataladi?", "v": ["Tovar xo'jaligi", "Viloyatlar o‘rtasidagi mehnat taqsimoti", "Markazlashgan davlat", "Bozor iqtisodiyoti"], "t": "Viloyatlar o‘rtasidagi mehnat taqsimoti"},
    {"s": "Yaponiyada eng nufuzli yirik yer egalari tabaqasi qanday nomlangan?", "v": ["Ryoka", "Xanke", "Samuray", "Mikado"], "t": "Xanke"},
    {"s": "Davlat ixtiyoridagi yerlar bo'lib, undan tushgan daromad maxsus qo'shin ta'minotiga sarflangan yer turi qaysi?", "v": ["Suyurg'ol", "Xolisa", "Allod", "Patta"], "t": "Xolisa"},
    {"s": "Ma'lum bir vaqtda turli mamlakat savdogarlari yig'iladigan yirik ulgurji savdo joyi qanday atalgan?", "v": ["Birja", "Yarmarka", "Bozor", "Faktoriya"], "t": "Yarmarka"},
    {"s": "Yunoncha 'dahriylar' ma'nosini anglatuvchi, cherkov ta'limotiga qarshi chiqqan kishilar kimlar?", "v": ["Vassallar", "Yeretiklar", "Kohinlar", "Shkolyarlar"], "t": "Yeretiklar"},
    {"s": "VIII asr oxiri – XI asr o‘rtalarida Skandinaviyada yashagan, dengiz orqali savdo va bosqinchilik yurishlari qilgan qabilalar qanday nomlangan?", "v": ["Franklar", "Vikinglar", "Gotlar", "Slavyanlar"], "t": "Vikinglar"},
    {"s": "Forscha 'to‘rt do‘st' ma’nosini anglatuvchi, islom tarixidagi dastlabki to‘rt xalifaga nisbatan qanday atama ishlatiladi?", "v": ["Muhojirlar", "Choryorlar", "Ansorlar", "Badaviylar"], "t": "Choryorlar"},
    {"s": "Xitoyda qo‘llaniladigan, taxminan 6 sotixga teng bo‘lgan yer maydoni o‘lchov birligini toping.", "v": ["Mino", "Mu", "Tirsak", "Shekel"], "t": "Mu"},
    {"s": "Xristianlikning asosiy timsoli bo‘lgan, IV asrda rasmiy sig‘inish buyumiga aylangan atama qaysi?", "v": ["Xoch", "Ikona", "Bazilika", "Kapella"], "t": "Xoch"},
    {"s": "Nemischa 'saylangan harbiy yo‘lboshchi', keyinchalik esa merosiy qabila boshlig‘i unvoni qanday atalgan?", "v": ["Graf", "Gersog", "Baron", "Vassal"], "t": "Gersog"},
    {"s": "Franklar davlatida qirol tomonidan tayinlangan, ma'muriy va harbiy ishlarni boshqaruvchi amaldor kim?", "v": ["Sherif", "Graf", "Voliy", "Markgraf"], "t": "Graf"},
    {"s": "Daniya qonunlari amal qiladigan Angliya hududlari tarixda qanday nom bilan atalgan?", "v": ["Burg", "Denlo", "Marka", "Ulus"], "t": "Denlo"},
    {"s": "O'rta asrlarda shaharlarda joylashgan, mustahkam himoyalangan qal'a qanday nomlanadi?", "v": ["Rabod", "Burg", "Ratusha", "Faktoriya"], "t": "Burg"},
    {"s": "O'rta asrlarda qo'lyozma kitoblar ko'chiriladigan va bezatiladigan maxsus ustaxona qaysi?", "v": ["Kollegiya", "Skriptoriya", "Birja", "Maktab"], "t": "Skriptoriya"},
    {"s": "Vizantiya imperiyasida zarb etilgan, xalqaro savdoda ishlatilgan oltin tanga nomini ko'rsating.", "v": ["Dinor", "Numisma", "Dirham", "Florin"], "t": "Numisma"},
    {"s": "Yunoncha 'podsho' ma'nosini anglatuvchi, Vizantiya hukmdorlari yuritgan unvon qaysi?", "v": ["Imperator", "Vasilevs", "Mikado", "Tlatoani"], "t": "Vasilevs"},
    {"s": "Qadimgi slavyan tilida 'tushunarli, bir xil tilda so'zlashuvchilar' ma'nosini anglatuvchi xalq nomi qaysi?", "v": ["Poloveslar", "Slavyanlar (slovenlar)", "Varyaglar", "Franklar"], "t": "Slavyanlar (slovenlar)"},
    {"s": "Qadimgi rus manbalarida qipchoq qabilalari qanday nom bilan atalgan?", "v": ["Vikinglar", "Poloveslar", "Varyaglar", "Skiflar"], "t": "Poloveslar"},
    {"s": "Xitoycha 'Uzun devor' ma'nosini bildiruvchi, ko'chmanchilardan himoyalanish uchun qurilgan mahobatli inshoot qanday ataladi?", "v": ["Jonka", "Changcheng", "Pagoda", "Zij"], "t": "Changcheng"},
    {"s": "Cho'l va sahrolarda ko'chmanchi hayot kechiruvchi arab qabilalari qanday nomlangan?", "v": ["Muhojirlar", "Badaviylar", "Ansorlar", "Xavorijlar"], "t": "Badaviylar"},
    {"s": "Islom tarixida Makka shahridan Madinaga ko‘chib o‘tgan musulmonlar qanday nomlangan?", "v": ["Ansorlar", "Muhojirlar", "Choryorlar", "Muslimlar"], "t": "Muhojirlar"},
    {"s": "Madinada muhojirlarga yordam bergan va islomni qo'llab-quvvatlagan 'tarafdorlar' kim deb ataladi?", "v": ["Badaviylar", "Ansorlar", "Choryorlar", "Xalifalar"], "t": "Ansorlar"},
    {"s": "Islomda 'to'g'ri yo'ldan boruvchi xalifalar' guruhi qanday nomlangan?", "v": ["Choryorlar", "Xilafoyi roshidinlar", "Voliylar", "Muhojirlar"], "t": "Xilafoyi roshidinlar"},
    {"s": "Shariat bo‘yicha zakot berish shart bo‘lgan boylikning eng kam miqdori qanday ataladi?", "v": ["Xiroj", "Moli nisob", "Ushr", "Talab"], "t": "Moli nisob"},
    {"s": "Islom dinida paydo bo'lgan turli diniy-huquqiy yo'nalishlar, oqimlar nima deb ataladi?", "v": ["Firqa", "Mazhab", "Sekta", "Ulus"], "t": "Mazhab"},
    {"s": "Islomda 'ajralib chiqqanlar' ma'nosini anglatuvchi ilk siyosiy va diniy guruh qaysi?", "v": ["Ansorlar", "Xavorijlar", "Badaviylar", "Muhojirlar"], "t": "Xavorijlar"},
    {"s": "Xalifalik davrida viloyatlarni boshqarish uchun tayinlangan hokim unvoni qanday bo'lgan?", "v": ["Graf", "Voliy", "Sherif", "Beklarbegi"], "t": "Voliy"},
    {"s": "Chingizxon ismiga qo'shilgan 'Chingiz' so'zi qanday ma'noni anglatadi?", "v": ["Podsho", "Kuchli, qudratli, toza", "Lashkarboshi", "Buyuk hukmdor"], "t": "Kuchli, qudratli, toza"},
    {"s": "Qamal paytida qal'a devorlarini teshish yoki buzish uchun ishlatiladigan maxsus moslama qanday atalgan?", "v": ["Katapulta", "Palaxmon", "Triyera", "Akinak"], "t": "Palaxmon"},
    {"s": "Hind tabaqalanish tizimida 'jangchilar' tabaqasi qanday nomlangan?", "v": ["Brahmanlar", "Kshatriylar", "Vayshilar", "Rajputlar"], "t": "Kshatriylar"},
    {"s": "Yaponcha 'Kunchiqar mamlakat' ma'nosini anglatuvchi davlat nomini toping.", "v": ["Choson", "Nippon", "Syoyen", "Xanke"], "t": "Nippon"},
    {"s": "Yunoncha 'shohona bino' ma'nosini bildiruvchi, G'arbiy Yevropada keng tarqalgan ibodatxona turi qaysi?", "v": ["Ratusha", "Bazilika", "Kapella", "Burg"], "t": "Bazilika"},
    {"s": "Katolik cherkovida ruhoniylarning uylanishini taqiqlash tartibi qanday nomlanadi?", "v": ["Interdikt", "Selebat", "Autodafe", "Indulgensiya"], "t": "Selebat"},
    {"s": "O'rta asr shaharlarida shahar kengashi (meriya) joylashgan ma'muriy bino qanday ataladi?", "v": ["Rabod", "Ratusha", "Ark", "Faktoriya"], "t": "Ratusha"},
    {"s": "Sharq shaharlarida hokim yoki hukmdor saroyi joylashgan markaziy qal'a qanday nomlanadi?", "v": ["Rabod", "Ark", "Shahriston", "Burg"], "t": "Ark"},
    {"s": "Sharq shaharlarida hunarmandlar va savdogarlar yashaydigan shahar tashqarisidagi mahallalar qanday atalgan?", "v": ["Ark", "Shahriston", "Rabod", "Faktoriya"], "t": "Rabod"},
    {"s": "Xitoyliklarning 600-700 kishi sig'adigan, okean safarlariga mo'ljallangan yirik kemalari qanday nomlanadi?", "v": ["Karavella", "Jonka", "Triyera", "Argo"], "t": "Jonka"},
    {"s": "Katoliklarning xususiy yoki kichik ibodatxonasi qanday ataladi?", "v": ["Bazilika", "Kapella", "Sinagoga", "Masjid"], "t": "Kapella"},
    {"s": "Yog'ochga ishlangan Iso payg'ambar, Bibi Maryam yoki avliyolarning muqaddas tasvirlari nima deb ataladi?", "v": ["Freska", "Ikona", "Mozaika", "Miniatyura"], "t": "Ikona"},
    {"s": "Universitetlarda dars beruvchi, yuqori ilmiy malakaga ega bo'lgan o'qituvchi qanday unvon bilan ataladi?", "v": ["Shkolyar", "Professor", "Magistr", "Rektor"], "t": "Professor"},
    {"s": "Astronomik kuzatishlar asosida sayyoralar harakati jadvali ko'rsatilgan ilmiy asar qanday ataladi?", "v": ["Panno", "Zij", "Xarita", "Stil"], "t": "Zij"}
]