# data_6.py

xronologiya_6 = [
    {"s": "Ilk paleolit davri qaysi yillarni o‘z ichiga oladi?", "v": ["Mil.avv. 1 mln - 100 ming yillik", "Mil.avv. 100 - 40 ming yillik", "Mil.avv. 40 - 12 ming yillik", "Mil.avv. 12 - 7 ming yillik"], "t": "Mil.avv. 1 mln - 100 ming yillik"},
    {"s": "O‘rta paleolit davri qachon bo‘lgan?", "v": ["Mil.avv. 1 mln - 100 ming yillik", "Mil.avv. 100 - 40 ming yillik", "Mil.avv. 40 - 12 ming yillik", "Mil.avv. 12 - 7 ming yillik"], "t": "Mil.avv. 100 - 40 ming yillik"},
    {"s": "So‘nggi paleolit davrini aniqlang:", "v": ["Mil.avv. 100 - 40 ming yillik", "Mil.avv. 40 - 12 ming yillik", "Mil.avv. 12 - 7 ming yillik", "Mil.avv. 6 - 4 ming yillik"], "t": "Mil.avv. 40 - 12 ming yillik"},
    {"s": "Mezolit davri qaysi yillarga to‘g‘ri keladi?", "v": ["Mil.avv. 40 - 12 ming yillik", "Mil.avv. 12 - 7 ming yillik", "Mil.avv. 6 - 4 ming yillik", "Mil.avv. 4 - 3 ming yillik"], "t": "Mil.avv. 12 - 7 ming yillik"},
    {"s": "Neolit davri qachon bo‘lgan?", "v": ["Mil.avv. 12 - 7 ming yillik", "Mil.avv. 6 - 4 ming yillik", "Mil.avv. 4 - 3 ming yillik", "Mil.avv. 2 - 1 ming yillik"], "t": "Mil.avv. 6 - 4 ming yillik"},
    {"s": "Qadimgi Sharqda ilk shaharlar va davlatlar qachon vujudga keldi?", "v": ["Mil.avv. 5-mingyillik", "Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "O'rta Osiyo janubida sug'orma dehqonchilik qachon vujudga keldi?", "v": ["Mil.avv. 6-mingyillik", "Mil.avv. 5-mingyillik", "Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Xom g‘ishtdan ko‘p xonali uylar qurila boshlangan davr:", "v": ["Mil.avv. 5-mingyillik", "Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Kulolchilik xumdonlaridan foydalanish qachon boshlangan?", "v": ["Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Sopol idishlarni hayvonlar va o'simlik naqshlari bilan bezash qachon rasm bo'ldi?", "v": ["Mil.avv. 5-mingyillik", "Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Mesopotamiyada shumerlar manzilgohlari paydo bo‘la boshlagan davr:", "v": ["Mil.avv. 5-mingyillik", "Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Shumerlar mixxatni qachon ixtiro qilishgan?", "v": ["Mil.avv. 5-mingyillik", "Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Odamlar Nil daryosi qirg‘oqlarini o‘zlashtira boshlagan vaqt:", "v": ["Mil.avv. 4-mingyillik boshlari", "Mil.avv. 4-mingyillik oxiri", "Mil.avv. 3-mingyillik boshlari", "Mil.avv. 5-mingyillik"], "t": "Mil.avv. 4-mingyillik boshlari"},
    {"s": "Nil vodiysida sermashaqqat turmushga moslashish qachon kuzatildi?", "v": ["Mil.avv. 4-mingyillik boshida", "Mil.avv. 4-mingyillik oxirida", "Mil.avv. 3-mingyillikda", "Mil.avv. 2-mingyillikda"], "t": "Mil.avv. 4-mingyillik oxirida"},
    {"s": "Uruk, Umma, Lagash, Ur shaharlari qachon vujudga keldi?", "v": ["Mil.avv. 4-mingyillik boshida", "Mil.avv. 4-mingyillik oxirida", "Mil.avv. 3-mingyillikda", "Mil.avv. 2-mingyillikda"], "t": "Mil.avv. 4-mingyillik oxirida"},
    {"s": "Eneolit davri qaysi yillarni o‘z ichiga oladi?", "v": ["Mil.avv. 4-3 mingyillik boshlari", "Mil.avv. 4-3 mingyillik o‘rtalari", "Mil.avv. 3-2 mingyillik", "Mil.avv. 5-4 mingyillik"], "t": "Mil.avv. 4-3 mingyillik o‘rtalari"},
    {"s": "Menes tomonidan Misr qachon birlashtirildi?", "v": ["Mil.avv. 3100-yil", "Mil.avv. 3000-yil", "Mil.avv. 2900-yil", "Mil.avv. 2600-yil"], "t": "Mil.avv. 3000-yil"},
    {"s": "Elam davlati qachon paydo bo‘ldi?", "v": ["Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik"], "t": "Mil.avv. 3-mingyillik"},
    {"s": "Mohenjarodo va Xarappa shaharlari qachon vujudga keldi?", "v": ["Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik"], "t": "Mil.avv. 3-mingyillik"},
    {"s": "Chjou qabilasi Xitoydagi Shan davlatiga qachon bostirib kiradi?", "v": ["Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik"], "t": "Mil.avv. 3-mingyillik"},
    {"s": "Bronza mehnat qurollari uchun asosiy ashyoga aylangan davr:", "v": ["Mil.avv. 4 - 3 mingyillik", "Mil.avv. 3-mingyillik o‘rtalari - 2-mingyillik", "Mil.avv. 2 - 1 mingyillik", "Mil.avv. 1-mingyillik"], "t": "Mil.avv. 3-mingyillik o‘rtalari - 2-mingyillik"},
    {"s": "Sargon I Akkad va Shumerni qachon birlashtirdi?", "v": ["Mil.avv. 3-mingyillik 1-yarmi", "Mil.avv. 3-mingyillik 2-yarmi", "Mil.avv. 2-mingyillik boshida", "Mil.avv. 4-mingyillik oxirida"], "t": "Mil.avv. 3-mingyillik 2-yarmi"},
    {"s": "Xuanxe daryosi o‘rta oqimida ilk davlat qachon paydo bo‘ldi?", "v": ["Mil.avv. 4-mingyillik oxiri", "Mil.avv. 3-mingyillik oxiri", "Mil.avv. 2-mingyillik o‘rtasi", "Mil.avv. 1-mingyillik"], "t": "Mil.avv. 3-mingyillik oxiri"},
    {"s": "Sopollitepa va Jarqo‘ton manzilgohlari qachon tashkil topdi?", "v": ["Mil.avv. 4-3 mingyillik", "Mil.avv. 3-mingyillik oxiri - 2-mingyillik", "Mil.avv. 2-1 mingyillik", "Mil.avv. VII-VI asrlar"], "t": "Mil.avv. 3-mingyillik oxiri - 2-mingyillik"},
    {"s": "Xitoyda ilk sivilizatsiyalar vujudga kelgan davr:", "v": ["Mil.avv. 4-3 mingyillik", "Mil.avv. 3-mingyillik oxiri - 2-mingyillik", "Mil.avv. II-I mingyillik", "Mil.avv. VIII asr"], "t": "Mil.avv. 3-mingyillik oxiri - 2-mingyillik"},
    {"s": "Xufu (Xeops) piramidasi qachon qurilgan?", "v": ["Mil.avv. 3000-yil", "Mil.avv. 2600-yil", "Mil.avv. 2100-yil", "Mil.avv. 1800-yil"], "t": "Mil.avv. 2600-yil"},
    {"s": "Ilonlar tasviri tushirilgan tosh tumor qaysi davrga oid?", "v": ["Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. IV asr"], "t": "Mil.avv. 2-mingyillik"},
    {"s": "Bobil podsholigi qachon tashkil topdi?", "v": ["Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. XVIII asr"], "t": "Mil.avv. 2-mingyillik"},
    {"s": "Old Osiyo hududida ilk davlatlar qachon paydo bo'la boshladi?", "v": ["Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. VIII asr"], "t": "Mil.avv. 2-mingyillik"},
    {"s": "Yunonistonda ilk shahar-davlatlar qachon vujudga keldi?", "v": ["Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. VIII asr"], "t": "Mil.avv. 2-mingyillik"},
    {"s": "Janubiy Yunoniston va Kritda sivilizatsiya vujudga kelgan vaqt:", "v": ["Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. XII asr"], "t": "Mil.avv. 2-mingyillik"},
    {"s": "Attikaning g'arbiy qismida Akropol qachon qurilgan?", "v": ["Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. V asr"], "t": "Mil.avv. 2-mingyillik"},
    {"s": "Xammurapi butun Mesopotamiyani qachon yagona davlatga birlashtirdi?", "v": ["Mil.avv. XIX asr", "Mil.avv. XVIII asr", "Mil.avv. XVII asr", "Mil.avv. XVI asr"], "t": "Mil.avv. XVIII asr"},
    {"s": "Hind daryosi manzilgohlari qachon zavolga yuz tutdi?", "v": ["Mil.avv. XIX asr", "Mil.avv. XVIII asr", "Mil.avv. XVII asr", "Mil.avv. XVI asr"], "t": "Mil.avv. XVIII asr"},
    {"s": "Giksoslar Misrga qachon hujum qilishdi?", "v": ["Mil.avv. XVIII asr boshida", "Mil.avv. XVIII asr oxirida", "Mil.avv. XVII asr boshida", "Mil.avv. XVI asrda"], "t": "Mil.avv. XVIII asr oxirida"},
    {"s": "Xettlar qachon birinchi marta temirdan foydalana boshladi?", "v": ["Mil.avv. XVIII-XVII asrlar", "Mil.avv. XIV-XIII asrlar", "Mil.avv. XII-XI asrlar", "Mil.avv. X asr"], "t": "Mil.avv. XIV-XIII asrlar"},
    {"s": "Doriylar Lakonika hududiga bostirib kirib, Spartaga asos solgan davr:", "v": ["Mil.avv. XIV asr", "Mil.avv. XIII asr", "Mil.avv. XII asr", "Mil.avv. XI asr"], "t": "Mil.avv. XII asr"},
    {"s": "Yunonlar Troyaga qarshi urushni qachon boshlagan?", "v": ["Mil.avv. 1300-yil", "Mil.avv. 1200-yil", "Mil.avv. 1100-yil", "Mil.avv. 1000-yil"], "t": "Mil.avv. 1200-yil"},
    {"s": "Isroil podsholigi qachon tuzildi?", "v": ["Mil.avv. XII asr", "Mil.avv. XI asr", "Mil.avv. X asr", "Mil.avv. IX asr"], "t": "Mil.avv. XI asr"},
    {"s": "Temirdan ishlangan xanjar va qin qaysi davrga oid?", "v": ["Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. 1-asr", "Milodiy 1-mingyillik"], "t": "Mil.avv. 1-mingyillik"},
    {"s": "Zardushtiylik dini O'rta Osiyoda qachon keng tarqalgan?", "v": ["Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik", "Mil.avv. 5-asr", "Milodiy 1-asr"], "t": "Mil.avv. 1-mingyillik"},
    {"s": "Zardusht qachon yashab o'tgan?", "v": ["Mil.avv. 2-mingyillikda", "Mil.avv. 1-mingyillikning 1-yarmida", "Mil.avv. 1-mingyillikning 2-yarmida", "Milodiy 1-asrda"], "t": "Mil.avv. 1-mingyillikning 1-yarmida"},
    {"s": "Finikiyada 22 ta undoshdan iborat alifbo qachon yaratildi?", "v": ["Mil.avv. XII asr", "Mil.avv. XI asr", "Mil.avv. X asr", "Mil.avv. IX asr"], "t": "Mil.avv. X asr"},
    {"s": "Surxondaryodan topilgan \"Kohin boshi\" haykalchasi qaysi davrga oid?", "v": ["Mil.avv. X-IX asrlar", "Mil.avv. VIII-VII asrlar", "Mil.avv. VI-V asrlar", "Mil.avv. IV asr"], "t": "Mil.avv. X-IX asrlar"},
    {"s": "O'rta Osiyodan topilgan eng qadimgi temir buyumlar qaysi davrga tegishli?", "v": ["Mil.avv. XI-X asrlar", "Mil.avv. IX-VIII asrlar", "Mil.avv. VII-VI asrlar", "Mil.avv. V asr"], "t": "Mil.avv. IX-VIII asrlar"},
    {"s": "Urartu davlati qachon gullab-yashnadi?", "v": ["Mil.avv. X asr", "Mil.avv. IX-VIII asr boshlari", "Mil.avv. VII asr", "Mil.avv. VI asr"], "t": "Mil.avv. IX-VIII asr boshlari"},
    {"s": "Etrusklar Italiyada 12 ta shahar-davlatni qachon tuzdi?", "v": ["Mil.avv. IX asr", "Mil.avv. VIII asr", "Mil.avv. VII asr", "Mil.avv. VI asr"], "t": "Mil.avv. VIII asr"},
    {"s": "Birinchi Olimpiya o‘yinlari qachon o‘tkazilgan?", "v": ["Mil.avv. 753-yil", "Mil.avv. 776-yil", "Mil.avv. 700-yil", "Mil.avv. 621-yil"], "t": "Mil.avv. 776-yil"},
    {"s": "Rim shahriga qachon asos solindi?", "v": ["Mil.avv. 776-yil", "Mil.avv. 753-yil", "Mil.avv. 509-yil", "Mil.avv. 395-yil"], "t": "Mil.avv. 753-yil"},
    {"s": "Chjou davlati zaiflasha boshlagan vaqt:", "v": ["Mil.avv. IX-VIII asrlar", "Mil.avv. VIII-VII asrlar", "Mil.avv. VI-V asrlar", "Mil.avv. IV asr"], "t": "Mil.avv. VIII-VII asrlar"},
    {"s": "Buyuk yunon koloniyalashtirish davri qachon bo‘lgan?", "v": ["Mil.avv. X-VIII asrlar", "Mil.avv. VIII-VI (VII) asrlar", "Mil.avv. VI-IV asrlar", "Mil.avv. IV-II asrlar"], "t": "Mil.avv. VIII-VI (VII) asrlar"},
    {"s": "Olviya, Xersones va Pantikapey koloniyalari qachon vujudga keldi?", "v": ["Mil.avv. IX-VII asrlar", "Mil.avv. VIII-VI asrlar", "Mil.avv. V-IV asrlar", "Mil.avv. III asr"], "t": "Mil.avv. VIII-VI asrlar"},
    {"s": "Misr yana qachon yagona davlatga birlashdi?", "v": ["Mil.avv. IX asr", "Mil.avv. VIII asr", "Mil.avv. VII asr", "Mil.avv. VI asr"], "t": "Mil.avv. VII asr"},
    {"s": "Yangi Bobil podsholigi qachon paydo bo‘ldi?", "v": ["Mil.avv. VIII asr", "Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V asr"], "t": "Mil.avv. VII asr"},
    {"s": "Podsho Kiaksar davrida Midiya qachon gullab-yashnadi?", "v": ["Mil.avv. VIII asr", "Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V asr"], "t": "Mil.avv. VII asr"},
    {"s": "Qadimgi Baqtriya davlati qachon tashkil topdi?", "v": ["Mil.avv. VIII asr", "Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V asr"], "t": "Mil.avv. VII asr"},
    {"s": "O'zbekiston hududida qadimgi shaharlar qachon rivojlangan?", "v": ["Mil.avv. IX-VIII asrlar", "Mil.avv. VII-VI asrlar", "Mil.avv. V-IV asrlar", "Mil.avv. III-II asrlar"], "t": "Mil.avv. VII-VI asrlar"},
    {"s": "Qiziltepa, Afrosiyob, Uzunqir shaharlari qaysi davrda rivojlandi?", "v": ["Mil.avv. VIII-VII asrlar", "Mil.avv. VII-VI asrlar", "Mil.avv. V-IV asrlar", "Mil.avv. III asr"], "t": "Mil.avv. VII-VI asrlar"},
    {"s": "Xitoy tarixida \"Ko‘p podsholik\" davri qaysi asrlarni o‘z ichiga oladi?", "v": ["Mil.avv. VIII-VI asrlar", "Mil.avv. VII-V asrlar", "Mil.avv. V-III asrlar", "Mil.avv. III-I asrlar"], "t": "Mil.avv. VII-V asrlar"},
    {"s": "Drakont qonunlari qachon tuzildi?", "v": ["Mil.avv. 753-yil", "Mil.avv. 621-yil", "Mil.avv. 594-yil", "Mil.avv. 509-yil"], "t": "Mil.avv. 621-yil"},
    {"s": "Ossuriya davlati qachon tugatib yuborildi?", "v": ["Mil.avv. 700-yil", "Mil.avv. 605-yil", "Mil.avv. 539-yil", "Mil.avv. 330-yil"], "t": "Mil.avv. 605-yil"},
    {"s": "Eronda Fors podsholigi qachon paydo bo‘ldi?", "v": ["Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V asr", "Mil.avv. IV asr"], "t": "Mil.avv. VI asr"},
    {"s": "Hindistonda Buddizm dini qachon paydo bo‘ldi?", "v": ["Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V asr", "Mil.avv. IV asr"], "t": "Mil.avv. VI asr"},
    {"s": "Rim davlati qachondan Respublika deb yuritila boshlandi?", "v": ["Mil.avv. VI asr oxiri", "Mil.avv. V asr boshida", "Mil.avv. IV asr o'rtasida", "Mil.avv. III asrda"], "t": "Mil.avv. VI asr oxiri"},
    {"s": "Solon qachon Afina hokimi bo‘ldi?", "v": ["Mil.avv. 621-yil", "Mil.avv. 594-yil", "Mil.avv. 509-yil", "Mil.avv. 443-yil"], "t": "Mil.avv. 594-yil"},
    {"s": "Kir II barcha forslarni qaysi yilda birlashtirdi?", "v": ["Mil.avv. 558-yil", "Mil.avv. 539-yil", "Mil.avv. 530-yil", "Mil.avv. 525-yil"], "t": "Mil.avv. 558-yil"},
    {"s": "Forslar Bobilni qachon bosib oldi?", "v": ["Mil.avv. 558-yil", "Mil.avv. 539-yil", "Mil.avv. 530-yil", "Mil.avv. 525-yil"], "t": "Mil.avv. 539-yil"},
    {"s": "Kir II massagetlar ustiga qaysi yilda yurish qildi?", "v": ["Mil.avv. 539-yil", "Mil.avv. 530-yil", "Mil.avv. 525-yil", "Mil.avv. 519-yil"], "t": "Mil.avv. 530-yil"},
    {"s": "Kambiz II Misrni qachon bosib oldi?", "v": ["Mil.avv. 530-yil", "Mil.avv. 525-yil", "Mil.avv. 522-yil", "Mil.avv. 519-yil"], "t": "Mil.avv. 525-yil"},
    {"s": "Doro I ning hukmronlik yillarini aniqlang:", "v": ["Mil.avv. 530-522 yillar", "Mil.avv. 522-486 yillar", "Mil.avv. 486-465 yillar", "Mil.avv. 336-323 yillar"], "t": "Mil.avv. 522-486 yillar"},
    {"s": "Rim Respublikasiga qachon asos solindi?", "v": ["Mil.avv. 753-yil", "Mil.avv. 594-yil", "Mil.avv. 509-yil", "Mil.avv. 49-yil"], "t": "Mil.avv. 509-yil"},
    {"s": "Xitoyda bambuk o‘rniga shoyiga yozishga o‘tish qachon yuz berdi?", "v": ["Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V asr", "Mil.avv. IV asr"], "t": "Mil.avv. V asr"},
    {"s": "Marafon jangi qachon bo‘lgan?", "v": ["Mil.avv. 490-yil", "Mil.avv. 480-yil", "Mil.avv. 479-yil", "Mil.avv. 338-yil"], "t": "Mil.avv. 490-yil"},
    {"s": "Salamin va Fermopol janglari qaysi yilda bo‘ldi?", "v": ["Mil.avv. 490-yil", "Mil.avv. 480-yil", "Mil.avv. 479-yil", "Mil.avv. 443-yil"], "t": "Mil.avv. 480-yil"},
    {"s": "Perikl necha marta strateg bo‘lib saylandi?", "v": ["Mil.avv. 443-429 yillarda 10 marta", "Mil.avv. 443-429 yillarda 15 marta", "Mil.avv. 460-440 yillarda 12 marta", "Mil.avv. 490-480 yillarda 5 marta"], "t": "Mil.avv. 443-429 yillarda 15 marta"},
    {"s": "Aleksandr Makedonskiy qachon taxtga o‘tirdi?", "v": ["Mil.avv. 338-yil", "Mil.avv. 336-yil", "Mil.avv. 334-yil", "Mil.avv. 330-yil"], "t": "Mil.avv. 336-yil"},
    {"s": "Aleksandr Fors davlatini qachon butunlay bosib oldi?", "v": ["Mil.avv. 334-yil", "Mil.avv. 330-yil", "Mil.avv. 329-yil", "Mil.avv. 323-yil"], "t": "Mil.avv. 330-yil"},
    {"s": "Aleksandr va Spitamen o‘rtasidagi hal qiluvchi jang qachon bo‘ldi?", "v": ["Mil.avv. 329-yil bahori", "Mil.avv. 328-yil kuzi", "Mil.avv. 327-yil qishi", "Mil.avv. 323-yil"], "t": "Mil.avv. 328-yil kuzi"},
    {"s": "Salavk qachon Bobil (Suriya) hukmdori bo‘ldi?", "v": ["Mil.avv. 323-yil", "Mil.avv. 312-yil", "Mil.avv. 280-yil", "Mil.avv. 300-yil"], "t": "Mil.avv. 312-yil"},
    {"s": "Sin Shixuandi Xitoyni qaysi yilda birlashtirdi?", "v": ["Mil.avv. 300-yil", "Mil.avv. 250-yil", "Mil.avv. 246-yil", "Mil.avv. 221-yil"], "t": "Mil.avv. 246-yil"},
    {"s": "Buyuk Ipak yo‘li qaysi davrlarda mavjud bo‘lgan?", "v": ["Mil.avv. II - milodiy VI asr", "Mil.avv. II - milodiy XVI asr", "Mil.avv. I - milodiy XV asr", "Milodiy I - XIX asr"], "t": "Mil.avv. II - milodiy XVI asr"},
    {"s": "Spartak qo‘zg‘oloni qachon bo‘lgan?", "v": ["Mil.avv. 100-90 yillar", "Mil.avv. 74-71 yillar", "Mil.avv. 49-44 yillar", "Milodiy 1-asr"], "t": "Mil.avv. 74-71 yillar"},
    {"s": "Yuliy Sezar qachon o‘ldirildi?", "v": ["Mil.avv. 49-yil", "Mil.avv. 44-yil", "Mil.avv. 31-yil", "Mil.avv. 29-yil"], "t": "Mil.avv. 44-yil"},
    {"s": "Oktavian qachon \"Avgust\" laqabini oldi?", "v": ["Mil.avv. 31-yil", "Mil.avv. 29-yil", "Mil.avv. 27-yil", "Milodiy 1-yil"], "t": "Mil.avv. 29-yil"},
    {"s": "Xristianlik dini qachon shakllana boshladi?", "v": ["Mil.avv. I asr oxiri", "Milodiy I asr boshlari", "Milodiy II asrda", "Milodiy 313-yil"], "t": "Milodiy I asr boshlari"},
    {"s": "Rim imperiyasining \"Oltin asri\" deb qaysi davr ataladi?", "v": ["Milodiy I asr", "Milodiy II asr", "Milodiy III asr", "Milodiy IV asr"], "t": "Milodiy II asr"},
    {"s": "Imperator Konstantin xristianlikni qachon teng huquqli din deb e'lon qildi?", "v": ["Milodiy 300-yil", "Milodiy 313-yil", "Milodiy 330-yil", "Milodiy 395-yil"], "t": "Milodiy 313-yil"},
    {"s": "Rim imperiyasi ikki qismga qachon ajralib ketdi?", "v": ["Milodiy 330-yil", "Milodiy 395-yil", "Milodiy 410-yil", "Milodiy 476-yil"], "t": "Milodiy 395-yil"},
    {"s": "G‘arbiy Rim imperiyasi qaysi yilda butunlay quladi?", "v": ["Milodiy 455-yil", "Milodiy 452-yil", "Milodiy 476-yil", "Milodiy 395-yil"], "t": "Milodiy 476-yil"},
    {"s": "\"Oks xazinasi\" kitobi qachon yozilgan?", "v": ["1877-yil", "1880-yil", "1896-yil", "1905-yil"], "t": "1905-yil"},
    {"s": "Mil.avv. 4-mingyillikda O'rta Osiyo janubida qanday dehqonchilik vujudga keldi?", "v": ["Laliqor dehqonchilik", "Sug'orma dehqonchilik", "Tog' oldi dehqonchiligi", "Ko'chmanchi dehqonchilik"], "t": "Sug'orma dehqonchilik"},
    {"s": "Mil.avv. 4-mingyillikda uylar qanday materialdan qurila boshlangan?", "v": ["Pishiq g'ishtdan", "Xom g'ishtdan", "Toshdan", "Yog'ochdan"], "t": "Xom g'ishtdan"},
    {"s": "Sopol idishlar hayvonlar va o'simlik naqshlari bilan bezatila boshlangan davr:", "v": ["Mil.avv. 5-mingyillik", "Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Mesopotamiyada shumerlar manzilgohlari qachon paydo bo'ldi?", "v": ["Mil.avv. 4-mingyillik", "Mil.avv. 3-mingyillik", "Mil.avv. 2-mingyillik", "Mil.avv. 1-mingyillik"], "t": "Mil.avv. 4-mingyillik"},
    {"s": "Qadimgi Xitoy hududida ilk davlat qaysi daryo bo'yida paydo bo'lgan?", "v": ["Yanszi", "Xuanxe", "Hind", "Nil"], "t": "Xuanxe"},
    {"s": "Mil.avv. 3-mingyillik oxirida ilk davlat qayerda paydo bo'ldi?", "v": ["Baqtriya", "Qadimgi Xitoy", "Misr", "Bobil"], "t": "Qadimgi Xitoy"},
    {"s": "Yunonlar Troyaga qarshi yurish qilgan yilni aniqlang:", "v": ["Mil.avv. 1300-yil", "Mil.avv. 1200-yil", "Mil.avv. 1100-yil", "Mil.avv. 1000-yil"], "t": "Mil.avv. 1200-yil"},
    {"s": "Kohin boshi (tosh haykalcha) qayerdan topilgan?", "v": ["Xorazm", "Surxondaryo", "Qashqadaryo", "Farg'ona"], "t": "Surxondaryo"},
    {"s": "Tosh gurzi qaysi davrga oid topilma hisoblanadi?", "v": ["Mil.avv. X-IX asrlar", "Mil.avv. IX-VIII asrlar", "Mil.avv. VII-VI asrlar", "Mil.avv. V asr"], "t": "Mil.avv. IX-VIII asrlar"},
    {"s": "Italiyada etrusklar nechta shahar-davlat tuzgan edi?", "v": ["10 ta", "12 ta", "15 ta", "20 ta"], "t": "12 ta"},
    {"s": "Buyuk yunon koloniyalashtirish davri (asrlarda):", "v": ["Mil.avv. VIII-VI (VII) asrlar", "Mil.avv. VII-V asrlar", "Mil.avv. V-III asrlar", "Mil.avv. III-I asrlar"], "t": "Mil.avv. VIII-VI (VII) asrlar"},
    {"s": "Qadimgi Baqtriya davlati qachon tashkil topgan?", "v": ["Mil.avv. VIII asr", "Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V asr"], "t": "Mil.avv. VII asr"},
    {"s": "Qiziltepa, Afrosiyob, Uzunqir shaharlari qaysi asrlarda rivojlangan?", "v": ["Mil.avv. IX-VIII asrlar", "Mil.avv. VII-VI asrlar", "Mil.avv. V-IV asrlar", "Mil.avv. III-II asrlar"], "t": "Mil.avv. VII-VI asrlar"},
    {"s": "Sug'd, Baqtriya va Xorazm aholisining asosiy mashg'uloti nima bo'lgan?", "v": ["Chorvachilik", "Sug'orma dehqonchilik", "Hunarmandchilik", "Savdo-sotiq"], "t": "Sug'orma dehqonchilik"},
    {"s": "Mil.avv. VII-VI asrlarda O'zbekiston hududida kimlar yashagan?", "v": ["Faqat forslar", "Sug'diylar, baqtriyaliklar, xorazmliklar, saklar", "Faqat yuechjilar", "Kushonlar va turklar"], "t": "Sug'diylar, baqtriyaliklar, xorazmliklar, saklar"},
    {"s": "Qadimgi Baqtriya uy-joy qo'rg'oni (Surxondaryo) qaysi davrga oid?", "v": ["Mil.avv. X-VIII asrlar", "Mil.avv. VII-IV asrlar", "Mil.avv. III-I asrlar", "Milodiy I-II asrlar"], "t": "Mil.avv. VII-IV asrlar"},
    {"s": "Xorazmda xorazmliklar qachon katta saroy qurganlar?", "v": ["Mil.avv. VII asrda", "Mil.avv. VI asrda", "Mil.avv. V asrda", "Mil.avv. IV asrda"], "t": "Mil.avv. VI asrda"},
    {"s": "Kir II qaysi yilda forslarni birlashtirdi?", "v": ["Mil.avv. 558-yil", "Mil.avv. 539-yil", "Mil.avv. 530-yil", "Mil.avv. 525-yil"], "t": "Mil.avv. 558-yil"},
    {"s": "Frada qo'zg'oloni qachon bo'lib o'tdi?", "v": ["Mil.avv. 530-yil", "Mil.avv. 522-yil", "Mil.avv. 519-yil", "Mil.avv. 509-yil"], "t": "Mil.avv. 522-yil"},
    {"s": "Doro I saklar ustiga qachon yurish qildi?", "v": ["Mil.avv. 522-yil", "Mil.avv. 519-yil", "Mil.avv. 490-yil", "Mil.avv. 330-yil"], "t": "Mil.avv. 519-yil"},
    {"s": "Yunonistonda teatr qachon paydo bo'ldi?", "v": ["Mil.avv. VII asr (2700 yil avval)", "Mil.avv. VI asr (2600 yil avval)", "Mil.avv. V asr (2500 yil avval)", "Mil.avv. IV asr (2400 yil avval)"], "t": "Mil.avv. V asr (2500 yil avval)"},
    {"s": "O'rta Osiyo hududida dastlabki tanga pullar qachon tarqalgan?", "v": ["Mil.avv. VII-VI asrlar", "Mil.avv. V-IV asrlar", "Mil.avv. III-II asrlar", "Milodiy I-II asrlar"], "t": "Mil.avv. V-IV asrlar"},
    {"s": "Oybo'yirqala shahri qaysi davrga oid?", "v": ["Mil.avv. VII asr", "Mil.avv. VI asr", "Mil.avv. V-IV asrlar", "Mil.avv. III asr"], "t": "Mil.avv. V-IV asrlar"},
    {"s": "Marafon jangi qachon sodir bo'lgan?", "v": ["Mil.avv. 490-yil", "Mil.avv. 480-yil", "Mil.avv. 479-yil", "Mil.avv. 338-yil"], "t": "Mil.avv. 490-yil"},
    {"s": "Plateya jangi qachon bo'lgan?", "v": ["Mil.avv. 490-yil", "Mil.avv. 480-yil", "Mil.avv. 479-yil", "Mil.avv. 338-yil"], "t": "Mil.avv. 479-yil"},
    {"s": "Xorazm Ahamoniylar davlatidan qachon mustaqil bo'ldi?", "v": ["Mil.avv. VI asr", "Mil.avv. V asr", "Mil.avv. IV asr", "Mil.avv. III asr"], "t": "Mil.avv. IV asr"},
    {"s": "Buyuk Xitoy devorini qurish ishlari qachon boshlangan?", "v": ["Mil.avv. VI asr", "Mil.avv. V asr", "Mil.avv. IV asr", "Mil.avv. III asr"], "t": "Mil.avv. IV asr"},
    {"s": "Qadimgi Xorazm davlati mavjud bo'lgan davr:", "v": ["Mil.avv. VII-IV asrlar", "Mil.avv. IV - milodiy III asrlar", "Mil.avv. III-I asrlar", "Milodiy I-IV asrlar"], "t": "Mil.avv. IV - milodiy III asrlar"},
    {"s": "Beotiya jangi qachon sodir bo'ldi?", "v": ["Mil.avv. 336-yil", "Mil.avv. 334-yil", "Mil.avv. 338-yil", "Mil.avv. 330-yil"], "t": "Mil.avv. 338-yil"},
    {"s": "Filip II qachon o'ldirildi?", "v": ["Mil.avv. 338-yil", "Mil.avv. 336-yil", "Mil.avv. 334-yil", "Mil.avv. 323-yil"], "t": "Mil.avv. 336-yil"},
    {"s": "Aleksandr Makedonskiy Maroqandni qachon egalladi?", "v": ["Mil.avv. 330-yil", "Mil.avv. 329-yil", "Mil.avv. 328-yil", "Mil.avv. 327-yil"], "t": "Mil.avv. 329-yil"},
    {"s": "Aleksandr Panjobga (Hindiston) qaysi yilda hujum qildi?", "v": ["Mil.avv. 329-yil", "Mil.avv. 328-yil", "Mil.avv. 327-yil", "Mil.avv. 323-yil"], "t": "Mil.avv. 327-yil"},
    {"s": "Qo'yqirilganqala (Xorazm) qaysi asrda qurilgan?", "v": ["Mil.avv. IV asr", "Mil.avv. III asr", "Mil.avv. II asr", "Mil.avv. I asr"], "t": "Mil.avv. III asr"},
    {"s": "Xitoyda Sin davlati qachon shakllandi?", "v": ["Mil.avv. IV asr", "Mil.avv. III asr", "Mil.avv. II asr", "Mil.avv. I asr"], "t": "Mil.avv. III asr"},
    {"s": "Qadimgi Qang' davlati qaysi davrda mavjud bo'lgan?", "v": ["Mil.avv. III - milodiy III asr", "Mil.avv. IV - milodiy I asr", "Mil.avv. II - milodiy II asr", "Milodiy I-IV asrlar"], "t": "Mil.avv. III - milodiy III asr"},
    {"s": "Qadimgi Dovon davlati qaysi davrda mavjud bo'lgan?", "v": ["Mil.avv. IV-II asrlar", "Mil.avv. III - milodiy III asr", "Mil.avv. II-I asrlar", "Milodiy I-IV asrlar"], "t": "Mil.avv. III - milodiy III asr"},
    {"s": "Antiox Salavkiylar hukmdori bo'lgan yil:", "v": ["Mil.avv. 312-yil", "Mil.avv. 280-yil", "Mil.avv. 250-yil", "Mil.avv. 246-yil"], "t": "Mil.avv. 280-yil"},
    {"s": "Parfiya va Yunon-Baqtriya davlatlari Salavkiylardan qachon ajralib chiqdi?", "v": ["Mil.avv. 312-yil", "Mil.avv. 280-yil", "Mil.avv. 250-yil", "Mil.avv. 221-yil"], "t": "Mil.avv. 250-yil"},
    {"s": "Shoshtepada doira shaklidagi olov ibodatxonasi qachon qurilgan?", "v": ["Mil.avv. III asr", "Mil.avv. II asr", "Mil.avv. I asr", "Milodiy I asr"], "t": "Mil.avv. II asr"},
    {"s": "Qang' davlati qachon qudratli davlatga aylandi?", "v": ["Mil.avv. III asr oxiri", "Mil.avv. II asr oxiri", "Mil.avv. I asrda", "Milodiy I asrda"], "t": "Mil.avv. II asr oxiri"},
    {"s": "\"Samoviy otlar\" ovozasi Xitoygacha qachon yetib borgan?", "v": ["Mil.avv. III asrda", "Mil.avv. II asr oxirida", "Mil.avv. I asrda", "Milodiy II asrda"], "t": "Mil.avv. II asr oxirida"},
    {"s": "Dovon davlati qachon gullab-yashnagan?", "v": ["Mil.avv. III-II asrlar", "Mil.avv. II-I asrlar", "Milodiy I-II asrlar", "Milodiy III asr"], "t": "Mil.avv. II-I asrlar"},
    {"s": "Oqchaxon qal'adagi saroy va ibodatxona qaysi davrga oid?", "v": ["Mil.avv. III-II asrlar", "Mil.avv. II-I asrlar", "Milodiy I-II asrlar", "Milodiy III asr"], "t": "Mil.avv. II-I asrlar"},
    {"s": "Yuechjilar Yunon-Baqtriya davlatini qachon qulatdi?", "v": ["Mil.avv. 250-yil", "Mil.avv. 140-130-yillar", "Mil.avv. 100-yil", "Milodiy 1-asr"], "t": "Mil.avv. 140-130-yillar"},
    {"s": "Xitoyda qog'oz qachon ixtiro qilindi?", "v": ["Mil.avv. II asr", "Mil.avv. I asr", "Milodiy I asr", "Milodiy II asr"], "t": "Mil.avv. I asr"},
    {"s": "Strabon qaysi davrda yashagan?", "v": ["Mil.avv. II asr", "Mil.avv. I asr oxiri", "Milodiy I asr boshlari", "Milodiy II asr"], "t": "Mil.avv. I asr oxiri"},
    {"s": "Xorazmda kumush va mis tangalar qachon zarb qilina boshlangan?", "v": ["Mil.avv. III-II asrlar", "Mil.avv. I asr - milodiy dastlabki asrlar", "Milodiy II-III asrlar", "Milodiy IV-V asrlar"], "t": "Mil.avv. I asr - milodiy dastlabki asrlar"},
    {"s": "Ayolning sopol haykalchasi qaysi asrlarga oid?", "v": ["Mil.avv. I-II asr", "Milodiy I-II asr", "Milodiy III-IV asr", "Milodiy V asr"], "t": "Mil.avv. I-II asr"},
    {"s": "Rimda harbiy boshliqlar qachondan real kuchga aylandi?", "v": ["Mil.avv. III asr", "Mil.avv. II asr", "Mil.avv. I asr", "Milodiy I asr"], "t": "Mil.avv. I asr"},
    {"s": "Spartak va Mark Krass o'rtasidagi hal qiluvchi jang qachon bo'ldi?", "v": ["Mil.avv. 74-yil", "Mil.avv. 71-yil kuzi", "Mil.avv. 49-yil", "Mil.avv. 44-yil"], "t": "Mil.avv. 71-yil kuzi"},
    {"s": "Yuliy Sezar Rubikon daryosidan qachon o'tdi?", "v": ["Mil.avv. 74-yil", "Mil.avv. 49-yil", "Mil.avv. 44-yil", "Mil.avv. 31-yil"], "t": "Mil.avv. 49-yil"},
    {"s": "Antoniy va Oktavian o'rtasidagi urush qachon bo'lgan?", "v": ["Mil.avv. 44-yil", "Mil.avv. 31-yil", "Mil.avv. 29-yil", "Milodiy 1-yil"], "t": "Mil.avv. 31-yil"},
    {"s": "Oktavian qo'shinlari Misrga qachon yetib keldi?", "v": ["Mil.avv. 31-yil", "Mil.avv. 30-yil", "Mil.avv. 29-yil", "Mil.avv. 27-yil"], "t": "Mil.avv. 30-yil"},
    {"s": "Kvint Kursiy Ruf qaysi davrda yashagan?", "v": ["Mil.avv. I asr", "Milodiy I asr", "Milodiy II asr", "Milodiy III asr"], "t": "Milodiy I asr"},
    {"s": "Kushon podsholigiga qachon asos solindi?", "v": ["Mil.avv. I asr", "Milodiy I asr", "Milodiy II asr", "Milodiy III asr"], "t": "Milodiy I asr"},
    {"s": "Vifleemda Iso qachon tug'ilgan?", "v": ["Mil.avv. I asr boshida", "Milodiy I asr boshida", "Milodiy II asrda", "Milodiy III asrda"], "t": "Milodiy I asr boshida"},
    {"s": "Foyoztepadan topilgan Budda haykali qaysi asrlarga oid?", "v": ["Mil.avv. I-II asrlar", "Milodiy I-II asrlar", "Milodiy III-IV asrlar", "Milodiy V asr"], "t": "Milodiy I-II asrlar"},
    {"s": "Trayan qachon Rim imperatori bo'ldi?", "v": ["Milodiy 74-yil", "Milodiy 98-yil", "Milodiy 117-yil", "Milodiy 313-yil"], "t": "Milodiy 98-yil"},
    {"s": "Kushon davlati hukm surgan davrni aniqlang:", "v": ["Mil.avv. I - milodiy I asr", "Milodiy I-III asrlar", "Milodiy II-IV asrlar", "Milodiy III-V asrlar"], "t": "Milodiy I-III asrlar"},
    {"s": "Xorazm mahalliy taqvimi qaysi davrda amalda bo'lgan?", "v": ["Mil.avv. IV - milodiy III asr", "Milodiy I-VIII asrlar", "Milodiy III-IX asrlar", "Milodiy V-X asrlar"], "t": "Milodiy I-VIII asrlar"},
    {"s": "Tarixchi Arrian qaysi asrda yashagan?", "v": ["Milodiy I asr", "Milodiy II asr", "Milodiy III asr", "Milodiy IV asr"], "t": "Milodiy II asr"},
    {"s": "Tuproqqal'a shahri qaysi asrlarga oid?", "v": ["Milodiy I-II asrlar", "Milodiy II-III asrlar", "Milodiy III-IV asrlar", "Milodiy IV-V asrlar"], "t": "Milodiy II-III asrlar"},
    {"s": "Dalavarzintepadan topilgan Budda boshi tasviri qaysi davrga tegishli?", "v": ["Milodiy I-II asrlar", "Milodiy II-III asrlar", "Milodiy IV asr", "Milodiy V asr"], "t": "Milodiy II-III asrlar"},
    {"s": "Xitoy imperiyasi qachon 3 ga bo'linib ketdi?", "v": ["Milodiy II asr", "Milodiy III asr", "Milodiy IV asr", "Milodiy V asr"], "t": "Milodiy III asr"},
    {"s": "Kushon, Xorazm, Qang' va Dovon davlatlari qachon parchalana boshladi?", "v": ["Milodiy II asr", "Milodiy III asr", "Milodiy IV asr", "Milodiy V asr"], "t": "Milodiy III asr"},
    {"s": "Rim imperiyasi kuch-qudrati qachondan zaiflasha boshladi?", "v": ["Milodiy I asr", "Milodiy II asr", "Milodiy III asr", "Milodiy IV asr"], "t": "Milodiy III asr"},
    {"s": "Konstantinopol shahriga qaysi yilda asos solindi?", "v": ["Milodiy 313-yil", "Milodiy 330-yil", "Milodiy 395-yil", "Milodiy 476-yil"], "t": "Milodiy 330-yil"},
    {"s": "Olimpiya o'yinlari qachon to'xtab qoldi?", "v": ["Milodiy 330-yil", "Milodiy 394-yil", "Milodiy 395-yil", "Milodiy 476-yil"], "t": "Milodiy 394-yil"},
    {"s": "Alarix boshchiligidagi gotlar Rimga qachon yurish qildi?", "v": ["Milodiy 395-yil", "Milodiy 410-yil", "Milodiy 452-yil", "Milodiy 455-yil"], "t": "Milodiy 410-yil"},
    {"s": "Attila boshchiligidagi xunnlar Italiyaga qachon bostirib kirdi?", "v": ["Milodiy 410-yil", "Milodiy 452-yil", "Milodiy 455-yil", "Milodiy 476-yil"], "t": "Milodiy 452-yil"},
    {"s": "Vandal qabilasi Rimga qachon yurish qildi?", "v": ["Milodiy 410-yil", "Milodiy 452-yil", "Milodiy 455-yil", "Milodiy 476-yil"], "t": "Milodiy 455-yil"},
    {"s": "So'nggi Rim imperatori Romulni kim ag'dardi?", "v": ["Alarix", "Attila", "Odoakr", "Konstantin"], "t": "Odoakr"},
    {"s": "Amudaryo xazinasi (Oks xazinasi) qaysi yilda topilgan?", "v": ["1822-yil", "1877-yil", "1880-yil", "1905-yil"], "t": "1877-yil"},
    {"s": "\"Buyuk Ipak yo'li\" nomini kim bergan?", "v": ["J.F. Shampolyon", "O. Dalton", "F. Rixtgofen", "Gerodot"], "t": "F. Rixtgofen"},
    {"s": "Buxorolik savdogarlar karvoniga qaroqchilar qachon hujum qildi?", "v": ["1877-yil", "1880-yil may oyi", "1896-yil", "1905-yil"], "t": "1880-yil may oyi"},
    {"s": "Olimpiya o'yinlari qayta tiklangan yil:", "v": ["1822-yil", "1877-yil", "1880-yil", "1896-yil"], "t": "1896-yil"},
    {"s": "Mixxat ixtirochilarini aniqlang:", "v": ["Misrliklar", "Shumerlar", "Finikiyaliklar", "Xitoyliklar"], "t": "Shumerlar"},
    {"s": "Mil.avv. 4-mingyillik oxirida Mesopotamiyada vujudga kelgan shahar:", "v": ["Bobil", "Lagash", "Memfis", "Maraqand"], "t": "Lagash"},
    {"s": "Akkad va Shumerni Sargon I qachon birlashtirdi?", "v": ["Mil.avv. 3-mingyillik boshida", "Mil.avv. 3-mingyillik 2-yarmi", "Mil.avv. 2-mingyillik", "Mil.avv. IV asr"], "t": "Mil.avv. 3-mingyillik 2-yarmi"},
    {"s": "Mil.avv. XVIII asrda Bobil podshosi kim edi?", "v": ["Sargon I", "Xammurapi", "Nabukodonosor", "Kir II"], "t": "Xammurapi"},
    {"s": "Sparta davlatiga asos solgan qabila:", "v": ["Axeylar", "Doriylar", "Etrusklar", "Gotlar"], "t": "Doriylar"},
    {"s": "Finikiya alifbosi nechta harfdan iborat edi?", "v": ["20 ta", "22 ta", "24 ta", "30 ta"], "t": "22 ta"},
    {"s": "Mil.avv. VI asrda Buddizm dini qayerda paydo bo'ldi?", "v": ["Xitoy", "Hindiston", "Eron", "Yunoniston"], "t": "Hindiston"},
    {"s": "Marafon jangi qaysi davlatlar o'rtasida bo'lgan?", "v": ["Rim va Karfagen", "Yunoniston va Fors (Eron)", "Misr va Xett", "Aleksandr va Spitamen"], "t": "Yunoniston va Fors (Eron)"},
    {"s": "Mil.avv. 312-yilda Bobilda kim hokimiyatga keldi?", "v": ["Aleksandr", "Salavk", "Antiox", "Doro III"], "t": "Salavk"},
    {"s": "\"Oks xazinasi\" kitobi muallifi kim?", "v": ["Rixtgofen", "Shampolyon", "O. Dalton", "Arrian"], "t": "O. Dalton"},
    {"s": "Sin Shixuandi qaysi davlat hukmdori edi?", "v": ["Xitoy", "Hindiston", "Misr", "Bobil"], "t": "Xitoy"},
    {"s": "Mil.avv. 49-yilda Sezar qaysi daryodan o'tdi?", "v": ["Nil", "Rubikon", "Amudaryo", "Tibr"], "t": "Rubikon"},
    {"s": "Imperator Konstantin poytaxtni qaysi shaharga ko'chirdi?", "v": ["Rim", "Konstantinopol", "Afina", "Iskandariya"], "t": "Konstantinopol"},
    {"s": "Milodiy 476-yil qaysi imperiyaning qulash yili?", "v": ["Sharqiy Rim", "G'arbiy Rim", "Fors", "Kushon"], "t": "G'arbiy Rim"},
    {"s": "Mil.avv. 776-yilda qanday muhim voqea yuz berdi?", "v": ["Rimga asos solindi", "Ilk Olimpiya o'yinlari", "Sezar o'ldirildi", "Misr birlashdi"], "t": "Ilk Olimpiya o'yinlari"},
    {"s": "Menes tomonidan Misr birlashtirilishi qachon sodir bo'lgan?", "v": ["Mil.avv. 4-mingyillikda", "Mil.avv. 3000-yilda", "Mil.avv. 2600-yilda", "Mil.avv. XVIII asrda"], "t": "Mil.avv. 3000-yilda"},
    {"s": "Temirdan foydalanishni birinchi bo'lib boshlaganlar:", "v": ["Misrliklar", "Xettlar", "Shumerlar", "Saklar"], "t": "Xettlar"},
    {"s": "Mil.avv. XI asrda Falastinda qaysi podsholik tuzildi?", "v": ["Bobil", "Isroil", "Midiya", "Urartu"], "t": "Isroil"},
    {"s": "Drakont qonunlari qaysi shaharda tuzilgan?", "v": ["Rim", "Afina", "Sparta", "Bobil"], "t": "Afina"},
    {"s": "Mil.avv. 525-yilda Misrni kim bosib oldi?", "v": ["Kir II", "Kambiz II", "Doro I", "Aleksandr"], "t": "Kambiz II"},
    {"s": "\"Tarix otasi\" Gerodot qaysi asrda yashagan?", "v": ["Mil.avv. VI asr", "Mil.avv. V asr", "Mil.avv. IV asr", "Mil.avv. III asr"], "t": "Mil.avv. V asr"},
    {"s": "Aleksandr Makedonskiyning Sharqqa yurishi qachon boshlandi?", "v": ["Mil.avv. 336-yil", "Mil.avv. 334-yil", "Mil.avv. 330-yil", "Mil.avv. 327-yil"], "t": "Mil.avv. 334-yil"},
    {"s": "Spitamen qo'zg'oloni Aleksandrga qarshi qachon bo'lgan?", "v": ["Mil.avv. 330-328 yillar", "Mil.avv. 329-328 yillar", "Mil.avv. 327-323 yillar", "Mil.avv. IV asr boshida"], "t": "Mil.avv. 329-328 yillar"},
    {"s": "Mil.avv. III asrda Rimda kimlar teng huquqli deb e'lon qilindi?", "v": ["Faqat patritsiylar", "Barcha fuqarolar", "Faqat harbiylar", "Faqat erkaklar"], "t": "Barcha fuqarolar"},
    {"s": "Qadimgi Dovon davlati qachon gullab-yashnagan?", "v": ["Mil.avv. III-II asrlar", "Mil.avv. II-I asrlar", "Milodiy I-II asrlar", "Milodiy III asr"], "t": "Mil.avv. II-I asrlar"},
    {"s": "Buyuk Ipak yo'li qachon tugadi (rasmiy to'xtadi)?", "v": ["Milodiy VI asr", "Milodiy X asr", "Milodiy XVI asr", "Milodiy XIX asr"], "t": "Milodiy XVI asr"},
    {"s": "Spartak qo'zg'oloni necha yil davom etgan?", "v": ["2 yil", "3 yil (74-71 yillar)", "5 yil", "10 yil"], "t": "3 yil (74-71 yillar)"},
    {"s": "Antoniy va Oktavian jangi qayerda bo'lgan?", "v": ["Rim yaqinida", "Yunoniston qirg'oqlarida", "Misr cho'llarida", "Marafon dalasida"], "t": "Yunoniston qirg'oqlarida"},
    {"s": "Milodiy I asrda Rim qanday maqomga ega edi?", "v": ["Kichik qishloq", "Eng yirik va aholisi ko'p shahar", "Faqat harbiy lager", "Faqat savdo porti"], "t": "Eng yirik va aholisi ko'p shahar"},
    {"s": "Budda haykali (Foyoztepa) qaysi viloyat hududidan topilgan?", "v": ["Xorazm", "Surxondaryo (Termiz)", "Toshkent", "Samarqand"], "t": "Surxondaryo (Termiz)"},
    {"s": "Rim imperiyasining \"Oltin asri\" deb e'tirof etilgan asr:", "v": ["Milodiy I asr", "Milodiy II asr", "Milodiy III asr", "Milodiy IV asr"], "t": "Milodiy II asr"},
    {"s": "Milodiy 395-yilda imperiyani kim bo'lib berdi?", "v": ["Konstantin", "Feodosiy (vafotidan so'ng)", "Romul", "Trayan"], "t": "Feodosiy (vafotidan so'ng)"},
    {"s": "J.F. Shampolyon qaysi davlat olimi edi?", "v": ["Angliya", "Fransiya", "Germaniya", "Rossiya"], "t": "Fransiya"},
    {"s": "\"Oks xazinasi\" qayerdan topilgan?", "v": ["Nil vodiysidan", "Qubodiyon (Baqtriya)", "Rim shahridan", "Afrosiyobdan"], "t": "Qubodiyon (Baqtriya)"}
]